### ISSUE TITLE
People of WordPress - July 2022

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#100]
This is a copy of the original card as there is an error on the cards with the migration. This will be merged with the original once resolved.

Feature: Carla 

Summaries are below.

[Link to the Slack thread on 13 July 2022](https://wordpress.slack.com/archives/C0GKJ7TFA/p1657829757994519?thread_ts=1657725616.257869&cid=C0GKJ7TFA)

[Link to the Slack thread on 20 July 2022](https://wordpress.slack.com/archives/C0GKJ7TFA/p1658329992122449)

**Comment by abhansnuk** [comment]
Summary copied from main card:
- Surendra identified key areas for revision in previous review
- Alison is working on first draft
- Larissa to liaise with featured WordPresser for facts update and pictures needed. To also look at SEP headings and what might need updating with Alison, and work alongside her
- Mary: offered to assist and shadow Meher with images. Volunteer from the Spanish community came forward to assist.

- Meher is picking up the piece swapped out for July as we have not heard back from the contributor working on it. She will check on with the person being featured and we may use that for September or November 2022 instead.
- Nalini: GitHub cards to be updated with swaps. Need Ali-WPFiddlyBits GitHub ID to add her to the cards on the new repo
- Abha and Meher assisted in trying to contact Carla. Pictures obtained and update on facts sent to Larissa (added to the bottom of the google doc and to be put into the feature by Ali/ Larissa/ Abha) 
- reviewing to start after 22 July. First draft in 26/7/2022. First review in progress. Update sent to Chloe

Revised deadlines for feature now set for August 2022: Bud Kraus. @marybaum working on this and liaising with Bud. Copy first draft by 30 June 2022. Link this to promo on WCUS.

Discussion on ongoing need to assist HeroPress with images and issue checks for PofWP. Meher to follow up and draft an idea.

**Comment by abhansnuk** [comment]
- Draft in review.

- Fact-checking done with person featured done by @murillol . Any dates to be checked, please check information Larissa has pasted at the bottom of the document.

- Any further comments from @Bringmannn to be added.

- Edit for additional quotes to be added.

- Note: last two days of cycle fall on weekends this month, for majority of contributors who are working on this, these dates are fine and easier for some. 

- SEO review in progress: @murillol 

- Any potential Spanish translation issues to be reviewed by @murillol and @vimes1984 .

- Photo editing: pictures obtained via @murillol . @meherbala to review 28-28 July 2022 and identify what is needed to be done.

**Comment by nalininsbs** [comment]
Reminder: change access on document. Remove any personal contacts once complete.

**Comment by abhansnuk** [comment]
Thanks, useful reminder. 
From your checklist, I have also checked we can link this particular document to the GitHub card rather than just the Slack thread.

**Comment by meherbala** [comment]
Received only 2 images for this month's POWP.

Taken one image and created it in the feature image size.

Resized both the image to be used in the article.

Uploaded them to in Media Section, in the News Dashboard.

Will add the images once the article has been drafted in the News Dashboard.

**Comment by murillol** [comment]
do you want me to ask Carla for more images? @meherbala @abhansnuk

**Comment by abhansnuk** [comment]
Further reviews.

In News admin.

Over to you @meherbala for the pictures, alt tags and adding WP IDs at the bottom please, as well as your usual checks. Can you please liaise with @murillol if you need extra photos?

When you are out of the post, I will go back in and continue with the layout review and text. Thanks everyone.

**Comment by meherbala** [comment]
@abhansnuk the following have been done:
1) pictures 
2) alt tag
3) additional categories 
4) article tags
5) HeroPress block at the end of the article
6) WP.org handles of everyone who contributed

>Can you please liaise with @murillol if you need extra photos?

I would have been great to have more photos but its too late to ask.

Over to @murillol and @abhansnuk

**Comment by meherbala** [comment]
Link to the post: https://wordpress.org/news/2022/07/people-of-wordpress-carla-doria/

Thank you everyone for their hard work.
