### ISSUE TITLE
People of WordPress - August 2022

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#101]
This is a copy of the original card as there is an error on the cards with the migration. This will be merged with the original once resolved.

Link to the Slack thread on 13 July 2022 https://wordpress.slack.com/archives/C0GKJ7TFA/p1657829757994519?thread_ts=1657725616.257869&cid=C0GKJ7TFA

Link to the Slack thread on 20 July 2022 https://wordpress.slack.com/archives/C0GKJ7TFA/p1658329992122449

The threads contain the links to the documents and updates.

**Comment by abhansnuk** [comment]
**Revised deadlines for feature now set for August 2022:** 
Bud Kraus. @marybaum working on this and liaising with Bud. Copy first draft by 30 June 2022. Link this to promo on WCUS.

**Comment by meherbala** [comment]
Can I get access to the pictures for Aug POWP? 

If we have fewer images please can we ask Bud to share some images?

CC: @marybaum, @abhansnuk, @murillol

**Comment by nalininsbs** [comment]
@marybaum I know you are following up on photographs. Do we have these now please? Thank you.

**Comment by meherbala** [comment]
Any update on the photos @marybaum.

I am may not available on the 30th and 31st. 

Hence would like to finish this by this weekend.

Thanks

CC: @nalininsbs

**Comment by nalininsbs** [comment]
The latest version has again been shared with Chloe. Note I have replaced the link above as there were changes again this week from outside the team/ People of WordPress and items deleted. @abhansnuk @meherbala @vimes1984 can you please go through the permissions and change everyone to comment apart from the people currently editing.  Thank you

**Comment by abhansnuk** [comment]
I can have a look. I noticed there were four people typing into the document this morning too. I am readding the fact check from the file too.

**Comment by abhansnuk** [comment]
Editing reviews in progress. Chloe reviewed. Additional photos being sourced. 
Further research / fact updating has been completed. Items with Bud to check, and then update the piece. 
To be uploaded and tested on the CMS on 2022/8/31.

**Comment by murillol** [comment]
Link to published piece: https://wordpress.org/news/2022/08/people-of-wordpress-bud-kraus/
