### ISSUE TITLE
The Month in WordPress: August 2022 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#102]
The expected publication date for the August 2022 edition of The Month in WordPress is **Friday, September 2, 2022**.

### How can you help?

If you have any news or Make team updates that would be valuable and relevant to the post, please feel free to **add them as a comment to this GitHub card**, or share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness by Tuesday - August 30, 2022, if possible.

The draft will be added to this card and shared in the Marketing channel prior to publication for review. Your input and suggestions will be appreciated, too.

### Additional background

The Month in WordPress is a monthly roundup of all the major WordPress news and Make team updates that is usually published by the 5th of each month at WordPress.org/News. It features news from the previous month to publication. To see what's typically featured, please check out any of the [latest editions](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by chaion07** [comment]
Happy to volunteer again for the August edition of Month in WordPress. Thanks!

**Comment by nalininsbs** [comment]
@rmartinezduque could you please add the published link to this when it is out please and remove the help wanted label. Thank you

**Comment by rmartinezduque** [comment]
@nalininsbs Yes, we can share this GitHub card at this week's meeting and let people know that they can subscribe to it for updates. I usually share the link and close the issue when the post is published. I'll also remove the help-wanted label.

**Comment by abhansnuk** [comment]
Hello @rmartinezduque, @costdev has asked in dev chat in the next Month in WordPress if you can include the following. Thanks. 

In the Feedback & testing requests section, include [WP Plugin Dependencies feature plugin](https://wordpress.org/plugins/wp-plugin-dependencies/)

**Comment by rmartinezduque** [comment]
Hi @abhansnuk and @costdev, thanks for the suggestion! I don't have much context on this plugin and I think it would help me to have some more information:

- What is this plugin for?
- What exactly do users have to test/give feedback on?
- Where can they leave feedback/comments?
- Is there an additional Make post we can link to? I see this https://make.wordpress.org/core/2022/02/24/feature-project-plugin-dependencies/, but it's from February.

Thank you for any answers that you can provide!

**Comment by rmartinezduque** [comment]
Hi @abhansnuk, @costdev, just checking in to see if you can provide more information on the above request. Thanks!

**Comment by costdev** [comment]
Hi @rmartinezduque, we were preparing a new Make post that I won't be ready in time for the August 2022 Edition.

I'll follow up on the the next issue once the Make post is published 🙂

**Comment by rmartinezduque** [comment]
No problem, thanks for the update @costdev. I appreciate it. 🙂

**Comment by rmartinezduque** [comment]
Hi @chaion07! Thanks for asking. 🙂 This week has been busy and I'm still working on the draft, but I will share the link soon for review!

**Comment by rmartinezduque** [comment]
👋 The draft for the [August 2022 edition of The Month in WordPress is now ready for review](https://docs.google.com/document/d/1P31-grSwlMQRlP_h5z4WLB0GUXmWacnfX-9Xkw_57tg/edit#heading=h.8m8irz39b0fm).

Please note that I'm still waiting for some 6.1 and LearnWP updates that haven't been posted yet. I'm hoping to publish it tomorrow, September 2, at 15:00 UTC, if the missing information is available and a final review can be made. If this is not possible, the post will be pushed back to Monday.

Either way, I would appreciate if you could **review the draft and leave any suggestions by tomorrow, Sept 2**. Thanks!

**Comment by chaion07** [comment]
I went through the draft and suggested some changes including comments. Thanks @rmartinezduque 💗

**Comment by rmartinezduque** [comment]
Thank you!

Just a quick update here: **I'll hold off the post until Monday** to go through the suggestions done today and include the latest information about the 6.1 walk-through.

**Comment by abhansnuk** [comment]
Hello @rmartinezduque I have added some suggestions. Thanks.

**Comment by rmartinezduque** [comment]
Thanks, Abha!

**Comment by rmartinezduque** [comment]
**The Month in WordPress – August 2022 is now published**: https://wordpress.org/news/2022/09/the-month-in-wordpress-august-2022/. Thank you to all the people who contributed to this edition. ❤️

_If you'd like to contribute to the next edition of the Month in WordPress, feel free to subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/109._
