### ISSUE TITLE
2022/8/31 Global Marketing Team Meeting and week planning

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#106]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Coffee break rota](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by thetinyl** [comment]
🖐️ I'm happy to help take notes for Aug 31 meeting.

**Comment by sereedmedia** [comment]
Hi y'all. Bringing some tidings from the Meta team with regard to the navigation on wordpress.org.

[This post](https://make.wordpress.org/meta/2022/08/18/navigation/) happened recently and while there are proposals and suggestions on that post, during the convo in Meta about it, I suggested that while the implementation of a revised navigation menu is Meta territory, the discussion around and structure of a site's navigation menu is really very much a Marketing issue. 

Currently, Meta is making a trac post about it to monitor the progress of the revision as a whole. Can marketing take up this discussion and create a proposal?

**Comment by abhansnuk** [comment]
I was in the meta team meeting for another issue, and promised to link up the query on the above to GitHub and the team reps @eidolonnight @nalininsbs and @murillol. Over to you. Thanks @sereedmedia

**Comment by abhansnuk** [comment]
Issues on the P2 - please keep the screenshots you sent @nalininsbs . These can be added to the other identified items and a meta ticket raised.

I have resolved the two issues in the agenda post with the strange embed. All done and now agenda should work ok. https://make.wordpress.org/marketing/2022/08/30/agenda-marketing-meeting-august-31-2022/

**Comment by rmartinezduque** [comment]
Hello! Could we add the following item as part of the Contributor Events updates in today's meeting? Thanks!

- Openverse will be remotely participating in the WordCamp US Contributor Day. This provides an opportunity for people unable to attend WCUS in person to engage with the event and get involved with Openverse. The team shared more details in [this post](https://make.wordpress.org/openverse/2022/08/30/openverse-remote-contributor-day-at-wordcamp-us-2022/).

_I'm aware it's not related to the Marketing team, but I think it's good to spread the word so that contributors interested in contributing to Openverse are aware of the opportunity._ 

I also shared an update regarding the Photo Directory challenge on [this GitHub card](https://github.com/WordPress/Marketing-Team/issues/80#issuecomment-1232789621) (GitHub card 80). Thanks!

**Comment by thetinyl** [comment]
Hey all! I've got the meeting notes from Aug 31 in draft and ready for review: https://make.wordpress.org/marketing/?p=9846&preview=true

**Comment by thetinyl** [comment]
@nalininsbs @eidolonnight @murillol Just following up on the notes draft linked above. Let me know if it needs edits or is ready for publication. 👍

**Comment by murillol** [comment]
hi @thetinyl! I believe @nalininsbs is looking over them right now

**Comment by abhansnuk** [comment]
> I was in the meta team meeting for another issue, and promised to link up the query on the above to GitHub and the team reps @eidolonnight @nalininsbs and @murillol. Over to you. Thanks @sereedmedia

Update from August 31, 2022 Marketing team meeeting from @eidolonnight: a new iteration of the [WordPress.org](http://wordpress.org/)[ main navigation will be launching soon](https://github.com/WordPress/wporg-mu-plugins/pull/257). This is the result of the [nav conversation in Meta](https://make.wordpress.org/meta/2022/08/18/navigation/). 

Update shared at September 2022 Marketing team meeting from @eidolonnight: post [Simplifying the admin bar in the global navigation menu](https://make.wordpress.org/meta/2022/09/01/simplifying-the-admin-bar-global-navigation-menu/).

Nicholas confirmed in the meeting "no more action items for now. The issues were all tracked in Meta’s repos, so nothing to be added or done in Marketing." [Link to Slack thread](https://wordpress.slack.com/archives/C0GKJ7TFA/p1662563966561509).

**Comment by abhansnuk** [comment]
Published notes from the August 31, 2022 meeting. 
Props to @thetinyl and @nalininsbs for notes summary and review, to @eidolonnight, @nalininsbs and @murillol for meeting preparation and facilitation.
