### ISSUE TITLE
WordCamp Asia 2023 Marketing Table Contributor Day

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#108]
WordCamp Asia 2023 has announced a Contributor Day, This will take place on February 17, There will be more information in the coming weeks. Thank you to the WordCamp Asia team for the update.

**Comment by dugyen** [comment]
[Call for the Contributors Stories is Open](https://asia.wordcamp.org/2023/call-for-contributors-stories/) :
**It’s the first Asian flagship WordCamp dedicated to Contributors and WordPress Communities who contribute to WordPress. We plan to feature some stories from seasoned contributors who enjoyed their experience at contributing events.**

**Comment by nalininsbs** [comment]
If anyone is interested in helping with the Marketing table at this event, please add yourself to the ticket. The table leads and Slack team support from WordCamp Europe and WordCamp US can help anyone wanting to help. We have some templates and documents from these events which can assist too.

**Comment by kawserz** [comment]
Please assign me here. Hopefully, I will be there at WordCamp Asia.

**Comment by eidolonnight** [comment]
@abhansnuk do we have the times of the event? Specifically Contributor Day? I won't be attending in-person, but would maybe be able to help out in Slack.

**Comment by jpantani** [comment]
@eidolonnight @abhansnuk While I don't think I'll be able to attend in person, I do anticipate being able to help on Slack given that a 9am start in Bangkok is only 7 pm in California, and 11 pm in New York.

**Comment by dugyen** [comment]
@dugyen from WordCamp Asia 2023 Contributor Day Team. 
@abhansnuk  could you please let me know, among you all who will be attending WordCamp Asia 2023 to lead our Marketing Table?

**Comment by mumtahinafaguni** [comment]
Please count me in for the marketing table. Already I've purchased my WC Asia Ticket.

**Comment by nalininsbs** [comment]
Highlighted this call at the meetings in October and November. 

Please add to the card if you intend to be at the contributor day and involved in the marketing table. 
The WordCamp Asia team will need some contributors from the team to assist with this in person, working alongside the remote support that is being planned. I will be joined by @jpantani , @abhansnuk , @meherbala and others who have already volunteered to support remotely and via Slack.

It would also help to have more contributors who are familiar with contributing to WordPress in person at the marketing table in Asia. If you could help with this, please add to this card or contact me if you are unsure.

**Comment by nalininsbs** [comment]
Thank you to those who have added to the card saying they would like to participate at the marketing table at WordCamp Asia too. Please do continue to add to this card.

**Comment by nalininsbs** [comment]
@dugyen is there a date you need to know about who will be present from teams and what will be available for anyone wanting to join marketing at the event? Thank you

**Comment by Afrin29** [comment]
You can include me in this marketing table contributor day. I will be present at WC Asia.

**Comment by nalininsbs** [comment]
Thank you @Afrin29.

**Comment by nalininsbs** [comment]
This ticket is highlighted weekly in the Marketing Team meetings. If you are attending and would be able to assist or participate at a marketing table contributor day, please add to this card. Thank you.

**Comment by dugyen** [comment]
Is our new team reps announced yet? @abhansnuk

**Comment by jpantani** [comment]
I've scanned through this but it doesn't appear there are any in-person leads to help facilitate Contributor Day? Just want to make sure I haven't missed anything?

**Comment by robinwpdeveloper** [comment]
Hi @jpantani are you joining WC Asia in person?
We are keen to provide few suggestions to the organizing team on Friday.

If you attending in person and wants to lead the table please let us know 😊

**Comment by nalininsbs** [comment]
I think Robin, you are going in person and a few others have added to this card saying they will join the table. The last discussion on this was that we will need to have some Slack live support and pre-preparation as we did for WCUS. 

At least one person will need to be assisting on the ground, this does not have to be a 'table lead' necessarily and having to prepare everything. It can be someone who is willing to help with materials others (including themselves if they would like to assist) have prepared before the event. Are there exact times in UTC yet @robinwpdeveloper and @dugyen, and a timetable for the day?

@dugyen are you asking contributors to indicate which team they will want to be contributing to on the day and if they are new to contributing? Thank you Robin and Ugyen.

**Comment by santanainniss** [comment]
Hello all! 

Unfortunately I don't have the means to attend in person this year. It doesn't seem that any team reps will be in attendance. Not to worry! I have found at least 1 table lead!! Our long time contributor, and WCEU table lead Yvette has agreed to lead a table! WOOHOO!

@dugyen Are you/the organizing team hoping to have two tables at the event? Perhaps one of the folks that have commented here would be able the lead a second table? 

Let's figure out our on the ground support, and then we can move on to discuss the format, topics, and plans for contributor day!

**Comment by nalininsbs** [comment]
This is great news that Yvette will be there ad able to take a table. I heard today that another other long standing contributor is trying to arrange to go too. I will ask if she can add to this card if she is able to go.

**Comment by santanainniss** [comment]
That's great @nalininsbs! If you can share their information we are still (I believe) looking for one more on the ground table lead!

**Comment by dugyen** [comment]
Great thanks to @santanainniss for nominating our amazing two marketing table leads for WordCamp Asia 2023. 
Looking very forward to seeing you soon in person @DominykaGH & Yvette WordCamp Asia 2023 and especially Contributor Day on February 17TH.

**Comment by yvettesonneveld** [comment]
Hey there, I'm looking forward to this! @dugyen How many contributors are you expecting in total? I would not be surprised if this would become the biggest contributor day ever? I have never seen contributor day tickets run out so fast!

**Comment by kafleg** [comment]
@yvettesonneveld We still have some seats left. So, we don't have actual data now. We'll inform you when we get the data. 
Thank you

**Comment by abhansnuk** [comment]
@yvettesonneveld and @robinwpdeveloper, the [Five for the Future email template task](https://github.com/WordPress/Marcomms-Rolling-tasks/issues/18) for contributors had a lot of progress at WordCamp US' contributor day in 2022. @eidolonnight has added next steps on the card. This may be useful for WCAsia CD too to progress it. 
I have added some suggestions on where it could live on the P2.

**Comment by sereedmedia** [comment]
Linking content here by @nalininsbs from [WCUS 2022 ticket](https://github.com/WordPress/Marketing-Team/issues/90#issuecomment-1331379117) (

- WCUS Social Content Brainstorm: https://docs.google.com/spreadsheets/d/1zwr3aaNmLreFpYJssohPWt1JwtAyvLNxl6sYdVdtmt8/edit?usp=sharing

- Brainstorming: How could we sustainably produce short-form video content for use on social media?: https://docs.google.com/document/d/1PgCn3fl3aydTL8CPTbMoIorA2wa4iDzsmYivpgSCwYs/edit?usp=sharing

- Brainstorming: What channels and things could we be doing that we’re not doing now? https://docs.google.com/document/d/1y_Z_oytdkuwtag6Wa7D1b61KGT9u3XnbYGAYqGeNSfE/edit?usp=sharing

Drive for WCUS 2022: https://docs.google.com/document/d/1qpVCYmzFNjgp1HitUqT6byFTKmjSm38oyTF0yoeR2nw/edit#

**Comment by santanainniss** [comment]
@mumtahinafaguni @kawserz Hi there! We just found out from WC Asia organizers that 100 people indicated their interest in contributing to Marketing at Contributor Day! Wooohooo! Based on this, we're anticipating ~60 contributors and ~5 tables. 

We were originally anticipating fewer tables. This is a GOOD problem to have! 

Would either of you be available to help @DominykaGH and @yvettesonneveld? We are looking for two more table leads to help the contributors get started. We have complete documentation so you would be able to plug in right away. We need help at least the first session 09:45 - 11:00 local time.

**Comment by sereedmedia** [comment]
Hi everyone! Tagging @Afrin29 and @shahidul95, who said they would be at WCAsia! 

If you're participating in WC Asia Contributor Day, in person or remotely, this is our Starting ticket and virtual sign-in sheet: [Start Here! Contributor ticket for WordCamp Asia Contributor Day - February 17 2023](https://github.com/WordPress/Marketing-Team/issues/185) 

WordCamp Asia Contributor Day kicks off in about 5.5 hours, at 02:45 UTC / 09:45 Bangkok [official schedule](https://asia.wordcamp.org/2023/schedule/)

You can view the WordCamp Asia Contributor doc here: [google doc](https://docs.google.com/document/d/1VQ2fVt1uORoG_dDN9iDNYYcgt7GjW8Udpjr_i4kDhiE/edit#)

Thank you @mumtahinafaguni for stepping in to a table lead role! We appreciate you so much!!

See you all in Slack!
