### ISSUE TITLE
The Month in WordPress: September 2022 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#109]
The expected publication date for the September 2022 edition of The Month in WordPress is ~~October 10, 2022~~ **October 14, 2022**.

### How can you help?

If you have any news or Make team updates that would be valuable and relevant to the post, please feel free to **add them as a comment to this GitHub card**, or share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness by Friday, September 30, 2022, if possible.

The draft will be added to this card and shared in the Marketing channel prior to publication for review. Your input and suggestions will be appreciated, too. If you have any questions on how to contribute, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of all the major WordPress news and Make team updates that is usually published by the 5th of each month at WordPress.org/News. It features news from the previous month to publication. To see what's typically featured, please check out any of the [latest editions](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
**Update**: I'm going to be away for the next weeks and I might run a little behind when I'm back, so I'm going to push the publication deadline for the September edition to October 10, 2022. However, if possible, it will be published on the date initially indicated.

**Comment by rmartinezduque** [comment]
This week I've had very limited availability and found it challenging to make progress on The Month of WordPress draft. I'm hoping to have a draft finished by the 10th of October, but to allow for a few days of review/feedback, I'm afraid I need to push the publication date to October 13 or 14. Sorry for any inconvenience. 😔

**Comment by rmartinezduque** [comment]
The draft for the September 2022 edition of The Month in WordPress is ready for review. I'm hoping to publish it on Friday, October 14. If you have any suggestions, please share them before the **end of the day tomorrow (October 13)**.

Link: https://docs.google.com/document/d/1KSfOCDfjoY-_6VWv6xJL3XXYFHLrnA8EWsdxOaD52yA/edit.

Also, remember to include your WordPress.org profile link or username as a comment at the end of the document so that all contributions can be credited. Thank you!

**Comment by thetinyl** [comment]
Took a look at this @rmartinezduque and it looks great from a copy standpoint (in my opinion). Just had one minor copy edit suggestion.

**Comment by abhansnuk** [comment]
Hello @rmartinezduque I have made some edits and added info about items due out today in suggestion mode. I wonder if we can break up the long section on Team updates too or put in sub sections? Thanks for all your work on this edition. So much happening in WP!

Is it possible to link to the podcast Josepha was in hosted by GoDaddy to promote the things she was talking about? As it was out of the direct Make space, it may not be possible.

**Comment by rmartinezduque** [comment]
Thank you for those suggestions, @abhansnuk. I will make a second revision to the document to incorporate feedback today. There are indeed a lot of things happening in WP! :D 

> I wonder if we can break up the long section on Team updates too or put in sub sections?

Sure, maybe we can separate the WordPress Translation Day update since it's longer. Or group the Learn WordPress updates together. I will make a second revision to the document to incorporate feedback today.

> Is it possible to link to the podcast Josepha was in hosted by GoDaddy to promote the things she was talking about? As 
it was out of the direct Make space, it may not be possible.

Yes, as far as I know, we usually don't include links to company events to avoid favoring one over the other. That was a great event, so we can still promote it ourselves on our personal social platforms.

**Comment by rmartinezduque** [comment]
The [draft is reviewed](https://docs.google.com/document/d/1KSfOCDfjoY-_6VWv6xJL3XXYFHLrnA8EWsdxOaD52yA/edit#) and ready to be published tomorrow. Thank you all for your contributions and suggestions!

I'll share the link when the post is live.

**Comment by rmartinezduque** [comment]
The **Month in WordPress – September 2022 is now published**: https://wordpress.org/news/2022/10/the-month-in-wordpress-september-2022/. Thanks again to everyone who contributed to this edition. ❤️

If you'd like to contribute to the October edition of the Month in WordPress, feel free to express your interest and subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/131.

**Comment by chaion07** [comment]
Thanks @rmartinezduque for everything you do towards the WordPress Community
