### ISSUE TITLE
Meeting: 2 March 2022

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#11]
Link to meeting planning discussion card https://github.com/WordPress/Marcomms-Internal-Comms/discussions/19

**Comment by bjmcsherry** [comment]
@nalininsbs @eidolonnight @murillol  I posted the Google Docs for the notes here: https://docs.google.com/document/d/1otEEBHJJ-ajxJkDOwqPrikpzuvAF6KXI1C5vtpqcqDA/edit?pli=1#

@eidolonnight approved, and I published the final live here: https://make.wordpress.org/marketing/2022/03/08/notes-global-marketing-team-march-2-2022/

**Comment by nalininsbs** [comment]
Thank you for writing this @bjmcsherry and volunteering.  There are some Slack IDs in the post, would you be able to update them please with WordPress.org IDs? When you do a preview of the notes, if a Slack logo appears before the name, this means it is a Slack ID. Thank you.
