### ISSUE TITLE
2022/9/14 Global Marketing Team Meeting and week planning

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#110]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
[Coffee break card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by nalininsbs** [comment]
Social question: Which sport do you most like to watch? How would you recommend it to others?

**Comment by yashwardhanrana** [comment]
I can do the notes for this one. Thanks!

**Comment by murillol** [comment]
Script: https://docs.google.com/document/d/1-LXQov88uz9OZxCeHt3PJ6NIWImalBlegXaqMpcC4Go/edit?usp=sharing

**Comment by nalininsbs** [comment]
Agenda https://make.wordpress.org/marketing/2022/09/14/agenda-wordpress-global-marketing-team-meeting-september-14-2022/

This includes some changes from the draft following conversations at and around WordCamp US and ongoing accessibility discussions:
- to display and spacing 
- links to GitHub setting up an account and mentioning it is free to have an account
- adding in some additional numbering
- how the time is added
- making the newer information on how to get involved in planning into a heading section to make it easier for accessibility
- a few more additions will be added in future weeks. These will include with some testing / discussion with other teams on listing GitHub items,

**Comment by nalininsbs** [comment]
To overcome one of the issues faced by notetakers, we need date of the meeting in the introduction and with the agenda link. This will help notetakers know they are in the right meeting. eg These are the Marketing Team from September 7, 2022 meeting. It should also help with accessibility.

**Comment by santanainniss** [comment]
Is it possible still to add something to the agenda? I'd just like to highlight this Issue, which is a call for brainstorming contribution about the Halloween episode for the WP Briefing podcast. It will be a great first issue to get our new WCUS contributors engaged! https://github.com/WordPress/Marketing-Team/issues/113

**Comment by murillol** [comment]
I planned to include the latest WP Briefing episode in section 4, so I can definitely include the call for brainstorming in that item :-)

**Comment by murillol** [comment]
The draft of the notes by @yashwardhanrana are here: https://make.wordpress.org/marketing/?p=9950&preview=true

I'm having a hard time with a few WordPress ID's, for instance Courtney's and Hauwa's. Can you check it if you have time please @nalininsbs? Other than that I think they're good to go.

**Comment by nalininsbs** [comment]
I added what the abbreviations stood for, and the Learn WordPress item which was in Open Floor, clarified the reference to the handbook.

@abhansnuk if you are around can you add the link to the walkthrough transcript and two other threads added in the notes.  I have checked the other items @murillol .

**Comment by abhansnuk** [comment]
All done. Updated the categories and shortened the excerpt. Moved the contributor story update to the Contributor events section and shared the WCAsia card.

**Comment by abhansnuk** [comment]
Published link https://make.wordpress.org/marketing/2022/09/20/notes-global-marketing-meeting-september-14-2022/

I will create the other GitHub cards for you after my next recording. If there is anything else you want help with on GitHub, just add it to the list. Thanks @murillol, @nalininsbs, and thanks @yashwardhanrana . I can add that item about Next meeting to the card to update the notes for you later too.

**Comment by abhansnuk** [comment]
Nalini I can see the milestone issue you documented and replicate it. I will share with Meher and Chris, and we will find a solution. Thanks for reporting it.
