### ISSUE TITLE
Polyglots Team September 2022 newsletter - marketing input

### ISSUE THREAD

**Issue by naokomc** [WordPress/Marketing-Team#115]
Here's the draft of the September Polyglots newsletter that @varlese and I put together.
P2 version: https://docs.google.com/document/d/1rvt5_dE8FwtDr-rCwqK43Hm2zxI8igXZEO7oKZfa454/edit#
Email version: https://docs.google.com/document/d/1R0Xy00NgTEOAws2itxJQbUMh9E3_SQ-GJ6pqHVdHM-c/edit
It would be great if Marketing Team could take a look. Thanks!

@abhansnuk @murillol (since you've shared feedback in the past, but anyone's input is welcome)

**Comment by abhansnuk** [comment]
Updated the milestone for this card with the new publication date posted by Erica in the marketing slack channel.

**Comment by varlese** [comment]
[And the September newsletter is now live.](https://make.wordpress.org/polyglots/2022/09/30/polyglots-monthly-newsletter-september-2022/) Thank you @abhansnuk for your help!
