### ISSUE TITLE
Polyglots Newsletter - March 2022

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#12]
This is due to go out in the third week of March 2022.

Cross-link to GitHub card on video and image work for this: [Gautum [](video](https://github.com/WordPress/Marcomms-Rolling-tasks/issues/77).)

**Comment by nalininsbs** [comment]
17 March 2022: Link from Naoko to draft of Polyglots Newsletter March 2022 - [Slack [](thread](https://wordpress.slack.com/archives/C0GKJ7TFA/p1647526204435329?thread_ts=1645083348.674109&cid=C0GKJ7TFA)) 
[Link to document](https://docs.google.com/document/d/1TMUPVXURQcLo_VXk2UcXz05QtaH6Wo6AXOCC0Lrerfg/edit#)

**Comment by abhansnuk** [comment]
Published post at https://make.wordpress.org/polyglots/2022/03/22/polyglots-monthly-newsletter-march-2022/

Be A Translator video featured in this edition: https://youtu.be/cx5CU5vrAAc
Polyglot contributor Gautam Navada ([vgnavada](https://profiles.wordpress.org/vgnavada/)) 

Contributors from marketing: WP.org IDs: webcommsat, adeebmalik, nalininonstopnewsuk, anjanavasan
