### ISSUE TITLE
2022/11/02 Global Marketing Team meeting and planning

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#121]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by abhansnuk** [comment]
Robin confirmed for notes on 2 November 2022.

**Comment by robinwpdeveloper** [comment]
Please assign this card to me. 
I have confirmed taking notes on Nov 2, 2022.

Thanks for giving me the chance.

**Comment by nalininsbs** [comment]
Possibly for the agenda - 6.1 media sharing https://github.com/WordPress/Marketing-Team/issues/135. Message sent to Reyes.

**Comment by rmartinezduque** [comment]
Confirming here that https://github.com/WordPress/Marketing-Team/issues/135 can be added to tomorrow's agenda. Thanks!

**Comment by robinwpdeveloper** [comment]
Draft added in this [google doc](https://docs.google.com/document/d/1OB8yioXnKj9kh8yB4Fz-IU-6WUQ78S5tGCtMsIPOHfQ/edit?usp=sharing)

**Comment by robinwpdeveloper** [comment]
[Note draft](https://make.wordpress.org/marketing/?p=10264&preview=true) added on P2 blog site.
@nalininsbs @abhansnuk please let me know if any correction is needed. 

Thanks.

**Comment by nalininsbs** [comment]
Hello @robinwpdeveloper and thank you.
- added past tense for a few items
- added Reyes' update from the thread
- there was no update on the release marketing itself, in case this is coming, added a note on this to go with your link to the thread
- added Lauren's update on the video from Slack
- removed the items which were to assist contributors joining during the live part of the session, eg continue to add to threads
- added categories
- added excerpt
- changed tenses and put updates in reported format. Specific quotes marked where needed
@abhansnuk can you go through and add any GitHub cards and links with text.

**Comment by nalininsbs** [comment]
Published: https://make.wordpress.org/marketing/2022/11/07/notes-global-marketing-team-meeting-november-2-2022/

**Comment by nalininsbs** [comment]
Props list: @robinwpdeveloper , @abhansnuk , @nalininsbs , @rmartinezduque .
