### ISSUE TITLE
6.1 Release Social Content Idea: "Behind the Scenes" for Twenty Twenty-Three

### ISSUE THREAD

**Issue by thetinyl** [WordPress/Marketing-Team#128]
Social media content around Twenty Twenty-Three, the new default theme that's being released with 6.1, has been received really well on the official WordPress accounts. 

Based on how this default theme came together with such strong community involvement, and how it uses style variations to further illustrate the evolution of theming, I think there's a great opportunity to share some "behind the scenes" content to drive extra excitement—both about the theme and the release. 

**Some thought-starter ideas:**

- Inspiration behind each style (as told by their authors)
- Mood boards, color palettes, other visual elements that might have inspired the styles
- A look at the creative/technical process
- How to use the style variations (possibly video)

**How can you help?**
If you have other ideas for interesting types of "behind the scenes" content that might help showcase the new theme, and highlight the way the community was involved, please share them here. 

If you wanted to help with wrangling/organizing this content from the style authors, please let me know either here or on Slack (I'm laurlittle on .org). I've also [reached out in the core-themes-projects channel](https://wordpress.slack.com/archives/C03T2GLB97W/p1664993596819649) for assistance.

**Timeline (tentative)**
- Collecting content/information from theme authors: Oct 17-Oct 28
- First round of content: Oct 31-Nov 7
- Note: Collecting ideas for additional posts is ongoing after the release.

**Additional information**
Check out the TT3 style announcement post to learn more about the theme, and the process behind its creation.

**Comment by thetinyl** [comment]
Currently working on a questionnaire to help capture information directly from style authors about their inspiration/process. (Thanks to critterverse from the Design Team for [this idea](https://wordpress.slack.com/archives/C03T2GLB97W/p1665000304133789)!)

**Comment by thetinyl** [comment]
Shared the [drafted questionnaire](https://forms.gle/BbmW8wkbKyCXF4bY6) with the core-themes-projects channel in Slack. Hoping to start circulating it to style authors this week.

**Comment by nalininsbs** [comment]
This is on today's agenda under the releases update section.
Is there a last day for contributions @thetinyl ? Thank you for raising.

**Comment by thetinyl** [comment]
Thanks for including this on the agenda @nalininsbs. And for asking about a timeline—I've updated the ticket to include some dates. 

Since this could be great content to have ongoing after the release, the dates above are flexible. If folks want to continue to share ideas after the November 1 release, they absolutely can.

**Comment by sereedmedia** [comment]
How about a Twitter Space talking to the folks who worked on Twenty Twenty-Three? WordPress loves the Twitter Space. Also, I'm sure a few folks on the Twenty Twenty-Three team would be happy to make a little video talking about their favorite part or what they worked on, and that could be edited into a Reel/TikTok. Promoting the community and contributors at the same time as promoting the new theme is such a win!!!

**Comment by nalininsbs** [comment]
Highlighted at the marketing team meeting on November 2, 2022

**Comment by thetinyl** [comment]
Great ideas @sereedmedia! I'm vaguely aware of Twitter Spaces, but haven't been involved in hosting/creating one. Do you have any experience with them? 

Here's a [spreadsheet with some the information gathered from the questionnaire](https://docs.google.com/spreadsheets/d/1SMr8BLEe7XBRYnEZdn-WWyZBTFrvxf6m6HV0Bw3YGRI/edit?usp=sharing) from which we can start putting together posts. 

I think I'm going to get started with these quick post ideas that should come together quickly:

- Carousels/multi-image posts that show the original inspiration and then the final style variation
- A breakdown of color palettes or other design elements (for style authors that included them)

**Comment by nalininsbs** [comment]
@thetinyl are you still wanting input for this? Or is there a finished item to link to it and close the task? Thank you.

**Comment by thetinyl** [comment]
Thanks for checking in @nalininsbs! I'll be sharing some content tomorrow or early next week on here. 

Would it be possible to keep this task open another week or two? Just in case what I share inspires some additional ideas with others on the team.

**Comment by thetinyl** [comment]
Want to share the first in this series of posts that went live on social, featuring @luminuu's style variation "Pilgrimage":

- [Instagram](https://www.instagram.com/p/Cl6aXBJMlPo/?igshid=YmMyMTA2M2Y=)
- [Twitter](https://twitter.com/WordPress/status/1600910612443369472)
- [Facebook](https://www.facebook.com/WordPress/photos/a.10158758550782911/10160328562732911/?__cft__[0]=AZX5Fz505QHZowqWTdTzZbQMDrUagH-oRg17iAJW5rIelS3Y68WMcQoNuEllD2He60W4b7HoaBovb8hrFCEiocyR-L91qeXE8QmaSLUxR4LgGMPvOafeCIvG3ypgVPps0VGs5cptGyXNJei0UVXnyv1rAaNU_6q9D6DziU4wanueBROIi8OXTabTbWqwavxWvgBN5ssYZPwTKE5zS_EV4fX0&__tn__=%2CO%2CP-R)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_wordpress-activity-7006621169676099585-Flco?utm_source=share&utm_medium=member_android)

Note that the bulk of the content is being posted on Instagram (with the other platforms pointing to IG to see more content).

**Comment by nalininsbs** [comment]
@thetinyl do you want to share your update in the team meeting this week? Thank you for sharing above.

**Comment by thetinyl** [comment]
@nalininsbs Sure. Happy to share the above update and another one with the second batch of content:

Posts featuring @amjadr360's style variation "Grapes":

- [Instagram](https://www.instagram.com/p/CmPAQX9sGKa/)
- [Twitter](https://twitter.com/WordPress/status/1603776996433092613)
- [LinkedIn ](https://www.linkedin.com/posts/wordpress_wordpress-activity-7009555503185854464-e5Uj)
- [Facebook](https://www.facebook.com/WordPress/photos/a.10158758550782911/10160344950282911/?__cft__[0]=AZVgWBvtzHDFsLRj1qFgA-5Nmbh7v8mAfiqIzIyWvSzGHxiUDyXhRYcXeJhd6coM8qgF_UjiTL0pXD3VsclV8qqijRQ9qnrYp1F87mF8Q6B-hyzV_9XQe99I45CeiIXNPjjjoMi2TrMDOYu29S6EPzDsnGsb6Mt3t7Sv-G70LIIk5xiw1JTLXiip0Td6KLht0ykqWlCmwhK8ZQxvwO7aFT3J&__tn__=%2CO%2CP-R)

**Comment by sereedmedia** [comment]
Can this be updated to be for 6.2 instead of 6.1? One of the marketing team reps @robinwpdeveloper is on the 6.2 team so we could like take advantage of this alignment to setup a process for promoting Behind the Scenes snippets/contributor profiles for each release.

Not sure if it would be better to close this and make a new card for 6.2? But I wouldn't want to lose the ideas etc. @abhansnuk any ideas for card mgmt?

**Comment by abhansnuk** [comment]
Hello, suggest a new card for 6.2 as this was specifically for 6.1. But suggest you wait for @jpantani and @marybaum who are co-leads for marketing comms of the release. 

Marcomms is wider than the marketing team and as the squad has only just been announced last week. I am sure they will both want to encourage involvement from the marketing team too 😀.

Keeping a separate 6.1 card @sereedmedia also makes it easier for other teams who might be continuing to work on docs and training materials relating to that release, and might want to see what social media was focusing on.

**Comment by thetinyl** [comment]
@sereedmedia I'd agree with @abhansnuk about starting a new card for 6.2. This card in particular is focused specifically around the Twenty Twenty-Three default theme (a highlight from 6.1). Having a fresh card might make it easier to follow new ideas that relate to 6.2.

**Comment by jpantani** [comment]
Agreed. This should be a fresh card for 6.2 
Also just stating for the record that @thetinyl is also a MarComms co-lead.

**Comment by sereedmedia** [comment]
@thetinyl Could you close this card and possibly make the new one for 6.2?

**Comment by abhansnuk** [comment]
Just adding to Jonathan's message above, @MaryBaum, another member of the Marketing Team, is a MarComms co-lead for 6.2 too. Just as info to assist @sereedmedia, there are a few other marketing team members on the release squad or involved in different parts of the release again this release,
