### ISSUE TITLE
October 2022 Polyglots Newsletter - Marketing input

### ISSUE THREAD

**Issue by varlese** [WordPress/Marketing-Team#129]
Hi Marketing team! The next Polyglots monthly newsletter is coming up soon, and I'd like to request some Marketing feedback and review once the email and P2 drafts are ready. I'll add those here as soon as we have them. 

Expected publish date is October 21, 2022.

**Comment by varlese** [comment]
Here is the link to the email draft: https://docs.google.com/document/d/1twxJvfcMLlfK0UxthnGB4BJ1oah-lkUkk8qOrq-AUxc/edit?usp=sharing

And here is the link to the Make/Polyglots draft: https://docs.google.com/document/d/14_XOF1yuUi0w0CZK7-im6CIwaNeXY65o2_FeDKVN9rU/edit?usp=sharing

**Comment by abhansnuk** [comment]
Hi @varlese I have added some comments and suggestions. Some exciting tools coming up, they sound great.

**Comment by varlese** [comment]
[The October newsletter is now published.](https://make.wordpress.org/polyglots/2022/10/21/polyglots-monthly-newsletter-october-2022/) Thank you for your help!
