### ISSUE TITLE
People of WordPress - October 2022

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#132]
(moving across card from old repo as name reconfirmed)

**Comment by nalininsbs** [comment]
@meherbala is leading on this and in communication with the person being featured. Thank you for also picking up some of the drafting and research on this Meher.

A discussion on links to WP Accessibility Day and cross links to WordPress.tv accessibility videos has started.

**Comment by abhansnuk** [comment]
Meher has confirmed and is liaising with Raghavendra Satish Peri, who is to be featured in this edition.

**Comment by meherbala** [comment]
Yes I am working with Raghavendra and will send an update soon.

**Comment by nalininsbs** [comment]
Meher has the updated from Raghavendra, and will be sharing queries at a collaboration session after dev chat today. Thank you Meher for all your work on this and stepping in to cover other aspects too.

**Comment by meherbala** [comment]
As I have written in the Google document 

> As of 07-10-2022, there is no revised version of the original article. I had a call with Raghavendra today and I will be coordinating with him directly to work on his article. I will update this document by the 21st Oct with the revised version.

----

**Update as of 27-10-2022:**

[Link to the Google document](https://docs.google.com/document/d/1fbriD6fnatXJp7oYDuJSQBboc4ArV8IPFyeooQU6kj0/edit?usp=sharing) for the POWP Oct month.

Moved the article to the editing phase with @Bringmannn, @abhansnuk, and Mary (for some reason I am unable to tag Mary). 

@murillol please can you take a look at the sub-headings and SEO?

**Comment by meherbala** [comment]
Thanks, @murillol. I accepted all your suggestions.

**Comment by meherbala** [comment]
**Update:**

Due to Raghavendra's health, he does not have many photos and he suggested I use the pictures from his Facebook account. 

I have downloaded a few, resized them, and uploaded them to P2.

I am coordinating with Raghavendra on the few points mentioned by Abha and get it resolved by tomorrow.

Hoping by tomorrow the article will be on P2, ready to be published.

**Comment by meherbala** [comment]
POWP Article has been published. 

https://wordpress.org/news/2022/10/people-of-wordpress-raghavendra-satish-peri/

**Comment by meherbala** [comment]
Thanks to @abhansnuk, and Surendra Thakor for the interviews and for writing this feature, and to Mary Baum, @Bringmannn, and @murillol for reviews.

**Comment by nalininsbs** [comment]
Props for this article: @meherbala , @abhansnuk , @sthakor, @Bringmannn , @murillol .

**Comment by nalininsbs** [comment]
This will be reopened post release work in training for translation into Hindi.
