### ISSUE TITLE
People of WordPress - Maedah B

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#133]
Moving across from old board https://github.com/wpmarketingteam/Marcomms-Series/issues/7

**Comment by abhansnuk** [comment]
Group message sent to Maedah, listed in planner to check on update. Draft has some fact checks and recent updates to complete. Ali and Larissa to be added to this as assignee. Mary highlighted queries in the draft.

**Comment by abhansnuk** [comment]
January was confirmed as Hauwa, if December is a month to skip as New Year's Eve. If not, then Hauwa for Dec edition.

**Comment by murillol** [comment]
> Group message sent to Maedah, listed in planner to check on update. Draft has some fact checks and recent updates to complete. Ali and Larissa to be added to this as assignee. Mary highlighted queries in the draft.

Do we have an email address for Maedah (just in case)? I haven't seen her online in a really really long time and suspect she might see the message when it's too late @abhansnuk

**Comment by meherbala** [comment]
FYI For Nov and Dec editions, I will be able to only help with the images.

**Comment by nalininsbs** [comment]
Depending on whether we hear back on September's, we will be able to use this later in the year. Thank you for trying to contact Maedah.

**Comment by meherbala** [comment]
_For Nov my only request is to provide me the images at the earliest so I can process and upload them to P2 as from Nov end I will be on a break until Jan end._

**Comment by abhansnuk** [comment]
[Draft](https://docs.google.com/document/d/1ORut1J16WJyCqoO0_TyqIlS72XQxcY92ZlpmFYHz-HU/edit) as it stands at the moment (this is not complete).
To check with Alison if this include any follow up information received from Maedah, remaining queries.

**Comment by meherbala** [comment]
> I messaged Maedah last week on LinkedIn but have not received a response yet.

@murillol according to her tweet account, it looks like she is attending the nextjs.org conference. So maybe she has not yet seen your message on LinkedIn.

Maybe contact her on Twitter.

**Comment by abhansnuk** [comment]
Message sent to Maedah via her website contact form and sent a message via Twitter. Thanks Meher.

**Comment by murillol** [comment]
Was able to get in touch with Maedah via email, she is open to answering fact-checking questions and providing more context where needed. Abha now has her email too and I've shared a document with some questions for Maedah to answer.

**Comment by abhansnuk** [comment]
Moving @nalininsbs comment from the old card to this:
[Google document](https://docs.google.com/document/d/1ORut1J16WJyCqoO0_TyqIlS72XQxcY92ZlpmFYHz-HU/edit?usp=sharing) - there are a number of queries that need to be checked with Maedah including items for updating. Last week, contact was remade with Maedah from messages. Date to be confirmed for a call to go through these.

This is scheduled for the November 2022 edition.

**Comment by murillol** [comment]
I shared [this document](https://docs.google.com/document/d/1Wq6EnpYPl-8gORnRYb8Jh7Z4VFRwHjBArTD1eVo6mpE/edit?usp=sharing) with questions for Maedah and asked her to have it done by end of next week, and also asked her to share photos.

**Comment by nalininsbs** [comment]
Thank you @murillol for copying all the questions from the documents into one document for Maedah. Do we have photographs, which are copyright free to use, from Maedah please?

**Comment by murillol** [comment]
I also had added some other questions that weren’t in the document - please
see if they’re ok! I asked Maedah for photos, she hasn’t sent any yet.

**Comment by murillol** [comment]
I followed up with Maedah today about the photos and whether she can make the November 12th deadline.

**Comment by murillol** [comment]
Update: Maedah replied and said she would have some respones for us by 12 November (today).

**Comment by murillol** [comment]
**Update**: Maedah has sent in answers! Still no photos, I've asked again :)

**Comment by murillol** [comment]
@abhansnuk Not sure if you saw my previous message! Maedah's answers are in the shared document (I've also pasted them in the working document). She still has not shared any photos.

**Comment by abhansnuk** [comment]
Thanks Larissa. We need pictures to publish and edit time for these too. Can you follow up please @murillol. We need images in the next few days, really by Thursday. Thanks for the update. cc @meherbala and @marybaum to alert on delay on photos.

**Comment by murillol** [comment]
I am following up every other day! I will be travelling from
Wednesday-Friday with limited internet access, if you can also email her
about the photos that might help too!

**Comment by abhansnuk** [comment]
Thanks @murillol and for all the follow ups on this one. We still have gaps in content. I have added some questions into the information at the bottom. I will email Maedah too and see how we can help her with the remaining items.

**Comment by abhansnuk** [comment]
As at November 27, 2022, pictures and some information needed. This feature will be swapped with the postponed September edition. This will enable more time to gather the information. Thanks to @meherbala for stepping in to check through what is needed to do this and reviewing items. Thanks to @murillol for follow ups. Thanks to @Bringmannn @marybaum and @nalininsbs for the discussions and any rechecks.

**Comment by abhansnuk** [comment]
Moved to 2023 in discussion with Chloe. Information and pictures for feature - need more time.

**Comment by abhansnuk** [comment]
Updates:
- follow-ups resent 
- email 23 Jan to assist with pictures and to arrange a call to gather remaining research and links
- once above done, publication date can be confirmed. Moved for provisional Feb 2023 publication. This would be good timing with WCAsia on Feb. 
- Follow-ups include: Abha, Larissa, Meher, Maja, Mary, Chloe.

**Comment by abhansnuk** [comment]
This ticket can be closed for now. It can be reopened in future as needed.

Thank you to everyone who has given time to this feature.
