### ISSUE TITLE
WordPress Media Outreach

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#135]
To help support the marketing efforts of the major release, I'll be working with the [Marketing & Communications co-lead](https://make.wordpress.org/core/6-1/) (@jpantani) to send summarized information on WordPress 6.1, based on the community’s collaborative effort on the [About page](https://docs.google.com/document/d/1gnoOTQ8RuT_NTEgt3RtAc8KiwsAw73C4wEABNWuJADo/edit?usp=sharing) and the release post at [WordPress.org/news](http://wordpress.org/news), to some WordPress and tech media outlets.

These efforts are new, so the media list is currently not very extensive. Targets include WP Tavern and Post Status, and others not exclusively related to WordPress but who could help create additional visibility for the WordPress project and community, such as Search Engine Journal, which normally covers WordPress major updates.

### How can you help?

If you have suggestions for reliable media outlets (and a point of contact preferably) that could benefit from having this information, please feel free to share them as a comment on this GitHub card (without disclosing contact details). That will allow us to create a media list for future releases as well. Thanks!

**Comment by nalininsbs** [comment]
@rmartinezduque will you be able to share more on this at this week's Marketing meeting? Thank you

**Comment by rmartinezduque** [comment]
Hi @nalininsbs, yes. My idea was to share this during tomorrow's meeting. Thanks!

**Comment by sereedmedia** [comment]
I know at least one podcast you could hit up! 😄 

Is there a doc for this? If we are making list with actual contacts, then we should not post them here. 

However if it is WordPress media you want: https://wppodcasts.com/

WPPodcasts is basically a compilation of all of the WordPress-themed podcasts. It was created by [Topher](https://profiles.wordpress.org/topher1kenobe/) of Photos and Support Team renown.

**Comment by nalininsbs** [comment]
@rmartinezduque do you still want input on this card? Is there a deadline for this? Thank you.

**Comment by rmartinezduque** [comment]
Thanks for the suggestions, @sereedmedia!

> Is there a doc for this? If we are making list with actual contacts, then we should not post them here. 

I agree! There's no doc yet, and I'm wondering how we can build this without disclosing contact details publicly. 🤔 Perhaps one option is to simply share links to the media's site in a collaborative spreadsheet. I'll think about some options this week.

> @rmartinezduque do you still want input on this card? Is there a deadline for this? Thank you.

@nalininsbs, thanks for checking in. I think it would still be useful to build a media list for future releases and major announcements. So suggestions are welcome any time. I edited the title of the GitHub card to make it clear that this is not a task just related to the 6.1 release, but more of an ongoing effort.

**Comment by sereedmedia** [comment]
This issue is relevant again in light of the upcoming 6.2 release. Perhaps we could generate an open list of relevant publications and link that folks can add to, and we can keep contact information in a more secure place.

It would be great to have a spreadsheet with a basic list (with no PID available) for WCAsia contributors to use, as I think we would be able to compile some publications outside of the standard (US-centric) WP media pool.

**Comment by rmartinezduque** [comment]
Thanks for following up on this, @sereedmedia.

> Perhaps we could generate an open list of relevant publications and link that folks can add to, and we can keep contact information in a more secure place.

Yes! I've actually moved the list I'm building to this spreadsheet: https://docs.google.com/spreadsheets/d/1y5BAFvLIeRb_FkhqqRFzDFeWlpnGzcUvScSBY3ueprI/edit?usp=sharing. Right now, it's focused on WP news sites, podcasts, and newsletters. I have not added any contact info.

> It would be great to have a spreadsheet with a basic list (with no PID available) for WCAsia contributors to use, as I think we would be able to compile some publications outside of the standard (US-centric) WP media pool.
I'm interested in hearing more about this. What is PID? :) And do you mean they can help by adding media outlets to the list?

In that case, perhaps it would be good to consider some kind of criteria. For example, I think it doesn't make much sense to include blogs whose content is more focused on tutorials for now. I can also divide the spreadsheet into different tabs by region (e.g. America/Europe/Asia/Africa, etc), although it may not be very useful at the moment.

**Comment by rmartinezduque** [comment]
Information about WordPress 6.2 was sent to some media outlets on March 29, 2023, including Search Engine Journal, TechSpot, TechRadar, Ars Technica, Cloud7, and WebDesignerDepot. I'm still monitoring links. I'll be away from keyboard (AFK) this week and will share any relevant updates from coverage upon my return (April 10).

**Comment by sereedmedia** [comment]
> I'm interested in hearing more about this. What is PID? :) And do you mean they can help by adding media outlets to the list?

Sorry, I meant PII! Personally Identifiable Information.

> And do you mean they can help by adding media outlets to the list?

Yes, contributors can add suggestions for less well-known media outlets, such as those that are more popular in specific regions or those that are in other languages.

**Comment by sereedmedia** [comment]
> Information about WordPress 6.2 was sent to some media outlets

I'd love to read the press release you sent out, @rmartinezduque! Perhaps that is something we can do via GH for the next round, just opening it for comments and suggestions as with the About page edit process.

**Comment by jpantani** [comment]
I'm not sure the process for media outreach needs a period open for comments and suggestions. The team is actively involved/invited in the About Page and General Announcement post feedback processes, which is a source of truth for marketing purposes. That said a certain amount of transparency in what's being sent out, to me, seems sufficient, and I'm sure @rmartinezduque would not mind sharing.

**Comment by rmartinezduque** [comment]
> I'd love to read the press release you sent out, @rmartinezduque!

Sure, @sereedmedia. Just to clarify, I didn't send any specific press releases but simply reached out to a few media outlets to inform them of the 6.2 release. This is what the outreach email included:

> WordPress [announced today](https://wordpress.org/news/2023/03/dolphy/), March 29, 2023, the release of WordPress 6.2 “Dolphy.”
>
> This major release consolidates the block editing experience with significant updates like a revamped site editing interface, new styling features, and a distraction-free writing mode—easing users to bring their creative ideas to life without code. Moreover, a new integration with [Openverse](https://openverse.org/) (formerly CC Search) enables quick access to 700 million+ free, openly-licensed images and audio. Visit the [WordPress 6.2 “Dolphy” announcement](https://wordpress.org/news/2023/03/dolphy/) for a complete list of features. High-resolution assets are available in [this media kit](https://drive.google.com/drive/folders/1dh-P8BVRGowvI6ckf0th6Rkhc41lfhwc?usp=share_link).
>
> This is one of the last major releases planned before entering Phase 3 of the WordPress roadmap, Collaborative Editing, and falls in celebration of the [project's 20th anniversary](https://wordpress.org/news/2023/01/wordpress-is-turning-20-lets-celebrate/).

I agree with @jpantani that opening this up for feedback and comments may not be especially useful in this case, given that what we send out is based on the About page and release post at /news. Also, while I'm in favor of making the process as transparent as possible, I'm generally somewhat reluctant to share upfront and in a public way information to be sent to media outlets, as it may result in it leaking out of our control. For future releases, I would suggest following the same approach and working with the release leads to send any relevant information.

**Comment by rmartinezduque** [comment]
Circling back here to share some links from WordPress 6.2 coverage, which saw no major changes with respect to the previous major release. It came mainly from WordPress-related media and company blogs that offered a walkthrough of the new changes in a neutral to positive tone. There are certainly more, but here are some links (in English) I found, published on or after the release day:

- WP Tavern: [WordPress 6.2 “Dolphy” Introduces a Revamped Site Editor, Distraction-Free Writing Mode, and Updated Block Inserter](https://wptavern.com/wordpress-6-2-dolphy-introduces-a-revamped-site-editor-distraction-free-writing-mode-and-updated-block-inserter)
- Post Status: [Tech Roundup Week Ending March 31](https://poststatus.com/tech-roundup-week-ending-march-31/)
- Cloud7: [WordPress 6.2 “Dolphy” is now available](https://cloud7.news/development/wordpress-6-2-dolphy-is-now-available/)
- The WP Minute: [Beta label removed, Assistant Pro, more acquisitions](https://thewpminute.com/beta-label-removed-assistant-pro-more-acquisitions/)
- Torque Social Hour: [Talking WordPress 6.2 with Aurooba Ahmed](https://torquemag.io/2023/03/torque-social-hour-talking-wordpress-6-2-with-aurooba-ahmed/)
- Press This: [What’s New in WordPress 6.2](https://redcircle.com/shows/0c33a225-47e8-4b48-aae7-d1eff5ea2470/ep/ff69c126-e18b-4772-84f7-271cae9cffc6)
- Yoast: [WordPress 6.2: A new site editing experience](https://yoast.com/wordpress-6-2/)
- Kinsta: [What’s New In WordPress 6.2: Browse Mode, Style Book, Improved Navigation Menus, New APIs, and Much More](https://kinsta.com/blog/wordpress-6-2/)
- WPBeginner: [What’s New in WordPress 6.2 (Features and Screenshots)](https://www.wpbeginner.com/news/whats-new-in-wordpress-6-2-features-and-screenshots/)
- ManageWP: [What’s new in WordPress 6.2: Dolphy](https://managewp.com/blog/whats-new-in-wordpress-6-2-dolphy)
- kitchensinkWP: [Podcast E476 – WordPress 6.2](https://kitchensinkwp.com/podcast-e476-wordpress-6-2/)
- Vipe Studio: [WordPress 6.2 “Dolphy” Release is here ~ Let’s Check What’s New](https://vipestudio.com/en/wordpress-6-2-dolphy-release-is-here-let-s-check-what-s-new/)
- InMotion Hosting: [Seven Major Changes in WordPress 6.2](https://www.inmotionhosting.com/support/edu/wordpress/wp-releases/seven-changes-in-wordpress-62/)
- Hostinger: [WordPress 6.2 Is Finally Here: A Detailed Overview](https://www.hostinger.com/blog/wordpress-6-2)
- WPExperts: [WordPress 6.2 – Exciting Features and Improvements to Watch Out For](https://wpexperts.io/blog/wordpress-6-2/)
- DevriX: [WordPress 6.2: What to Expect?](https://devrix.com/wordpress-6-2/)

Others published before the release date include:
- GoDaddy: [What’s new in WordPress 6.2: Dolphy](https://www.godaddy.com/garage/whats-new-in-wordpress-6-2/)
- WPDeveloper: [WordPress 6.2 Is Here: Improved Site Editor, Openverse Integration, And More!](https://wpdeveloper.com/wordpress-6-2-release/)
- iThemes: [What to Expect in WordPress 6.2](https://ithemes.com/blog/what-to-expect-in-wordpress-6-2/)
- WPwatercooler - [EP447 – What’s New in WordPress 6.2?](https://wpwatercooler.com/wpwatercooler/ep447-whats-new-in-wordpress-6-2/).

Feel free to share any additional links.

**Comment by rmartinezduque** [comment]
I'm going to close this issue since there have been no further actions in a while. For any media efforts related to WordPress releases, we can always track them down in their relevant GitHub issues. As a reminder, [this is the one for 6.5](https://github.com/WordPress/Marketing-Team/issues/356).
