### ISSUE TITLE
WordCamp Kolkata - Contributor Day, 17 Dec 2022

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#136]
Update following the marketing meeting on October 26, 2022:
Potential Marketing Team table will be available at this event.

Mumtahina Faguni: Kolkata WordCamp will be on 17 & 18 December 2022. & 17th Dec will be the contributor day. Though call contributor lead for contributor isn’t open yet, it will be asap. 

rahuldsarker: Yes, we will have a contributors day. We will reach out for assistance very soon.

**Comment by nalininsbs** [comment]
This item has been raised at weekly Marketing meetings. No further information has come from the WordCamp so far.  I will share again in Slack today.

**Comment by nalininsbs** [comment]
Nothing further on this. Closing the card.
