### ISSUE TITLE
Marketing Notes roster/ rota

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#138]
I am looking at using GitHub features for this rota. This is a temporary holding card requested by @nalininsbs , which will be converted to the GitHub beta feature later this week. 

For now, forward planning rota in slack for greater visibility. This is shared in meeting notes and meetings themselves too. https://wordpress.slack.com/archives/C0GKJ7TFA/p1664956621412719

**Comment by abhansnuk** [comment]
[October 5](https://github.com/WordPress/Marketing-Team/issues/116) - 
[@Adeeb Malik](https://wordpress.slack.com/team/U02V93FUT6E)
 is confirmed for October 5 (offered online group session to get started)
[October 12](https://github.com/WordPress/Marketing-Team/issues/117) - Robin is already confirmed (offered online group session to get started)
October 19 - 
[@Kawser](https://wordpress.slack.com/team/U03UA1CCQ07)
 will be doing his first notes. Abha and Meher - can you please include Kawser in the session to help new notetakers.
October 26 - 
[@vimes1984](https://wordpress.slack.com/team/U0337R5K8)
 could you do the notes from the meeting on October 26?
November 2 - asked 
[@Robin](https://wordpress.slack.com/team/U02762E2W9G)
 if November 2 notes also works for him
November 9 - 
[@YashwardhanRana](https://wordpress.slack.com/team/UBVQG2RBR)
 could you take this?
November 16 - 
[@Maja Loncar](https://wordpress.slack.com/team/UJ4NS3LGL)
 could you take this?
November 23 - 
[@Ugyen](https://wordpress.slack.com/team/U7B8WJNRZ)
 could you take this?
November 30 - 
[@Shanta (slspeller911)](https://wordpress.slack.com/team/U0429NQHAU9)
 could you take this? Congratulations to Shanta for her first notes published yesterday!

**Comment by robinwpdeveloper** [comment]
I am interested taking notes (1 or 2) on December as well. 
If no one is interested then feel free to add me. :)

**Comment by deshabhishek007** [comment]
I can take notes on 28th Dec Meeting.

**Comment by abhansnuk** [comment]
Hello. The meeting has been cancelled for 28 Dec @deshabhishek007. I see from Slack today, a question has gone to @slspellar911 about two dates in December. Perhaps when Shanta has replied, if there is another date available in December, you could do that. Thanks for volunteering.

**Comment by abhansnuk** [comment]
**December 2022**

[30 November 2022](https://github.com/WordPress/Marketing-Team/issues/125) GitHub #125  - @Shanta Speller
[7 December 2022](https://github.com/WordPress/Marketing-Team/issues/143) GitHub #143 - @Shanta Speller
[14 December 2022](https://github.com/WordPress/Marketing-Team/issues/144) GitHub #144 - @robinwpdeveloper
[21 December 2022](https://github.com/WordPress/Marketing-Team/issues/145) GitHub #145 - waiting to hear from one of the new volunteers

28 December 2022 - no live meeting, please add updates to the relevant task’s GitHub card.

**Comment by nalininsbs** [comment]
Update: notes for 30 November 2022 done by @murillol and 7 December 2022 by @nalininsbs .  
21 December 2022 notes volunteer @vimes1984 .

2023 team reps will be able to add January 2023 summary onwards. @deshabhishek007 if you would like to volunteer for one of the January notes, you would be welcome. Same for any previous volunteers and team members. Thank you all and for those who have supported new contributors in using the blog site.

**Comment by Ghimbgida** [comment]
- [ ] AMAN EBRAHIM

**Comment by robinwpdeveloper** [comment]
@abid112 and @mahbubshovan interested to take notes. 
May be we can add them in the January notetakers list.

**Comment by abhansnuk** [comment]
Adding @sereedmedia to this card.

**Comment by nalininsbs** [comment]
Handover to the new team reps for 2023. To add to the list of interested volunteers for 2023: @deshabhishek007 volunteered on November 16, 2022.

**Comment by sereedmedia** [comment]
Hi all! Meetings for 2023 will be Tuesdays at 15:00 UTC, with the first meeting of the year on January 17. Dates for January and February that need notetakers:

- January 17
- January 24
- January 31
- February 7
- February 14
- February 21
- February 28

Tagging volunteers who previously expressed interest in note-taking: @deshabhishek007, @abid112, @mahbubshovan

**Comment by robinwpdeveloper** [comment]
Nominating @abid112 for January 24 and 31

**Comment by robinwpdeveloper** [comment]
Updated January notes rota.

**Comment by robinwpdeveloper** [comment]
@mumtahinafaguni, @Afrin29 volunteered for the month of February.

**Comment by robinwpdeveloper** [comment]
Hi @deshabhishek007. 
Thanks for volunteering.

Can you take February 14 meeting note?

**Comment by robinwpdeveloper** [comment]
Note takers list updated for the month of February.

**Comment by becreativemkt** [comment]
@robinwpdeveloper, add me for the first week of March! Thank you!

**Comment by sereedmedia** [comment]
Closing this, as it is out of date. We have finalized the new notes taking process, but we need to properly document it so we can get note-taking volunteers again. Will close this Rota card and followup with new processes on this card: https://github.com/WordPress/Marketing-Team/issues/194
