### ISSUE TITLE
The Month in WordPress: November 2022 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#142]
The estimated publishing date for the November 2022 edition of The Month in WordPress is **December 20, 2022**.

### How can you help?

You can help by collecting any news or Make team updates that would be valuable and relevant to the post, such as:

- Announcements or significant news from Make WP teams
- Major updates or news from flagship WordCamps (WordCamp US, WordCamp Asia, and WordCamp Europe)
- Testing and feedback calls

Please **add them as a comment to this GitHub card with its relevant link and a brief description** by Wednesday, December 14, 2022, if possible. For example:

> The Training Team shared a new post on [how to become an online workshop facilitator or tutorial presenter](https://make.wordpress.org/training/2022/09/30/become-an-online-workshop-facilitator-or-tutorial-presenter-today/).

Alternatively, you can share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness. Please note that, for brevity, it may not be possible to include all links/updates in the final post.

The draft will be added to this card and shared in the Marketing channel prior to publication. Your review and input will be appreciated, too. If you have any questions or are unsure how to help, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of WordPress news and updates from the Make teams. It's usually published at the beginning of each month at WordPress.org/News, and it features news from the month prior to publication. To see its format and what's typically included, check out any of the [latest issues](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
@santanainniss Are there any upcoming WPDiversity events that you'd like to highlight in the next edition of the Month in WordPress?

**Comment by santanainniss** [comment]
> 

Nothing currently scheduled! But the [2022](https://make.wordpress.org/community/diverse-speaker-training-group-wpdiversity-2022-year-end-report) year end report may be of interest. That may be better for the December edition of the Month in WP?

**Comment by rmartinezduque** [comment]
Thanks, @santanainniss! I included this report in this edition: https://make.wordpress.org/community/2022/12/17/report-wpdiversity-inclusion-and-diverse-speaker-workshops-october-and-november-2022/. Please feel free to review it. If there's another one coming, we can highlight it in December's edition, yes. :)

**Comment by rmartinezduque** [comment]
**The Month in WordPress – November 2022 is now published**: https://wordpress.org/news/2022/12/the-month-in-wordpress-november-2022/. Thank you to everyone who contributed to this edition! ❤️

**Comment by rmartinezduque** [comment]
If you'd like to contribute to the next edition of The Month in WordPress, feel free to express your interest and subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/154. Thanks!
