### ISSUE TITLE
2022/12/07 Global Marketing Team meeting

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#143]
**All things related to this meeting and any collaborations during the week, including:**

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the diary dates post has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by murillol** [comment]
Script: https://docs.google.com/document/d/1L32UmCBGSiJ8to7DRfvS1alNHhkOb-i5c6N_ykVrdNY/edit?usp=sharing

**Comment by santanainniss** [comment]
Hello all, would it be possible to add the note taking process [discussion](https://github.com/WordPress/Marketing-Team/discussions/148) to today's marketing meeting agenda? 

Here is some text if it is helpful!

"Call for collaboration: help the Marketing Team review and simplify the note taking process. A GitHub discussion is currently open. Please take a look and join the discussion https://github.com/WordPress/Marketing-Team/discussions/148 "

**Comment by nalininsbs** [comment]
Added @santanainniss

**Comment by nalininsbs** [comment]
Hello @robinwpdeveloper how are you with the notes from last week's meeting? Thank you for volunteering.

**Comment by nalininsbs** [comment]
As Shanta's status is showing away, notes draft done. Thank you to @abhansnuk for accessibility items within it. Draft preview shared in marketing. Please check the links within it. Thank you. https://make.wordpress.org/marketing/?p=10467&preview=1&_ppp=71aaa277ce

**Comment by nalininsbs** [comment]
Thank you to @murillol for checking links etc. Notes published https://make.wordpress.org/marketing/2022/12/14/notes-global-marketing-team-meeting-december-7-2022/
