### ISSUE TITLE
2022/12/14 Global Marketing Team meeting

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#144]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by abhansnuk** [comment]
@robinwpdeveloper had volunteered to do the notes for this week.

**Comment by eidolonnight** [comment]
Let's collect some feedback and share [Suggest Topics for the 2023 WordPress Community Summit](https://make.wordpress.org/community/2022/12/08/suggest-topics-for-the-2023-wordpress-community-summit/)

**Comment by nalininsbs** [comment]
This will be a very good topic on WordPress Community Summit. Can there be a slot to share ideas in the meeting itself this week?


Sent message to WordCamp Kolkata on Marketing slack. The contributor day is this week. 

Team rep nominations to be progressed. Added discussion links to the GitHub card in the meantime.

Added to the GitHub cards on notes for last week and 30 November. Notes pending.

**Comment by nalininsbs** [comment]
Thank you to @robinwpdeveloper who volunteered to take notes for this week's meeting.

**Comment by nalininsbs** [comment]
@eidolonnight is there a post on the marketing description update to highlight at this week's meeting please? Thank you. https://github.com/WordPress/Marketing-Team/issues/87

**Comment by nalininsbs** [comment]
Request on the polyglots outreach newsletter card on anything for the marketing meeting. https://github.com/WordPress/Marketing-Team/issues/139

**Comment by nalininsbs** [comment]
For script, last week's meeting notes published https://make.wordpress.org/marketing/2022/12/14/notes-global-marketing-team-meeting-december-7-2022/

I can not do the tables with dictation equipment. Do we have a script template ready @murillol and @eidolonnight? Thank you

**Comment by robinwpdeveloper** [comment]
Hi @nalininsbs 
Here is the [preview](https://make.wordpress.org/marketing/?p=10492) of the note. 
Please let me know if any correction is needed.

Thanks

**Comment by nalininsbs** [comment]
Checking if notes reviewed.

**Comment by nalininsbs** [comment]
[Published notes from last week ](https://make.wordpress.org/marketing/2022/12/19/notes-global-marketing-team-meeting-december-14-2022/).

Thanks @robinwpdeveloper for drafting. I have made some small edits. I also changed the WordPress IDs to the website versions, added categories, tags, excerpt. I added GitHub card for emojis.

**Comment by murillol** [comment]
Closing as Notes have been published and final edits made by Nalini directly in the post.
