### ISSUE TITLE
Polyglots December Newsletter - review request

### ISSUE THREAD

**Issue by varlese** [WordPress/Marketing-Team#149]
I'm planning to publish this month's Polyglots newsletter on Tuesday, **December 20, 2022**. There are a few relevant posts that are still in the works, so I'm hoping to share the drafts by Wednesday, December 14. I'll leave them in a comment on this issue. 

If anyone on the Marketing team is able to help review and share any feedback on those drafts, once they're shared, that would be so helpful. Thank you for your help!

**Comment by varlese** [comment]
Here you go! 
- [Draft for Make/Polyglots](https://docs.google.com/document/d/1DDA7RNJ2w1agRRmIdnm5xyLbLKOZBYiqhOtTKqh1nms/edit#heading=h.8nazhw52twz3)
- [Email draft](https://docs.google.com/document/d/11cTwaOif8m2MxcMZe_9P2hXRTY15D371ZcQkTMHN9Y4/edit#)

On the email draft, any suggestions to make the subject and preview text more engaging are more than welcome :)

**Comment by rmartinezduque** [comment]
Hi Erica! Thanks for sharing. This looks great! I left a minor suggestion in the document, feel free to accept or reject it as you see fit. 🙂 Are you still planning to publish the Make post tomorrow (December 20)? Just asking to see if I can feature it the next edition of the Month in WordPress, which I'm also hoping to publish tomorrow or on Dec 21. Thank you!

**Comment by varlese** [comment]
Thank you so much @rmartinezduque!

Apologies for not being able to answer sooner, but we _just_ published the newsletter for the month: [December 2022 Polyglots newsetter](https://make.wordpress.org/polyglots/2022/12/20/polyglots-monthly-newsletter-december-2022/). Hoping you can still include it in the Month in WordPress 🙌

**Comment by rmartinezduque** [comment]
Yay! Thank you, @varlese. I just added a link to the newsletter, and I'm hoping to post the Month on WP in the next few hours. 🙂
