### ISSUE TITLE
People of WordPress - Daniel K

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#156]
Published January 31, 2023: https://wordpress.org/news/2023/01/people-of-wordpress-daniel-kossmann/ 

---------------------------------------------------------------------------------------------------------------------------------------
Migrating from the PofWP board.

Person to be featured: Daniel Kossmann

Continents: South America/ Brazil

HeroPress original story for partial source material upto 2021: [link](https://heropress.com/essays/tales-of-a-serial-contributor/ )

Google doc: [[link removed as published and to prevent further changes via general Internet users]]
Please only add comments in suggestion mode. 

Photos: 1 from original story. Two to three additional images needed.

Provisional date: January 2023. Potentially brought forward. 2022/12/28 discussion with contributors allocated.

**Comment by murillol** [comment]
Update: 

- first draft is in [Google Doc ](https://docs.google.com/document/d/1aH8dKYSAtpuAmHGUgs53hPb9UwtHq0b-ifcZTE88syA/edit?usp=sharing)
- Brought it down from 2395 words to 1362 and it still feels a little long but I'm not sure where else to cut content from @abhansnuk 
- Daniel has not replied regarding being available for a fact check, or about the photos. I reached out through Slack and doesn't look like he has been online at all. 
- I will definitely let you all know if/when he replies, but as mentioned I will be travelling until January 28 and will not be available for rewrites

**Comment by abhansnuk** [comment]
I will look at it this coming week. Do you want me to follow up with Daniel?

**Comment by murillol** [comment]
Yes please @abhansnuk as he still has not replied to me (and probably not seen the Slack message)

**Comment by robinwpdeveloper** [comment]
I mistakenly clicked the close button from project view issue viewer modal. Reopened again.

**Comment by abhansnuk** [comment]
Follow up contact has been successful now with Daniel via message sent by Twitter by @abhansnuk. Discussion resumed on Slack with @abhansnuk @meherbala and @murillol on interview abs updating. 

He is looking for pictures and will liaise with @meherbala on these for editing and checking. 

Additional questions resent. New quotes to be added, and links. Some parts of the journey to be reduced to enable newer information and specific quotes. 

25 Jan @marybaum 
25 Jan, then onto review of updated piece to date to Chloe.

This is now for publishing on January 31, 2023, swapped in discussion with original schedule. 

Post publication in English: Portuguese translations follow-ups / check if locale has a news page. To discuss further with Daniel - Larissa to lead.

**Comment by sereedmedia** [comment]
(Sorry clicked Close in error)

**Comment by abhansnuk** [comment]
I could not find this card yesterday, so adding the updates now. 
- More pictures came in from Daniel January 31, 2023 - edited and uploaded by @meherbala. 
- Text further reduced with options which were highlighted.
- Links to relevant meetups and WordCamps added.
- Quotes checked and incorporated fact-check changes. Additional information from Daniel added and update shared.
- @Bringmannn added updates / edits / rephrasing of highlighted items/ answered questions

- P2 tested and text adjusted for better fit and headlines adjustments as needed for layout. 
- New pictures added. 
- Alt text issue still does not show in test. 
- Readded again and should be displaying. This needs further testing and if necessary a meta ticket raised.

Published link: https://wordpress.org/news/2023/01/people-of-wordpress-daniel-kossmann/

To do:
- Google doc permissions issue with new changes made from random internet user. Doc to be checked before archived.
- Published link to be added to spreadsheet.
- Follow up query on translation.
- Recheck alt text.
- To check with Chloe what to do next on the new social media flow for news items. Twitter and Facebook no longer need to be added into post via Jetpack. Social now goes through tool being used. Excerpt still needs to be added and tested via Jetpack before publishing.
- Props to be added.
- Liaison with HeroPress for cross link and share link so they can promote.
- Send link to locale, and to Erica for Polyglots newsletter as mentions Polyglots. Shorter snippet version to be checked with Daniel for next Polyglots newsletter.
- Follow up on quotes display in new design and any information for better display.
- Still need additional SEO contributor for headlines etc alongside Larissa as two who were helping with this side have moved. Ask Chloe for suggestions.

**Comment by sereedmedia** [comment]
@abhansnuk is the translation link available yet? thank you!

**Comment by nalininsbs** [comment]
Follow up sent on translation.

**Comment by nalininsbs** [comment]
@abhansnuk or @murillol can you follow up with Daniel on translation link. Last message he was translating this. Thank you.

**Comment by kossmann** [comment]
Hi! Here is the translation link: https://br.wordpress.org/2024/01/24/pessoas-do-wordpress-daniel-kossmann/
Is there anything I can do to help with next steps?

**Comment by nalininsbs** [comment]
Thank you @kossmann and to Guga Alves, Pamela Ribeiro and Ramon Ahnert for the translation onto Brazilian Portuguese. This has been added to the original feature. 

Do you think that where we put translations into the original English language features, it would be useful to add text referring to the translation in the translated language too? We have been discussing how best to add translations for a long time. It would be useful to have your insight. As the story is in the news section for the language may be enough. We can ask again in marketing and polyglots too. Thank you for previously highlighting the importance of translating these features.

**Comment by nalininsbs** [comment]
I will close this card as specific translation is complete. 

@eidolonnight could we use discussion area now in GitHub to look at how to add translations as this is a general item? Thank you for input.
