### ISSUE TITLE
People of WordPress - Monika R

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#157]
Migrating from the PofWP board.

Person to be featured: Monika Rao

Continents: Asia

HeroPress original story for partial source material upto 2021: [link](https://heropress.com/essays/the-power-of-women-in-wordpress/ )

Google doc: [Removed working doc links as the feature has been published]
Please only add comments in suggestion mode.

Photos: 1 from the original story. Two to three additional images are needed.

Provisional date: March 2023, may move as Maedah B's feature to allocate once ready. 

Draft: Pooja had originally offered to work on this. Alison (tbc), Yvette (tbc)

More people to add to assignees.

**Comment by abhansnuk** [comment]
This has been opened for early gathering and editing of suitable images.

**Comment by meherbala** [comment]
Article published: https://wordpress.org/news/2023/04/people-of-wordpress-monika-rao/

**Comment by abhansnuk** [comment]
Just checking if there is a translation coming of this as there was some mention of this?

**Comment by meherbala** [comment]
I have asked @anandau to translate this POWP to Hindi. He will do it in the coming weekend.

**Comment by anandau** [comment]
Published the translated article on the Hindi rosetta site 
[View Post](https://hi.wordpress.org/2023/07/31/%E0%A4%B5%E0%A4%B0%E0%A5%8D%E0%A4%A1%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A5%87%E0%A4%B8-%E0%A4%95%E0%A5%87-%E0%A4%B2%E0%A5%8B%E0%A4%97-%E0%A4%AE%E0%A5%8B%E0%A4%A8%E0%A4%BF%E0%A4%95%E0%A4%BE/)

**Comment by meherbala** [comment]
@abhansnuk and @nalininsbs can we add the translated article at the end of the main article?

**Comment by nalininsbs** [comment]
I have moved this to Done for @abhansnuk as her GitHub access is not working as it should. 

Please do not close this card until the translation has been done and added.

**Comment by nalininsbs** [comment]
@meherbala do we need to use translated words for 'translation in Hindi' on the end of the English version? Picking up this question from the discussion on another card on how we add translations for the series uniformly and so they are clear. Thank you.

**Comment by abhansnuk** [comment]
I have added the translation under the Share section, and thanks to Anand in the contributors section. Suggest we amalgamate the discussion on how we add translations to a GitHub discussion. We can then mark this individual ticket as complete. 

@nalininsbs do you want to add the closing props to all involved and close this card please?

Thanks @anandau for the translation into Hindi. 

I think I saw another language translation too but can not refind the message/ post. If anyone finds it, please do add it to this card as a task to be added to the post. Thanks everyone.

**Comment by nalininsbs** [comment]
Translation is on the post with the Hindi text for the title. Thank you @abhansnuk and Anand.

There were two other translations of this. Do we have the links?
