### ISSUE TITLE
Marketing Team Reps nominations, elections and confirmations for 2024

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#158]
For awareness and diary.

Link to 2023 planning card. https://github.com/WordPress/Marketing-Team/issues/38
Thinking on this for 2023 began in September 2022.

**Comment by nalininsbs** [comment]
For 2023 team reps diary planning: @sereedmedia @santanainniss @robinwpdeveloper

**Comment by santanainniss** [comment]
In an effort to clear the project board, I am closing this issue. A new issue can be opened in the recommended timeframe of September 2023 in preparation for team reps for 2024. Thank you to all for you contributions here!

**Comment by nalininsbs** [comment]
@santanainniss this is for 2024, that is next year, so I will reopen it.
