### ISSUE TITLE
2023/1/17 Global Marketing team meeting and weekly planning

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#161]
New time for 2022: Tuesdays at 15:00 UTC.

Note: the first meeting of 2023 will be Tuesday, January 17, 2023 at 15:00 UTC. Setting up card to help 2023 marketing reps.

All things related to this meeting and any collaborations during the week, including:
- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by sereedmedia** [comment]
Commenting here to check GH access.

**Comment by sereedmedia** [comment]
Working outline for the Jan 17 2023 meeting agenda:

**Hello and welcome**
1. Attendance thread
2. Social question

**Contribution opportunities** 
1. Meeting notes in 2023
- Discussion about notes process
2. Coffee break
- Discussion about coffee breaks

**Team Rep Changeover**
1. Celebration
2. New Team Reps posts
- 2023 Marketing Goals

**Marketing project and task updates**
1. GitHub issues
2. Social media
4. Contributor events update
5. WordCamp Asia
- Contributor Day table leads secured
- Marketing and Learn teams potential collaboration
6. Make WordPress publications
- This Month in WordPress - Dec 2022

**Diary Dates - upcoming events and meetings**

**Open Floor**

**Comment by sereedmedia** [comment]
@bjmcsherry are you able to do a social media update for this marketing team meeting?

**Comment by robinwpdeveloper** [comment]
[WordPress 6.2 release squad](https://make.wordpress.org/core/2023/01/17/wordpress-6-2-planning-roundup/) has been finalized.

**Comment by robinwpdeveloper** [comment]
Hi @abhansnuk, I am unable to add myself in the assignee list.
Do you think it is possible to give the assignee access to all current Marketing Team Reps?
So that we can add any assignee if needed. 

I am not sure what access level we should have. But I think it's fine to ask. :)

**Comment by courtneyr-dev** [comment]
- [Project Overview: Learning Needs Analysis](https://make.wordpress.org/training/2023/01/14/project-overview-learning-needs-analysis/)
- [Project Thread: Learning Needs Analysis](https://make.wordpress.org/training/2023/01/16/project-thread-learning-needs-analysis/)

Brief the marketing team about these and looking ahead to collaboration

**Comment by robinwpdeveloper** [comment]
[Meeting note](https://make.wordpress.org/marketing/?p=10603) is ready for review now.

**Comment by robinwpdeveloper** [comment]
[Meeting note](https://make.wordpress.org/marketing/2023/01/23/notes-global-marketing-team-meeting-jan-17-2023/) published.
