### ISSUE TITLE
2023/1/24 global Marketing team meeting and weekly planning

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#162]
New time for 2022: Tuesdays at 15:00 UTC.

Note: the first meeting of 2023 will be Tuesday, January 17, 2023 at 15:00 UTC. Setting up card to help 2023 marketing reps.

All things related to this meeting and any collaborations during the week, including:
- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by sereedmedia** [comment]
Commenting here to check GH access.

**Comment by robinwpdeveloper** [comment]
If anyone has any agenda to add in this week's meeting feel free to add.

**Comment by becreativemkt** [comment]
Hi guys!

**Comment by robinwpdeveloper** [comment]
@abid112 volunteered for this week's note.
Let us know when your note script is ready for review.

**Comment by robinwpdeveloper** [comment]
@abid112, few resources to help you out with the meeting notes.
- Weekly Chat Agenda: https://docs.google.com/document/d/1pehPLeMlZkcO7ti3JZwzHoqcJ7O5aAYECGy2J96XwA0/edit?usp=share_link 

- Meeting Note Template: https://docs.google.com/document/d/1P1h4NgkrseOmzM2w-uOKCFVbL-zpUhQ_B6JIqr02QI8/edit?usp=sharing

**Comment by abid112** [comment]
Meeting note is ready here: https://docs.google.com/document/d/16cBoCcJ51jkGgBwHUxEEbvA9v1ctbMQRiD_QJk7IwAg/edit#

Please review. Also, I need access to post this! Cheers!

**Comment by robinwpdeveloper** [comment]
@abhansnuk I am unable to add @abid112 as contributor to Make Marketing P2 blog site.
https://make.wordpress.org/marketing/ 

My current role is Editor.

**Comment by robinwpdeveloper** [comment]
Thanks @abid112 
Draft is ready for review. 
https://make.wordpress.org/marketing/?p=10625

**Comment by sereedmedia** [comment]
Final notes post: https://make.wordpress.org/marketing/2023/01/31/notes-global-marketing-team-meeting-jan-24-2023/
