### ISSUE TITLE
2023/1/31 global Marketing team meeting and weekly planning

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#163]
New time for 2022: Tuesdays at 15:00 UTC.

Note: the first meeting of 2023 will be Tuesday, January 17, 2023 at 15:00 UTC. Setting up card to help 2023 marketing reps.

All things related to this meeting and any collaborations during the week, including:
- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting and to support accessibility
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- [Marketing Team coffee break planning card](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by sereedmedia** [comment]
Commenting here to check GH access.

**Comment by robinwpdeveloper** [comment]
@abid112 volunteered to take note for this week too.

**Comment by rmartinezduque** [comment]
Hi! Adding this update for today's meeting:

> The draft for the January 2023 edition of The Month in WordPress is ready for review. More information can be found on [this GitHub card](https://github.com/WordPress/Marketing-Team/issues/166#issuecomment-1410280449).

**Comment by robinwpdeveloper** [comment]
@abid112, Template to help you out with the meeting notes.

Meeting Note Template: https://docs.google.com/document/d/14jmQkHx29uqY5a1aqxjDsAF6R5yh0KrkCNzV0bbEPII/edit?usp=sharing 

After completing the note share the draft (google doc link) url here.

**Comment by abid112** [comment]
Here it is: https://docs.google.com/document/d/1sADSzysoc7S1ehZ-IN_DRbcLZMU646hGFfAzGcgyr9Y/edit?usp=sharing

**Comment by robinwpdeveloper** [comment]
Thanks @abid112 
Draft for review: https://make.wordpress.org/marketing/?p=10635&preview=true

**Comment by sereedmedia** [comment]
Notes from meeting published: https://make.wordpress.org/marketing/2023/02/07/notes-global-marketing-team-meeting-january-31-2023/
