### ISSUE TITLE
Polyglots January Newsletter - Review request

### ISSUE THREAD

**Issue by varlese** [WordPress/Marketing-Team#164]
Hello Marketing team!

We're hoping to publish January's Polyglots newsletter within the next week, by Wednesday, January 18th. If it's possible, we would love to be able to publish it sooner, by Friday, January 13th.

With that in mind, here are the drafts for the newsletter this month:
- [Draft for the Make/Polyglots blog](https://docs.google.com/document/d/1SL-60fUEdDxGy1_uQZbkbH5I-IVLZkaWykyc_mGy0zQ/edit#heading=h.3t21avo6a1mp)
- [Draft for the MailChimp campaign](https://docs.google.com/document/d/1gSN67mlmaF2NpYWHGdXpCXV7pGWlFSIKsIPa04PenfE/edit#heading=h.3t21avo6a1mp)

As always, any feedback is more than welcome. Thank you so much!

**Comment by abhansnuk** [comment]
Hi Erica. I have added some suggestions into the blog document. Lots of interesting updates again this month 😀.

**Comment by varlese** [comment]
Thank you @abhansnuk and @rmartinezduque for taking a look at this! We've just [published this month's edition over on the Make/Polyglots blog](https://make.wordpress.org/polyglots/2023/01/13/polyglots-monthly-newsletter-january-2023/).

Thank you so much for your help with a quick turnaround. And it will definitely not be quite so quick for the February edition 😃

**Comment by rmartinezduque** [comment]
Thank you for the update, Erica!
