### ISSUE TITLE
The Month in WordPress: January 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#166]
The estimated publishing date for the January 2023 edition of The Month in WordPress is ~~February 16, 2023~~ **February 3, 2023**.

### How can you help?

You can **help by collecting any news or Make team updates** that would be valuable and relevant to the post, such as:

- Announcements or significant news from Make WP teams
- Major updates or news from flagship WordCamps (WordCamp US, WordCamp Asia, WordCamp Europe)
- Testing and feedback calls

Please **add them as a comment to this GitHub card with their relevant link and a brief description** by Friday, January 27, 2023. Here's an example:

> The Training Team shared a new post on [how to become an online workshop facilitator or tutorial presenter](https://make.wordpress.org/training/2022/09/30/become-an-online-workshop-facilitator-or-tutorial-presenter-today/).

Alternatively, you can share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness. Please note that, for brevity, it may not be possible to include all links/updates in the final post.

The Month in WordPress draft will be added to this card and shared in the Make Marketing Slack channel before publication. Your review and input will be appreciated. If you have any questions on how to contribute, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of WordPress news and updates from the Make teams. It's usually published at the beginning of each month at WordPress.org/News, and it features news from the month prior to publication. To see its format and what's typically included, check out any of the [latest issues](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
Historically, The Month in WordPress is published by the 5th of each month. For one reason or another, in recent months I have not been able to maintain this cadence and have had to post several editions later in the month. My goal for the January 2023 edition is to publish it in early February to resume the original cadence, which feels more appropriate for this type of monthly digest. Note that this also means that the next edition may be lighter on updates.

**Comment by abhansnuk** [comment]
Hello @rmartinezduque, we have this old tickets initiative in Core as part of the WP 20th anniversary celebrations. https://make.wordpress.org/core/2023/01/24/proposal-old-tickets-trac-triage-sessions/
Thanks!

**Comment by rmartinezduque** [comment]
Thanks, @abhansnuk. I've just added it to the draft.

**Comment by abhansnuk** [comment]
Thanks Reyes. I have added some suggestions to the draft. I am trying to find out the time of the Learn survey, and will come back to you within the hour.

**Comment by rmartinezduque** [comment]
The January 2023 edition of the Month in WordPress is now live: https://wordpress.org/news/2023/02/the-month-in-wordpress-january-2023/. Thanks, @abhansnuk, for contributing to this edition!

**Comment by rmartinezduque** [comment]
For those interested in contributing to the next edition of The Month in WordPress, please feel free to subscribe to this GitHub card for updates: https://github.com/WordPress/Marketing-Team/issues/176. Thanks!
