### ISSUE TITLE
2023/02/07 global Marketing team meeting and weekly planning

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#170]
#### Meeting time: Tuesday, 7 February, 2023 at 15:00 UTC

The Marketing team meeting is held weekly Tuesdays at 15:00 UTC. This ticket is for all things related to this specific meeting, including:

- agenda planning 
- script to assist the running of the meeting and to support accessibility
- notes documentation, including links to draft notes and published post, and any queries about notes drafting
- items for agenda, including items for Open Floor and updates from other Make Teams
- any asynchronous update on tasks to be provided in the meeting
- links to any relevant items
- tracking any updates to the team Google calendar on planned collaborations
- tracking updates to the diary dates post

Useful links:
- [Marketing GitHub Tasks board](https://github.com/orgs/WordPress/projects/21)

**Comment by sereedmedia** [comment]
2023-02-07 WordPress Marketing Team Weekly Chat
Hello and welcome to our weekly Global WordPress Marketing Team meeting!
1a. Attendance thread
1b. Social question
2. New contribution opportunities
2a. Coffee break
2b. Good first issues
3. Team News
3a. Marketing updates
3b. Contributor events update
3c. Make WordPress publications roundup
3d. WordPress.org social media updates
4. Projects and Tasks
4a. New
4b. Open
4c. Closing soon
4d. Recently closed
4e. Other issues (not yet in GitHub)
5. Open Floor
6. Next Steps
Our next meeting is 14 February, 2023 at 15:00 UTC.

**Comment by rmartinezduque** [comment]
Hello! Just an update from me for today's meeting that I thought would be of interest:

Openverse is moving from wordpress.org/openverse to openverse.org this week. Along with this move, the homepage is getting a fresh look, header, and footer. More information can be found in [this post](https://make.wordpress.org/openverse/2023/02/03/openverse-is-moving/). I coordinated with the team to share some WordPress.org social posts. The first ones went live yesterday, and a new round will go out once the changes are live.

**Comment by robinwpdeveloper** [comment]
Thanks @mumtahinafaguni for taking today's note.

**Comment by rmartinezduque** [comment]
My intention was to add it to the agenda, I hope this is the right GitHub card. 😄

**Comment by sereedmedia** [comment]
Notes published here: https://make.wordpress.org/marketing/2023/02/14/notes-global-marketing-team-meeting-7-february-2023/
