### ISSUE TITLE
Review of proposed Marketing Team description

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#175]
We're reviewing the proposed Marketing Team description to ensure it aligns with the broader WordPress project.

The proposed description:

_The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users and contributors._

**Comment by sereedmedia** [comment]
Tagging in some folks who commented on the previous discussion here: https://github.com/WordPress/Marketing-Team/issues/87

@eidolonnight @rmartinezduque @murillol @robinwpdeveloper @jpantani @nalininsbs @santanainniss @thetinyl

**Comment by sereedmedia** [comment]
A thought I just want to toss out there before discussion starts again: In my opinion, the scope of the Marketing team, and its description, should be broad enough to include activity from all contributors, whether sponsored or volunteer.

**Comment by josephahaden** [comment]
Thanks for re-opening this discussion, Sé! Here's what I shared in Slack plus some additional explanation:

> From a readability perspective, it’s a very complex sentence. I worry it will make it difficult for brand new contributors to determine what to expect once they arrive to the team.

The complexity of this sentence rates at a post-grad level. Even if everyone visiting that page can understand it with some effort, 1) we should always aim to reduce friction where possible and 2) it doesn't fit with the WordPress voice.

<img width="941" alt="Screenshot 2023-02-02 at 7 59 06 AM" src="https://user-images.githubusercontent.com/1886921/216380251-0f0f317f-9784-41a2-9b34-1a15a4ec2d7b.png">


> From a wonk-ish perspective, I worry that we’re suffering from [The Curse of Knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) here. If I try to read this without the knowledge of what I expect from that team, it reads like you’re a field marketing team. Like you design and execute Instagram-worthy popup experiences.

I think the primary type of contribution this group will have is in the realm of communications, regardless of whether it dovetails with specific and measurable campaigns or not. From the current sentence, I don't get the sense that the team's goal is to be a driving mechanism for expressing/amplifying the value of WordPress which is what we need.

**Comment by sereedmedia** [comment]
What about something along the lines of:

_The Marketing team's mission is to share the value of WordPress with current and future users and contributors, supporting the growth and development of the WordPress project through promotion and communication._

That's clocking in at a high school reading level.

**Comment by jpantani** [comment]
This is a really exciting transformation @sereedmedia and @santanainniss — I also quite like the reduced version Santana has offered.

**Comment by josephahaden** [comment]
Great edits, folks. If you prefer the shorter one I'll go ahead and get it updated. Just let me know!

**Comment by rmartinezduque** [comment]
Hello! Thank you for re-opening this. I don't mean to be picky, but regarding one of the points Josepha mentions, I'm somewhat concerned that the above sentences are a bit longer and also score as "post-graduate" on Hemingway. I wonder if its readability can still be improved, even if only by splitting the description in two:

> The Marketing team's mission is to share the value of WordPress with current and future users and contributors. To this end, the team focuses on supporting the growth of the WordPress project through marketing communications.

To avoid repeating the word "team," we can also say something like, "the group focuses on...," or "a key focus is supporting...".

**Comment by santanainniss** [comment]
Those are solid points, @rmartinezduque. Thank you so much for naming this. We are in a bit of a bind. I've played around with the Hemingway Editor for quite a while now and cannot get any sentence including all priorities to clock in at under a 12th grade reading level. I don't want us to reopen the entire discussion again, as the priority items (e.g. audiences, mission) were discussed at length on GH 87. 

Our main problem is all of the and clauses. "current and future" "users and contributors." Some word choice also ups the reading level required. For example, "The marketing team's mission is..." is a 6th grade level, where "The mission of the Marketing team is..." is a 4th grade reading level. Longer, but more accessible. 

I did some rearranging and got most everything in with a score of grade 8. 

**> _The Marketing Team focuses on sharing the value of WordPress to current and future users and contributors. Its mission is to support the growth of the WordPress project._**  

@josephahaden would you be amenable to this pared down version that includes the main points but clocks in at an 8th grade reading level? I think Reyes makes a strong, and global contributor-centric point that our description should be more readable for folks with varying levels of English proficiency.

**Comment by sereedmedia** [comment]
Re: approval process, I'd like to put the revised description we end up with on the agenda for our marketing meeting tomorrow to get any final input from our team and make sure we haven't left anything out. We can then resubmit for project approval.

**Comment by josephahaden** [comment]
I don't know that it needs to be so short as to constitute poetry, though. We could boldly take three whole sentences and make it a paragraph! I've included a couple of examples below that include all of what I saw in the originals:

> The Marketing team helps communicate the value of WordPress to the world. We create and manage campaigns that promote the growth of the WordPress project. From WordCamps and Contributor Days, to volunteers and new users, we’re here to help all parts of the project succeed!

> The Marketing team helps communicate the value of WordPress to new and current users. We create and manage campaigns that promote the growth of the WordPress project. If they're here to learn about contribution or how to use the software, our work helps folks find their way!

> The Marketing team shares the value of WordPress to users and contributors at all skill levels. We create and manage campaigns that promote the growth of the WordPress project. No matter where you are in your journey, we promote content to find your way!

**Comment by sereedmedia** [comment]
I propose we take a ship-and-iterate approach to this issue so we are able to move forward with a working description, while continuing to assess/review to make sure it works for everyone long-term. Our team wants to have an updated iteration available for WordCamp Asia, so we would like to review it at our meeting February 7. 

Readability is an accessibility issue and we all want to reduce as much friction as possible. I've moved away from that the phrase "shares the value of WordPress" as it is consider "hard" by Hemingway editor. Incorporating multiple sentences for translatability as @rmartinezduque mentioned (thank you!), readability suggestions from @josephahaden (thank you!), combining terms as @santanainniss has proposed (thank you!), and without straying too far from the original proposal the team agreed on, I suggest this, which is testing at an _11th grade_ reading level on Hemingway.

> _**_The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project._**_

**Comment by santanainniss** [comment]
Wow wow wow! Thank you so much for the synthesis here @sereedmedia. I really like how you were able to incorporate feedback from each of us, and still come out with something that respects the integrity of the previous conversations with contributors over on GH87. 

> The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

I'm on board with moving forward with this description.

**Comment by santanainniss** [comment]
> The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.

Alrighty, we've circled back together and feel good about this path forward. All good to get this updated, @josephahaden?

**Comment by josephahaden** [comment]
Updated
