### ISSUE TITLE
Update Marketing team documentation with new working description

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#182]
The new marketing description has been approved and updated on the Make WordPress homepage - #175 

The new working description is:

**The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project.**

We now need to update it across the project, ideally prior to WordCamp Asia Contributor Day. I'm creating an issue so we can ensure we've updated it everywhere we need to do so. Please note if we need to update the description in any other locations:

- [x] Make Marketing welcome/header - https://make.wordpress.org/marketing/
- [x] Handbook main page - https://make.wordpress.org/marketing/handbook
- [x] Handbook about page - https://make.wordpress.org/marketing/handbook/about/
- [x] Handbook Get Involved page - https://make.wordpress.org/marketing/handbook/getting-involved/

**Comment by sereedmedia** [comment]
I updated the Header, which is located at: https://make.wordpress.org/marketing/welcome

I converted it to the block editor while I was at it.

**Comment by sereedmedia** [comment]
Updated Handbook main page: https://make.wordpress.org/marketing/handbook/

Noting previous text here for reference:

```
The Make WordPress Marketing Handbook is a repository for resources to market WordPress as open source software and the WordPress community.

It has resources to help you get started contributing to the Marketing Team and signposting the tools we use.
Update: July 2021 – We are currently moving and reorganizing some of our project management tools to [GitHub](https://github.com/wpmarketingteam) due to changes in other tools we used and to help with the different groups the team interacts with.
```

**Comment by sereedmedia** [comment]
Updated Get Involved page. Also updating a text-based reference to the meeting time on that page.

**Comment by sereedmedia** [comment]
Are there any other locations to update this description?

**Comment by sereedmedia** [comment]
I updated this in the Slack marketing team description as well.

**Comment by abhansnuk** [comment]
I have replaced the old description with the new one on the readme for the GitHub repo. I can't think of anywhere else at the moment from the ones you have already done Se.

**Comment by sereedmedia** [comment]
Great! This looks like it can be closed to me!
