### ISSUE TITLE
6.2 "Behind the Scenes" Social Content Ideas

### ISSUE THREAD

**Issue by thetinyl** [WordPress/Marketing-Team#184]
This issue is meant to collect and organize "behind the scenes" social content for the WordPress 6.2 release (scheduled for March 28, 2022). 

For an example, check out what was done to [help highlight WordPress 6.1's Twenty Twenty-Three theme](https://github.com/WordPress/Marketing-Team/issues/128).

**Comment by thetinyl** [comment]
@sereedmedia I'm curious what you had in mind for this release? I can add that direction/context to the description above.

**Comment by sereedmedia** [comment]
Thanks for this post @thetinyl! The styles of twentytwentythree lent themselves to some beautiful posts. I'd like to see if we can come up with some ideas around creating the new features unique to 6.2 that could be showcased through imagery, a video, a contributor story, etc. 

I don't have ready a non-commercial link that lists out those upcoming features, so if anyone can find one to include here as reference, that would be great!

**Comment by sereedmedia** [comment]
Oh hey, look, I found one: https://docs.google.com/document/d/1gOh3m5_teYYUaZdOOI8SI96HcFXDnx2f4j__7LOue_8/edit#

**Comment by abhansnuk** [comment]
@thetinyl I have added labels to help surface this card in searches. When you have more content on this and if you would like it shared in core meetings, let me know. I am sure there will be some really strong social media ideas coming through from marketing.

**Comment by sereedmedia** [comment]
I am pretty sure this is moot at this point, as we didn't collect materials. I'm going to close this ticket and hopefully we can do another Behind the Scenes campaign for an upcoming release. (Definitely for 6.4, the second all-women/nonbinary release)
