### ISSUE TITLE
Start Here! Contributor ticket for WordCamp Asia Contributor Day - February 17 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#185]
# Hello and welcome to Contributor Day! 

Thank you for being here and contributing to the Make Marketing Team!

## Contributor Day Doc
Here is a link to the primary doc we are using for the day. This Google doc lists:

- Goals
- Schedule
- Primary tasks for the day
- Links to good first issues and related materials
- Contact information for the table and team leads

https://docs.google.com/document/d/1VQ2fVt1uORoG_dDN9iDNYYcgt7GjW8Udpjr_i4kDhiE/edit?usp=sharing

### Getting Setup
If you're here, that means you're already setup on GitHub. Great! In addition to talking with the team on-site, you can ask any questions or make comments on this ticket. The Marketing Team Reps will be monitoring it throughout the day. Also, be sure to sign in to the Marketing channel on Slack. 

If you're ready to go, let us know you are here by commenting on this ticket, then check out some Good First Issues:
https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue

## Tasks

- [ ] Comment on this ticket and say hi! If you like you can introduce yourself, and let us know what brought you to the Marketing team! We'd also love to know what languages you speak/write.
- [ ] Check out Good First Issues

**Comment by leanlailacaba** [comment]
Hello! Le-an from the Philippines. Been a marketer for 8 years and a content creator as well. Excited to be here!

**Comment by shilpahshah** [comment]
Hey, Shilpa here - thank you to whoever put together this document to help us get here!

**Comment by sereedmedia** [comment]
Hi everyone! I'm Sé, one of this 2023 marketing team reps. Im an unsponsored contributor who has been working in WP since 2007!I'm joining remotely today from California! 🏵

**Comment by auchinpain** [comment]
Hello everyone! I'm Auch from Singapore! This is my first time contributing to WP. Excited to meet all of you!

**Comment by scottmurcott** [comment]
Hi! Scott from South Africa here :) I've been in marketing and advertising for a decade. Happy to be here and thanks for organizing!

**Comment by sereedmedia** [comment]
Thank you to everyone who participated in WordCamp Asia! Extra thanks to our Contributor Day table leads: Yvette Sonneveld and Dominyka Miksenaite. Your efforts are appreciated!

Please follow this Marketing Team GitHub repository to continue to contribute, and join the weekly Marketing Team meetings in the #marketing WP Make Slack channel every Tuesday at 15:00. If you need help figuring out how to contribute, come ask at the meeting!
