### ISSUE TITLE
Updating the handbook page to include more information about GitHub and Slack for new contributors

### ISSUE THREAD

**Issue by santanainniss** [WordPress/Marketing-Team#188]
The Marketing Handbook page includes information about GitHub for new contributors. 

Link: [https://make.wordpress.org/marketing/handbook/getting-involved/new-contributor-orientation/#managing-tasks-with-github]

This is the text from the handbook page:

> The Marketing team uses GitHub for managing tasks and assets.
> 
> [lab.github.com](https://lab.github.com/) has several free courses available for learning. Courses that will be specifically helpful for contributing to this team are:
> 
> - [Introduction to GitHub](https://lab.github.com/githubtraining/introduction-to-github)
> - [Communicating using Markdown](https://lab.github.com/githubtraining/communicating-using-markdown)
> - [Community starter kit](https://lab.github.com/githubtraining/community-starter-kit)

In creating this year's Contributor Day activities for WordCamp Asia, I identified that some helpful information was missing:

- How to sign up for a GitHub account
- How to find the Marketing team repository in GitHub

I'm going to to add these pieces of information to the Handbook page!

**Comment by santanainniss** [comment]
I have updated the handbook page to read: 

> The Marketing team uses GitHub for managing tasks and assets. If you do not have a GitHub account already, you can set one up by visiting https://github.com/login and following the account setup instructions. 
> 
> Once you have an account with GitHub, you can find and join the Marketing Repository here at this link:  https://github.com/WordPress/Marketing-Team.
> 
> Marketing tasks are typically divided into two types: Issues and Discussions. Discussions are most often used before an action has been decided on. Issues are created when a clear action is needed. 
> 
> If you need additional training resources, [lab.github.com](https://lab.github.com/) has several free courses available for learning. Courses that will be specifically helpful for contributing to this team are:
> 
> 	•	[Introduction to GitHub](https://lab.github.com/githubtraining/introduction-to-github)
> 	•	[Communicating using Markdown](https://lab.github.com/githubtraining/communicating-using-markdown)
> 	•	[Community starter kit](https://lab.github.com/githubtraining/community-starter-kit)

**Comment by sereedmedia** [comment]
I've updated the handbook even more:

1. Separated out the WP ID and Slack section
2. Made ordered lists for each section (WP, Slack, GH)

**Comment by sereedmedia** [comment]
We are done editing the handbook for today. New edits can be part of a larger team convo and be on a new ticket.
