### ISSUE TITLE
Write poetry to support WordPress 6.2 release announcements

### ISSUE THREAD

**Issue by thetinyl** [WordPress/Marketing-Team#193]
### Background

Since at least version 3.8 (possibly earlier), every Beta and RC release announcement published has included a fun concluding haiku. A haiku is a very short poem that is three lines long, with each line having a specific number of syllables: 5, 7, 5. 

The release announcement haiku is typically written by the author of the release announcement, but for the remaining Beta and RC announcements in 6.2—the Mar/Comms release leads felt it would be a great way for others on the Marketing team to contribute. 

You don't need to be a poet, or even directly involved with release activities—just a love for words and/or WordPress will do!

Here are some examples from previous releases: 

- WordPress 6.0: [Beta 1](https://wordpress.org/news/2022/04/wordpress-6-0-beta-1/), [Beta 2](https://wordpress.org/news/2022/04/wordpress-6-0-beta-2/), [RC1](https://wordpress.org/news/2022/05/wordpress-6-0-release-candidate-1/), [RC2](https://wordpress.org/news/2022/05/wordpress-6-0-release-candidate-2-rc2-now-available-for-testing/)
- WordPress 6.1: [Beta 3](https://wordpress.org/news/2022/10/wordpress-6-1-beta-3-now-available/), [RC2](https://wordpress.org/news/2022/10/wordpress-6-1-release-candidate-2-now-available/), [RC3](https://wordpress.org/news/2022/10/wordpress-6-1-release-candidate-3/)

### How you can participate

Follow the guidelines and add your poem to the [6.2 Release Haiku Collection](https://docs.google.com/document/d/1jWosM6atMjmoOSbwpS-JD8PlVK8aBbGO5fhlVdD0IpQ/edit?usp=sharing). 

**Haiku Guidelines**

- One release announcement per contributor—there are a limited number of announcements, and we want to make sure others have a chance to contribute! 
- Follow the 5, 7, 5 syllable structure—you can use this [haiku syllable counter](https://www.poetry.com/is-it-haiku) for extra help.
- Write in the WordPress voice—use the [WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/) for reference.
- Stay on topic—each haiku should relate to the celebratory feeling of a new release, testing, or a general love of WordPress.
- Include your WordPress.org username—so you can be attributed properly on the announcement post.
- Have fun—feel inspired by the amazing work and passionate community that you’re a part of.

### Release Announcement Schedule

Release announcements are following the [current development cycle](https://make.wordpress.org/core/6-2/) for the 6.2 release. With this in mind, haikus will need to be submitted no later than the dates outlined below:

- **Beta 4:** Haiku due February 27, published February 28
- **RC1:** Haiku due March 6, published March 7
- **RC2:** Haiku due March 13, published March 14
- **RC3:** Haiku due March 20, published March 21

If you have any questions or thoughts, feel free to comment them on this ticket or reach out to @thetinyl (laurlittle on Making WordPress Slack) or @jpantani.

**Comment by nomad-skateboarding-dev** [comment]
Beta will leave us
The code sings such happy songs
6.2 RC

*Although this might be getting ahead and better suited to the actual RC? 🤷

nomadskateboarding on .org 🙂

**Comment by jpantani** [comment]
> Beta will leave us The code sings such happy songs 6.2 RC
> 
> *Although this might be getting ahead and better suited to the actual RC? 🤷
> 
> nomadskateboarding on .org 🙂

I like it! May I suggest a small change and then use it for RC1?
“Beta has left us…”

**Comment by nomad-skateboarding-dev** [comment]
> I like it! May I suggest a small change and then use it for RC1?
> “Beta has left us…”


That would be awesome! 😀 Change sounds good, so credit yourself if it's used!

**Comment by shilpahshah** [comment]
Time for soft string freeze
Loose ends of Beta 3 tied
Beta 4 for all

First-timer, please feel free to edit / improve :-)

My WordPress profile is @shilpashah

**Comment by sereedmedia** [comment]
RC2? 

Listen, we are close
One step to final RC
Breathe, and keep going

**Comment by jpantani** [comment]
@mehrazmorshed Thanks for giving it a go! This is the kind of first-time contribution the team is actively encouraging! 
So... the first line has one extra syllable. May I suggest "CMS reigns supreme" or please give us your revised version and we can use it? 

@sereedmedia - sweet it's noted! and in the document. 

Also, Sé we've not hit our quota. How do you suggest moving forward? Closing this ticket and reopening per cycle? Reactivating per release cycle? Sounds like this was a hit from a participation POV.

**Comment by mehrazmorshed** [comment]
@jpantani Thank you so much for mentioning. 
I have edited according to your suggestion.

**Comment by sereedmedia** [comment]
@mehrazmorshed @jpantani CMS reigns supreme is 6 syllables. How about "WP reigns supreme"?

**Comment by sereedmedia** [comment]
@jpantani i suggest moving this into the review category, adding the links back when each haiku is published, then closing the ticket and reopening a new one for 6.3.

**Comment by sereedmedia** [comment]
okay i was going a little nuts on whether or not "wp" was 2 syllables or more but "w" is officially one according to this:

https://www.howmanysyllables.com/syllables/w

**Comment by jpantani** [comment]
Thank you to all who have participated. All entries have been logged. We will open a new ticket and reference for any future release campaigns or similar.
[6.2 Release Haiku Collection](https://docs.google.com/document/d/1jWosM6atMjmoOSbwpS-JD8PlVK8aBbGO5fhlVdD0IpQ/edit?usp=sharing)
