### ISSUE TITLE
New Meeting Notes Format testing

### ISSUE THREAD

**Issue by santanainniss** [WordPress/Marketing-Team#194]
Team Reps met to review and consolidate the consistent themes from GitHub Discussion 148. That discussion is now locked. Thank you and props to all contributors that joined the discussion. It's these discussions that move our team forward! 

An example of the notes structure being tested can be found here: https://make.wordpress.org/marketing/2023/02/21/notes-for-the-global-marketing-team-meeting-14-february-2023/

This issue is to collect feedback on the new notes format. Comment feedback below or directly on the posted notes. We will iterate again after a feedback period of at least 60 days.  

### Discussed in https://github.com/WordPress/Marketing-Team/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **santanainniss** December  5, 2022</sup>
There have been many conversations and GitHub issues opened in 2022 related to note taking, pain points for contributors, and how to make the notes easier for contributors. Some examples of this include [GitHub Issue 68](https://github.com/WordPress/Marketing-Team/issues/68), [GitHub Issue 103,](https://github.com/WordPress/Marketing-Team/issues/103), and these Slack threads: [Thread 1](https://wordpress.slack.com/archives/C0GKJ7TFA/p1669822936218659), [Thread 2](https://wordpress.slack.com/archives/C0GKJ7TFA/p1662565856018919), [Thread 3](https://wordpress.slack.com/archives/C0GKJ7TFA/p1664956621412719). 

Some common pain points include:

-Granting new contributors blog access/new contributors unsure how to navigate the blog for note taking, following best practices in the blog e.g. tagging the notes, etc 
-Using Slack, copy/pasting Slack links into the notes 
-Contents of notes: linking contributor ideas, linking Slack threads, how much of the meeting include in the notes etc, structure of the notes 
-Consistency of notes vs the agenda 
-Time commitment: amount of time to create/draft notes, review and editing of notes, time between meeting and posting of the notes.

Make Marketing contributors have gone above and beyond to help onboard new contributors to the note taking process: hosting Zoom training calls, requesting screenshots and or videos be made help educate new contributors, and many edits to the handbook page. Despite this meaningful work, contributors new and seasoned continue to struggle with these pain points. 

This made me wonder: are we solving the right problem? I looked around at the notes of various Make teams, and found a few important differences between their process for note taking and our own. Here are some of those differences:

- Make Marketing notes include far more Slack links than many other make teams. Where Marketing tends to link each item from the agenda and much of the content of the meeting itself. Teams like [Openverse](https://make.wordpress.org/openverse/2022/12/02/community-meeting-recap-29-november-2022/) and the [Diversity Speaker Training (Community) Team](https://make.wordpress.org/community/2022/11/24/recap-of-the-diverse-speaker-training-group-wpdiversity-amer-emea-on-november-23-2022/) link only stat and end points. The [Docs ](https://make.wordpress.org/docs/2022/11/30/summary-for-docs-team-meeting-november-29-2022/) and [Photos](https://make.wordpress.org/photos/2022/06/17/recap-of-team-meeting-june-2/) teams list only starting point Slack link. 
-Make Marketing notes tend to contain a lot more detail and complexity, whereas the linked examples above include only brief summaries. 

I'd like to open a conversation with all members of the Community to discuss how we can make the note taking process simpler and less complex. Restructuring our notes and processes to be closer to those of other Make teams can help us reduce the need for continual trainings and complex documentation.  </div>

**Comment by sereedmedia** [comment]
Yay! So currently, I'm using the following format, which follows the outline of the agenda, but only documents certain components.

## Outline

### 1. Intro
Meeting prep links, names of meeting lead and note-taker, and a link to the starting post from the Slack meeting.

### 2. Team News
Marketing team specific information, not necessarily tied to a ticket
- WordPress Publications - highlights any new publications (newsletters, WP Briefings, project posts, etc.)
- WordPress.org social media updates - social media stats

### 3. Marketing Project and Task Discussion
To keep this from being a second list of GH tickets, I am proposing we only note  any tickets that had discussion in the meeting thread. We don't need to say "who said what", but summarize the discussion (folks can go read the thread if they want specifics).

### 4. Open Floor
One item for each topic started in the open floor period. I propose that this is a summary of the discussion or announcement only. I also propose that this does include names so we can refer back to that person for future GH tickets or other expansion. 

### 5. Next Steps
Time of the next meeting and link to that meeting prep GH issue.

### 6. Attendance
List of names and wp.org handles of folks who checked in on the Attendance thread for contribution documentation purposes. I propose we put both folks' name and wp.org handle so we can associate the two names whenever possible.

I am also currently considering the meeting to be "closed" on the day before the next meeting, which would mean we would finish the notes on the day before the meeting to be sure to gather all feedback. (I was late publishing this week's notes, but ideally they would be posted on the day before the meeting.)

**Comment by sereedmedia** [comment]
Related, but not this exact topic: We have not been posting an agenda for 2023, but some (ahem! Courtney), has recommended that we do. Just noting here for discussion's sake, as they are related, particularly the publishing timeframe.

**Comment by courtneyr-dev** [comment]
It helps remind folks a meeting is coming up

**Comment by jennimckinnon** [comment]
I'm mainly stuck right into the Documentation Team and we publish agendas and meeting summaries as blog posts. Here are a couple of examples for inspiration and/or to get a glimpse of how another Make team is handling it:

- [Example agenda](https://make.wordpress.org/docs/2023/03/06/agenda-for-docs-team-bi-weekly-meeting-march-7-2023/)
- [Example meeting summary](https://make.wordpress.org/docs/2023/03/06/summary-for-docs-team-meeting-february-21-2023/)

**Comment by rmartinezduque** [comment]
I really appreciate the shorter and concise format of the latest meeting notes published (https://make.wordpress.org/marketing/2023/03/14/notes-global-marketing-team-meeting-5-march-2023/) and that they don't go into so much detail. In this regard, I particularly liked the Marketing Project and Task Discussion section.

From a reader's point of view, I think it makes it much easier to scan through the notes and see the most important discussion points, conclusions, or action items at a glance.

**Comment by sereedmedia** [comment]
We have been using the current notes format for a while, I think we can probably close this out and reevaluate at the end of the year.

**Comment by sereedmedia** [comment]
Closing this out, as we've got a notes format set for now.
