### ISSUE TITLE
The Month in WordPress: March 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#200]
The estimated publishing date for the March 2023 edition of The Month in WordPress is ~~April 6, 2023~~ **April 3 or 4, 2023**.

### How can you help?

You can **help by collecting any news or Make team updates** that would be valuable and relevant to the post, such as:

- Announcements or significant news from Make WP teams
- Major updates or news from flagship WordCamps (WordCamp US, WordCamp Asia, WordCamp Europe)
- Testing and feedback calls

Please **add them as a comment to this GitHub card with their relevant link and a brief description** by Monday, February 27, 2023. Here's an example:

> The Training Team shared a new post on [how to become an online workshop facilitator or tutorial presenter](https://make.wordpress.org/training/2022/09/30/become-an-online-workshop-facilitator-or-tutorial-presenter-today/).

Alternatively, you can share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness. Please note that, for brevity, it may not be possible to include all links/updates in the final post.

The Month in WordPress draft will be added to this card and shared in the Make Marketing Slack channel before publication. Your review and input will be appreciated. If you have any questions about contributing, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of WordPress news and updates from the Make teams. It's usually published at the beginning of each month at WordPress.org/News, and it features news from the month before publication. To see its format and what's typically included, check out any of the [latest issues](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
Interesting links for the next issue:

**WordPress 6.2**

- [WordPress 6.2 live demo is available](https://wordpress.org/news/2023/03/your-wordpress-6-2-preview/).
- [WordPress 6.2 Release Candidate 1](https://wordpress.org/news/2023/03/wordpress-6-2-release-candidate-1/) became available for download on March 9, 2023.
- General Release (March 28)

**Team updates**
- The Themes Team proposed [a new community themes project](https://make.wordpress.org/themes/2023/03/03/hallway-hangout-community-themes-initiative/). The goal is to bring together a squad of people to build block themes all year around the same way the default themes are built.

**WP20 Updates**
-

**Comment by sereedmedia** [comment]
I'd love to let folks know about the new Make Slack channel #website-redesign that is focused on the wordpress.org redesign process!

**Comment by santanainniss** [comment]
Hi @rmartinezduque I am going through GH and I'm wondering if there are any updates on this?

**Comment by rmartinezduque** [comment]
Hi @santanainniss, I do have some updates indeed! Thanks for following up. I plan to draft March's edition of Month in WordPress soon and hope to circulate it for review by the end of the week. I'll keep folks posted in Slack.

I will move up the publishing date to next Monday (April 3) or Tuesday (April 4), since I will be AFK (away from keyboard) at the end of next week.

**Comment by rmartinezduque** [comment]
Hi! The draft for the March 2023 edition of The Month in WordPress is ready for review. Please leave any comments or suggestions by April 1 at 22:00 pm UTC.

Link: https://docs.google.com/document/d/1GZXBthTR98H208-B-R-VvXFA3xiQDD9-48lmYuTjIh8/edit?usp=share_link

Also, remember to include your WordPress.org profile link or username as a comment at the end of the document so that all contributions can be credited. Thank you!

**Comment by rmartinezduque** [comment]
The **March 2023 post of The Month in WordPress is live**: https://wordpress.org/news/2023/04/the-month-in-wordpress-march-2023/. Thank you to everyone who contributed to this edition!
