### ISSUE TITLE
Polyglots March 2023 newsletter - Review request

### ISSUE THREAD

**Issue by varlese** [WordPress/Marketing-Team#203]
Hello Marketing team!

We have a draft of the March Polyglots newsletter available for review. The related drafts are here:
- [Draft for Make/Polyglots](https://docs.google.com/document/d/1qibAbNarA3U6mkXcoaJH91YdLoGHejtdkbCe3CCF2h4/edit)
- [Draft for MailChimp](https://docs.google.com/document/d/1gBZhJVfrWJWp2lsn-gaJyLwzXCcfOtSgYLXn0-HZ1Ng)

We're hoping to publish this by next week, on March 15, 2023. If the team has time, we welcome any feedback or suggestions!

**Comment by sereedmedia** [comment]
Hi, is this published already? I'm late to the party lol.

**Comment by varlese** [comment]
Yes! I'm so sorry, I usually try to share the links once published as soon as possible and completely forgot this time. 

This was published last [Wednesday on Make/Polyglots](https://make.wordpress.org/polyglots/2023/03/15/polyglots-monthly-newsletter-march-2023/). Thank you for checking, and I will go ahead and close this issue!
