### ISSUE TITLE
The Month in WordPress: April 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#209]
The estimated publishing date for the April 2023 edition of The Month in WordPress is **May 4, 2023**.

### How can you help?

You can **help by collecting any news or team updates** that would be valuable and relevant to the post, such as:

- Announcements or significant news from Make WP teams
- Major updates or news from flagship WordCamps (WordCamp US, WordCamp Asia, WordCamp Europe)
- Testing and feedback calls

Please **add them as a comment to this GitHub card with their relevant link and a brief description** by April 30, 2023. Here's an example:

> The Training Team shared a new post on [how to become an online workshop facilitator or tutorial presenter](https://make.wordpress.org/training/2022/09/30/become-an-online-workshop-facilitator-or-tutorial-presenter-today/).

Alternatively, you can share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness. Please note that, for brevity, it may not be possible to include all links/updates in the final post.

The Month in WordPress draft will be added to this card and shared in the Make Marketing Slack channel before publication. Your review and input will be appreciated. If you have any questions about contributing, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of WordPress news and updates from the Make teams. It's usually published at the beginning of each month at WordPress.org/News and features news from the month before publication. To see its format and what's typically included, check out any of the [latest issues](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
Interesting links for the next issue:

**New in the Gutenberg plugin**
- [Gutenberg 15.5](https://make.wordpress.org/core/2023/04/05/whats-new-in-gutenberg-15-5-05-april/) brings many user-facing features to improve the creation experience, such as caption styles customization and theme-defined template patterns when adding a new template.

**Team updates**
- Preparations for the next [women's and non-binary WordPress release squad](https://make.wordpress.org/core/2023/04/07/preparing-for-the-next-women-nonbinary-release-squad/) are underway.
- This post looks at the [performance improvements](https://make.wordpress.org/core/2023/04/05/wordpress-6-2-performance-improvements-for-all-themes/) introduced in WordPress 6.2 for all themes.


**Testing and feedback requests**
- The latest version of the Preferred Languages feature plugin [needs testing and feedback](https://make.wordpress.org/core/2023/04/03/preferred-languages-help-test-the-latest-version/).

**Comment by rmartinezduque** [comment]
Hi! 👋 The draft for the April 2023 edition of The Month in WordPress is ready for review. Please leave any comments or suggestions by May 2 at 10:00 pm UTC.

Link: https://docs.google.com/document/d/1_Gz6H9x1OFs9pXY9NL4nf_nBJh2Mo1uQsU6KfmI9sAg/edit.

Remember to include your WordPress.org profile link or username as a comment at the end of the document so that all contributions can be credited. Thank you!

**Comment by jennimckinnon** [comment]
Just reviewed and added 2 suggestions on typos. Nice work! 🎉 🍪

**Comment by rmartinezduque** [comment]
The April 2023 edition of The Month in WordPress is live: https://wordpress.org/news/2023/05/the-month-in-wordpress-april-2023/. Thank you, @jennimckinnon and @sereedmedia, for contributing to this edition! 🎉

**Comment by rmartinezduque** [comment]
For those interested in contributing to May's edition of The Month in WordPress, please comment and subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/226. Thanks!
