### ISSUE TITLE
2023/04/18 Global Marketing team meeting and weekly planning

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#214]
**Meeting time: Tuesday, 18 April, 2023 at 15:00 UTC**

The Marketing team meeting is held weekly in the Make WordPress #marketing Slack channel on Tuesdays at 15:00 UTC. 

This ticket is for all things related to this specific meeting, including:

- agenda planning
- script to assist the running of the meeting and to support accessibility
- notes documentation, including links to draft notes and published post, and any queries about notes drafting
- items for agenda, including items for Open Floor and updates from other Make Teams
- any asynchronous update on tasks to be provided in the meeting
- links to any relevant items
- tracking any updates to the team Google calendar on planned collaborations
- tracking updates to the diary dates post

Please add any items for discussion as a comment here!

**Useful links:**

- [Marketing GitHub Tasks board](https://github.com/orgs/WordPress/projects/21)
- [All Marketing Team GitHub Issues](https://github.com/WordPress/Marketing-Team/issues)

**Comment by sereedmedia** [comment]
This meeting will be lead by @santanainniss and notes will be taken by @robinwpdeveloper.

**Comment by jpantani** [comment]
I doubt I will be able to attend tomorrow and have a tricky AFK situation coming up limiting my availability but I'd like to put this task back on the radar sooner than later 😅  : https://github.com/WordPress/Marketing-Team/issues/51
It's Grow Your Story and there are all the User Generated Snippets (Redacted user info though to protect privacy) that I'd like to put back into a some type of GYS, Summer Loving Social Campaign highlighting all the good that WordPress has brought to people's lives. I believe this will help build/reinforce a narrative that WordPress is a platform upon which folks don't just build their story(/ies) online but also in their lives. 
I'm a firm believe that if we make WordPress users look great it makes WordPress itself look great.
Looking to develop a little cohort of helpers who want to be a part of this campaign to select and refind copy, hunt for images, etc. Thanks!

**Comment by jpantani** [comment]
I'd also like to get some additional coverage for the work on /Project about the book:
Announced on the team channel https://wordpress.slack.com/archives/C0GKJ7TFA/p1681426966917669
Here's the post: https://make.wordpress.org/project/2023/04/13/wordpress-at-20-in-print/
I believe this is an ideal editorial review task for Marketing. 😄

**Comment by sereedmedia** [comment]
@jpantani do you want to make a GH ticket for it?

**Comment by jpantani** [comment]
If the WP20 Book already resides on GitHub, I'm not too keen on the idea of following multiple tickets and creating duplicate work, but if the GitHub is closed and points just to the GitHub repo, I would be open to that. Pls advise 😃

**Comment by sereedmedia** [comment]
Closed early accidentally! 

Notes draft are here: https://docs.google.com/document/d/1GFAPfVqRtnnOvnJxq-G_LN_XmWku-TBTAQUS7lkXNZY/edit?usp=sharing
Published here: https://make.wordpress.org/marketing/2023/04/24/notes-global-marketing-team-meeting-18-april-2023/
