### ISSUE TITLE
2023/05/02 Global Marketing team meeting and weekly planning 

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#216]
**Meeting time: Tuesday, 02 May, 2023 at 15:00 UTC**

The Marketing team meeting is held weekly in the Make WordPress #marketing Slack channel on Tuesdays at 15:00 UTC.

This ticket is for all things related to this specific meeting, including:

- agenda planning
- script to assist the running of the meeting and to support accessibility
- notes documentation, including links to draft notes and published post, and any queries about notes drafting
- items for agenda, including items for Open Floor and updates from other Make Teams
- any asynchronous update on tasks to be provided in the meeting
- links to any relevant items
- tracking any updates to the team Google calendar on planned collaborations
- tracking updates to the diary dates post

Please add any items for discussion as a comment here!

**Useful links:**

- [Marketing GitHub Tasks board](https://github.com/orgs/WordPress/projects/21)
- [All Marketing Team GitHub Issues](https://github.com/WordPress/Marketing-Team/issues)

**Comment by sereedmedia** [comment]
This meeting will be lead by @sereedmedia and notes will be taken by @santanainniss

**Comment by jpantani** [comment]
New Grow Your Story Issue created: https://github.com/WordPress/Marketing-Team/issues/222

- Really looking for community collaborators to talk about copy edits and photo sourcing

New WP20 Book Ticket created: https://github.com/WordPress/Marketing-Team/issues/223

- Haven't had much traction from contributors on this to date

**Comment by sereedmedia** [comment]
@jpantani i've got quite a few ideas about why the book may not get much traction, the main logistical one being it is quite hard to edit text or make suggest using issues and not pull requests.

**Comment by jpantani** [comment]
@sereedmedia - people should be able to use pull requests. Were you unable to do either?

**Comment by sereedmedia** [comment]
it said on the page to use issues for feedback. perhaps that's changed.

**Comment by sereedmedia** [comment]
![Screen Shot 2023-05-01 at 4 35 51 PM](https://user-images.githubusercontent.com/28426780/235549520-8507c110-eb5b-4ef6-8318-afc276c02b71.png)
@jpantani please see above. it includes a direct link to the issues page, so i don't think i'm misreading it. but perhaps.

**Comment by jpantani** [comment]
Yes, that's correct @sereedmedia, issues are the stated preference, as noted here. I have seen a pull request come in too and why I asked if neither was available. As I'm not a developer though, I'm curious to know why issue vs. pull request is a bit of a sticking point. I'd be interested to learn more about your point of view on that. 

For me though as I've been tasked with shepherding this project into the "wild," I guess the part that I'm more worried about was seeing so few responses as I thought it would have generated more interest in the editing process (similar to the About Page every release.) I see bringing issues like this to the Marketing team as a great way to get involved with helping tell the WordPress story. So I'm scrutinizing that part, and how it could go better in the future. Unfortunately, updating the chapters in a collaborative editing document like Google Docs was not going to be a sustainable option in this instance so I helped carve out other ways of ensuring that we work in public.

**Comment by sereedmedia** [comment]
@jpantani I think putting the doc in GitHub makes a lot of sense. The difference between the pull request and the issue is with a pull request, someone can make edits directly to the text or suggestions to the text within the context of that text, much more akin to a Google doc. An issue requires someone to provide that context manually, by writing it out, i.e. " in section x, there is a part that says "y", I think should be "z", which is much more like editing by email. Issues -ased editing is a lot more involved on both side, as it is a lot more difficult for adding suggestions and edits, but it's a lot more difficult to implement those changes on the writer's side. With a pull request you can accept or deny changes and it will automatically include them. With issues, they must be manually found and edited.

**Comment by sereedmedia** [comment]
Notes draft: https://docs.google.com/document/d/1tvlfrkJw-TxIAKqySeH0BhA0sEgiTs1WZXtlb5_rbA8/edit?usp=sharing

Published: https://make.wordpress.org/marketing/2023/05/08/notes-global-marketing-team-meeting-2-may-2023/
