### ISSUE TITLE
WordCamp Europe 2023 Marketing Table Contributor Day preparation and organization

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#218]
This is a starter ticket to contain information, ideas, and materials for WCEU Contributor day, to be held 08 June, 2023.

If you are attending, please comment on this ticket so we can connect with you!

**Comment by rmartinezduque** [comment]
I'm attending WCEU and will be happy to help during Contributor Day.

**Comment by rmartinezduque** [comment]
Yes, I'll be happy to serve as Marketing table lead, @sereedmedia. I'll confirm tomorrow if I can attend this week’s coffee break, as I'm not sure yet if I can make it.

**Comment by sereedmedia** [comment]
Hooray! We can reschedule the collaboration session/coffee break so it works with your schedule. I just set the time at its normal time so it was on the table. Please let me know what works for you and that will be the time we have it at!

**Comment by sereedmedia** [comment]
Just some docs/links/questions/tasks in preparation for the next Collaboration and Social Session (only a proposed title) WordCamp Europe Thursday, May 18 at 17:00 UTC.

- [ ] Review and update the [Marketing Team at Contributor events page](https://make.wordpress.org/marketing/handbook/getting-involved/marketing-team-at-contributor-events/): 
- [ ] Review and update and/or copy the [Make WordPress Marketing Team Contributor Doc from WC Asia](https://docs.google.com/document/d/1VQ2fVt1uORoG_dDN9iDNYYcgt7GjW8Udpjr_i4kDhiE/edit?usp=sharing) 
- [ ] Review and assess the [WordPress Marketing Team Onboarding Documentation from WC Asia](https://docs.google.com/document/d/1Yv7VmSiP1gXU3e0OeltN368FFHMG7Uazbvc6HkkBX7Q/edit#heading=h.go0i46tx) 

1. [ ] Should/could this be incorporated directly into the [Handbook / Get Involved / Marketing Team at Contributor events page](https://make.wordpress.org/marketing/handbook/getting-involved/marketing-team-at-contributor-events)?
2. [ ] Is there a more global source for technical onboarding for Learn or Docs or Community?
3. [ ] How is WCEU Contributor Day being managed in terms of onboarding brand new contributors with no Slack/GitHub/WP.org access?
4. [ ] How does WCEU's plan affect or change our process?

- [ ] Are there any expectations, historical or forecasted or data-sourced from attendees, for numbers of people who are attending Contributor Day overall and who might be plan to attend the Marketing table?
- [ ] Are there any expectations, historical or forecasted or data-sourced from attendees, on how many Contributor Day atendees may be brand new contributors?

**Comment by sereedmedia** [comment]
Here is  starting list of stock photo ideas:

- [ ] Close-up of hands typing on a laptop keyboard, showcasing productivity and technology.
- [ ] Overhead shot of a desk with a computer, notebook, and smartphone, representing a modern workspace.
- [ ] Flat lay of various tech gadgets like smartphones, tablets, and smartwatches, highlighting connectivity.
- [ ] Top view of a person's hand holding a smartphone with a blank screen, ideal for showcasing mobile apps or websites.
- [ ] Creative composition of colorful marketing materials like flyers, brochures, and business cards.
- [ ] Isolated shot of a hand reaching out to touch a virtual screen, symbolizing futuristic technology.
- [ ] Conceptual image of a light bulb with digital circuitry inside, representing innovative ideas in technology and marketing.
- [ ] Image of a person wearing smart glasses, illustrating the concept of augmented reality and digital information.
- [ ] Abstract representation of binary code and data streams, conveying the concept of digital communication and technology.
- [ ] Flat lay of a trendy workspace with a sleek laptop, notepad, coffee cup, and marketing-related objects like a pen or graph.
- [ ] Dynamic shot of a person using a digital drawing tablet, emphasizing creativity and digital design skills.
- [ ] Close-up of hands holding a smartphone and using a mobile marketing app, demonstrating engagement and analytics.
- [ ] Image of a person interacting with a virtual reality headset, showing the immersive nature of technology.
- [ ] Creative composition of various social media icons and symbols, reflecting digital marketing strategies.
- [ ] Isolated shot of a blank digital billboard or screen, suitable for showcasing advertisements or promotions.
- [ ] Minimalist image of a person's hand holding a minimalist smartphone, highlighting simplicity and elegance in technology.
- [ ] Conceptual image of gears and cogs in motion, symbolizing the inner workings of technology and marketing strategies.
- [ ] Image of a person using a smart home device or voice assistant, representing the integration of technology in daily life.
- [ ] Flat lay of colorful sticky notes with marketing-related keywords or concepts, representing brainstorming and planning.
- [ ] Abstract composition of colorful wires and cables, evoking the idea of connectivity and network infrastructure.

**Comment by rmartinezduque** [comment]
For future reference, materials for WCEU Contributor Day preparation can be found in this Google Drive folder: https://drive.google.com/drive/folders/11nZ1F365COrhOgBhVFi2rnXxlycZt844.

> How is WCEU Contributor Day being managed in terms of onboarding brand new contributors with no Slack/GitHub/WP.org access?

This year, it looks like there will be a centralized table at Contributor Day to onboard new contributors. Emails have been sent out with instructions. However, there is still no 100% guarantee that folks will read these emails or come prepared in advance. I'll report on the experience when we return from WCEU and we can work on improving the current documentation. We can also add some resources to our handbook to help prepare future Contributor Table leads.

**Comment by rmartinezduque** [comment]
Sharing here the WCEU 2023 Contributor Day retrospective that Sam and I put together: https://docs.google.com/document/d/1dwv5z2HJauzfIqebj_duetQWAwLpVZOI2xaiNPA0LYA/edit.
