### ISSUE TITLE
Promote Helping to Documentation team with Mobile Apps docs

### ISSUE THREAD

**Issue by OlaIola** [WordPress/Marketing-Team#219]
Mobile Docs documentation needs to be moved from WordPress.com to .org
and along the way, it needs:

- cataloguing existing materials,
- validating their actuality,
- finding absence of some parts,
- write what is missing,
- translate to different languages (need its own promotion).

Mobile Apps users can be interested in contributing, no technical skills needed, and even more people which less technical skilled or just new Apps users can make really great work in finding what is inaccurate, missed or vague and also can find many places when the apps themselves can be improved. Especially tricky is to find what is absent compare to what is there already, so, there is a bit of a challenge in this task too.

[Open issues in Docs GitHub](https://github.com/orgs/WordPress/projects/89/views/1)

## Goal is to promote help to Documentation team with Mobile Apps docs

We can:
- prepare content and images for social media
- use social media to share this call
- reach out to people who use WordPress mobile Apps directly

Please, if you have any other suggestions, write them below as well as fill in about any other activities with mobile docs' promotion to keep everyone in the loop.

**Comment by OlaIola** [comment]
Docs Team's call for help: [Integrating the Mobile app documentation into HelpHub](https://make.wordpress.org/docs/2023/04/17/integrating-the-mobile-app-documentation-into-helphub/)

**Comment by OlaIola** [comment]
[Contribute to the Future of the WordPress App](https://make.wordpress.org/mobile/2023/04/11/contribute-to-the-future-of-the-wordpress-app/)

**Comment by jennimckinnon** [comment]
I spoke with Estela Rueda to confirm what's needed as she has taken point on this, and I also volunteered myself to help. As such, she has made me an admin of the [project board here on GH for the mobile app docs](https://github.com/orgs/WordPress/projects/89/views/1).

Estela can help after WCEU in the coming weeks, and I can help now as well as post WCEU.

Here's my understanding thus far on what needs to be completed:

## Step One
As it stands now, the project board is just a carbon copy of the order in which the docs are organized on WordPress.com. It's currently in a FAQ format, which isn't necessarily great for WordPress.org. The articles may end up needing to be tutorials, for example.

Before we're able to get contributors to help, we'll need to take a look at the current docs structure and decide if it needs rearranging.

For details, please see [Integrating the Mobile app documentation into HelpHub](https://make.wordpress.org/docs/2023/04/17/integrating-the-mobile-app-documentation-into-helphub/).

## Step Two
After that, what's needed is to organize the project board with the new structure, if it has changed. Adding relevant labels, columns, etc. can also be done at that time.

## Step Three
Beyond that, what's needed are contributors who are familiar with the mobile app as well as the changes that are in progress to do a content review. [In summary](https://make.wordpress.org/mobile/2023/04/11/contribute-to-the-future-of-the-wordpress-app/), the Jetpack-powered features of the plugin are being taken out and only core features will remain.

The content review that's needed has to do with going over the current articles from WordPress.com and determining:

- Whether the current content is still relevant
- What needs to be omitted or added
- What needs updating (text, screenshots, links, etc.)

Then, logging these details so they can be organized and ready to be worked on further.

## Step Four
After all that's done and dusted, contributors can work on any rewrites and adding other necessary elements.

## Step Five
Another final round of content review by two contributors is needed.

## Step Six
The articles can be added to WordPress.org to finish up.

## Additional Note
Once step two has been completed, this project can be promoted as described above with this issue.

**Comment by sereedmedia** [comment]
All issues in the Doc GH are in review. We can close out this ticket now, huzzah.
