### ISSUE TITLE
Showcase Guidelines and Content Moderation 

### ISSUE THREAD

**Issue by jpantani** [WordPress/Marketing-Team#221]
Efforts to refine the guidelines and revisit how content is added and moderated to the WordPress showcase were recently published on two Make Blogs: /project and /marketing. 
In the Revitalizing the Showcase [post on Content Moderation Efforts](https://make.wordpress.org/project/?p=278) its background and strategic importance are discussed.
Related to Marketing Team and its efforts to improve the Showcase, the [proposed guidelines for content moderation](https://make.wordpress.org/marketing/?p=10817) are discussed.
It would be wonderful to hear a collection of voices on this issue and track them here.

**Comment by sereedmedia** [comment]
Super excited to see this conversation here! Thanks @jpantani!

**Comment by sereedmedia** [comment]
Relevant articles from the Marketing Team blog, so we can ensure we continue to progress:

- From an earlier redesign/rescoping (not sure what happened as a result) for the Showcase: https://make.wordpress.org/marketing/2019/01/23/showcase-redesign/

- A case study of one of the additions to the Showcase. It makes all the sense to me to have teh showcase be real case studies: https://make.wordpress.org/marketing/2018/12/09/rollingstone-com-a-wordpress-migration-and-redesign-case-study/
- A call for case studies from the WP community/ecosystem:  https://make.wordpress.org/marketing/2017/08/02/calling-all-wordpress-agencies/

**Comment by harryjackson1221** [comment]
Just ran across this issue so wanted to share as much as I could. As I think of other things, I will try to share more. This was a project that began something like 7 years ago, so bear with me.   

Also, please feel free to tag me or Slack me in the future if you need any historical background or info about any of the past items. 

The case studies project was quite popular, and we did about 6 or 7 case studies for the blog. Rolling Stone was the first one, and it was a big deal. I was chatting with some people over in Penske at WCUS this year about that, fun times!

For the redesign, we did have buy in from executive leadership on the redesign at the time, but things just sort of got busy. My biggest struggle was making sure we had enough help with running the showcase, promoting the survey and writing the case studies. 

I would like to say, this work was a great contributor day item for new folks. You can reach out to meta to have the "comments" for new submissions exported to a csv, and use it on a sheet to track sites that should go into the showcase. We divided the work up between a handful of contributors, got a few of the good submissions published, and used this work at WCUS 2019 to create the parallax image on the homepage. 

Having big ticket items for first time contributors to be a part of was really a big hit that year.  This image is a new, updated version of that homepage collage, and we didn't do it but, I wanted to give a visual representation. 

<img width="962" alt="image" src="https://github.com/WordPress/Marketing-Team/assets/29436971/cca942fa-2a70-46bb-aab7-7b610742eac3">

One of the contributors that helped with this work was at WCUS this year, and we had a great time talking about how much fun that was. Gave me the warm fuzzies, I tell you!

Sadly, though - without being able to onboard enough people to help out and commit to the work needed ongoing, the project just kind of fizzled. I didn't want to get something going that would ultimately fail, so blame me for the lack of progress. 

Looking at the activity in Slack, it feels like the now team with ya'll is probably more ready for it than we were. 🤞

**Comment by eidolonnight** [comment]
Proposal and discussion regarding Showcase moderation is available here:

[Process Proposal: Moderating the New Showcase](https://make.wordpress.org/marketing/2024/01/12/process-proposal-moderating-the-new-showcase/)

**Comment by lozmatic1971** [comment]
Looking at the Submission Criteria (https://wordpress.org/showcase/submit-a-wordpress-site/) I think we should also add 'publication' to this bullet point:

- Representing a notable organization, government entity, or corporation as an official blog or website.

**Comment by lozmatic1971** [comment]
A couple of thoughts about [Revitalizing the Showcase ](https://make.wordpress.org/marketing/2023/04/19/showcase-submission-guidelines/):

- I think we need an extra step in the process, or handover to another one, to promote individual showcases.
- "Limit the WordPress.org Showcase to 100 entries". What if there are 500 great sites to showcase?

Showcase pages rank well and get good traffic. Eg: [wordpress.org/showcase/playstationblog](http://wordpress.org/showcase/playstationblog) gets 136 clicks a month from 20 keywords (according to SpyFu). It's folk looking for the Playstation blog so not landing on the site they expect, but it's still an opportunity to grow brand awareness.

**Comment by eidolonnight** [comment]
> I think we should also add 'publication' to this bullet point

Added.

> I think we need an extra step in the process, or handover to another one, to promote individual showcases.

Agreed, though that can be discussed in a separate [discussion](https://github.com/WordPress/Marketing-Team/discussions). Please note that moderation is the top priority right now, and that it has been several months since anyone has written a Showcase entry.

> "Limit the WordPress.org Showcase to 100 entries". What if there are 500 great sites to showcase?

This is, for now, a soft limit, and one that was communicated as a way to keep the Showcase manageable in the future. The old Showcase had no limit, and as a result it was full of old sites that no longer represented the best of WordPress. Scanning and moderating sites within the Showcase has proven difficult. A limit allows for old sites to naturally attrition, thus keeping the Showcase fresh.
