### ISSUE TITLE
WP20 Book: Building Blocks: The Evolution of WordPress 2013-2023

### ISSUE THREAD

**Issue by jpantani** [WordPress/Marketing-Team#223]
# Overview
**Objective** Ticket to coordinate marketing efforts around the WP20 Book

WordPress commissioned a book to commemorate the 20th anniversary of WordPress. It focused on the updates to the community, software, and how WordPress engages in the world over the span of the last decade from 2013-2023.

Here are some relevant items for background
[Announcement post](https://make.wordpress.org/project/2023/04/13/wordpress-at-20-in-print/)
[Comms plan](https://docs.google.com/document/d/1SfI1JsimBW4hoYgVjVeCPkrzkA5mpH-91Tp-IJSV2do/edit)
Hashtag: #WP20Book

## How you can help
Please read the book, for fun or to learn more about what makes WordPress tick. 
The book has been thoroughly edited (by humans and AI) so grammar shouldn't be an issue. 
What we're looking for are additional **fact checkers, citations, sources** or other relevant info. 
We are doing these additional checks in prep for a print edition later in the year.

Want to add a review that WordPress can use on its social media channels? Include your review in a comment below

Log pull requests for [editorial issues here](https://github.com/WordPress/wp20-book/issues)

Stuck on how to help, comment below or reach out to @jpantani on Slack

**Comment by sereedmedia** [comment]
I have NOT gone through much of these docs at all yet, but of the ones I did, I didn't see many links.

Have the various Make WordPress Team's P2s been used as references for this project at all? If so, it would be great to link to relevant original documents on make.WordPress.org.

**Comment by sereedmedia** [comment]
@jpantani Do we need to continue to keep this issue open?

**Comment by jpantani** [comment]
I don't think that's necessary @sereedmedia

**Comment by sereedmedia** [comment]
Closing as noted.
