### ISSUE TITLE
Prepare and post Marketing Team update for Updates channel

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#228]
Somehow it has not been on the Marketing Team's radar to post updates to the [Make Updates blog/P2](https://make.wordpress.org/updates/).

**The last Marketing Team update to this blog was September 2020!** https://make.wordpress.org/updates/2020/09/03/marketing-team-update-for-august-2020/

We need to restart this posting, and to make it manageable, I propose we begin with a Monthly post. 

Additionally, rather than recap everything that has happened since September 2020 (2 years, 8 months, and 12 days!!), we can start from April 2023 and move forward with monthly updates. 

Moving forward with that, I will draft the April 2023 update and post it here for review. I am setting a deadline of Friday, May 19 for publishing. 

**Feedback of any kind welcome and encouraged.**

## Tasks

- [x] Draft April 2023 Marketing Team update for WP Make Updates blog
- [x] Review draft
- [ ] Publish by May 19, 2023

**Comment by sereedmedia** [comment]
Here is a doc with a draft for an update covering the first half of 2023! @robinwpdeveloper please check it out.

**Comment by sereedmedia** [comment]
Doc link! https://docs.google.com/document/d/1lqjCoc3qkLA6dQGAX_itNcb1UZ5bjCkOpM-BAu2663M/edit

**Comment by robinwpdeveloper** [comment]
Great job @sereedmedia 
Looks good to me.

**Comment by sereedmedia** [comment]
Thanks for the review @robinwpdeveloper!

I've published the Team Update here: [https://make.wordpress.org/updates/2023/08/14/marketing-team-update-the-first-half-of-2023/](https://make.wordpress.org/updates/2023/08/14/marketing-team-update-the-first-half-of-2023/)

Closing this issue. Here is a new GitHub issue to manage the next update, hopefully in October 2023: https://github.com/WordPress/Marketing-Team/issues/270
