### ISSUE TITLE
-> Start Here! Marketing Team Contributor Table for WordCamp Sylhet, Bangladesh 20 May 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#231]
স্বাগতম!

# Welcome to the WordCamp Sylhet Contributor Day! 
Thank you for your interest in the Marketing Team! 

- [ ] Let us know you are here by introducing yourself in the comments of **this** GitHub issue
- [ ] Join the #marketing channel on Make WP Slack
- [ ] Read through the [Make Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/)
- [ ] Complete one prompt a day (or all 12 days!) from the[ #WP20 From Blogs to Blocks campaign](https://make.wordpress.org/marketing/2023/05/02/20-days-to-celebrate-20-years-of-wordpress-from-blogs-to-blocks/) ([Day 1 is here.](https://make.wordpress.org/marketing/2023/05/08/day-1-wp20-from-blogs-to-blocks/))
- [ ] Explore the [Marketing Team Issues in GitHub](https://github.com/WordPress/Marketing-Team/issues)
- [ ] Check out some of [Good First Issues](https://github.com/WordPress/Marketing-Team/labels/good%20first%20issue) in the Marketing GitHub
- [ ] Let us know what you worked on, and if you have questions, in the comments of this GitHub issue. 

## About Using GitHub

- The Marketing Team manages its operations on GitHub: https://github.com/WordPress/Marketing-Team
- Sometimes contributing just means providing feedback (which is **very** useful)
- You can view the GitHub [issues](https://github.com/WordPress/Marketing-Team/issues) and [discussions](https://github.com/WordPress/Marketing-Team/discussions) without a GitHub account. If you’d like to comment on an issue, you will need to [sign up for a GitHub account](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account)

**Comment by thesunitarai** [comment]
Let's make it happen.

**Comment by shahidul95** [comment]
Let's contribute together

**Comment by mohiuddinomran** [comment]
Let's make it happen

**Comment by ZebaAfiaShama** [comment]
Hi there
Excited to join.

**Comment by shuyeb007** [comment]
Hi, This is Shuyeb from WP Manage Ninja. Excited!

**Comment by hameemkay** [comment]
Hello Peeps!

**Comment by farhatchowdhury18** [comment]
Great! Let's get started.

**Comment by mrahsid** [comment]
I'm in.

**Comment by habibur2010** [comment]
Hi I Habib from Technext

**Comment by Nazimel** [comment]
Hello, this is Nazir!

**Comment by hameemkay** [comment]
Hi, this is Hameem from BTS Tech (not BTS Army 😄)

**Comment by toufiqwebappick** [comment]
Hi there!

**Comment by ashikur698** [comment]
This is Ashik. Glad to be a part of this awesome journey.

**Comment by Premaanjum** [comment]
Hello I'm Prema, and I'm very glad to be a part of this journey.

**Comment by kawserz** [comment]
So glad to be here! 👋

**Comment by nusrat-f21** [comment]
Hello, this is Nusrat. Glad to be here.

**Comment by Partho-Hore** [comment]
Hi all, 
This is Partho from WPManageNinja!

**Comment by Premaanjum** [comment]
Hello everyone,
I'm Anzuman Ara Chowdhury from WPManageNinja

**Comment by hameemkay** [comment]
Hallo allemaal! (hello everyone!)
This is Hameem from BTS Tech

**Comment by iamtowhid** [comment]
Hello everyone!

This is Towhidul Islam, participated in the contributor day of WordCamp Sylhet, Bangladesh.

**Comment by sereedmedia** [comment]
### ধন্যবাদ

Thank you to everyone who participated in WordCamp Sylhet! Extra thanks to our Contributor Day table leads: @mumtahinafaguni and @thesunitarai. Your efforts are appreciated!

Please follow this Marketing Team GitHub repository to continue to contribute, and join the weekly Marketing Team meetings in the #marketing WP Make Slack channel every Tuesday at 15:00. If you need help figuring out how to contribute, come ask at the meeting!

**Comment by thesunitarai** [comment]
Thank you, @sereedmedia and @robinwpdeveloper, for the guidance and help. Thanks to @mumtahinafaguni and all the participants of the Marketing table at WordCamp Sylhet 2023. :)

**Comment by mumtahinafaguni** [comment]
Thanks again, @sereedmedia , @robinwpdeveloper , @thesunitarai <3 Hopefully, will get the chance again to collaborate with you all. Also, grateful to all the participants :D

**Comment by Nazimel** [comment]
Thank you @sereedmedia! Learned a lot about contributing to WordPress. Let's make WordPress together!
