### ISSUE TITLE
Start Here! New Marketing Team Contributor Issue for WordCamp Sylhet Contributor Day - 20 May 2023

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#232]
### Hello and welcome to Contributor Day for WordCamp Sylhet 2023

Thank you for being here and contributing to the Make Marketing Team!

Getting Setup
If you're here, that means you're already setup on GitHub. Great! In addition to talking with Marketing team members on-site at Contributor Day, you can ask any questions or make comments on this issue. The Marketing Team Reps will be monitoring it throughout the day. Also, be sure to sign in to the Marketing channel on Slack.

**Comment by sereedmedia** [comment]
Duplicate of https://github.com/WordPress/Marketing-Team/issues/231

**Comment by iamtowhid** [comment]
Hello there!

Towhidul is ready to get started! 🌟

**Comment by shussen21** [comment]
I'm in

**Comment by mohiuddinomran** [comment]
Hello,
I'm in

**Comment by Nazimel** [comment]
Hi, this is Nazir!

**Comment by toufiqwebappick** [comment]
Hello there!

**Comment by mrahsid** [comment]
Hi there 🤜🤛

**Comment by ZebaAfiaShama** [comment]
Hello 👋

**Comment by shahidul95** [comment]
Hi, all there 👋🏻
Let's contribute together...

**Comment by shuyeb007** [comment]
I am here!

**Comment by farhatchowdhury18** [comment]
Hi! Excited to be part of this team!

**Comment by hameemkay** [comment]
Hello everyone, IM On

**Comment by habibur2010** [comment]
Hi I am Habib from Technext

**Comment by shussen21** [comment]
Hello everyone

**Comment by saiful136** [comment]
Hi there, 👋

**Comment by prithuthakuri** [comment]
Hello 👋

**Comment by ashikur698** [comment]
Bonjour. Je suis la.
