### ISSUE TITLE
People of WordPress - Stefano C

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#233]
Copied information to card from @abhansnuk update on document.

**Timing:** brought forward to coincide with WordCamp Europe promos and event in early June.

**Google doc:** https://docs.google.com/document/d/1kU3XpLvnOmqD9I7O8h1wce0X1eXqC0OLdKKXa9d4CVc/edit?usp=sharing 

Photographs: three received to be checked by Meher/ Mary/ Mark

**Comment by nalininsbs** [comment]
Stefano added his update and answered questions on Google doc. Fact review completed.

Photos sent to @meherbala for editing - editing done and uploaded to CMS May 30, 2023

**Comment by nalininsbs** [comment]
I have previewed the photos and formatting. I am getting an issue with the end picture and the quote blocks still. @meherbala @murillol @abhansnuk could you see if you are getting this? https://wordpress.org/news/?p=15030&preview=1&_ppp=9dd6565fb0 
Thank you.

All other comments are in the post. @majadidit you had this same problem as I see before . Can you see quote blocks or only part of them? Thank you

**Comment by nalininsbs** [comment]
Thank you @Bringmannn for the final review. Excerpt, image and block check to go. Then we publish for the May edition. 

@abhansnuk did you get a reply from WCEU on whether they wanted the tickets link to be added at the end of the story for this coming week?

**Comment by nalininsbs** [comment]
A reference/ link to the Photo Team could be added.

From previous notes, WordPress Italian Community link still need. WordPress Meetup Rome if meeting in person, can link too.

**Comment by meherbala** [comment]
Article published: https://wordpress.org/news/2023/05/people-of-wordpress-stefano-cassone/

**Comment by robinwpdeveloper** [comment]
Closing as it is already published 🎉

**Comment by nalininsbs** [comment]
Hello. These are not closed until the translation is available. This is then added to the People of WordPress English version. An Italian translation has been done and this will need to be added. We move the card to the done column when the English version is published.  Thank you.

**Comment by nalininsbs** [comment]
Over to @meherbala and @abhansnuk to add the link to the Italian version once the text to go with the link in Italian has come in. Please add the link to this and the credit for the translator. We should add the translator's name to the piece too. Thank you.

**Comment by majadidit** [comment]
I would love to translate this document to Serbian if needed and if we have somewhere to post it. I am on vacation until end of July but will coordinate with @nalininsbs over that

**Comment by abhansnuk** [comment]
We need a standard block / text we use for translations. Checking with polyglots as appears to be one for some locales with releases.

**Comment by meherbala** [comment]
This story has been translated into Italia by [Lidia Pellizzaro](https://profiles.wordpress.org/lidialab/)

https://it.wordpress.org/news/2023/06/chi-contribuisce-a-wordpress-stefano-cassone/

**Comment by nalininsbs** [comment]
Translation is on the post. Thank you @abhansnuk . 

Thank you to Stefano Cassone for sharing about his adventures in WordPress.

Props to Abha Thakor (@webcommsat), the late Surendra Thakor, and Meher Bala (@meher) for interviews, writing the feature and collaborating on images, to Chloe Bringmann, Mark Smallman, Nalini Thakor,, Mary Baum (@marybaum), and Maja Loncar for help with reviews, and Lidia Pellizzaro for the Italian translation.
