### ISSUE TITLE
Share and help collect #WPPhotos stories

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#238]
**Are you a photo contributor?** The Marketing team would love to know the story behind some of the photos you've submitted, how you got into photography, or why you became a contributor to the [WordPress Photo Directory](https://wordpress.org/photos/).

➡️ [Share your WPPhotos story or experience by filling out this form](https://docs.google.com/forms/d/1sAyrbhX5A7Q3459nx1yeXRtU688tL9uSZZpG8EzgoNg/edit).

Some of these stories will be featured on WordPress.org's social media accounts. For inspiration, these are some photo stories we posted on Twitter and other WordPress.org social platforms:

- [Photo story from Topher](https://twitter.com/WordPress/status/1529802289493561346)
- [Photo story from Marcus Burnette](https://twitter.com/WordPress/status/1517542249650864130)
- [Photo story from Anne McCarthy](https://twitter.com/WordPress/status/1521516443023593472)
- [Photo story from Roy Tanck](https://twitter.com/WordPress/status/1588147738004316162/)

If you've already shared your story, help encourage other photo contributors to share theirs using the same form.

**Comment by abhansnuk** [comment]
Hi @rmartinezduque this [photo](https://wordpress.org/photos/photo/137653183d/) of a hill village in Nepal I moderated recently would make a good WPPhotos story. It is a long view of a Pokhara valley village from Pumdikot hills, Kaski district, Nepal. The picture shows hill top houses amongst the trees. 
Person who took the photo is mbigul on WordPress.org, bigul on Slack.

**Comment by sereedmedia** [comment]
I shared this form with the Photos team. If this is to be an ongoing campaign, it should likely be added into the Handbook and this issue closed.

**Comment by rmartinezduque** [comment]
I added a few more examples to the handbook and agree we can close this issue. Our processes have changed a bit since I opened this issue and I honestly don't think that Google form is needed anymore. For those folks who'd like to draft, contribute, or amplify any photo stories, I'd suggest pointing them to the GitHub amplification form instead.
