### ISSUE TITLE
WPPhotos Social Content Contribution Guide

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#239]
Thanks for taking the time to contribute to the #WPPhotos campaign! This quick guide will help you get started and ensure you have the right resources.

## What to know before getting started

You'll want to learn more about the Photo Directory (WPPhotos) social media campaign and how to write in the WordPress voice. To get up to speed, use the following resources:

➡️ [Check out the WPPhotos info in the Marketing Handbook](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpphotos) to familiarize yourself with the social campaign's goals and current content and see some examples of social posts.

➡️ [Read the WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/) to learn more about the recommended practices and guidelines all Marketing contributors are encouraged to follow when writing content for WordPress.org platforms, including the [considerations for social media](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#social-media). If you have already read this guide, you can skip this step. ;)

## How to contribute

**[Use this spreadsheet](https://docs.google.com/spreadsheets/d/1D38LhF_tmWjZEUZjnztYFk1zFEBH4fqJFsRDLRlgaAM/edit#gid=0)** to suggest social media content for this campaign.

- **Submit the social content** you’d like to contribute under the ‘Suggested content’ column. For inspiration, explore the 'Examples/Published posts' spreadsheet tab.
- The hashtag for the campaign is **#WPPhotos**.
- **Images** [optional]: Feel free to search for any pictures on the [Photo Directory](https://wordpress.org/photos/) that could be used with the social post and add their URL to the ‘Suggested images’ column in the spreadsheet.
- **Alt text**: If you suggest a specific image(s) for your content, add some descriptive alt text under the  ‘Alt text’ column.
- Use the **‘Notes’** column to specify if your post is targeted for a particular platform/channel (e.g., Instagram) or to leave any good-to-know information.
- Once you’re done, we recommend you **proofread your content** to ensure no grammar or spelling mistakes. You can use free grammar tools like [Grammarly](https://www.grammarly.com/grammar-check) or the [Hemingway App](https://hemingwayapp.com/) to check its readability.
- Lastly, don’t forget to drop your WordPress.org username (or a link to your wordpress.org profile) under the 'Contributor' column.

💡 Feel free to ask in the [Marketing channel](https://wordpress.slack.com/archives/C0GKJ7TFA) of the Make WordPress Slack if you have any questions before or while contributing content to this campaign.

**Comment by chaion07** [comment]
Wow! This too is an interesting 'Good first issue' to contribute to 😊

**Comment by minalagarwal85** [comment]
This was so much fun! Suggested a couple :)

**Comment by goodplansam** [comment]
Written a few more for the campaign!

**Comment by nahidsharif** [comment]
Is it still available to contribute?

**Comment by nalininsbs** [comment]
@rmartinezduque this is a wonderful opportunity for people to contribute. Is it still open for contribution or do you have any revised instructions to aid the current focus for WPPhotos? Thank you Reyes.

**Comment by rmartinezduque** [comment]
This is still open for contributions, yes. 🙂

**Comment by rmartinezduque** [comment]
> [Use this spreadsheet](https://docs.google.com/spreadsheets/d/1D38LhF_tmWjZEUZjnztYFk1zFEBH4fqJFsRDLRlgaAM/edit#gid=0) to suggest social media content for this campaign.

Please note that this spreadsheet is no longer in use.

If you’d like to contribute content or amplify any stories that can help promote the WordPress Photo Directory, please use the Request for Amplification form instead: https://github.com/WordPress/Marketing-Team/issues/new/choose.
