### ISSUE TITLE
Celebrating Pride Month and WordPress Diversity

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#240]
In June, Pride Month celebrates and commemorates the LGBTQIA+ communities. Marketing can help mark this month with different initiatives and opportunities to show WordPress' support and commitment to diversity, equity, and inclusion (DE&I).

Here are some ideas we can discuss and work on during Contributor Day at WordCamp Europe 2023:

- [ ] **Collect testimonials from people in the community that can be repurposed and amplified in different channels**, such as a post or on WordPress.org's social media platforms. Some interview/testimonial questions we can use to gather insights and stories include:
  - Introduction: Introduce yourself and briefly describe your background and involvement in the WordPress community.
  - Lessons Learned: What valuable diversity lessons have you learned from your experience in the WordPress community? Are there any insights or advice you wish you had known earlier?
  - Empowering Others: How do you contribute to creating a more inclusive and diverse environment in WordPress? What strategies or resources have been instrumental in your career growth or journey within WordPress? Are there any specific opportunities or initiatives that have opened doors for you?
  - Impact: How do you believe diversity and inclusion contribute to the growth and innovation within the WordPress community? What steps do you think should be taken to promote DE&I in WP and the tech industry?
- [ ] **Check if there are any Pride-related sources or collections in the Openverse catalog** that we can highlight and use as part of the [#WPOpenverse social media campaign](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpopenverse). [Here's an example of a social post](https://twitter.com/WordPress/status/1658860455497019393?s=20) that we did to highlight the collection of images from NASA’s James Webb Space Telescope.
- [ ] **Highlight websites/webshops run by people from the community** (suggested on [Slack](https://wordpress.slack.com/archives/C037W5S7X/p1685655099950139?thread_ts=1685654943.821579&cid=C037W5S7X) by @tacoverdo)
- [ ] **Help compile articles and resources on this topic written by members of the community** so the Community team can share them in their [Meetup Organizer Newsletter](https://make.wordpress.org/community/tag/meetup-organizer-newsletter/) (suggested on [Slack](https://wordpress.slack.com/archives/C037W5S7X/p1685655146855559?thread_ts=1685654943.821579&cid=C037W5S7X) by @tacoverdo)

Do you have others? Feel free to share them.

**Comment by jpantani** [comment]
In love with this idea @rmartinezduque ! Thank you

**Comment by TheCraigHewitt** [comment]
I grabbed a few image examples from the Openverse that we could use:

- https://openverse.org/image/3db6e6b7-e023-45d8-bcad-cee21340d017?q=LGBTQ
- https://openverse.org/image/9b475a47-65ae-41d9-b6e9-ffcb7fd49cb0?q=LGBTQ
- https://openverse.org/image/14a25155-308a-4014-a3b1-5eb2cf32c0b1?q=pride
- https://openverse.org/image/3d77e9a3-ae06-4b00-9245-c5ff27dc516b?q=pride
- https://openverse.org/image/956c4b2b-d5b5-4db3-857f-a9a4d123c4f4?q=LGBTQ

Would love some feedback on whether these are aligned with the goals of the issue item:

> Check if there are any Pride-related sources or collections in the Openverse catalog that we can highlight and use as part of the [#WPOpenverse social media campaign](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpopenverse). [Here's an example of a social post](https://twitter.com/WordPress/status/1658860455497019393?s=20) that we did to highlight the collection of images from NASA’s James Webb Space Telescope.

If so, I would propose the next step could be to create a Google Sheet to compile a larger list of images to share on social along with writing out the text aspects of the posts that associate each image. I'm happy to continue on that path if everyone agrees.

**Comment by sereedmedia** [comment]
@TheCraigHewitt yes please do so. if you do, please make the doc public and share the link here! thanks!

**Comment by lorenzobartoli6992** [comment]
I want to report some italians site of a LGBTQ+ associations. 

https://www.arcigay.rimini.it/ 
https://www.cassero.it/
https://www.romapride.it/

Those are a Wordpress site focused on blogging news about future of lgbtq+ rights in Italy.

**Comment by TheCraigHewitt** [comment]
Welcome any feedback on this: https://docs.google.com/spreadsheets/d/1tF6pmCLOvyAz8ppcgSemqVqsyvQr-rlZFHzOF461AvY/edit?usp=sharing

**Comment by lorenzobartoli6992** [comment]
Good Job @TheCraigHewitt

**Comment by rmartinezduque** [comment]
I just opened this Google doc so we can gather some stories/testimonials from community members: https://docs.google.com/document/d/1QvvYJ0zG2T1B1NV4VGp7G-3hd3DtfLR-R24d5o13mZs/edit.

**Comment by courtneyr-dev** [comment]
Noting Michelle Freschette has started [lgbtqpress.com](https://lgbtqpress.com).

**Comment by smokejumper123** [comment]
@rmartinezduque 

> I just opened this Google doc so we can gather some stories/testimonials from community members: https://docs.google.com/document/d/1QvvYJ0zG2T1B1NV4VGp7G-3hd3DtfLR-R24d5o13mZs/edit.

@rmartinezduque I added a few of my thoughts/ideas to your document.  Hope they help!

**Comment by rmartinezduque** [comment]
That's great. Thank you, @smokejumper123!

**Comment by rmartinezduque** [comment]
I am closing this issue as there has been no further activity from WCEU due to other priorities. We can always refer to this and/or use the testimonials collected in future issues if we want to run a campaign for this year's Pride Month (or another with similar goals of celebrating and promoting WordPress diversity).
