### ISSUE TITLE
 Familiarize yourself with the WordPress Brand Writing Style Guide

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#241]
A great first step to contribute to the Make Marketing team is to learn about the recommended practices and guidelines all contributors are encouraged to follow when writing content in the WordPress.org brand voice.

- Read the [WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/) and [the social media guidelines](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#social-media).
- Comment on this GitHub card when you're done or if you have any questions or feedback.

**Comment by chaion07** [comment]
Interested to get involved here too. Thanks!

**Comment by sereedmedia** [comment]
This issue was primarily for WCEU contributor day 2023. The guidance in the primary post has been moved to the Make Marketing Team handbook here: https://make.wordpress.org/marketing/handbook/getting-involved/new-contributor-orientation/#first-steps
