### ISSUE TITLE
The Month in WordPress: June 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#243]
The estimated publishing date for the June 2023 edition of The Month in WordPress is **July 5, 2023**.

### How can you help?

You can **help by collecting any news or team updates** that would be valuable and relevant to the post, such as:

- Announcements or significant news from Make WP teams
- Major updates or news from flagship WordCamps (WordCamp US, WordCamp Asia, WordCamp Europe)
- Testing and feedback calls

Please **add them as a comment to this GitHub card with their relevant link and a brief description** by July 2, 2023. Here's an example:

> The Training Team shared a new post on [how to become an online workshop facilitator or tutorial presenter](https://make.wordpress.org/training/2022/09/30/become-an-online-workshop-facilitator-or-tutorial-presenter-today/).

Alternatively, you can share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness. Please note that, for brevity, it may not be possible to include all links/updates in the final post.

The Month in WordPress draft will be added to this card and shared in the Make Marketing Slack channel before publication. Your review and input will be appreciated. If you have any questions about contributing, please feel free to reach out.

### Additional background

The Month in WordPress is a monthly roundup of WordPress news and updates from the Make teams. It's usually published at the beginning of each month at WordPress.org/News and features news from the month before publication. To see its format and what's typically included, check out any of the [latest issues](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by rmartinezduque** [comment]
Interesting links and updates for May's edition:

### WordPress releases

- The [WordPress 6.4 development cycle and release team](https://make.wordpress.org/core/2023/06/05/wordpress-6-4-development-cycle/) are now published. This major release is expected on November 7, 2023, and will reprise the underrepresented gender release initiative introduced in WordPress 5.6.

### New in the Gutenberg plugin
- 

### Team updates
- Tune in to [Episode 57 of WP Briefing](https://wordpress.org/news/2023/06/episode-57-the-power-of-wordpress-mentorship/) to learn more about the Contributor Mentorship Program and how it can help increase the success of new contributors over time.

### Testing and feedback requests
- 

### Events
-

**Comment by chaion07** [comment]
Following along so that I can add my updates when the time is right. Thanks!

**Comment by chaion07** [comment]
Any update on the collaboration document yet? Thanks!

**Comment by eidolonnight** [comment]
June was skipped due to focus on the 6.3 release assets. The July edition issue is https://github.com/WordPress/Marketing-Team/issues/266

In an effort to make these monthly posts a bit easier to collaborate on, I've created a template with instructions and already made a copy for July. This template includes the post's layout, common sources for news, and some instructions. We can iterate on this based on contributor suggestions.

@chaion07 @jennimckinnon I would appreciate your input on July's edition.
