### ISSUE TITLE
[AMPLIFY]: Kim Parsell Scholarship 2023 Recipient

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Marketing-Team#250]
### Post date

29 June 2023 (later is fine)

### Where would you like this shared?

Any/All of the above

### Campaign

Other

### Announcing the 2023 Kim Parsell Memorial Scholarship Winner: Yumi Nishioka
To honor the memory of [Kim Parsell](https://2017.us.wordcamp.org/kim-parsell-memorial-scholarship-2017/), the WordPress Foundation set up a memorial scholarship to ensure that Kim’s core values would continue to be infused into the WordPress community. The scholarship is awarded each year to a woman-identifying WordPress contributor who has never attended WordCamp US before, and requires financial assistance to attend. 

This year’s scholarship recipient is awarded to [Yumi Nishioka](https://profiles.wordpress.org/mimitips/), who we believe embodies the values that Kim would have appreciated. 

Yumi is a Web/UI Designer and Developer based in Tokyo. She’s the lead organizer of WordCamp Tokyo 2019 and has been a WordPress contributor since 2018.

In 2019, she began hosting a personal study group on the Gutenberg Project, which meets twice a month. Then in 2021, she started co-organizing monthly [small study sessions](https://web-design.connpass.com/) about Design and WordPress.

**Yumi, what is your favorite and/or proudest contribution to the WordPress Open Source Project?**
While there have been numerous contributions I’m proud of, one that stands out is my commitment to the core code. Although it was a small code change, the experience of being actively involved in the open-source software that I use daily was incredibly rewarding.
**Why would it be important to you to attend WordCamp US 2023?**
I believe it will provide me with valuable opportunities for personal growth and development as a WordPress contributor. Drawing from my experience leading WordCamp Tokyo 2019, I anticipate encountering inspiring individuals and gaining new perspectives. I am not very confident in communicating in English, but attending the event would encourage me to overcome language barriers and engage in design-related contributions I have previously hesitated to pursue. I am especially working on enhancing my design workflow with Figma and WordPress, and I would like to get the chance to share my insights and knowledge on this subject with others.
When not contributing to WordPress, Yumi spends her time doing freelance work and raising a family.

**Please join us in congratulating Yumi and welcoming her to WordCamp US 2023!**

![Yumi photo](https://github.com/WordPress/Marketing-Team/assets/131417782/4692872e-705a-4d1b-86ce-81806c108a2c)

### Style confirmation

- [X] I've read the WordPress Brand Writing Style Guide

### Any additional notes or details?

**Content:**
The above text is taken directly from the WCUS and WordPress Foundation blog posts announcing the 2023 scholarship recipient, which are scheduled to be published tomorrow. Please feel welcome to change or expand upon this content.

**Timing:** Please feel welcome to publish later this week (any time after the recipient is announced on the WCUS and WPF blogs), or at a later date.

**Comment by bjmcsherry** [comment]
This campaign has been published. A slight change was requested and updated to include the name Mimi instead of Yumi, which we could update on all platforms except Twitter which keeps editing functions locked to Twitter Blue users only.

**Comment by bjmcsherry** [comment]
Closing topic.
