### ISSUE TITLE
[Tracking] Pages on MakeWP that show the % of WP

### ISSUE THREAD

**Issue by meherbala** [WordPress/Marketing-Team#255]
### Comment

@eidolonnight as and when I come across pages on MakeWP that show the percentage I am going to add them to this ticket, so we don't lose them and you can make the necessary. 

1. https://wordpress.org/about/features/

**Comment by eidolonnight** [comment]
This initiative started quite some time ago, and since then, W3Techs has updated its measurement methodology. I think we can safely close this issue.
