### ISSUE TITLE
Contributor event 31 March 2022 - request by Multidots

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#26]
Link to Slack thread request from Chirag Patel https://wordpress.slack.com/archives/C0GKJ7TFA/p1647588366222279.
Request for material shared again at Marketing Team meeting on 23 March 2022.

> Hey Everyone — Thank you so much for your contribution to WordPress. I am Chirag Patel, Project Manager of Multidots. My team and I are celebrating a company-wide contribution day this month, and a small group is dedicated and interested in contributing to marketing during this contribution day. So, I would like to join this group to learn about areas where my team and I can contribute to this channel! Feel free to share any details that will help make our contribution more effective and meaningful.

**Comment by nalininsbs** [comment]
Is there an update on this event to share at the marketing meeting today?

**Comment by abhansnuk** [comment]
A suggestion on polyglots-related task shared with Chirag in Slack. 

Adding some useful links for the event below:
https://learn.wordpress.org/workshop/an-introduction-to-contributing/

What is contributing?
https://europe.wordcamp.org/2021/contribute-to-wordpress/what-is-contributing/

Contribute to WordPress resource - from WordCamp Europe 2021 
https://europe.wordcamp.org/2021/contribute-to-wordpress/

**Comment by eidolonnight** [comment]
I believe the following issues would be the most impactful for this contributor group:

- https://github.com/WordPress/Marketing-Team/issues/7
- https://github.com/WordPress/Marketing-Team/issues/36
- https://github.com/WordPress/Marketing-Team/issues/47

**Comment by abhansnuk** [comment]
Chirag to help you onboard new contributors at the event, I have done a quick update to the [Getting Involved page](https://make.wordpress.org/marketing/handbook/getting-involved/) and added the link to the YouTube videos for setting up Slack. Have a great event!

**Comment by ronakganatra-multidots** [comment]
Hello @abhansnuk ,

Thank you for created this board, Me and @harshbhatt10 has worked on the #7 .

**Comment by abhansnuk** [comment]
Would you be able to update the header and see if it lets you change it @murillol ? Would you like to go back to the contributors who worked on the image a version for the header image for WordPress Events on Twitter? Thanks.

**Comment by murillol** [comment]
Ok I just updated it and its looks pretty cool! [Check it out](https://www.linkedin.com/company/12976001/admin/) @abhansnuk 

Will the multidots folks be doing another Contributor Day or should I just mention in the [original card](https://github.com/WordPress/Marketing-Team/issues/36)?

**Comment by abhansnuk** [comment]
The contributors who came from the multidots event are happy to make adjustments to the design, so suggest you add the request on this card and link Chirag Patel to it in Slack too as well as adding his GitHub ID to the request. Thanks @murillol
