### ISSUE TITLE
[AMPLIFY]: Announcing the first Learn WordPress Course Cohort

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Marketing-Team#268]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Developers

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin

### Campaign

None/Not sure/Other

### MakeWP Team

Training

### What do you want to amplify?

Announcing the first Learn WordPress Course Cohort.

### Amplification request details

The WordPress training team is launching a new type of learning experience, a course cohort. A course cohort is defined as a group of people who go through a learning journey at the same time. The topic of this cohort will be Developing your first WordPress Block, and will be perfect for first-time WordPress block developers, who have never built a block before. Interested parties can apply to be part of this cohort using the sign up form in the post

### Links

https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/

### Deadline

10 August 2024

### Additional important dates

The signup form will remain open until the 20th of August 2023.

**Comment by bjmcsherry** [comment]
A campaign has been created for this and will deploy this week.
