### ISSUE TITLE
Contributor Day WordCamp Vienna, 24 April 2022

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#27]
Planned contributor day at Word Camp Vienna. 
https://vienna.wordcamp.org/2020/what-is-a-wordpress-contributor-day-and-why-should-i-come/

**Comment by abhansnuk** [comment]
The team is looking at how contributor event cards can work most effectively in the Marketing GitHub going forward and what can go in the handbook. This card can be an example to work through.

**Comment by nalininsbs** [comment]
Some contributors who have contributed to marketing in the past or at marketing tables are at the event today. The Handbook card, social media cards, and GrowYourWP cards were shared via the WordCamp Vienna website for anyone wanting to contribute to marketing.

- [March Handbook review](https://github.com/WordPress/Marketing-Team/issues/47) 
- Social media card
- [GrowYourWP campaign awareness](https://github.com/WordPress/Marketing-Team/issues/51) 

Thank you to @abhansnuk and @eidolonnight for discussing this in a collaboration a few weeks ago.

If anyone attended in person, please update the card. Thank you.

**Comment by nalininsbs** [comment]
Informal discussions about how to promote contributing took part at the event. Ideas are to be taken to Europe. Thank you to anyone who gave time to this and encouraging the discussions.
