### ISSUE TITLE
[AMPLIFY] Contribute remotely to Core on the WCUS CD day

### ISSUE THREAD

**Issue by OlaIola** [WordPress/Marketing-Team#274]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Developers

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin

### Campaign

#WordCamp

### MakeWP Team

Core

### What do you want to amplify?

Invite to contribute remotely to Core on the WCUS CD day

### Amplification request details

Key points to highlight:
- Contributors from all over the world can join remotely on Slack Core channel
- New contributors can prepare beforehand to be productive on the day
- New contributors are invited to join the New Core Contributor Chat before the WCUS CD on August 23rd, 7 pm UTC to get help with environment installation, look up some tickets, meet each other and make plans for the next day

### Links

https://make.wordpress.org/core/?p=107443&preview=1&_ppp=155c70556f

### Deadline

22 August 2023

### Additional important dates

Right now the post is still in draft, but it will be published soon.

**Comment by sereedmedia** [comment]
This is completed
