### ISSUE TITLE
[AMPLIFY]:  Openverse x SMK collaboration

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/Marketing-Team#275]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Solicit feedback

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, WordPress users (existing), WordPress users (new/potential), Builders/implementers

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Openverse

### What do you want to amplify?

We'd like to amplify this post on Openverse's collaboration with its providers

### Amplification request details

Some on the Openverse team had a chance to meet with members of one of our providers, SMK. This is a fun post showing the collaboration that can come from open communication, sharing content, and working together!

### Links

https://make.wordpress.org/openverse/2023/08/17/cultivating-collaborative-pathways-with-statens-museum-for-kunst-smk/

**Comment by rmartinezduque** [comment]
I can take care of this one :)

**Comment by AetherUnbound** [comment]
That copy looks great! Thanks @rmartinezduque !

**Comment by rmartinezduque** [comment]
Just a quick note to confirm the social posts have been drafted and are currently under review. Brett will take care of getting them out, possibly tomorrow (August 23).

**Comment by rmartinezduque** [comment]
Closing this issue as social media posts to amplify the Openverse x SMK collab have been posted. Thanks for getting them out, @bjmcsherry! Below are the links—feel free to reshare:

- [X/Twitter](https://twitter.com/WordPress/status/1694381291196526761)
- [Linkedin](https://www.linkedin.com/posts/wordpress_wpopenverse-activity-7100146980940591104-o3bu/)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid0KEUGWbhVwoeCwC5c8WYHY924wSrWECCwMvTiWoqWVxeK7ex8thNt739GmooJxNUyl)
- [Instagram](https://www.instagram.com/p/CwSxKp5tFnA/)
