### ISSUE TITLE
The Month in WordPress: August 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#277]
### Comment

The Month in WordPress is a monthly roundup of WordPress news aimed at keeping existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the August 2023 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/10d6-7cyKdipO-TfnkZphBmyHZSA8d4UlFUcNNmoaLI4/edit).

## How you can help

You can **help by collecting any news or team updates** that would be valuable and relevant to the post and **writing summaries** for such news by September 5, 2023. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the August 2023 edition of The Month in WordPress is **September 8, 2023**. The document will be closed for edits on **September 5, 2023**, to allow for final edits and preparation for posting.

**Comment by bsanevans** [comment]
The Training Team has created drafts of the first three learning pathways we intend to publish on Learn.WordPress.org and are looking for feedback from the community. Could we have this post highlighted in this edition, please? 🙇‍♂️ 
https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/

**Comment by bsanevans** [comment]
By the way, thank you for always linking the GitHub issue for the next edition when closing out the previous month's edition! I get to follow along each month - it's a great workflow! 🌟

**Comment by rmartinezduque** [comment]
Hi Ben! I'm glad the current workflow is useful! We are actually trying a new Google doc template so it's easier to write and contribute content for everyone.

> Could we have this post highlighted in this edition, please? 🙇‍♂️
https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/

Wes gave us a heads-up about the project in the [Make Marketing Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1693377536780319), and I already included this in the draft:

> The Training Team is outlining learning pathways for users, designers, and developers to enhance their educational experience on Learn WordPress. [Share your feedback](https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/) by September 12, 2023.

Feel free to suggest any edits or another blurb [directly in the doc](https://docs.google.com/document/d/10d6-7cyKdipO-TfnkZphBmyHZSA8d4UlFUcNNmoaLI4/edit#heading=h.80m0giwf1w01). It's under the "Requests for feedback & testing" section. Thank you!

**Comment by bsanevans** [comment]
@rmartinezduque Oh, I see, the doc was clearly linked in the issue 🤦‍♂️ Got it. I'll add directly to the doc in future.

> Feel free to suggest any edits or another blurb [directly in the doc](https://docs.google.com/document/d/10d6-7cyKdipO-TfnkZphBmyHZSA8d4UlFUcNNmoaLI4/edit#heading=h.80m0giwf1w01).

What we have there now looks great 👍

**Comment by chaion07** [comment]
The Design Triage is Back: https://make.wordpress.org/design/2023/08/18/design-specific-triage/

**Comment by rmartinezduque** [comment]
Hi @chaion07! Thanks for the suggestion. I'm leaving that update out because this edition is already packed with many updates. However, please feel free to share any additional suggestions for the next post. I'll open a new GitHub issue once this edition is published.

**Comment by rmartinezduque** [comment]
The draft for the August 2023 edition of The Month in WordPress is ready for review. Comment or suggest edits by September 10 at 10:00 am UTC. I'm hoping to publish it on Monday, September 11.

Link: https://docs.google.com/document/d/10d6-7cyKdipO-TfnkZphBmyHZSA8d4UlFUcNNmoaLI4/edit.

Remember to include your WordPress.org profile link or username as a comment at the end of the document so that all contributions can be credited. Thank you!

**Comment by rmartinezduque** [comment]
The August 2023 edition of The Month in WordPress is now live: https://wordpress.org/news/2023/09/the-month-in-wordpress-august-2023/!

**Comment by rmartinezduque** [comment]
For those interested in contributing to the next edition of The Month in WordPress, please comment and subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/297. Thanks!
