### ISSUE TITLE
[AMPLIFY]: Looking for feedback: Learning pathway outlines

### ISSUE THREAD

**Issue by westnz** [WordPress/Marketing-Team#291]
### What is the goal of this amplification request? (select all that apply)

Solicit feedback

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#LearnWP

### MakeWP Team

Training

### What do you want to amplify?

Looking for feedback: Learning pathway outlines

### Amplification request details

We have started the process of drafting rough outlines for learning pathways intended for Users, Designers, and Developers. We are requesting community feedback.  Everything is outlined in this post: https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/

Many thanks

### Links

https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/

### Deadline

The due date of feedback is on the 12th of September

### Additional important dates

The due date for feedback is on the 12th of September.

**Comment by rmartinezduque** [comment]
@DanSoschin, can you help amplify this as part of the #LearnWP social campaign?

**Comment by DanSoschin** [comment]
Tentatively scheduled for midday Tues Sept 5 EST on Twtr/FB/LI.

Help shape the future of the WordPress Learn project - free educational resources about all things #WordPress. Provide your feedback by September 12 here >> https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/ #LearnWP

**Comment by westnz** [comment]
Thank you so much! 💚
