### ISSUE TITLE
The Month in WordPress: September 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#297]
### Comment

The Month in WordPress is a monthly roundup of WordPress news aimed at keeping existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the September 2023 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/1l01_qofoQXHKmlfe5NWkn-zwnZkgXK_Py8JwwYo0P3M/edit).

## How you can help

You can **help by collecting any news or team updates** that would be valuable and relevant to the post and **writing summaries** for such news by October 4, 2023. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the September 2023 edition of The Month in WordPress is **October 6, 2023**. The document will be closed for edits on **October 4, 2023**, to allow for final edits and preparation for posting.

**Comment by DanSoschin** [comment]
We should include the annual survey >> https://wordpress.org/news/2023/09/help-influence-the-future-of-wordpress-by-taking-the-2023-annual-survey-today/

**Comment by abhansnuk** [comment]
The most recent People of WordPress issues of not already included.

If the Community Summit links are being featured, can I suggest wording to show how those who were not there or already active in Make Slack can add comments / get involved with any follow-ups? Thanks @rmartinezduque

**Comment by rmartinezduque** [comment]
Hi folks, I don't have the bandwidth to work on this edition of the Month in WordPress. I made a call for contributors on the [Make WP Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1695741430755069) but haven't received any answer yet. If there is no one interested in helping/contributing to this issue in the next few days, I'm afraid we will have to skip it.

**Comment by rmartinezduque** [comment]
This edition was skipped due to other priorities. Please follow this GitHub issue to contribute to the next edition: https://github.com/WordPress/Marketing-Team/issues/313.
