### ISSUE TITLE
[AMPLIFY] Contribute to BuddyPress 12.0.0 beta-testing

### ISSUE THREAD

**Issue by imath** [WordPress/Marketing-Team#298]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Builders/implementers, Developers, Plugin community, Theme community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

This Month in WordPress

### Campaign

None/Not sure/Other

### MakeWP Team

None/Other

### What do you want to amplify?

Contribute to BuddyPress 12.0.0 beta-testing

### Amplification request details

More than ever in BuddyPress history, we need you to test BuddyPress next major release. In 12.0.0, we're introducing a massive change solving [a 10-year-old issue](https://buddypress.trac.wordpress.org/ticket/4954) to finally comply with the WordPress way of generating rules to analyze requested URLs and route the visitor to the right site content: the [WP Rewrite API](https://developer.wordpress.org/apis/rewrite/). BP Plugin/Theme authors are strongly invited to check their work will be ready for 12.0.0.

### Links

https://buddypress.org/2023/09/buddypress-12-0-0-beta2/

### Additional important dates

The current target for final release is: October 30, 2023

**Comment by rmartinezduque** [comment]
@imath The September edition of Month in WordPress was skipped due to other priorities, so this update didn't make it in. Are you interested in amplifying the BuddyPress 12.0.0-beta2 testing call? If so, we might be able to include it in the next issue (November). Let me know, thanks!
