### ISSUE TITLE
Update the Social Media Campaigns page in the Marketing Handbook

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#303]
The Automattic-sponsored contributors that are listed as the primary contacts for the social media campaigns are out of date. 

Campaigns that need updating:

- [x] [#WPDiversity](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpdiversity)
- [x] [#GrowYourStoryWP](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#growyourstorywp)
- [x] [#WPBriefing](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpbriefing) 

https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/

**Comment by eidolonnight** [comment]
Thanks for finding this! That page has been updated with the latest information.
