### ISSUE TITLE
Monthly polyglot newsletter

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#31]
This is the Macro card for this regular task. Individual newsletter editions appear on the board in the other columns depending on their status, for example, to do, in progress. When the newsletter has been published, a link is to be added to the relevant edition card, and the card moved to Done. 

Any marketing-related items relating to the newsletter series as a whole should be added to this macro card.

**Background**
Monthly newsletter starting October 2021 to highlight what is happening with Polyglots Team and to help people find key information as the Polyglots slack channel and P2 (blog) are both very busy locations.

Promotions of sign-ups:
- through WPTranslationDay 2021 (September 2021)
- via Polyglots, Marketing and Community Teams (ongoing)
- included in the Month in WordPress newsletter for September 2021  and future editions where relevant
- to be shared in the Meetup Newsletter for October 2021 and future editions where relevant
- onwards on social media and marketing opportunities (ongoing)
- to WordCamps and contributor events featuring polyglot contributor table (ongoing)

Next marketing related steps include:
- monthly production cycle being created (Erica and Abha)
- Nicholas offered to assist with Mailchimp etc
- promotion on WPTranslationDay website
- will there be an archive link?

**Comment by eidolonnight** [comment]
This newsletter has not been sent via Mailchimp for over a year, and the widget is no longer present on https://make.wordpress.org/polyglots/. Closing this issue.
