### ISSUE TITLE
Call for Contributor Stories at WordCamp Asia 2024

### ISSUE THREAD

**Issue by chaion07** [WordPress/Marketing-Team#310]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know, Twitter/X, Facebook, Instagram, Linkedin, YouTube, Pinterest, Tiktok, Tumblr, Threads, Email, This Month in WordPress, WordPress media

### Campaign

#WordCamp

### MakeWP Team

Accessibility, CLI, Community, Core, Core Performance, Design, Documentation, Hosting, Marketing, Meta, Mobile, Openverse, Photos, Plugins Review, Polyglots, Sustainability, Support, Test, Themes, Tide, Training, TV

### What do you want to amplify?

Call for Contributor Story Announcement

### Amplification request details

Recently we published a call for [Contributor Story Submission](https://asia.wordcamp.org/2024/were-calling-for-contributors-stories/). We would really appreciate if you can promote this. We would ideally want to start the conversation about leading the Marketing Table at the Contributor Day for WordCamp Asia 2024. Please feel free to ask questions for clarifications. Thank you in advance.

### Links

https://asia.wordcamp.org/2024/were-calling-for-contributors-stories/

### Deadline

25 November 2023

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

To participate, kindly share your contribution story in 250 words or fewer, accompanied by text, audio, or visual records (1-10 minutes) via your preferred social media platforms, which you’d like us to accompany with.

**Comment by chaion07** [comment]
Here are the posts from 2023:

- https://asia.wordcamp.org/2023/contributor-stories-01/
- https://asia.wordcamp.org/2023/contributor-stories-akshaya-chetan-dominyka-subhasis-trinisha/
- https://asia.wordcamp.org/2023/contributor-stories-alisha-aayusha-robin-tanvirul-rahul/
- https://asia.wordcamp.org/2023/contributor-stories-ahamed-alberuni-leonardus-merkys-vikas/

**Comment by sereedmedia** [comment]
Thanks @bjmcsherry.

**Comment by chaion07** [comment]
Much appreciated. Thanks for the help!
