### ISSUE TITLE
The Month in WordPress: October 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#313]
The Month in WordPress is a monthly roundup of WordPress news aimed at keeping existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the October 2023 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/1tdoOSmn3JR8hpzkKu9Wy1nlkAHuklcyXytGViUP167Q/edit).

## How you can help

You can **help by collecting any news or team updates** that would be valuable and relevant to the post and **writing summaries** for such news by November 3, 2023. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the October 2023 edition of The Month in WordPress is **November 8, 2023**. The document will be closed for edits on **November 3, 2023**, to allow for final edits and preparation for posting.

**Comment by eidolonnight** [comment]
A big thanks to [Bernard Meyer](https://profiles.wordpress.org/bernard0omnisend/) for the content this edition. He also provided feedback for the template we use each month. I'm applying those changes now.

**Comment by rmartinezduque** [comment]
Please follow this GitHub issue if you'd like to contribute to the next edition: https://github.com/WordPress/Marketing-Team/issues/321.
