### ISSUE TITLE
Modify the text on #5ftF as an individual contributor's role has changed. 

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Marketing-Team#317]
### Comment

@ipstenu 's employer has changed and this should be updated: https://wordpress.org/five-for-the-future/

**Comment by Ipstenu** [comment]
@courtneyr-dev I'm also not doing plugins anymore so ... perhaps someone else should be the new example?

**Comment by naokomc** [comment]
The front page contributor section can only feature one person at the moment. With gratitude to @Ipstenu for letting us feature you for 4+ years on the 5ftF front page, it'd be good to highlight other 5ftF contributors.

How about @harishankerr and I contact companies that have been consistently involved for 3-4 years, and have them write a CEO note + featured contributor profile?
If we have multiple entries, we can even swap them from time to time (manually for now...), and have one page to include them all.

**Comment by abhansnuk** [comment]
This sounds like a great way forward and the marketing team could perhaps help be involved in finishing the text.

**Comment by abhansnuk** [comment]
Suggest for the what is now general update of this section of the site, a new ticket could be created as it goes forward and shared in marketing team meetings.

**Comment by naokomc** [comment]
Based on the criteria below, we put together a list of contributors to ask for a testimonial.

- Five for the Future sponsored contributor
- Their sponsoring company has been actively participating the 5ftF program for at least 2 years
- A part of underrepresented group
- The list represents diverse locations of contributors
- The contributor actively contributes to core release

https://docs.google.com/spreadsheets/d/1tqKZMB-2204ow6m8psIuAFt4Bq_y2VFnzwsvAtPa2JM/edit#gid=0

Hari and I will reach out to these contributors to ask for a statement from their company leadership & their contribution brief, using the existing Case Study front page section format.

*Leadership statement*
50-70 words
Name and title

*Contribution brief*
40-50 words
Profile photo, if different from Gravatar

Once we receive the text from contributors, it'd be great if Makreting Team can help with reviewing them 🙏 

@abhansnuk I hope it's okay that I am using this issue to discuss this particular section, but let me know if a new ticket is necessary!

**Comment by naokomc** [comment]
Request for review:

I have one entry ready to be published once the Marketing Team gives us the go-ahead. Please review the text in this doc. Thank you so much for your help!
https://docs.google.com/document/d/1HRRKrnS3DBmA2ROjXZ-zrGVZ_id9v7ARiBw-D-4m-tk/edit#heading=h.jsbgln9zbwa5

**Comment by angelasjin** [comment]
I suggested some light edits, feel free to accept or reject as you see fit. Excited to see this updated, thank you all very much!

**Comment by eidolonnight** [comment]
I've jumped in with some edits. Just to be sure, this copy replaces the section in this screenshot?

![CleanShot 2024-01-22 at 10 46 08@2x](https://github.com/WordPress/Marketing-Team/assets/115154/c402a360-1ccc-4483-81b5-8ee17cd82395)

**Comment by naokomc** [comment]
Thank you @angelasjin @eidolonnight ! Yes, Nicholas, that's the section we are updating.
Pooja's Case Study is now published.
<img width="707" alt="Screenshot 2024-01-23 at 17 32 55" src="https://github.com/WordPress/Marketing-Team/assets/34067/52569b99-2107-4f88-86b6-4af9eec02ea9">

I will add a new case study in a month or so.

**Comment by naokomc** [comment]
@eidolonnight (or anyone else on the @WordPress/marketing team)

I have a new case study ready for review. Could you take a look? Thanks!
https://docs.google.com/document/d/1HRRKrnS3DBmA2ROjXZ-zrGVZ_id9v7ARiBw-D-4m-tk/edit#heading=h.j8ny1vqwz4mh

After review, I will publish this version after February 26th.

**Comment by rmartinezduque** [comment]
I offered some minor suggestions, @naokomc. Is it ok to suggest some improvements to enhance the clarity of the leadership statement/testimonial?

**Comment by naokomc** [comment]
I've accepted all suggestions made by @rmartinezduque, @abhansnuk, and @ardianimaya.

Reyes - yes, additional suggestions to improve are welcome.

**Comment by rmartinezduque** [comment]
Thanks, @naokomc. I left another suggestion to reword a bit the testimonial for better readability and flow. Feel free to accept and reject as you see fit.

**Comment by naokomc** [comment]
@rmartinezduque, your edits look great!
I can publish Nadia's case study next week on Feb 27th.

@zzap shared her version, and it's ready for a review:
https://docs.google.com/document/d/1HRRKrnS3DBmA2ROjXZ-zrGVZ_id9v7ARiBw-D-4m-tk/edit#heading=h.d9v4e5utgi9s

**Comment by rmartinezduque** [comment]
Sounds great, @naokomc! I left a few minor suggestions for consideration in Milana's copy.

**Comment by harishankerr** [comment]
We didn't publish Nadia's case study earlier, it is now published (as on April 22nd). We will publish Milana's profile in May.

**Comment by naokomc** [comment]
@rmartinezduque I added another profile text. There is no hurry but it would be great if you could take a look.

**Comment by thetinyl** [comment]
@naokomc I made a few suggestions for edits on Francesca's profile. Let me know if you have any questions or if there's anything else I can help with!

**Comment by naokomc** [comment]
Wonderful! I've updated the post with most of your suggestions and will talk with the contributors and get back to the rest. I appreciate it a lot, @thetinyl!

**Comment by harishankerr** [comment]
Update: We have published Milana Cap's case study as of today (June 4th). Let's have this case-study on the site for June, and add a new one in July. 
Big thanks to @rmartinezduque , @naokomc , and @zzap for their help!

**Comment by abhansnuk** [comment]
@harishankerr so pleased to see that Caroline 
is being featured as she is inspirational. I have added some suggestions in a review. 

On another note, are you still looking for suggestions for people to feature for this?
Thanks


> **Update**
> Thanks to @naokomc's outreach efforts, we have a new case study from @carolinan for review. It has been [added to our shared document](https://docs.google.com/document/d/1HRRKrnS3DBmA2ROjXZ-zrGVZ_id9v7ARiBw-D-4m-tk/edit). Can I have someone review this please? @rmartinezduque @thetinyl

**Comment by rmartinezduque** [comment]
> Can I have someone review this please?

I added some minor suggestions to Carolina's copy, @harishankerr. Hope that helps!

**Comment by eidolonnight** [comment]
The latest design of https://wordpress.org/five-for-the-future/ appears to incorporate all the work mentioned here. Closing issue.
