### ISSUE TITLE
The Month in WordPress: November 2023 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#321]
### Comment

The Month in WordPress is a monthly roundup of WordPress news aimed at keeping existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the November 2023 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/11Nt3gl5iIm8xvUOb4KkuiK1REuqgcv5U1bnGmyVB0Tg/edit).

## How you can help

You can help by collecting any news or team updates that would be valuable and relevant to the post and writing summaries for such news by December 3, 2023. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the November 2023 edition of The Month in WordPress is December 6, 2023. The document will be closed for edits on December 3, 2023, to allow for final edits and preparation for posting.

**Comment by rmartinezduque** [comment]
cc @bernard0omnisend given your interest in contributing to the Month in WordPress. 😊

**Comment by bernard0omnisend** [comment]
Would be very very happy to help out again @rmartinezduque !

**Comment by rmartinezduque** [comment]
The [November 2023 edition of the Month in WordPress](https://wordpress.org/news/2023/12/the-month-in-wordpress-november-2023/) is now published. :tada: Thank you to @bernard0omnisend for contributing to this edition!
