### ISSUE TITLE
Marketing Team team rep election process

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#323]
This will be the GH ticket to manage the Marketing Team team rep election process for 2024.

**Comment by sereedmedia** [comment]
Here is the election post: https://make.wordpress.org/marketing/2023/12/06/election-process-and-nominations-for-makewp-marketing-team-reps-2024/

**Comment by sereedmedia** [comment]
Here is the timeline:

- Wednesday, December 6: Nominations open
- Tuesday, December 19: Nominations close
- Wednesday, December 20: Voting begins
- Tuesday, January 9: Voting closes
- Wednesday, January 10: New Marketing Team Reps announced
- Wednesday, January 10 – Monday, January 15: Team Rep onboarding and transition
- Tuesday, January 16: 2024 Marketing Team Reps begin term

**Comment by eidolonnight** [comment]
The election was complete and the team is currently [limited in scope](https://make.wordpress.org/marketing/2024/04/29/wordpress-media-corps-next-steps/) so we can close this issue.
