### ISSUE TITLE
Hiring for the Plugin Review team

### ISSUE THREAD

**Issue by foosantos** [WordPress/Marketing-Team#327]
### What is the goal of this amplification request? (select all that apply)

Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, Developers, Plugin community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Plugins Review

### What do you want to amplify?

We reopened the application process for the Plugin Review team

### Amplification request details

We are especially looking to decrease underrepresentation on the team. Maybe it would be possible to have a campaign or such to bring confidence to underrepresented people to apply? Maybe ask people to share this with their underrepresented friends.

### Links

https://make.wordpress.org/plugins/2023/12/02/join-the-plugin-review-team/

### Deadline

31 December 2023 (date that we'll close the applications)

### Additional important dates

Just a small note that people might need some days to prepare for the application (such as getting the references), so ideally we should share this as soon as possible.

**Comment by bjmcsherry** [comment]
This has been scheduled and will launch tomorrow on all major platforms.
