### ISSUE TITLE
[AMPLIFY]: News Post: "Alert: WordPress Security Team Impersonation Scams"

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/Marketing-Team#328]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

WordPress users (existing)

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin, Tumblr

### Campaign

None/Not sure/Other

### MakeWP Team

None/Other

### What do you want to amplify?

Warn users of scams impersonating "WordPress team" and "WordPress security team"

### Amplification request details

The WordPress Security Team is aware of multiple ongoing phishing scams impersonating both the “WordPress team” and the “WordPress Security Team“ in an attempt to convince administrators to install a plugin on their website which contains malware.

This post warns users that such emails are scams and details where and how various teams will communicate with WordPress community team members. 

### Links

https://wordpress.org/news/2023/12/alert-wordpress-security-team-impersonation-scams/

### Deadline

Immediate

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

MakeWP team: Security

**Comment by eidolonnight** [comment]
Discussed and resolved in [Make Marketing Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1701731157125529). Links to posts below:

- [Twitter/X](https://twitter.com/WordPress/status/1732175948617801766)
- [Facebook](https://www.facebook.com/593573715915605/posts/756455656294076)
- [Linkedin](https://www.linkedin.com/feed/update/urn:li:share:7137941641226530816/)
