### ISSUE TITLE
[AMPLIFY]:  Introducing Enhanced Content Safety Features on Openverse 

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/Marketing-Team#330]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Solicit feedback

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, WordPress users (existing), WordPress users (new/potential)

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Openverse

### What do you want to amplify?

We'd like to share new sensitive content browsing features which are available in Openverse.

### Amplification request details

The details of the features that are available are present in the linked P2 on our blog. While Openverse has always been filtering content that was reported by users, this new feature filters media that has sensitive textual content within it. It also allows users the ability to enable viewing sensitive results.

### Links

https://make.wordpress.org/openverse/2023/12/11/introducing-enhanced-content-safety-features-on-openverse/

**Comment by bjmcsherry** [comment]
Copy has been written for this, but with character spacing at a premium, I wanted to share it here before publishing. @AetherUnbound, is this okay?:

> Openverse has introduced a significant update with new features to filter sensitive content. By default, openly licensed 
media that contain sensitive content are now excluded from search results, ensuring an accessible and safer browsing experience: https://make.wordpress.org/openverse/2023/12/11/introducing-enhanced-content-safety-features-on-openverse/

**Comment by AetherUnbound** [comment]
Thanks @bjmcsherry! I would only modify

> By default, openly licensed media that contain sensitive content are now excluded from search results

To 

> By default, openly licensed media that contain sensitive _textual_ content are now excluded from search results

We already exclude known sensitive content by default, this new feature adds additional filtering based on the title/tags/description of the work! Would that sound okay?

**Comment by rmartinezduque** [comment]
@bjmcsherry, what do you think about this copy option to incorporate @AetherUnbound's feedback while staying within the allowed characters?

> ✨ Introducing new features for enhanced content safety on Openverse. By default, search results now exclude openly licensed media containing sensitive textual content—with the ability to adjust this setting based on your preferences: https://make.wordpress.org/openverse/2023/12/11/introducing-enhanced-content-safety-features-on-openverse/ #WPOpenverse

**Comment by bjmcsherry** [comment]
@rmartinezduque That works for me. @AetherUnbound Does the above copy from Reyes, work for you?

**Comment by AetherUnbound** [comment]
That sounds perfect!

**Comment by bjmcsherry** [comment]
Perfect. I will move forward and build out the campaign for us.

**Comment by bjmcsherry** [comment]
This Campaign has been built and will deploy over the next hour on LinkedIn, Twitter/X, Facebook, and Instagram.

**Comment by AetherUnbound** [comment]
Thanks folks!

**Comment by rmartinezduque** [comment]
These are the links to the social posts: 

- [X/Twitter](https://twitter.com/WordPress/status/1735066086830129154)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid036vjZxeUsiXiUN2RHedpLzCmGzqGi6Ap7RmuYqW1hcpizA5sBEUqVet5hRYQBFdUrl)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_wpopenverse-activity-7140831760593907712-ZhSB/)
- [Instagram](https://www.instagram.com/p/C0z2kNtsx1f/)
