### ISSUE TITLE
Create issue template to Amplify a minor release

### ISSUE THREAD

**Issue by peterwilsoncc** [WordPress/Marketing-Team#333]
### Comment

WordPress minor releases are often released without any public notice as they are scheduled by the security team and it would be terribly unwise to post about security issues before they are fixed.

It would be good to create an AMPLIFY issue template in this repository for the announcement of releases with a reduced set of fields than the standard AMPLIFY template:

* Version number
* Type of release:
   * Maintenance
   * Security 
   * Maintenance and Security
* Link to release announcement on the news blog

**Comment by eidolonnight** [comment]
@peterwilsoncc is the current [Request for Amplification](https://github.com/WordPress/Marketing-Team/issues/new/choose) issue template insufficient or difficult to use for this purpose?

**Comment by eidolonnight** [comment]
After discussing with @peterwilsoncc there appears to be a need for an issue template that would allow for an expedited process for sharing security and maintenance releases across social platforms. This essentially replaces functionality formerly available via Jetpack sharing on WordPress.org News.

Posts submitted through this form should not require copywriting and can simply follow this previously used format:

> Release Announcement: WordPress X.Y.Z is now available. This is a **security|maintainence** release, and #WordPress recommends updating all environments to this latest version. More information here: **LINK**

Submitted issues will be assigned to @bjmcsherry to queue in Sprout. They will be posted to Twitter/X, Facebook, and Linkedin.

On release types:
- Every _security_ release should be shared. The latest [survey results](https://wordpress.org/news/2024/02/2023-annual-survey-results-and-next-steps/) show that security is a concern, and these releases demonstrate WordPress's dedication to addressing these concerns.
- _Maintenance_ releases should be carefully considered before sharing. Remember that our audience across platforms exceeds 2 million people, many of whom are new-to-WordPress users.

I will follow up shortly with a v1 issue template.
