### ISSUE TITLE
[AMPLIFY]: WCEU Call for Sponsors

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Marketing-Team#336]
### What is the goal of this amplification request? (select all that apply)

Other

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

None/Other

### What do you want to amplify?

WCEU Call for Sponsors

### Amplification request details

Call for Sponsor on WCEU website: https://europe.wordcamp.org/2024/sponsors/call-for-sponsors/

### Links

https://europe.wordcamp.org/2024/sponsors/call-for-sponsors/

### Deadline

First half of January

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

I'm on the WCEU Sponsor team and we'd love to request the WP Marketing team help to give more visibility to our call for sponsors. I am not sure about the best channel for doing it, we trust your experience. Thank you so much! Isotta

**Comment by bjmcsherry** [comment]
A campaign has been scheduled to deploy shortly, with a call for sponsors at WordCamp Europe 2024.

**Comment by peiraisotta** [comment]
Thank you all! How can we find out the post published or the channels that you are going to use?

**Comment by bjmcsherry** [comment]
I can post them here now as they have actually launched. 

- Facebook: https://www.facebook.com/593573715915605/posts/764867795452862
- LinkedIn: https://www.linkedin.com/posts/wordpress_call-for-sponsors-activity-7143627466534780928-AaNj?utm_source=share&utm_medium=member_desktop
- Twitter/X: https://twitter.com/WordPress/status/1737861770377638004

**Comment by peiraisotta** [comment]
Thank you so much!
