### ISSUE TITLE
Promote the Annual Meetup Survey

### ISSUE THREAD

**Issue by catederosia** [WordPress/Marketing-Team#337]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

We want people to fill out the 2023 Meetup Survey

### Amplification request details

**Below is what I wrote in the November Meetup Organizer newsletter. Feel free to edit as you choose, of course.**

The 2023 Meetup Survey is Out
It’s annual survey time, an opportunity to work together to get a pulse on the local WordPress meetups.

By taking 15 minutes to fill out [the annual survey](https://wordpressdotorg.survey.fm/2023-meetup-annual-survey), you contribute to a more complete view of your community as well as adding your own unique perspective to the global program, both of which are invaluable. 

The more responses we have, the more data we have to work with and the greater the impact is for WordPress meetups around the world.

This year’s survey has been simplified into one survey for both organizers and attendees, with a focus on your experience and how to best support growing communities. About two thirds of the questions are true/false or multiple choice, with the remaining questions providing opportunities for you to share your thoughts and ideas.

Submissions will be accepted through 14 January, 2024.

### Links

https://wordpressdotorg.survey.fm/2023-meetup-annual-survey

### Deadline

14 January 2023

**Comment by bjmcsherry** [comment]
Hi @catederosia, this has been completed. The campaign has launched, and here are some links:

- Facebook: https://www.facebook.com/593573715915605/posts/765377132068595
- LinkedIn: https://www.linkedin.com/posts/wordpress_wordpress-activity-7143959623966879744-uTr4/
- Twitter/X: https://twitter.com/WordPress/status/1738193951159419149
