### ISSUE TITLE
Request: Learn monthly GA stats report for Training

### ISSUE THREAD

**Issue by bsanevans** [WordPress/Marketing-Team#338]
### Comment

_I'm moving my request from [this Slack conversation](https://wordpress.slack.com/archives/C0GKJ7TFA/p1702708807642989) here._

Training is interested in receiving regular Google Analytics statistics about leaner behavior on https://learn.wordpress.org/. Details of the metrics we'd like will change once the site redesign has happened.

But for the moment, we're interested to see what folks click on after they land on the homepage. We’d like to track this data before and after the site redesign, to see if the redesign funnels folks into the new Learning Pathways, as we intend it to, when it launches in July 2024.

Apparently, Training used to receive regular email updates with GA stats. This hasn't been passed onto the current team reps or Faculty, so we'd like to get this set up again.

Sending the report to `learn@wordpress.org` would be best, in my opinion, as it is a shared inbox for vetted Faculty Administrators and team reps and wouldn't cause a bottle neck in processes, relying on a single recipient.

Let me know if any additional information is needed.

Tagging @eidolonnight and @bjmcsherry , as I don't have access to assign this issue to you.

**Comment by bjmcsherry** [comment]
@bsanevans We looked into this recently with another team, but unfortunately, the new upgrade with GA4 removed the ability to email reports. I will look into an alternative solution for this, but in a previous case, we managed to build a report in GA4, and then get access for someone to log in to review the results themselves. But before we go that route again, I will take another look at solutions.

**Comment by eidolonnight** [comment]
@bjmcsherry I think they just recently re-implemented these in GA4. Here's the doc: https://support.google.com/analytics/answer/13722168?hl=en

**Comment by bjmcsherry** [comment]
Oh perfect. Then I will take a look next week and see about setting it up. :)

**Comment by bjmcsherry** [comment]
Following up here. It looks like only an admin is able to set up an emailed report which would be Matt or Barry. We may have to go back to the original idea of just getting someone with the Learn team access to the account so they can see reports and pull relevant information for the Learn team.

**Comment by bjmcsherry** [comment]
Following up here as I have been added as admin in GA4, and will work next on re-adding a stats report for scheduling to learn@wordpress.org.

**Comment by bsanevans** [comment]
Thank you for looking into this 🙇‍♂️

**Comment by bjmcsherry** [comment]
Hi @bsanevans, I have tested a few report emails and got one that you will find beneficial for what is needed here. However, before I can schedule it for Learn, I keep getting an error message for the email address you provided, 'learn@wordpress.org'. Would there be a second email I can try? At the very least, an individual who would be good with receiving the email and sharing it with the wider Learn team?

<img width="847" alt="Screenshot 2024-01-22 at 2 54 51 pm" src="https://github.com/WordPress/Marketing-Team/assets/97543370/1f51c1a9-7c11-42b5-864a-c6d57442d9b1">

**Comment by bsanevans** [comment]
Hmm, I wonder why that is... 🤔 I'll DM you an alternative.

**Comment by bjmcsherry** [comment]
The email report has been set up. The original request to send a monthly report to 'Learn@wordpress.org' was not allowed by GA4 rules, but we worked around a solution to send it to an individual email who will share it with others in the Learn team. 

I will close this request with this comment.
