### ISSUE TITLE
[AMPLIFY]: Mentorship Program Call for Mentors/Mentees

### ISSUE THREAD

**Issue by naokomc** [WordPress/Marketing-Team#340]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

Mentorship Program Call for Mentors/Mentees P2 post

### Amplification request details

We are working on a call for mentees/mentors for the next cohort of the mentorship program.
We plan to publish it in the week of January 8, 2024, and close the application within a month.
The post will be on the Community Team P2, similar to [this previous call](https://make.wordpress.org/project/2023/06/23/launch-your-wordpress-contributor-journey-through-the-mentorship-program-pilot/).

**Target Contribution Experience Levels**
- Seasoned contributors
- New contributors
- Contributors with some contributing experience who are seeking growth

If appropriate channels exist, I would love to connect with new groups, such as university students, design or marketing communities, general JavaScript/PHP communities, etc.

Also, we appreciate any recommendations for the [article draft](https://docs.google.com/document/d/1UNQgnxnDOk-kJYiUAmGEUwMdmL0Q87xAHvSJn4gozgk/edit) as well.

Reference GitHub Issue:
https://github.com/WordPress/wp-contributor-working-group-tracker/issues/6

### Links

https://docs.google.com/document/d/1UNQgnxnDOk-kJYiUAmGEUwMdmL0Q87xAHvSJn4gozgk/edit

### Deadline

12 January 2024

### Additional important dates

The call will close on February 7, 2024. We may need additional amplification around then.

**Comment by naokomc** [comment]
Announcement P2 post published:
https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/

**Comment by bjmcsherry** [comment]
Hi @naokomc, a campaign has been scheduled to deploy today. Once they are live, I will post the links and close the ticket for you. Most likely, though, they will already be live by the time you see this. ;)

**Comment by naokomc** [comment]
Thank you!

- [Facebook](https://www.facebook.com/WordPress/posts/pfbid0fp14DJPvFF8KuFWXc3aXoJdgHBU4uibhnqRdvf9ayuiBk7CxgVSdAs658nvUJuCql?__cft__[0]=AZXhe99SaSijFbdMvpnlxlUtMISoXdDGIN3sEBrGKl_vqwTFbDyQyrXMvMJzA0fNugQrypQeGhKJ-WkQj0MwRz8NwGAus14GLBUFO2tFGhs-gTR787XnUfXh8twAMrVSyDDNo-jm53ksLx3H3pdCo42JtlhkdzL4lfea5kMsV7y83I_taSTDW84vQiW_ffgnxkY&__tn__=%2CO%2CP-R)
- [Twitter](https://twitter.com/WordPress/status/1747732529434509416)
- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7153498223481950209/)

**Comment by bjmcsherry** [comment]
Thank you for posting that @naokomc. I will go ahead and close this ticket. :)
