### ISSUE TITLE
[AMPLIFY]: WordPress.org/news post on Site Editor tools

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#342]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Other

### What is the intended audience(s) for this content? (select all that apply)

WordPress users (existing), WordPress users (new/potential), Builders/implementers, Developers, Designers, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

Please amplify this recent /news post about Site Editor tools: https://wordpress.org/news/2023/12/leap-into-2024-with-these-site-editor-tools/

### Amplification request details

I am looking to amplify a WordPress.org/news post that was published today in order to do a push around the end/start of the year. The title intentionally mentions 2024 so it should line up nicely!

### Links

https://wordpress.org/news/2023/12/leap-into-2024-with-these-site-editor-tools/

### Additional important dates

I don't have a firm deadline in mind but I'd like for it to be amplified around the start of 2024.

**Comment by annezazu** [comment]
Happy to provide any additional info/work directly with folks here too ✨ Thanks in advance!

**Comment by bjmcsherry** [comment]
Posted the campaign to amplify the news post for Site Editor tools. 

- Links are here - 
Facebook: https://www.facebook.com/593573715915605/posts/769078471698461
LinkedIn: https://www.linkedin.com/feed/update/urn:li:share:7146291483736752129/
Twitter/X: https://twitter.com/WordPress/status/1740525812317553027

Closing thread with comment.
