### ISSUE TITLE
The Month in WordPress: January 2024 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#343]
### Comment

The Month in WordPress is a monthly roundup of WordPress news to keep existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the January 2024 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/1QNPO00Q7Lu2f6EIlwwYc02VJAiE3mqaJvYPgEq1WS8g/edit?usp=sharing).

## How you can help

You can help by collecting any news or team updates that would be valuable and relevant to the post and writing summaries for such news by February 2, 2024. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the January 2024 edition of The Month in WordPress is February 6, 2023. The document will be closed for edits on February 2, 2024, to allow for final edits and preparation for posting.

**Comment by bph** [comment]
The [What's new for Developer (January 2024)](https://developer.wordpress.org/news/2024/01/10/whats-new-for-developers-january-2024/) was just published. It would be fantastic,  if you could include it into the upcoming This month in WordPress.

**Comment by rmartinezduque** [comment]
Thanks, @bph! We'll keep it in mind. cc @bernard0omnisend, who's been helping with the content of the latest editions. 🙂

**Comment by rmartinezduque** [comment]
The draft for the January 2023 edition of The Month in WordPress is ready for review. If you'd like to suggest any edits, please do so by February 6 at 14 pm UTC to allow for any final edits and preparation for posting. Thank you!

Link: https://docs.google.com/document/d/1QNPO00Q7Lu2f6EIlwwYc02VJAiE3mqaJvYPgEq1WS8g/edit

**Comment by jennimckinnon** [comment]
Reviewed and suggested a few tiny edits

**Comment by rmartinezduque** [comment]
Thank you, @jennimckinnon!

**Comment by rmartinezduque** [comment]
The [January 2024 edition of The Month in WordPress](https://wordpress.org/news/2024/02/the-month-in-wordpress-january-2024/) is now published. 🎉

If you're interested in contributing content to February's edition, please follow and join this GitHub issue: https://github.com/WordPress/Marketing-Team/issues/364.
