### ISSUE TITLE
[AMPLIFY]:  Early opportunities to help test 6.5 features

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#345]
### What is the goal of this amplification request? (select all that apply)

Solicit feedback

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Core, Test

### What do you want to amplify?

https://make.wordpress.org/test/2024/01/13/early-opportunities-to-test-wordpress-6-5/

### Amplification request details

Mainly just want to activate folks in the new year to help test and provide feedback especially since we don't have ongoing calls for testing with the FSE Outreach Program. 

### Links

https://make.wordpress.org/test/2024/01/13/early-opportunities-to-test-wordpress-6-5/

### Deadline

ASAP/before Feb 13th

### Additional important dates

Feb 13th (beta 1) as that's when a much larger call for testing will go out.

**Comment by DanSoschin** [comment]
Happy to support this and I'll work on some content shortly!

**Comment by bjmcsherry** [comment]
Hello, we published a call-out for testing on Tuesday afternoon (January 16th).

Posts are here:
Facebook: https://www.facebook.com/593573715915605/posts/779316777341297
LinkedIn: https://www.linkedin.com/feed/update/urn:li:share:7153164776955613185/
Twitter: https://twitter.com/WordPress/status/1747399081591201937

I will close this thread with this comment. :)

**Comment by annezazu** [comment]
Amazing! Thank you so much.
