### ISSUE TITLE
[AMPLIFY]: Core Editor Improvement post on Robust revisions

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#352]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Other

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

Share some of what's to come in WordPress 6.5

### Amplification request details

I'd like to get some attention on part of what's shipping in 6.5 to both build excitement and perhaps get folks to help test out what's currently available: https://make.wordpress.org/core/2024/01/22/core-editor-improvement-robust-revisions-in-the-site-editor/

### Links

https://make.wordpress.org/core/2024/01/22/core-editor-improvement-robust-revisions-in-the-site-editor/

### Deadline

Ideally sometime in the next week.

**Comment by DanSoschin** [comment]
I'll get this queued up for you, Anne. ETA will be early in the week of Jan 29.

**Comment by DanSoschin** [comment]
![Screenshot 2024-01-23 at 4 32 34 PM](https://github.com/WordPress/Marketing-Team/assets/53192304/bce65327-1382-4bb7-bd5f-556e535fa1ae)

**Comment by DanSoschin** [comment]
please note the date in the screenshot is not the actual date the posts will ship. It's just today's date as this is a preview.

**Comment by DanSoschin** [comment]
Posts scheduled for Jan 30, 2024
