### ISSUE TITLE
[AMPLIFY]: Global sponsors 2024 individual thank you posts

### ISSUE THREAD

**Issue by peiraisotta** [WordPress/Marketing-Team#353]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

Please amplify the Global sponsors 2024 individual thank you posts already published

### Amplification request details

Please amplify the Global sponsors 2024 individual thank you posts already published:

- GoDaddy: https://central.wordcamp.org/news/2024/01/godaddy-sponsors-wordpress-community-events-worldwide/
- WPBeginner: https://central.wordcamp.org/news/2024/01/wpbeginner-joins-the-wordpress-global-community-sponsorship-program-in-2024/
- Automattic: https://central.wordcamp.org/news/2024/01/automattic-sponsors-wordpress-community-events-across-the-globe/
- Woo: https://central.wordcamp.org/news/2024/01/thanks-to-woo-for-sponsoring-community-events-worldwide/
- Bluehost: https://central.wordcamp.org/news/2024/01/thanks-for-sponsoring-global-wordpress-community-events-across-the-globe-bluehost/

Thank you so much!

### Links

All links have been shared in the amplification request details section

**Comment by bjmcsherry** [comment]
These have been scheduled and will be deployed over the next 5 days - 1 campaign per day. I will be closing this request with this comment.

**Comment by peiraisotta** [comment]
Thank you, @bjmcsherry ! If the campaigns you've scheduled are social media campaigns, would it be possible to have the links to the posts in here once you publish them, so I can reshare them with the global sponsors? Thanks a lot!

**Comment by bjmcsherry** [comment]
@peiraisotta I can absolutely do that. They are still running but will end by this Wednesday. I will put together a comprehensive list with links at that time for you. :)
