### ISSUE TITLE
Marketing Team Slack onboarding message when you join the channel

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Marketing-Team#355]
### Comment

I would like to create an onboarding message that appears in the Make WordPress Slack Marketing channel when someone joins.

The message should be concise and help onboard new members and direct them to the most important information and links. It should also be very welcoming.

Please add your ideas and copy for the onboarding message in the comments below.

**Comment by eidolonnight** [comment]
I like this idea for welcoming newcomers. In thinking about what is most important to communicate, I put together this bit of an outline:

- I would start with the team description, just to re-affirm what it is this team does.
- It would be nice to include a few links to work we do regularly, things like [the Month in WordPress] [Posts](https://wordpress.org/news/category/month-in-wordpress/) and [People of WordPress](https://wordpress.org/news/category/community/) series.
- Citing resources like this GitHub repo and the handbook would be helpful.
- Since we've seen the most success onboarding folks when they make a quick human connection, mentioning a few folks (probably team reps) to connect with might help keep people around.

From that, here is a first draft:

> The Marketing team promotes WordPress to current and future users and contributors. We create and amplify campaigns to support the growth of the WordPress project. That includes sharing project news across [various channels](https://make.wordpress.org/marketing/handbook/social-media-accounts/), publishing the [Month in WordPress](https://wordpress.org/news/category/month-in-wordpress/), and interviewing contributors for the [People of WordPress](https://wordpress.org/news/category/community/).
>
> If you'd like to help, take a look at the team [handbook](https://github.com/WordPress/Marketing-Team/issues) and the [Marketing GitHub repository](https://make.wordpress.org/marketing/handbook/). If you need help, just say hello and tag our team reps: INSERT TEAM REPS.

**Comment by rmartinezduque** [comment]
Thanks for opening this issue, @jennimckinnon! This is a great idea, and I like @eidolonnight's suggestion.

If we want to mention some projects that include content creation, like The Month in WordPress and People of WordPress, do you think it would be good also to include a link to the WordPress Brand Writing Style Guide? It seems a good first resource that [we usually ask new contributors](https://github.com/WordPress/Marketing-Team/issues/241) to familiarize themselves with before contributing.

**Comment by BenjaminZekavica** [comment]
@jennimckinnon Here one example :) 

----

### Welcome to the Make WordPress Marketing channel! 🥳

🚀 Exciting times ahead! Whether you're a seasoned contributor or a newbie, we're thrilled to have you on board. 
Here's a quick guide to kickstart your journey:

**1️⃣ Introduce Yourself** 🧭
Share a quick hello! What brings you to the Marketing team? We'd love to know.

**2️⃣ Check Our Handbook** 📘
Dive into our handbook for key info on ongoing projects, collaboration tools, and how we roll.
Link to our Handbook: https://make.wordpress.org/marketing/handbook

**3️⃣ Upcoming Meetings** 🗓️ 
Join our weekly meetings to sync up with the team. Times and agenda are in the handbook.
More informationen you can find here: https://make.wordpress.org/marketing/welcome/ 

**4️⃣ Explore our GitHub Marketing Repository 📌** 
See what tasks are cooking! Our Repository is where the magic happens.
Link to our Markting Team Tickets: https://github.com/WordPress/Marketing-Team/issues

**5️⃣ Connect on WordPress Slack** 💬 
Need help or just want to chat? Reach out in the **#marketing** channel.

Feel free to ask questions, share ideas, and let's make WordPress Marketing even more awesome together! ✨

**Comment by jennimckinnon** [comment]
@BenjaminZekavica Thank you! Did you get this example from somewhere or did you write it?

**Comment by BenjaminZekavica** [comment]
I wrote most of it. For the text improvement and spelling, I used some suggestions from ChatGPT.

**Comment by askhellosatya** [comment]
There's a spelling mistake, it should be "information".

> 3️⃣ Upcoming Meetings 🗓️
> Join our weekly meetings to sync up with the team. Times and agenda are in the handbook.
> More informationen you can find here: https://make.wordpress.org/marketing/welcome/

**Comment by jennimckinnon** [comment]
Thank you all for you valuable input! Unfortunately, due to the heavy-handed, opaque, short-sighted, and expeditious closing of the Marketing Team by project leadership, this task cannot move forward.
