### ISSUE TITLE
[AMPLIFY]: [WordPress Photo Festival 2024]

### ISSUE THREAD

**Issue by askhellosatya** [WordPress/Marketing-Team#358]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Other

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know, General WordPress community, MakeWP community, WordPress users (existing)

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin

### Campaign

#WPPhotos, #WordCamp

### MakeWP Team

Community, Marketing, Photos

### What do you want to amplify?

WordPress Photo Festival 2024

### Amplification request details

Let's collectively amplify the WordPress Photo Festival – a cutting-edge community event! Your support can make this virtual experience a game-changer for the WordPress Photos Directory and foster open-source contributions.

:globe_with_meridians: Event Highlights:
- Date: Feb 3-10, 2024
- Format: Virtual
- Mission: Grow the WordPress Photos Directory

:busts_in_silhouette: How You Can Help:
- Spread the word in your networks.
- Encourage participation for a vibrant community.

Details & Registration: [WordPress Photo Festival](https://events.wordpress.org/kerala/2024/photo-festival/)

### Links

https://events.wordpress.org/kerala/2024/photo-festival/

### Deadline

3rd February 2024

### Additional important dates

The event is scheduled from the beginning of 3rd Feb (18:00 IST) to 10th feb (18:00 IST). 

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

This is a next-gen global Community Event to maximize the WordPress Photos Directory and grow our WordPress contributor base.

**Comment by askhellosatya** [comment]
//assign

**Comment by askhellosatya** [comment]
**Twitter:**
Dive into the world of visual storytelling at the WordPress Photo Festival! 📸✨ Submit your best photos to the WordPress Photos Directory for a chance to win $100. Don't miss out! Learn more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyContest

**LinkedIn:**
Join the global WordPress Photo Festival – a celebration of creativity! 🌐📷 Contribute your best shots to the WordPress Photos Directory and stand a chance to win $100. Discover more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPress #PhotographyContest #CommunityEvent

**Facebook:**
Capture the moment and join the excitement of the WordPress Photo Festival! 🎉 Submit your top photos to the WordPress Photos Directory for a shot at winning $100. Explore more details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyContest

**Instagram:**
📸✨ Exciting news! Participate in the WordPress Photo Festival by submitting your stunning photos to the WordPress Photos Directory. You could win $100! Check out the details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyContest #CaptureTheMoment

Don't forget to include these images with the Post!
![IMG-20240127-WA0003](https://github.com/WordPress/Marketing-Team/assets/86514552/9c433c55-bdac-4356-81e1-1e274c89266b)
![IMG-20240127-WA0002](https://github.com/WordPress/Marketing-Team/assets/86514552/48b5ebc9-d6df-4ccc-94cb-81b7d72aa8be)
![IMG-20240127-WA0004](https://github.com/WordPress/Marketing-Team/assets/86514552/848d886e-17d4-4322-a45b-252e6b30731d)
![IMG-20240127-WA0001](https://github.com/WordPress/Marketing-Team/assets/86514552/d9c7383a-90e3-4976-906c-c3659c371f87)

**Comment by askhellosatya** [comment]
The draft has been reviewed by [Bigul Malai](https://profiles.wordpress.org/mbigul/), who finds it perfect. [Yashwardhan Rana](https://profiles.wordpress.org/yashwardhanrana/) suggests not mentioning the $100 reward on all platforms, emphasizing the goal of driving contributions with zeal rather than for the reward. Considering the event's contest nature, I propose including the prize money to boost engagement and attract new contributors to our WordPress photos directory.

The final decision rests with you, @jennimckinnon, @bjmcsherry, @eidolonnight, @Greennc. Your thoughts on including the prize money on all platforms will help us make an informed choice.

**Comment by jennimckinnon** [comment]
Thanks @askhellosatya! There are certain rules and regulations that need to be followed for various countries around the world where the contest will be made available. I'm not a lawyer, but according to US law (where the WordPress Foundation is registered) you need to provide [various items such as a Terms of Service and certain wording when promoting the contest](https://www.americanbar.org/groups/gpsolo/publications/gpsolo_ereport/2022/december-2022/sales-promotions-contests-sweepstakes-laws-regulations-your-business-clients-must-know/). I'm not sure if registered 501(c)3 non-profit organizations (such as the WordPress Foundation) are exempt from these regulations. As I'm not a lawyer, I cannot provide any further details or advice about the contest portion of this amplification request.

**Comment by askhellosatya** [comment]
Hi, @jennimckinnon! Appreciate your feedback. Your point is valid, so let's streamline the amplification process by removing that part promptly.
I'll be sharing an optimized draft very soon!

**Comment by askhellosatya** [comment]
It's an optimized draft; I've removed the winning prize and related info from the draft (as suggested by @jennimckinnon & Yashwardhan Rana) and added contribution + open-source part. Let's review it and make sure that it can be finalized within 24 hours so it can go live before 1st Feb!

> Twitter: 
> Immerse yourself in the world of visual storytelling at the WordPress Photo Festival! 📸✨ Share your best photos with the WordPress Photos Directory and become an open-source contributor. Learn more: https://events.wordpress.org/kerala/2024/photo-festival/festival/ #WordPressPhotoFestival #PhotographyEvent
> 
> LinkedIn:
> Join the worldwide WordPress Photo Festival – a celebration of creativity! 🌐📷 Contribute your best shots to the WordPress Photos Directory, showcasing your photography skills. Become an open-source contributor, ensuring a more accessible web for everyone. Discover more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPress #PhotographyEvent #Community
> 
> Facebook:
> Capture the moment and join the excitement of the WordPress Photo Festival! 🎉 Share your top photos with the WordPress Photos Directory and be part of this creative celebration. Explore more details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyEvent
> 
> Instagram:
> 📸✨ Exciting news! Participate in the WordPress Photo Festival by sharing your stunning photos with the WordPress Photos Directory. Showcase your creativity! Check out the details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyEvent #CaptureTheMoment
> 
> Remember to include these images with the post!
> 
> ![IMG-20240127-WA0001](https://github.com/WordPress/Marketing-Team/assets/86514552/b069c53f-127e-4876-8ece-30d410eecd8c)
> ![IMG-20240127-WA0004](https://github.com/WordPress/Marketing-Team/assets/86514552/2fe51f6b-67a5-4
> ![IMG-20240127-WA0003](https://github.com/WordPress/Marketing-Team/assets/86514552/d50b5b90-d0a4-47ad-aaf0-702ec574b627)
> 289-ac6f-4eac0267fc22)
> ![IMG-20240127-WA0002](https://github.com/WordPress/Marketing-Team/assets/86514552/f7897c72-2e53-4ff0-a050-b13fe5ac6c41)
>

**Comment by jennimckinnon** [comment]
@askhellosatya One of the images and the website still states the contest / being able to potentially win $100. Those will need to be modified as well to remove the references.

**Comment by askhellosatya** [comment]
@jennimckinnon, we can omit the image, but altering the website for contest reference is beyond our control. The event primarily involves photo contributions as part of a contest. We'll need to find an alternative approach – either excluding that aspect from our official marketing/amplification posts or sharing the contest guidelines along with the event information. What are your thoughts?

**Comment by jennimckinnon** [comment]
@askhellosatya I'm not qualified to give advice on this so I would recommend contacting one of the [Community Team's Program Managers](https://make.wordpress.org/community/community-deputies/) as they would likely be able to direct you to an answer far more than I could.

**Comment by eidolonnight** [comment]
This is looking good @askhellosatya. I agree with omitting the prize value from the social posts and focusing on contribution. I think we can also simplify this to a single image with a request for readers to click for more details.

![image](https://github.com/WordPress/Marketing-Team/assets/115154/562c416a-da98-4110-87eb-96d4d4ea71ed)

That's fairly standard for our posts, and the [guidelines for submissions](https://wordpress.org/photos/submit/) extend beyond those listed in the images shown above. Other than that, the latest copy looks good to me except for a slight adjustment for "open-source" (see [Writing about WordPress](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#writing-about-wordpress)).

**Twitter/X**
> Immerse yourself in the world of visual storytelling at the WordPress Photo Festival! 📸✨ Share your best photos with the WordPress Photos Directory and become an open source contributor. Learn more: https://events.wordpress.org/kerala/2024/photo-festival/festival/ #WordPressPhotoFestival #PhotographyEvent

**LinkedIn**
> Join the worldwide WordPress Photo Festival – a celebration of creativity! 🌐📷 Contribute your best shots to the WordPress Photos Directory, showcasing your photography skills. Become an open source contributor, ensuring a more accessible web for everyone. Discover more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPress #PhotographyEvent #Community

**Facebook**
> Capture the moment and join the excitement of the WordPress Photo Festival! 🎉 Share your top photos with the WordPress Photos Directory and be part of this creative celebration. Explore more details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyEvent

**Instagram**
> 📸✨ Exciting news! Participate in the WordPress Photo Festival by sharing your photos with the WordPress Photos Directory. Showcase your creativity! See the link in our bio for details. #WordPressPhotoFestival #PhotographyEvent #CaptureTheMoment (https://events.wordpress.org/kerala/2024/photo-festival/)

@bjmcsherry I think this is ready to schedule and ship.

**Comment by askhellosatya** [comment]
Thanks, @eidolonnight, for your feedback! Glad you liked the latest draft post. I think it's good to go. @jennimckinnon & @Greennc, what are your thoughts? Please ensure it goes online ASAP.

**Comment by bjmcsherry** [comment]
@askhellosatya, I do have a couple of changes to look at with the images, which I will list here:

- One of the photos with the headline "Beyond Code" seems to be missing some text in the final line of the bottom section. "...use the hashtag #WPKeralaPhotos with your" We should have that image updated.
- We can remove the ordinal numbers in the dates. So, consider using "February 3 to February 10, 2024." (without the _rd_ or _th_)

It is a good idea to continually use the [Writing Style Guide and Brand Book](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/). I have a couple of notes we can look at from the Style Guide listed below:

- It is helpful to avoid saying "open-source" with a hyphen. Always Keep the space (open source). Since this is just in the copy, I can fix it when I submit it in Sprout. 
- In the LinkedIn copy, using the em dash with no spaces is good. Again, I can fix this in Sprout, but it's still good to note. 

Finally, this isn't needed for the social posts, but I highly recommend adding an hourly submission deadline in UTC on the webpage. Otherwise, it will be a small window for accepting submissions that may otherwise be late. It's just something to consider.  :)

**Comment by askhellosatya** [comment]
@bjmcsherry, appreciate your detailed feedback. I'll revise and share an updated draft shortly. For the webpage and image update, I'll reach out to the event organizers promptly.

**Comment by askhellosatya** [comment]
**Draft Post**

**Twitter/X**

> Immerse yourself in the world of visual storytelling at the WordPress Photo Festival! 📸✨ Share your best photos with the WordPress Photos Directory and become an open source contributor. Learn more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyEvent

**LinkedIn**

 

> Join the worldwide WordPress Photo Festival – a celebration of creativity! 🌐📷 Contribute your best shots to the WordPress Photos Directory, showcasing your photography skills. Become an open source contributor, ensuring a more accessible web for everyone. Discover more: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPress #PhotographyEvent #Community

**Facebook**

> Capture the moment and join the excitement of the WordPress Photo Festival! 🎉 Share your top photos with the WordPress Photos Directory and be part of this creative celebration. Explore more details: https://events.wordpress.org/kerala/2024/photo-festival/ #WordPressPhotoFestival #PhotographyEvent


**Instagram**

> 📸✨ Exciting news! Participate in the WordPress Photo Festival by sharing your photos with the WordPress Photos Directory. Showcase your creativity! See the link in our bio for details. #WordPressPhotoFestival #PhotographyEvent #CaptureTheMoment (https://events.wordpress.org/kerala/2024/photo-festival/)

Regarding the updated image and webpage (now featuring UTC timings and running from Feb 3 to Feb 10), the changes will be applied and shared with you soon. Thanks!

**Comment by bjmcsherry** [comment]
Thanks @askhellosatya. I appreciate the update. :)

**Comment by rmartinezduque** [comment]
Hi @bjmcsherry and @askhellosatya, just a minor piece of feedback regarding the copy:

> WordPress Photos Directory

The name of the directory is usually written in singular, both on the [Photo Directory page](https://wordpress.org/photos/) and the posts shared as part of the [WPPhotos social media campaign](https://make.wordpress.org/marketing/handbook/social-media-accounts/social-media-campaigns/#wpphotos), i.e., WordPress **Photo** Directory. It's similar to Themes and Plugins. Their directories are called "Theme Directory" and "Plugin Directory." It would be great if you could update that in the copy for consistency. Thank you!

**Comment by askhellosatya** [comment]
@bjmcsherry, @rmartinezduque, and @eidolonnight, could you please make it live at your earliest convenience? The event is scheduled to start in 67 hours!

**Comment by bjmcsherry** [comment]
@askhellosatya Has the image been updated? We were just waiting for that to be sent over. If you don't believe that it can be done in time, then let me know, and I will adjust things accordingly.

**Comment by askhellosatya** [comment]
@bjmcsherry, given this event schedule and urgency, I believe we're ready to proceed without an image. I haven't received an updated image from the organizing team yet, so shipping it without an image is our only option.

**Comment by bjmcsherry** [comment]
Okay, with that in mind, I will go ahead with this image for all of the social platforms in this campaign:
<img width="645" alt="Screenshot 2024-01-31 at 5 18 29 pm" src="https://github.com/WordPress/Marketing-Team/assets/97543370/63ff18a5-c2d1-44af-aef6-bd0ec2fbd106">

**Comment by bjmcsherry** [comment]
@askhellosatya The campaigns are scheduled and will launch on February 1st at 1 PM UTC. With that, I will close this thread.

Remember to look up the posts and help amplify them to the community. :)
