### ISSUE TITLE
Alternative Banner Images for LinkedIn

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#36]
Our current [Make WordPress Marketing Team LinkedIn Page](https://www.linkedin.com/company/12976001/admin/) has a header image that is not changed often, and we would like for it to reflect current or evergreen campaigns/events (e.g. LearnWP, WPTranslationDay, etc).

**Task**: create an alternative banner image(s) for the Make WordPress Marketing Team LinkedIn Page 

_Themes_: 
- Learn WordPress #LearnWP
- "Timeless" banner to be used most of the time

_Dimensions_: 1128x191

_Skills Needed_:
- Previous experience designing/creating banners for social profiles

_Resources_:
- https://wptranslationday.org/wptd-2021/media-kit/
- https://make.wordpress.org/marketing/2020/12/09/help-us-promote-learn-wordpress/

**Comment by abhansnuk** [comment]
From @murillol at the marketing team meeting, 30 March 2022:
- banner images still needed
- contributors would need a familiarity with creating banners for LinkedIn
- @abhansnuk : [banner image size guide from LinkedIn](https://www.linkedin.com/pulse/fully-comprehensive-linkedin-size-guide-images-video-sarah-clay)

From discussion with @eidolonnight for this to be a potential task for a contributor event on 31 March 2022:
- images could be from [OpenVerse](https://wordpress.org/openverse/)

**Comment by kaushikbaroliya** [comment]
Howdy, 

I have designed a banner image for **Make WordPress Marketing Team LinkedIn Page**. Please find the attached banner image with dark and light color options.

![LinkedIn_header_banner_option_01](https://user-images.githubusercontent.com/102730573/161081707-e84ae929-650a-4d3b-b056-ba4bcfc245ad.jpg)
![LinkedIn_header_banner_option_02](https://user-images.githubusercontent.com/102730573/161081745-df8fd12b-0251-4676-a94c-a98e9aa0ca4d.jpg)

I appreciate your thoughts.

Thanks!

**Comment by ronakganatra-multidots** [comment]
This looks great @kaushikbaroliya .

Thanks

**Comment by nalininsbs** [comment]
Thank you @kaushikbaroliya. You had fun! Did you enjoy the contributor day?

**Comment by abhansnuk** [comment]
@murillol could this be available as a task at WCEU too to give another alternative image?  Its GitHub [card](https://github.com/WordPress/Marketing-Team/issues/64)

**Comment by murillol** [comment]
Nothing else for this card on my end @nalininsbs !
