### ISSUE TITLE
[AMPLIFY]: Online monthly Docs Team Contributor Day February 27, 2024

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Marketing-Team#363]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin

### Campaign

None/Not sure/Other

### MakeWP Team

Documentation

### What do you want to amplify?

Bring awareness to the February 2024 Docs Team online Contributor Day.

### Twitter/X, Facebook, and Linked In

We need your help – yes you. Join the Make WordPress Docs Team for the online monthly Contributor Day on Tuesday, February 27 to help with WordPress documentation. All are welcome: https://make.wordpress.org/docs/2024/02/01/online-monthly-docs-team-contributor-day-february-27-2024/

![Docs-Team-Contributor-Day-1200x675](https://github.com/WordPress/Marketing-Team/assets/9810898/015ca035-72a4-4d85-b90e-d49f6f955231)

### Instagram

We need your help – yes you. Join the Make WordPress Docs Team for the online monthly Contributor Day on Tuesday, February 27 to help with WordPress documentation. All are welcome: https://make.wordpress.org/docs/2024/02/01/online-monthly-docs-team-contributor-day-february-27-2024/

![Docs-Team-Contributor-Day-1080x1080](https://github.com/WordPress/Marketing-Team/assets/9810898/2c656fad-5ca7-4980-9502-07014278d290)

### Links

https://make.wordpress.org/docs/2024/02/01/online-monthly-docs-team-contributor-day-february-27-2024/

**Comment by bjmcsherry** [comment]
@jennimckinnon I just want to confirm. Is the above additional details or the suggested copy? Just to follow the writing guides a little more, I want to make a slight tweak. This is what I have now:

------------
Mark your calendars. 📆 The Documentation Team is hosting its next online Contributor Day on February 27! If you’re passionate about documentation, this is a great opportunity to share your skills and get involved. Details: https://make.wordpress.org/docs/2024/02/01/online-monthly-docs-team-contributor-day-february-27-2024/

#WordPress #WordPressCommunity
-------------

**Comment by jennimckinnon** [comment]
@bjmcsherry Yes, it was copy suggestions to get things kicked off.

Great edits, thank you!

**Comment by jennimckinnon** [comment]
I'm closing this request as the event is in less than 10 hours from the time of posting this comment.
