### ISSUE TITLE
[AMPLIFY]: WordPress is joining forces with Drupal, Joomla, and TYPO3 in the Open Website Alliance

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#365]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

None/Other

### What do you want to amplify?

WordPress is joining forces with Drupal, Joomla, and TYPO3 in the Open Website Alliance

### Amplification request details

Josepha and Chloé approved this copy for social platforms:

> At WordPress, we believe in the power of open source software to empower individuals and organizations worldwide. That's why we're thrilled to join forces with Drupal, Joomla, and TYPO3 in the Open Website Alliance—advocating for a digital future built on openness, collaboration, and innovation.

@eidolonnight will attach the charter to WordPress.org as a reference, and @bjmcsherry will proceed with scheduling social posts.

_Note: We might want to check the social media handles of Drupal, Joomla, and TYPO3 to tag them on our posts._

### Links

TBD

**Comment by eidolonnight** [comment]
PDF version of charter is uploaded and available at https://wordpress.org/news/files/2024/02/Open-Website-Alliance-Charter.pdf

**Comment by rmartinezduque** [comment]
Closing this issue since social posts went live on February 8:

- [Twitter](https://twitter.com/WordPress/status/1755516866485707064)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid02a2rDi5xrCH829d4cp4qnU5hsQAPrZRU3XvVsrJdBcNB2dhpYX57EZuPL7MiZqxzql)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_we-believe-in-the-ability-of-open-source-activity-7161282538181672960-hdqI/)
- [Instagram](https://www.instagram.com/p/C3FKgGgswhl/)

@bjmcsherry, I believe these are the social platforms where posts were shared. Feel free to add any other link I may have missed. Thanks!
