### ISSUE TITLE
Promote call to translate hosting pages

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#37]
_Copied from Trello for review
Has this been done and closed?_

Task: translate https://wordpress.org/hosting/ for local sites, like de.wordpress.org and nl.wordpress.org. This means more than translating words: it needs to show hosting companies that actually offer support in that particular language.

_Timeline_
10 July 2020
@abhansnuk 
Olga, Siobhan Seija, do you know if there was any additional progress on this? Thanks. If not, we can mark it up for discussion with the polyglots team as a possibility for WCUS Contributor Day or after post 5.5 translation day. Thanks

30 June 2019
@OlaIola:
I can translate on Russian, but I looked three hosts on this page and through hosts on «Host Test Results» and only GoDaddy has Russian version and phones. And also, we have a law that order to store personal information inside a country and there is nothing about physical location of data-center.

**Comment by abhansnuk** [comment]
Sent to Naoko (polygots) in Marketing slack channel to check if promotion of call still needed. [Slack message](https://wordpress.slack.com/archives/C0GKJ7TFA/p1648514173533029)

**Comment by naokomc** [comment]
[Spanish hosting page](https://es.wordpress.org/colabora/hosting/) exists, but in English only. As far as I'm aware, I don't think there are translated hosting pages yet.

For countries where it's common to use hosts listed on the English page, they can go ahead and start translating the current page.

For others, we will need to select hosts to list.
I had been meaning to check what the Hosting Community Team decided in terms of the requirements for hosts to list.

Currently, they are looking into completing the requirements for hosts to be listed on the page.
https://wordpress.slack.com/archives/C3D6T7F8Q/p1646817591490899

I feel comfortable selecting hosts and publishing the page after the referred doc ([WordPress.org Recommended Hosts Page “Requirement Matrix” Criteria](https://docs.google.com/document/d/1uvb3LsOyTZ0D2mVw7yokfCxMb0lCkFWdSnXD1b-2HWU/)) is completed. Meanwhile, I will remind teams it's recommended to follow the conversation and add any inputs.

**Comment by abhansnuk** [comment]
Would you like this card on marketing closed for now @naokomc and you can reopen it in future when you would like promotion of any call you are doing? Thanks for doing the status review.

**Comment by naokomc** [comment]
@abhansnuk 
FYI, we have mentioned this request in the Polyglots Meeting last week ([agenda](https://make.wordpress.org/polyglots/2022/03/30/agenda-weekly-polyglots-chat-march-30-2022-1300-utc/), [Slack](https://wordpress.slack.com/archives/C02RP50LK/p1648645618771869)).
I think closing this now and reopening after WCEU would be the best.

**Comment by sereedmedia** [comment]
I'm closing this ticket per the comments. It was created to promote a specific call for translation. If additional calls for translation need to be promoted, we can open a new issue.
