### ISSUE TITLE
[AMPLIFY]: The WordPress Foundation 2023 Annual Report is Now Available

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#370]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin

### Campaign

None/Not sure/Other

### MakeWP Team

Marketing

### What do you want to amplify?

The WordPress Foundation 2023 Annual Report is Now Available

### Amplification request details

The WordPress Foundation has recently [announced its 2023 Annual Report](https://wordpressfoundation.org/news/2024/the-wordpress-foundation-2023-annual-report-is-now-available/). Promoting it across WordPress social platforms would be good to inform and raise awareness about it.

Suggested copy for review:

> The WordPress Foundation has published its 2023 Annual Report, featuring insights into the growth and impact of the educational programs and events it supports. Learn more at https://wordpressfoundation.org/news/2024/the-wordpress-foundation-2023-annual-report-is-now-available/.

### Links

https://wordpressfoundation.org/news/2024/the-wordpress-foundation-2023-annual-report-is-now-available/

**Comment by bjmcsherry** [comment]
@rmartinezduque The campaign has been scheduled to deploy this coming Wednesday.

**Comment by rmartinezduque** [comment]
Social posts are published. Help by sharing and amplifying:

- [Twitter](https://twitter.com/WordPress/status/1757757104725651590)
- [Linkedin](https://www.linkedin.com/posts/wordpress_the-wordpress-foundation-has-published-its-activity-7163522778808193024-3FjZ/)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid0trQcvPH1iWcjKkvAosNr9md7bKY1T7v1oWpQn5ptQtDHK5jemmDuStp3bpNrHKxul)
- [Instagram](https://www.instagram.com/p/C3VFBJsMHtj/)
