### ISSUE TITLE
[AMPLIFY]: 15K photo milestone in the Photo Directory

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#382]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin

### Campaign

#WPPhotos

### MakeWP Team

Marketing, Photos

### What do you want to amplify?

15K photo milestone in the Photo Directory

### Amplification request details

I suggested the following copy to celebrate the 15K photo milestone in the Photo Directory:

> The WordPress Photo Directory recently hit a remarkable milestone, surpassing over 15,000 free photos! Come explore the latest additions—and help keep the collection growing by contributing yours: wordpress.org/photos/.
> 
> 📸 [Photo](https://wordpress.org/photos/photo/32665c5bc9/) by Nilesh Shiragave #WPPhotos

Social posts are tentatively scheduled to go out on Sunday and are pending review from @bjmcsherry.

### Links

https://wordpress.org/photos/

**Comment by askhellosatya** [comment]
Hi @rmartinezduque, the suggested copy looks good to go. Additionally, I believe we can mention that the WordPress Photo Festival 2024, as a next-gen event, makes a significant contribution to achieving this goal.

Here's the revised version with your suggestion included:

> The WordPress Photo Directory hits a milestone with over 15,000 free photos! Join us in celebrating this achievement, with the [WordPress Kerala Photo Festival 2024](https://events.wordpress.org/kerala/2024/photo-festival/), a next-gen event playing a significant role. Explore the collection and contribute yours: wordpress.org/photos/

cc: @eidolonnight, @jennimckinnon, @bjmcsherry, your suggestion?

**Comment by rmartinezduque** [comment]
Hi @askhellosatya, thanks for your suggestion. The social posts were already scheduled for yesterday (Sunday), so I'm afraid we cannot change the social copy.

Either way, and since the WordPress Kerala Photo Festival 2024 was promoted earlier on social, perhaps you can suggest another post (in a new amplification issue) that speaks about the number of submissions received as part of this WordPress event and how it has positively contribute to the Photo Directory, encouraging folks to help keep growing the collection. Something similar to what we did for the [World Photography Day challenge](https://x.com/WordPress/status/1564591280881025025?s=20). You could also share a link to https://wordpress.org/photos/t/wpkeralaphotos/ so folks could see and enjoy all the photos sent as part of the event. How does that sound?

**Comment by rmartinezduque** [comment]
I'm closing this issue since social posts are already out. @askhellosatya, feel free to open a new amplification request for any WordPress Kerala Photo Festival posts you'd like to suggest. Thank you!
