### ISSUE TITLE
[AMPLIFY]: Online monthly Docs Team Contributor Day March 26, 2024

### ISSUE THREAD

**Issue by jennimckinnon** [WordPress/Marketing-Team#384]
### What is the goal of this amplification request? (select all that apply)

Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin, This Month in WordPress

### Campaign

None/Not sure/Other

### MakeWP Team

Documentation

### What do you want to amplify?

March's online Contributor Day is coming up and we need to get the word out to get more people to attend and contribute.

### Amplification request details

Perviously suggested copy from @bjmcsherry:

Mark your calendars. 📆 The Documentation Team is hosting its next online Contributor Day on February 27! If you’re passionate about documentation, this is a great opportunity to share your skills and get involved. Details: https://make.wordpress.org/docs/2024/03/01/online-monthly-docs-team-contributor-day-march-26-2024/

#WordPress #WordPressCommunity

Image for Twitter/X, Facebook, and LinkedIn:

![image](https://github.com/WordPress/Marketing-Team/assets/9810898/d162e4c3-c44f-4370-928b-9d9e4dcd6a1a)

Image for Instagram:

![image](https://github.com/WordPress/Marketing-Team/assets/9810898/bee8924b-7d07-445e-b72b-8a55d1e9f369)

### Links

https://make.wordpress.org/docs/2024/03/01/online-monthly-docs-team-contributor-day-march-26-2024/

### Deadline

5 March, 2024

**Comment by jennimckinnon** [comment]
@eidolonnight Would you mind taking a look at this since this Contributor is coming up really soon? The Docs Team (including myself) would really appreciate it!

**Comment by bjmcsherry** [comment]
@jennimckinnon I've added this to the schedule for the March 26th Docs Day. I set the schedule for March 19th so that it is closer to the actual event but enough time for people to still want to schedule it in the calendar.

**Comment by bjmcsherry** [comment]
Posts have deployed this week. Addiitonally, I scheduled some last chance posts for Sunday to remind people to join.
