### ISSUE TITLE
The Month in WordPress: March 2024 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#389]
### Comment

The Month in WordPress is a monthly roundup of WordPress news to keep existing WordPress contributors engaged and updated while providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## Draft for the March 2024 edition

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/19yEvcJim7MA1vijq7pRd9HUQ7s1ieegefDM-LLt9WI4/edit#heading=h.azrsdrlqir8x).

## How you can help

You can help by collecting any news or team updates that would be valuable and relevant to the post and writing summaries for such news by April 1, 2024. Sources and instructions where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post. Anyone may add links, but please do not delete any.

If you have worked on the doc, add your name and a link to your WordPress.org profile to the bottom to credit all contributions.

## Timeline

The estimated publishing date for the March 2024 edition of The Month in WordPress is April 5, 2023. The document will be closed for edits on April 1, 2024, to allow for final edits and preparation for posting.

**Comment by devmuhib009** [comment]
Working on this, @rmartinezduque I have a question. When I [adding contents](https://docs.google.com/document/d/19yEvcJim7MA1vijq7pRd9HUQ7s1ieegefDM-LLt9WI4/edit), should I remove draft titles or instructional paragraphs? or I can just add my contents as comment?

**Comment by rmartinezduque** [comment]
Thank you for your contributions, @devmuhib009, they are much appreciated!

> When I [adding contents](https://docs.google.com/document/d/19yEvcJim7MA1vijq7pRd9HUQ7s1ieegefDM-LLt9WI4/edit), should I remove draft titles or instructional paragraphs? or I can just add my contents as comment?

Yes, please feel free to remove the instructions once you add any content. I haven't had a chance to review the WordCamp Asia section yet, but I noticed that we might want to make some edits in general to better align with the [WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/). I left some comments with more context in the draft. If you haven't read the brand guidelines yet, that's a great first step! Let me know if you have any questions.

I would also like to mention that there's the possibility that this edition will not be published, given that it is already behind schedule and there is missing content that I have not yet been able to work on. I don't want this to discourage you from contributing (I think it's still a great way to learn for future editions), but I also wanted to be honest about it.

**Comment by devmuhib009** [comment]
I will update the document soon and let you know.

**Comment by devmuhib009** [comment]
@rmartinezduque 
I updated few more things and few sections I think I am not perfect to participate. Because I am not regularly active on marketing team. So, I did not modify anything on "Team updates" and "Requests for feedback & testing".

Please take a look at the content and publish it if possible. Thanks

**Comment by rmartinezduque** [comment]
Thank you, @devmuhib009. I appreciate your efforts. Unfortunately, there is still a lot of content missing (this is not your fault at all; I understand it can be challenging for first-time contributors to know which updates to add), and the edition is significantly behind schedule. So I'm afraid it won't be published. Also, as I recently [shared on Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1713280792554289), I've paused efforts on future editions of the Month in WordPress series. Sorry for the inconvenience, and thanks again for your additions.

**Comment by devmuhib009** [comment]
No problem. I will find new issue to contribute.
