### ISSUE TITLE
[SHOWCASE]: Newsroom Spotify

### ISSUE THREAD

**Issue by elenafromnitropack** [WordPress/Marketing-Team#392]
### Submission ID

202212092312500

### Site URL

https://newsroom.spotify.com/

### Submission date

9 Dec 2022

### Submitter

Josepha Haden Chomphosy

### Theme

Choices

### Launched On

1 Jan 2011

### Country

US

### Description

Spotify's site for getting up to date news about their platform and hosted media.

### Reason for Submission

It's a large, well-known brand.

**Comment by thetinyl** [comment]
Thanks @jamesgiroux for drafting copy for this Showcase entry!

Funny story: We did have the Spotify newsroom included previously, so there was some pre-existing copy. I've taken a look at both and have smushed them together to bulk up the entry a little bit. 

Here's what I'm proposing based on what you've written:

> Spotify is a pioneer in audio streaming, offering over 615 million users worldwide a vast library of music, podcasts, and audiobooks. 
>
> For the Record is Spotify’s official online newsroom and hub for sharing updates about the technology, company, and other related information. Leveraging WordPress and its powerful publishing capabilities, the For the Record website delivers content in a playful grid layout, using a mix of various media to intrigue and engage.
>
>WordPress empowers the Spotify newsroom team to create and publish content quickly and easily. It leans into the flexibility of custom blocks, including beautifully designed playlist embeds that pull readers into a seamless and dynamic visual and sonic experience. 
 
We already have high-quality screenshots for this. 👍  
We'll aim to publish this on **Friday, June 28**.

**Comment by thetinyl** [comment]
This Showcase entry is now published: https://wordpress.org/showcase/for-the-record-spotify/

🚀
