### ISSUE TITLE
[SHOWCASE]: Motion.Page

### ISSUE THREAD

**Issue by elenafromnitropack** [WordPress/Marketing-Team#393]
### Submission ID

202212161231540

### Site URL

https://motion.page

### Submission date

16 Dec 2022

### Submitter

David Babinec

### Theme

Custom

### Launched On

30 Nov 2021

### Country

Czech Republic

### Description

Motion.page is a fully featured animation GUI in WordPress, which allows basically any person to create professional animations without leaving WordPress. While we are not a big organization, rather two fans of innovative products, we've put a ton of effort into building this and it showed up as a huge success. People love it, other companies are creating competition, basically the whole new market forms now for Animation plugins.

### Reason for Submission

Motion.page is one of the most unique plugins on the market. It was the first proper plugin which introduced the professional animation creation right in the WordPress, and allowed any WP site to get animated using GSAP without any coding knowledge. I believe that it's that kind of plugin which is breaking the boundaries of WordPress and pushes the innovation further.

### Any additional notes or details?

Very cool and custom design effects, Good traffic to the site (25k.monthly).

**Comment by lorenzo6992** [comment]
Hi, here a little suggested copy, best!

Motion.Page is an innovative platform that showcases the creative potential of WordPress in creating dynamic and engaging websites. With a focus on simplicity and effectiveness, Motion.Page allows users to easily create stunning web pages that capture attention across various sectors and purposes. Whether it's personal portfolios, small businesses, or large enterprises, Motion.Page leverages WordPress's robust capabilities to deliver visually appealing and functional websites that leave a lasting impression.

Motion.Page's user interface directly addresses the product's goals. Thanks to powerful customization options, their site aims to provide a unique online experience aligned with the identity and goals of their brand. Motion.Page demonstrates the power of WordPress as a versatile CMS capable of adapting to any type of website.

**Comment by ArtenidaC** [comment]
![motion-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/6eb10eff-50cd-498b-951c-92cfa860eae5)
![motion-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/4a73f99a-d368-4312-8977-a440e625b300)
Here are optimized screenshots for desktop and mobile.

**Comment by marko-srb** [comment]
Visually this site doesn't meet the 'eye' of a great style to be in Showcase (in my opinion). It's worth checking if due it's features it should find a place on Showcase though.

CC: @thetinyl

**Comment by thetinyl** [comment]
> Visually this site doesn't meet the 'eye' of a great style to be in Showcase (in my opinion).

I don't have a strong opinion. I'm happy to defer to your eye here, @marko-srb.
