### ISSUE TITLE
[SHOWCASE]: Harvard University

### ISSUE THREAD

**Issue by elenafromnitropack** [WordPress/Marketing-Team#394]
### Submission ID

202212231735070

### Site URL

https://www.harvard.edu/

### Submission date

23 Dec 2022

### Submitter

Hari Shanker R

### Author

The President and Fellows of Harvard College

### Theme

Custom Theme by Modern Tribe

### Launched On

8 Apr 2021

### Country

US

### Description

This is the official website of Harvard University, a private Ivy League research university in Cambridge, MA. It is veritably one of the top universities of the world. Throughout its existence, Harvard alumni, faculty, and researchers have included numerous heads of state, Nobel laureates, Fields Medalists, members of Congress, MacArthur Fellows, Rhodes Scholars, Marshall Scholars, and Fulbright Scholars; by most metrics, Harvard ranks at the top, or near the top, of all universities in the world in its alumni in each of these categories. Harvard is also ranked in the top 3 in most of the reputed rankings of the world.

### Reason for Submission

The site is unique and very well designed. It was designed by Modern Tribe and offers excellent typography and design language. More info here: https://tri.be/our-work/harvard-university/

**Comment by lorenzo6992** [comment]
Hey, here a suggested copy for the showcase page!!
Best!

Harvard University is one of the most prestigious universities in the world, with a rich history of academic excellence and innovation. Founded in 1636, Harvard is a beacon of knowledge, research, and development, welcoming students, faculty, and scholars from every corner of the globe. With its commitment to education and leadership, Harvard continues to shape the future.

Harvard's website, built on WordPress, is a brilliant example of how this platform can handle complex and extensive content, showcasing the university's long tradition of innovation. Thanks to the flexibility and customization offered by WordPress, Harvard has created an intuitive user experience, reflecting its global reputation. From personal blogs to government sites, WordPress once again demonstrates its ability to adapt to any need.

**Comment by ArtenidaC** [comment]
![www harvard-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/d9735426-6e1e-4010-be20-39ef40f1e5f0)
![www harvard-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/0921dae7-5505-445d-8ed0-7de989a7e6ae)

**Comment by thetinyl** [comment]
Thanks @lorenzo6992 and @ArtenidaC for your help here! There already seems to be an [entry for Harvard](https://wordpress.org/showcase/harvard-university/) live on the Showcase. 

I'm not sure how it was resubmitted into the moderation queue, so sorry about that! Your efforts are still very much appreciated.
