### ISSUE TITLE
[SHOWCASE]: https://enabloo.com

### ISSUE THREAD

**Issue by marijago** [WordPress/Marketing-Team#396]
### Submission ID

202401272024120

### Site URL

https://enabloo.com

### Submission date

27 Jan 2024

### Submitter

Termyl

### Author

Studio Enabloo

### Theme

Enabloo

### Launched On

19 May 2023

### Country

Benin

### Description

The website showcases Studio Enabloo’s case studies, work environment and more.

### Reason for Submission

Studio Enabloo's website captivates visitors with a unique blend of creativity and interactivity. The incorporation of parallax effects adds depth, guiding users through a dynamic and engaging journey as they scroll. The strategic use of Lottie files introduces animated elements that bring the content to life, offering a memorable visual experience. This combination of parallax and Lottie files not only showcases technical prowess but also elevates the overall user engagement.

**Comment by monchompa** [comment]
Enabloo is a high end design and production studio headquartered in Africa. Enabloo offers services that help take companies to new heights by creating digital products, brands, and experiences. They offer a range of services including brand and graphic design, UI/visual design, and product design.

Enabloo chose to use WordPress as their CMS do to its ability to create flexible and unique blends of animation and enhanced blocks. The strategic use of Lottie files and parallax elements allows them to introduce animated elements that bring the content to life, offering a memorable visual experience. This integration not only demonstrates technical expertise but also significantly enhances user engagement.

**Comment by ArtenidaC** [comment]
![www enabloo-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/f9a66e94-a41f-48ba-a5fc-e7d00c2b978c)
![www enabloo-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/dac48557-8b7c-49f4-bdc1-82d16c93d2f5)

**Comment by marko-srb** [comment]
This website doesn't seem to be on WordPress. Maybe I am wrong, but my code markup checker says it's not on WP. It should be re-checked.

**Comment by thetinyl** [comment]
According to [BuiltWith](https://builtwith.com/?https%3a%2f%2fwww.enabloo.com%2f), this site is running WordPress. I also see some hints of wp- when inspecting in my browser. 

I think we're ok to include. Thanks for double-checking, @marko-srb!

**Comment by marko-srb** [comment]
Then great, thanks @thetinyl!

**Comment by thetinyl** [comment]
Thanks everyone!

This site has been added to the Showcase: https://wordpress.org/showcase/studio-enabloo/
