### ISSUE TITLE
[SHOWCASE]: https://www.freethink.com/

### ISSUE THREAD

**Issue by marijago** [WordPress/Marketing-Team#397]
### Submission ID

202401101743400

### Site URL

https://www.freethink.com/

### Submission date

10 Jan 2024

### Submitter

Nick Diego

### Author

Freethink

### Theme

Unknown

### Launched On

Unknown

### Country

US

### Description

"Freethink is a news site that approaches global news a bit differently than traditional news organizations. Here is a quote from their site: 

""At Freethink, we believe the daily news should inspire people to build a better world. While most media is fueled by toxic politics and negativity, we focus on solutions: the smartest people, the biggest ideas, and the most ground breaking technology shaping our future."""

### Reason for Submission

While this site does not utilize a block theme, they are using blocks for post content. The site also features a great modern design with exceptional mobile responsivity. This site is also built on WordPress VIP.

**Comment by alexandraanderson** [comment]
working on this one ...

**Comment by ArtenidaC** [comment]
![www freethink-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/32d2c5ff-6bcc-49fa-a616-ca29162694e3)
![www freethink-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/669731c3-3755-4850-bd02-f112a5e8d492)

**Comment by thetinyl** [comment]
Thanks @marijago for moderating and @alexandraanderson for drafting initial copy. And thank you @ndiego for the submission. 

[Freethink](https://wordpress.org/showcase/freethink/) is now live on the Showcase. 🚀
