### ISSUE TITLE
[SHOWCASE]: https://be-beau.fr/

### ISSUE THREAD

**Issue by augurlu** [WordPress/Marketing-Team#398]
### Submission ID

202312211130360

### Site URL

https://be-beau.fr/

### Submission date

14 Nov 2023

### Submitter

Antoine Paufichet

### Author

Paolo

### Theme

be-beau

### Launched On

14 Nov 2023

### Country

France

### Description

be-beau is a French graphic design agency specializing in branding. We support brands with their visual identity revamp, logo creation, graphic charter, advertising campaign creation, website, mobile application, shooting, video, etc. Our mission is to make brands shine in the eyes of their targets, to make it consistent with their value proposition and also across all media. This website present the compagny, our expertises, our achievements. Antoine Paufichet is our founder and creative director, and also proud to be Head of UX/UI at Be API, a French WordPress agency.

### Reason for Submission

The site was recently put online and highlights the latest WordPress technologies including FSE.
It was designed to be simple, beautiful, and elegant with animation finesse.

**Comment by ArtenidaC** [comment]
working on this

**Comment by ArtenidaC** [comment]
![be-beau-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/b776aac2-62c9-4771-92ce-b8ddb9dcaecc)
![be-beau-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/6fc9035f-744e-4f31-ab9f-f20c1ee62fcb)

**Comment by thetinyl** [comment]
👋 Thanks for your help with the content for this showcase entry, @ArtenidaC! 

I've made adjustments to the copy you provided to match the flow of the other published entries. Here is my suggested edit:

>be-beau is a French design agency specializing in brand design, visual identity, and creating thoughtful digital experiences that elevate brand appeal. Their cross-disciplinary expertise provides their clients a full suite of creative and technical services. 
>
>The be-beau website has a clean, modern look that prioritizes an effortless user experience. It takes visitors through the agency’s previous work, services, and guiding principles, using a sophisticated Block theme—and the versatility of modern WordPress—to present it all.

**Comment by marko-srb** [comment]
looking good 🎉
