### ISSUE TITLE
WPDiversity - Diverse Speaker Training group (#WPDiversity) Volunteers Zoom Call, 2022/02/23

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#4]
Information from @jillb Slack https://wordpress.slack.com/archives/C0GKJ7TFA/p1644448715233209

Event date: Wednesday, February 23, 2022 at 17:00-18:00 UTC
Last time to register:
Booking deadline for promotion purposes: Still available anytime up to the end of the meeting at 18:00 UTC.

Suggested key messaging:
Curious to learn more about the Diverse Speaker Training Group? Get more information about #WPDiversity programs, how you can help, and chat about ideas with current contributors on Zoom on Wednesday, February 23, 2022 at 17:00-18:00 UTC. This meeting is welcome to all who value a diverse, inclusive, and welcoming WordPress community. Register via Zoom or share any questions via this link: https://wp.me/p2U65r-8VM

Note: Jill has sent information on pictures. They are linked from the Slack message above on 9 February 2022. Pictures can be used for WordPress.org social too - linked to @eidolonnight

**Comment by murillol** [comment]
**Update**: I’ve prepared the copy for the @ wordpressevents (Twitter + Facebook) and Make WordPress Marketing team (LinkedIn) channels, and will update this card with the links to the posts as they go out. [Working Document](https://docs.google.com/document/d/1tMZdC2tqtEXlBoizx83jL3oKnGdZ6lbRgXIcDfmiq5Y/edit?usp=sharing).

For the official handles, Nicholas has indicated the messages are going out on Sunday, 20 February 2022 [in this thread](https://wordpress.slack.com/archives/C0GKJ7TFA/p1645168987751389?thread_ts=1644448715.233209&cid=C0GKJ7TFA). An image from SOTW will be used.

**Comment by murillol** [comment]
**Update**: Published Posts

| Link  | Account |
| ------------- | ------------- |
| [Twitter](https://twitter.com/WordPress/status/1495418721837404165)  | @ wordpress  |
| [Facebook](https://www.facebook.com/WordPress/posts/10159717844697911)  | @ wordpress  | 
| [Twitter](https://twitter.com/wordpressevents/status/1495401650865029124)  | @wordpressevents|
| [Twitter](https://twitter.com/wordpressevents/status/1496152097405952003) | @wordpressevents |
| [Facebook](https://www.facebook.com/wordpressevents/posts/345364830808604)  | @wordpressevents |
| [LinkedIn](https://www.linkedin.com/posts/make-wordpress-marketing-team_open-invitation-diverse-speaker-training-activity-6899129672592887808-1JGL)  | Make WordPress Marketing Team |
| [LinkedIn](https://www.linkedin.com/posts/make-wordpress-marketing-team_wpdiversity-wordpress-activity-6901898717142552577-xc41)  | Make WordPress Marketing Team |

**Comment by nalininsbs** [comment]
@murillol and Anjana (@anjanavasan - to check ID) could you add any final updates to this task once you have them? Thank you. 

I added a link to this card to the notes from last week's meeting.

**Comment by nalininsbs** [comment]
Published recap from @jillb https://make.wordpress.org/community/2022/02/24/recap-of-the-diverse-speaker-training-group-wpdiversity-on-february-23-2022/

**Comment by murillol** [comment]
I have no final updates! Anjana's GitHub ID appears to be @Starbuck245
