### ISSUE TITLE
[AMPLIFY]: Meetup Organizer Newsletter, March 2024

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Marketing-Team#402]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Other

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Email

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

Meetup Organizer Newsletter

### Amplification request details

Please review the draft of the Meetup Organizer Newsletter for March 2024, make suggestions/edits as necessary, and prepare to send via MailChimp. Please contact myself (@courtney-pk) and @askhellosatya with any questions about the content.

### Links

https://docs.google.com/document/d/1LfaHe1GFnLXwKQg9llfif1GIgzv27TA3LgVoYtwKkqY/edit?usp=sharing

### Deadline

March 22, 2024

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

Here is the Community Team's process for this newsletter:
https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/meetup-organizer-newsletter/

**Comment by bjmcsherry** [comment]
Hi @courtney-pk, the email has been completed and is ready to deploy. Do you have an idea of when you would like it to deploy?

**Comment by courtney-pk** [comment]
Great, thanks @bjmcsherry! We can do it any time now, unless you have a suggestion on a good time of day to do it? Also, did you make any edits that I should transfer over to the post we make on Make/Community?

**Comment by bjmcsherry** [comment]
Shall we do 12 pm UTC on Friday, March 22? @courtney-pk

**Comment by courtney-pk** [comment]
Sounds good @bjmcsherry! Can you confirm if there have been any changes to the copy, so I can prepare the Make/Community post? Thank you!

**Comment by bjmcsherry** [comment]
@courtney-pk No changes to the copy. I was good. :)

**Comment by courtney-pk** [comment]
Make/Community post is scheduled to publish on Friday, March 22 at 14:00 UTC.

**Comment by bjmcsherry** [comment]
Thanks @courtney-pk. The email was deployed at the same time. Nice work, all!!. :)

**Comment by bjmcsherry** [comment]
Closing ticket with this comment.
