### ISSUE TITLE
[AMPLIFY]: Openverse's Dark mode project

### ISSUE THREAD

**Issue by fcoveram** [WordPress/Marketing-Team#403]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, WordPress users (existing), Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#WPOpenverse

### MakeWP Team

Openverse

### What do you want to amplify?

Show the upcoming dark mode feature of Openverse

### Amplification request details

Show the benefits of shifting the user interface to a dark theme.

Dark mode is a product-wide setting that adapts the user interface to provide a comfortable experience in low-light environments and, in some cases, improve accessibility for those with visual impairments, as [pointed out by NN/g](https://www.nngroup.com/articles/dark-mode/).

The project is being tracked in [Openverse repository, issue 3592](https://github.com/WordPress/openverse/issues/3592)

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

The project is currently in progress, so this issue intends to inform in advance one of the releases planned for this year that impact Openverse's UX/UI.

Additionally, the [project proposal document](https://github.com/WordPress/openverse/pull/3913) has a section related to marketing to list new or existing campaign opportunities. Any marketing idea, either specific or broad, is welcome to complement the documentation and keep the comms' next steps trackable.

The request was also [shared](https://wordpress.slack.com/archives/C0GKJ7TFA/p1710844691166359) in the slack channel.

**Comment by fcoveram** [comment]
Hey folks 👋 

Coming back to this issue after months to ask whether this request could be kick off soon. The dark mode project ([openverse#3592](https://github.com/WordPress/openverse/issues/3592)) is almost done and we are ready to communicate the new features publicly on our channels.

If this request is able to be addressed, who could be the DRI? Regarding graphic material, I'm the individual who will do it.

**Comment by eidolonnight** [comment]
@bjmcsherry can DRI the social piece of this. We also haven't talked about Openverse on WordPress.org News for a while. This might make a nice short post.

@fcoveram do you have screenshots, video, or other assets that you can share here? Any recommendations for copy? Looks like this has been in the works for a while.

**Comment by fcoveram** [comment]
Thanks @eidolonnight for the response. A post on WordPress News sounds excellent ✨ 

Regarding assets, we only have the mockups. But I can create any piece needed for the post on News and any other channel. 

For the copy, here is a list of the project aspects worth mentioning.
* Project goal: Refine the search experience by adapting the user interface to the user's preference
* The feature brings the brand essence to a dark context
* The new dark theme does not compromise accessibility as it targets AA level, as per the [accessibility team definitions](https://make.wordpress.org/accessibility/handbook/which-questions-should-you-ask/).
* The project also introduces a new way of showing upcoming features in context.

The design issue ([openverse#3959](https://github.com/WordPress/openverse/issues/3959)) could inspire other ideas in addition to the above ones.

As for the next steps and the visuals needed, I suggest creating a draft to iterate the content so that I can create the graphic pieces needed depending on the content extension.

How does that sounds @eidolonnight @bjmcsherry ?

**Comment by fcoveram** [comment]
I forgot to mention three things:
1. In the design issue, the most relevant content for this purpose is the initial comment. 
2. The design of Openverse homepage change during its development. Here is the [latest design](https://github.com/WordPress/openverse/issues/4936) already implemented.
3. You can see dark mode working [here](https://staging.openverse.org). You first need to:
    * Go to the [preferences page](https://staging.openverse.org/preferences)
    * Toggle on the `dark_mode_ui_toggle` control
    * Go back to the homepage by clicking on Openverse logo in the top-left area.

**Comment by fcoveram** [comment]
Coming here to kindly ask if you folks @eidolonnight @bjmcsherry have talked about a tentative time to work on this. This work doesn't block the implementation.

**Comment by bjmcsherry** [comment]
@fcoveram I will work on this today, and come back with some copy for a social campaign that we can review, and possibly look at how we add a design to this.

**Comment by fcoveram** [comment]
Awesome. Thanks @bjmcsherry

**Comment by bjmcsherry** [comment]
I have a draft for everyone with the Openverse Dark mode campaign [here](https://docs.google.com/document/d/1yXCJFyYXXC0u_Z4y7EJqAZsQO1tTjylLc8i4tLdS5yk/edit?usp=sharing). 

I wanted to point out a couple of things. 
1.) It includes two options for pre-launch and post-launch. I don't have a date for this, so the pre-launch is slightly ambiguous, and just saying that it is coming. 
2.) Both of the pre/post campaigns come with copy that has slight variations. Using the information I have from the project thread, I created a version that is more "features-driven" and one that is more "Accessibility-driven." I got a sense from the project threads and here that both are important aspects of the 'why', so I included it just to provide some talking points, but I am happy to listen to all feedback, and we move in the direction that works best for this project. 

Thanks, everyone.

**Comment by bjmcsherry** [comment]
@fcoveram Thanks for the feedback. I will work on the post-launch angle now. This copy for the General Features will target X, LinkedIn, Facebook, Threads, Bluesky, and Instagram. Tumblr isn't a very responsive audience for us, but since this is a photo-centric post, I may post it there as well. I can work on a /News post as well, but would I be able to get a quote from Openverse or, specifically, someone who worked on the project? It might be a nice callout in the /News post to have this included.

**Comment by fcoveram** [comment]
> Tumblr isn't a very responsive audience for us, but since this is a photo-centric post, I may post it there as well

That sounds good.

> I can work on a /News post as well, but would I be able to get a quote from Openverse or, specifically, someone who worked on the project?

Perhaps @dhruvkb or @obulat can provide a short paragraph noting a key improvement or challenge. I'm thinking of how we had to "rebuild" the whole UI. Any ideas are welcome.

To confirm the outcome of this. The announcement will involve a post on News and posts on X, LinkedIn, Facebook, Threads, Bluesky, and Tumblr, where these latter imply a short paragraph and a gallery of screenshots/mockups. Am I correct?

**Comment by dhruvkb** [comment]
The post launch posts look good. I have some small feedback on the content.

- Battery life: The impact of dark mode on battery life would be microscopic. For one, we don't use pure blacks so the pixels would still have to be turned on, and on an image-heavy site like ours, there is very little black on the screen anyway and the content will determine how much battery life is actually saved. Calling it "sustainable" feels like a stretch to me.

- Accessibility: While dark mode does make the site more accessible in low-light situations and for people who might have light sensitivity, the true accessibility leap has only been unblocked by this change, which would be adding support for high-contrast and color-vision-deficiency-friendly themes. I'm not downplaying the a11y gains here, only pointing out that much more a11y gains will be made now that theming is supported.

I want to re-emphasise that the posts are great and no specific changes are necessary. I only wanted to suggest focusing the posts more around the topics of comfort (_now play beach sounds at night_) and personal style (_"dark mode everywhere!"_).

---

As for the quote, my part in this was smaller so I'll defer to @obulat on that front. I do remember @fcoveram had to put in an inordinate amount of effort (and color science) to prototype many many different palettes before he found the perfect one that was balanced for both light and dark modes. That experience is also definitely quotable from the design perspective.

**Comment by bjmcsherry** [comment]
@fcoveram That's what I am thinking. The quote doesn't need to be long. I was thinking it could be used in a quote block similar to [this post](https://wordpress.org/news/2023/09/openverse-wins-the-2023-oeg-open-infrastructure-award/). 

The tactics are correct, though. If we want a post on /News, I will begin working on that and get something for us early next week. 



> The post launch posts look good. I have some small feedback on the content.
> 
> * Battery life: The impact of dark mode on battery life would be microscopic. For one, we don't use pure blacks so the pixels would still have to be turned on, and on an image-heavy site like ours, there is very little black on the screen anyway and the content will determine how much battery life is actually saved. Calling it "sustainable" feels like a stretch to me.
> * Accessibility: While dark mode does make the site more accessible in low-light situations and for people who might have light sensitivity, the true accessibility leap has only been unblocked by this change, which would be adding support for high-contrast and color-vision-deficiency-friendly themes. I'm not downplaying the a11y gains here, only pointing out that much more a11y gains will be made now that theming is supported.
> 
> I want to re-emphasise that the posts are great and no specific changes are necessary. I only wanted to suggest focusing the posts more around the topics of comfort (_"now play beach sounds to sleep at night"_) and personal style (_"dark mode everywhere!"_).

Thanks for the feedback. I will revisit these posts and make adjustments.

**Comment by bjmcsherry** [comment]
Here is an updated piece of copy for social that is again focused on General Features and only for post-release:

> Openverse.org now features a sleek, modern Dark Mode designed for your comfort and style. 🌘
>
>Why explore in Dark Mode?
>
>-Experience easier browsing in low-light environments.
>-Enjoy a look that complements your personal aesthetic.
>-A thoughtful design for users with light sensitivity.
>
>✨ Switch to Dark Mode and make Openverse.org your own today: [Link to Openverse.org]
>
>#WPOpenverse #WordPress

If this works now, I will move on to creating a larger piece for the blog post.

**Comment by bjmcsherry** [comment]
Thanks, @fcoveram. I have a [draft for the blog post here](https://docs.google.com/document/d/1lJ_a4d3dSj4HcMtixqHqFWkUk4e63eg_oVaZRL0CjWA/edit?usp=sharing) that we can begin to review. It focuses on the same elements as the social post. The title is a play on the "Sight for Sore Eyes" quip. I like it here as a light and playful lead-in, but we can adjust if needed. We also have a generic Quote Block that should be filled in later by someone with Openverse, but for now, I have placed it for visibility. 

![Image](https://github.com/user-attachments/assets/78fa59f8-4281-4398-a7a5-3af3e9295123)

**Comment by dhruvkb** [comment]
I like the post very much, and the title is great too. It's quite _"light"_ (hehe!) and casual, while including all the points we needed to make. Thanks!

**Comment by fcoveram** [comment]
Great work @bjmcsherry. I added a few comments and inserted the images made for this and the posts on socials. In this [drive folder](https://drive.google.com/drive/folders/10tF7KlWl-DSK1SSlFtbQ_WCr7Va6o_3E?usp=sharing) you can see all images and the video attached.

**Comment by obulat** [comment]
Thank you for writing the post, @bjmcsherry, I also like it! As for the socials posts, I prefer the first options with the emphasis on accessibility because they highlight our values.

**Comment by bjmcsherry** [comment]
@fcoveram I have reviewed the suggested edits and approved each one. The question you had (brand essence) has been addressed, and a suggestion has been added to the paragraph to address that need. Let me know if this works for you. :)

**Comment by bjmcsherry** [comment]
@fcoveram Changes have been made, and I think we are ready to move this into a draft for /News, which I will begin early next week.

**Comment by fcoveram** [comment]
Yes! I saw the change it looks great. We're ready to lunch.

**Comment by bjmcsherry** [comment]
Hi @fcoveram, I have a draft of the post for /News. You can see it here: https://wordpress.org/news/?p=18168&preview=true&_thumbnail_id=18169

One note: the post was becoming really image-heavy, so I didn't use the image you had with the desktop and mobile side-by-side. However, if you do want that in, I will try to make room.

**Comment by dhruvkb** [comment]
We've launched the dark mode feature now. Please let us know when the socials go out and we will amplify them through our accounts on the same platforms.

**Comment by bjmcsherry** [comment]
@fcoveram [Updates made](https://wordpress.org/news/?p=18168&preview=true&_thumbnail_id=18169). 

I moved the final line to the end of the post after the GIF. I did stack the images, as you requested. I think the images do show better not in a gallery, but there's a lot of scrolling for the article with so many large images. I wonder if we should choose only one image in this segment rather than two. Maybe that is just me, though. :D

**Comment by bjmcsherry** [comment]
Scratch that. New update. I used a slider feature, so keep it to one section, which I think really works well here. I am using a wide view so the image shows bigger, but we can also keep it to the columned width of the rest of the article, too. Let me know your thoughts here.

**Comment by bjmcsherry** [comment]
Changes made. The post is published. I will work on the scheduling for social. I want to try to give it space around all the SOTW content we are publishing.

**Comment by bjmcsherry** [comment]
Hey guys, the social posts are now out: 
X: https://x.com/WordPress/status/1867183894224629953
Instagram: https://www.instagram.com/p/DDemyazM-wD/
LinkedIn: https://www.linkedin.com/feed/update/urn:li:share:7272986073742348289/
Bluesky: https://bsky.app/profile/wordpress.org/post/3ld4jluu4tk2e
Threads: https://www.threads.net/@wordpress/post/DDemyxnoNMH
Facebook: https://www.facebook.com/593573715915605/posts/978851827387790

I will close this ticket with this comment. :)
