### ISSUE TITLE
[AMPLIFY]: WordPress Contributor Mentorship Program Graduation Amplification

### ISSUE THREAD

**Issue by harishankerr** [WordPress/Marketing-Team#410]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, WordPress users (existing), Builders/implementers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin, Tumblr

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

Celebrating WordPress Contributor Mentorship Program Mentees and Announcing Their Graduation

### Amplification request details

The February 2024 cohort of the WordPress Contributor Mentorship Program has come to an end, and we are having graduation parties tomorrow. Following the same, we will be publishing a blog post announcing the completion of the program, and celebrating our mentors and mentees. We would love your help in: 

- Amplifying the post itself through social media
- Celebrating selected mentors and mentees through dedicated social media posts 

The objective of this is to:

- Create awareness around the WordPress Contributor Mentorship Program
- Recruit more mentors and mentees for the next cohort (to happen in November 2024). We won't have a call for mentees and mentors yet, but we want to create awareness around the same at this point. 

### Links

TBD

### Deadline

April 11, 2024

### Additional important dates

The program graduation is happening tomorrow (April 4th 2024) and we will be publishing the post on April 5th 2024. We would like amplification next week (Week of April 8th), and potentially share some posts celebrating mentors and mentees later on.

**Comment by bjmcsherry** [comment]
Hi @harishankerr, do you know when the post will be published?

**Comment by harishankerr** [comment]
@bjmcsherry We'll be publishing this tomorrow (Friday, April 5) after the graduation call today.

**Comment by harishankerr** [comment]
@bjmcsherry The post was just published! https://make.wordpress.org/community/2024/04/08/wordpress-contributor-mentorship-2024-q1-cohort-graduates/
If it's all good with the team, I'd like us to start amplifying the announcement.

**Comment by bjmcsherry** [comment]
Hi @harishankerr, how does this copy sound for the online promotion for social?:

---------------

> 🚀 We're thrilled to celebrate the achievements of our latest cohort of WordPress Contributor Mentorship graduates! 🌟 Discover their journey and how you can be part of the next wave of WordPress innovators. https://make.wordpress.org/community/2024/04/08/wordpress-contributor-mentorship-2024-q1-cohort-graduates/
> 
> #WordPress #WordPressCommunity

---------------

**Comment by harishankerr** [comment]
@bjmcsherry That sounds excellent, please share that tweet!

**Comment by bjmcsherry** [comment]
That is great to hear. This has been scheduled and will be deployed later today for several platforms. I will close this amplification thread with this comment.
