### ISSUE TITLE
[AMPLIFY]:  Openverse: Introducing Collection views for Tags, Creators, and Sources

### ISSUE THREAD

**Issue by zackkrida** [WordPress/Marketing-Team#414]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#WPOpenverse

### MakeWP Team

Openverse

### What do you want to amplify?

Openverse now offers new Collection search views, allowing users to view works belonging to an individual tag, creator, or source. 

### Amplification request details

Here is a Make post describing the new functionality:

https://make.wordpress.org/openverse/2024/04/16/introducing-collection-views-for-tags-creators-and-sources/

### Links

https://make.wordpress.org/openverse/2024/04/16/introducing-collection-views-for-tags-creators-and-sources/

### Deadline

None

**Comment by rmartinezduque** [comment]
Congrats on launching this new feature, @zackkrida! Do you think it would be possible for you or @fcoveram to help with an image for social media? Having something similar to the one he created to announce the [enhanced content safety features](https://twitter.com/WordPress/status/1735066086830129154) would be great.

**Comment by fcoveram** [comment]
Sure! I can work on a visual during this week or in the early days of the next one.

**Comment by rmartinezduque** [comment]
Sharing a few copy options for consideration (I kept "Collection" in capital letters for consistency with the Make post):

Option A:
> Ever wanted to search for images or audio files from a specific creator, source, or tag in Openverse? Now you can. Introducing the new Collection views—a better way to explore and find the free creative works you need. ✨ [Link to post] #WPOpenverse 

Option B:
> Searching for free creative works just got better. ✨ Meet Openverse's Collection views, a new feature to browse images and audio files by creators, sources, and tags—and easily find what you're looking for. [Link to post] #WPOpenverse

**Comment by fcoveram** [comment]
I initially thought about an image, but it's hard to convey the whole flow without multiple steps, so I ended up doing a video. Here is in two sizes:
* 1:1 in 1080px
* 16:9 in 1600px

https://github.com/WordPress/Marketing-Team/assets/895819/2a7d2d45-408f-447f-ba6b-a1c0891e66d1

https://github.com/WordPress/Marketing-Team/assets/895819/40d4d058-e074-45a8-95e0-e60ef72a2097

**Comment by zackkrida** [comment]
It appears that the the posts went live. Thanks @rmartinezduque! Should this issue be closed?

**Comment by rmartinezduque** [comment]
Yes, [Twitter/X](https://twitter.com/WordPress/status/1785387188764426580), [Facebook](https://www.facebook.com/WordPress/videos/454800107076200/), and [Linkedin](https://www.linkedin.com/posts/wordpress_wpopenverse-activity-7191215572896960512-bdh_/) posts are out. I don't see the Instagram post, though. @bjmcsherry, did I schedule that post correctly, or has it been rescheduled for another day?

**Comment by rmartinezduque** [comment]
I followed up with @bjmcsherry on this, who confirmed that Sprout doesn't seem to allow a reel to be added to the main feed of posts once the video has been published. I've rescheduled a new Instagram post to go out later today and asked Brett to review it to ensure it shows in the main profile feed, so I'm closing this issue for now.
