### ISSUE TITLE
Kim Parsell Memorial Scholarship for WordCamp US 2024

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/Marketing-Team#415]
This is a request to amplify the Call to Action (1) for qualified applicants to apply for the Kim Parsell Scholarship for 2024, and (2) for everyone to share and help amplify the scholarship announcement within their networks. Here is the link to the announcement on the WPF site: [https://wordpressfoundation.org/news/2024/kim-parsell-2024/](https://wordpressfoundation.org/news/2024/kim-parsell-2024/)

The application deadline is May 30. Ideally WordPress could amplify that the application is open; and then in mid-May share a reminder that the application will close on May 30.

**Comment by bjmcsherry** [comment]
Hi @hellojuliarose, I added the amplification tag for you and just assigned myself to this. Now, I have a couple of things to note: 

1.) The URL (https://wordpressfoundation.org/news/2024/kim-parsell-2024/) is pulling in the WP logo as an image for social but is being cut off. So, I would like to create a unique image. That leads to number 2...

2.) Do you know if I could use the image from the WordCamp US site here: https://us.wordcamp.org/2023/apply-now-for-the-kim-parsell-memorial-scholarship/? I suspect that if it is WCUS, it will be okay, but I wanted to confirm. 

Here is some copy for your review. Plus, an image in advance, so long as I am free to use the image:

> 📚 In 2024, WordPress will once again offer the Kim Parsell Memorial Scholarship for travel to WordCamp US. The Kim Parsell Memorial Scholarship honors Kim's legacy by supporting aspiring WordPress contributors. Click here for details: https://wordpressfoundation.org/news/2024/kim-parsell-2024/ 
#WordPress

![TW Kim Parsell Scholarship](https://github.com/WordPress/Marketing-Team/assets/97543370/57ad3fe6-a8f8-43a3-8069-2e00aaad575c)

**Comment by hellojuliarose** [comment]
@bjmcsherry this is fantastic, thank you! Yes, you are welcome to use that image (and any images from WCUS).

**Comment by bjmcsherry** [comment]
@hellojuliarose, the campaign has been scheduled to launch on Sunday. I will close this ticket with my comment, but please let me know if you need anything else.
