### ISSUE TITLE
[SHOWCASE ISSUE] Bi-Rite Market showcase image displays an error

### ISSUE THREAD

**Issue by definegravity** [WordPress/Marketing-Team#416]
### Comment

Heading to the Bi-Rite Market showcase [page](https://wordpress.org/showcase/bi-rte-market/) the hero image shows the following:
![CleanShot 2024-04-22 at 14 24 43@2x](https://github.com/WordPress/Marketing-Team/assets/5426598/cde56a03-8008-4392-b2f7-d17c88e81e1c)

But the [site](https://biritemarket.com/) looks fine.
![CleanShot 2024-04-22 at 14 25 14@2x](https://github.com/WordPress/Marketing-Team/assets/5426598/4a0aaf3b-d7c9-4335-b64c-cfd04b20193f)

**Comment by definegravity** [comment]
Another site on the showcase with a similar issue: [Asian Legacy Library](https://wordpress.org/showcase/the-asian-legacy-library/)

![CleanShot 2024-04-22 at 14 35 42@2x](https://github.com/WordPress/Marketing-Team/assets/5426598/998127c5-359b-4c6b-8b2f-53e9a733e9a1)

**Comment by dd32** [comment]
These use `mShots` by WordPress.com for generating thumbnails; It looks like these sites are rate-limiting or blocking the mshots service.

Showcase supports defining custom images for these cases, we just need to upload two images:
> Capture a desktop image at 1920 wide by 1080 tall, use at least 2x dpi.
> Capture a mobile image at 375 wide by 667 tall, use at least 2x dpi.

**Comment by definegravity** [comment]
Hi, @dd32! Thanks, got it. I've captured the Bi-Rate Market. 

For the Asian Legacy Library, however, the site if broken on mobile and I can't get a good capture.


![Bi rite Market](https://github.com/WordPress/Marketing-Team/assets/5426598/c9f0fe2c-c881-451d-a275-eedc2fd89eb2)
![Birite Market](https://github.com/WordPress/Marketing-Team/assets/5426598/e0384de6-8721-44d1-b583-a45856493dfc)

**Comment by eidolonnight** [comment]
[Bi-Rite Market](https://wordpress.org/showcase/bi-rte-market/) and [The Asian Legacy Library](https://wordpress.org/showcase/the-asian-legacy-library/) have been updated with manual screenshots. Thanks for the bug reports @definegravity. If you'd like to continue helping with the Showcase (maybe helping with manual screenshots?), we have a [handbook available](https://make.wordpress.org/marketing/handbook/getting-involved/wordpress-showcase/).
