### ISSUE TITLE
[AMPLIFY]: Blueprints gallery

### ISSUE THREAD

**Issue by adamziel** [WordPress/Marketing-Team#420]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

MakeWP community, Builders/implementers, Developers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, WordPress Media

### Campaign

None/Not sure/Other

### MakeWP Team

Meta

### What do you want to amplify?

Blueprints gallery announcement post

### Amplification request details

We've just launched the Blueprints Gallery. It's like [https://wordpress.org/plugins](https://t.co/11GuiHZ7SV), but for  Blueprints. You can:

• Share your Blueprints
• Try Blueprints created by others
• Edit them in builder

Let's make sure the news reaches the community.

Amplifying the news on social media and reaching out to WordPress news outlets such as WP Tavern, PostStatus, WP Minute would go a long way.

The message would be along the lines of 

> The [Blueprints Gallery](https://github.com/WordPress/blueprints/) just launched! It’s a space to share WordPress Playground Blueprints, try Blueprints built by others, edit, remix, and experiment with them – see the [announcement post](https://make.wordpress.org/meta/2024/05/15/the-blueprint-gallery-share-your-wordpress-creations-with-playground/) for more details. And what are Blueprints? [They’re WordPress setups](https://github.com/WordPress/blueprints/tree/trunk?tab=readme-ov-file#what-are-blueprints) you can launch directly in your browser with a single click thanks to the magic of WordPress Playground! We are looking for Blueprint ideas and contributions in form of GitHub issues, discussions, and Pull Requests. Join the [#meta-playground](https://wordpress.slack.com/archives/C04EWKGDJ0K) channel on [WordPress.org Slack](https://make.wordpress.org/chat/) and check out the [Blueprints](https://github.com/WordPress/blueprints/issues/) repository!”

On, in case that matters, I just re-tweeted about it: https://twitter.com/adamzielin/status/1790741784047284366

### Links

https://make.wordpress.org/meta/2024/05/15/the-blueprint-gallery-share-your-wordpress-creations-with-playground/

**Comment by thetinyl** [comment]
👋 Hey @adamziel! What do you think of this copy to amplify the Blueprint Gallery:

> Meet the Blueprints Gallery: a new directory of WordPress setups you can launch right in your browser with the magic of WordPress Playground. Try, edit, and remix Blueprints made by others—or share your own unique WordPress builds. Learn more and come play: [LINK]

Do you happen have any visuals/graphics that you've been using to illustrate the Blueprint Gallery/Blueprints or even WordPress Playground?

**Comment by DanSoschin** [comment]
These have shipped.
