### ISSUE TITLE
New Guide on Getting Started with Showcase at Contributor Days

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#421]
### Comment

As you might know, @bernard0omnisend and I will lead the Marketing table at WCEU Contributor Day, and as part of our preparations, we have been discussing our main focus for the day. Given the current Make Marketing situation, the Showcase activity seems an ideal opportunity for new and experienced contributors to get involved during Contributor Day.

With this in mind, we have drafted a new guide to help folks contribute to the Showcase during this day. This document aims to be hosted on the GitHub Wiki and supplement the [existing Showcase guide](https://github.com/WordPress/Marketing-Team/wiki/WordPress-Showcase) by offering resources for getting started on a Contributor Day. It also outlines various ways contributors can get involved in the Showcase based on their experience and interests.

Hopefully, this will help provide more guidance for contributing to the Showcase at WCEU and other Contributor Days of flagship WordPress events.

### Request for feedback and review

Feel free to review the [current draft](https://docs.google.com/document/d/1QuHLEWKc5XDAz2krLdzijqwMJYh2Retdbh6DSsIG17A/edit#heading=h.tk8hdtij3cxi) and share any feedback or comments, especially if you think something is missing that could help new Showcase contributors by June 3, 2024. Thanks!

**Comment by rmartinezduque** [comment]
@thetinyl, given your involvement and experience with the Showcase, I think your input or review of the draft may be particularly useful. It would be great if you could take a look at it and let us know your thoughts. 🙏

**Comment by thetinyl** [comment]
Thanks @bernard0omnisend and @rmartinezduque for your efforts putting this together. I think it looks great. 

As a general comment, it does feel a little on the long side. As a companion piece to existing documentation, I think it's a nice opportunity to be as concise as possible to get folks up and running quickly—especially when we're sending them forth to just read more. 

I've added some more specific copy suggestions for your consideration in the document linked above.

**Comment by rmartinezduque** [comment]
Thanks for your suggestions, @thetinyl! Based on your feedback, I made some additional adjustments to ensure the content is as concise and helpful as possible. If @bernard0omnisend agrees, I think the doc is ready to be published.

**Comment by rmartinezduque** [comment]
I'm closing this issue for now. I talked with Bernard, and he agreed with Lauren's suggestions, so I've just created the GitHub page: https://github.com/WordPress/Marketing-Team/wiki/Getting-Started-at-a-Contributor-Day.

Any additional edits can be made directly on GitHub. Thank you!
