### ISSUE TITLE
[AMPLIFY]: WordPress 6.6 beta 2

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#424]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

WordPress 6.6 beta 2 release now available, please test 

### Amplification request details

Availability of the release, just out, and need for testing. All info in the post. 

Post also has info on number of fixes and closed tickets since Beta 1, if needed. 

@marybaum
@meherbala 

### Links

https://wordpress.org/news/2024/06/wordpress-6-6-beta-2/

### Additional important dates

11 June 2024 release

**Comment by bjmcsherry** [comment]
Hi @abhansnuk, I have seen the request, and will begin work on this now.

**Comment by bjmcsherry** [comment]
The campaign has been scheduled, and they will launch shortly. I will close this ticket with my comment. :)
