### ISSUE TITLE
[SHOWCASE]: bluebell.com

### ISSUE THREAD

**Issue by joshhargett** [WordPress/Marketing-Team#425]
### Submission ID

202311100158530

### Site URL

https://www.bluebell.com/

### Submission date

10 November 2023

### Submitter

Kori Ashton

### Author

Digital Uprise

### Theme

Custom

### Launched On

5 Aug 2021

### Country

US

### Description

Custom WordPress theme for major ice cream brand

### Reason for Submission

A popular southern ice cream brand chose and trusts WordPress as their platform.

**Comment by lorenzo6992** [comment]
Hi, here a little suggested text:

Bluebell is a renowned ice cream brand, known for its delicious and creamy creations that delight the taste buds of both young and old. Founded in 1907, Bluebell has grown to become one of the most beloved ice cream companies in America, offering a wide range of classic and innovative flavors. With its commitment to quality and excellence, Bluebell continues to bring joy and sweetness with every bite.

Just as Bluebell stands out for its innovation in flavors, its website also reflects this innovative spirit by effectively and creatively. With a modern and captivating interface but with a intuitive user experience, the site demonstrates how WordPress can adapt to any need, from small blogs to more structured and complex e-commerce sites.

**Comment by marko-srb** [comment]
👋

@joshhargett its a nice suggestion, but I am afraid this website doesn't follow good enough design practices, nor looks 'up-to-date' with stylistic choices. Although the business is amazing and has a very long history, our Showcase should reflect examples that would inspire people to make a website with WordPress, or at least subtly admire to what has been made with WordPress. 

I was part of the group of people who designed the new Showcase and made the first selection in the Showcase list, and I believe it would be good that we try pushing 'top-quality' or in some scenarios famous brands with 'mid-quality' design and aesthetic choices, as well as unique functionalities for our Showcase. 

In that light I'd suggest that this website doesn't get on Showcase, and maybe gets reconsidered for some other form of sharing on a different medium/channel.

**Comment by thetinyl** [comment]
Aside from @marko-srb's notes above, I believe this site in particular isn't viewable everywhere. @rmartinezduque mentioned that there were several folks at WCEU in Turin (and elsewhere in EU) that couldn't access this site. 

Between the brand being fairly regional, the design being dated and not particularly unique, and the issues with access for visitors outside of North America, this site won't be added to the Showcase at this time. 

Thanks @joshhargett and @lorenzo6992 for moderating and providing content for this one. Your efforts are still very much appreciated!
