### ISSUE TITLE
[SHOWCASE]: digitalists.at

### ISSUE THREAD

**Issue by gusteci** [WordPress/Marketing-Team#426]
### Submission ID

202402121720350

### Site URL

https://digitalists.at/

### Submission date

12 Feb 2024

### Submitter

digitalists

### Author

digitalists

### Theme

digitalists

### Launched On

3 Feb 2024

### Country

Austria

### Description

We are digitalists – a creative digital agency focusing on webdesign, branding, online shops, campaigns and strong digital moments.

### Reason for Submission

A mix of scroll animations, transitions, micro animations and interactive elements transforming the experience into a personal adventure and inviting users to find out more about our services and references.

**Comment by lorenzo6992** [comment]
Ciao! Here a suggested text for the site Digitalist:

Digitalists is a digital marketing agency specialised in creating innovative solutions to help businesses grow online. With a team of passionate experts, Digitalists offers SEO services, web design, and content strategies to enhance their clients' digital presence. Their mission is to turn ideas into reality, crafting engaging and impactful digital experiences.

Digitalists' website, built on WordPress, stands out for its freshness and originality, redefining the concept of a "Corporate Site". Featuring a cutting-edge user interface aimed at delivering a memorable user experience, Digitalists has effectively leveraged WordPress's capabilities as a CMS. This modern and dynamic approach perfectly reflects their expertise and innovation in the field of digital marketing.

**Comment by ArtenidaC** [comment]
![digitalists-mobile](https://github.com/WordPress/Marketing-Team/assets/172582891/6a9d4f3d-1480-46b6-a5a5-e394086f0869)
![digitalists-desktop](https://github.com/WordPress/Marketing-Team/assets/172582891/35135e00-0267-48ba-b0e2-5f86cf85eb64)

**Comment by thetinyl** [comment]
Thanks everyone!

This has been added to the Showcase: https://wordpress.org/showcase/digitalists/ 🥳
