### ISSUE TITLE
[SHOWCASE]: Disney & ABC Press

### ISSUE THREAD

**Issue by jamesgiroux** [WordPress/Marketing-Team#427]
### Submission ID

554

### Site URL

https://dgepress.com

### Submission date

13 June 2024

### Submitter

James Giroux

### Author

Disney & ABC Press

### Theme

Custom

### Country

USA

### Description

Disney is one of the premier global brands in creative content and entertainment. Known worldwide for its movies, TV shows, music and theme parks, it has developed a legacy of delighting customers for almost a century. The site dgepress.com is how Disney communicates what is happening across its television brands.

### Reason for Submission

Disney needed a content platform that would unite multiple network sites into a cohesive editorial workflow with integrated digital asset management. With WordPress, Disney was able to streamline content updates for 8,000 press members, which resulted in an 8x improvement in editorial velocity and improved both asset security and embargoed content distribution.

**Comment by jamesgiroux** [comment]
I wrote the Description/Reason for Submission as though it would be the copy for the website, feel free to adjust if you think it needs it. My suggestion is to combine the two paragraphs as follows:

**Description**

Disney is one of the premier global brands in creative content and entertainment. Known worldwide for its movies, TV shows, music and theme parks, it has developed a legacy of delighting customers for almost a century. The site dgepress.com is how Disney communicates what is happening across its television brands.

Disney needed a content platform that would unite multiple network sites into a cohesive editorial workflow with integrated digital asset management. With WordPress, Disney was able to streamline content updates for 8,000 press members, which resulted in an 8x improvement in editorial velocity and improved both asset security and embargoed content distribution.

**Comment by jamesgiroux** [comment]
![Dgepress](https://github.com/WordPress/Marketing-Team/assets/1839527/7e6cefb1-f39f-45a9-87b3-b40916d3697d)

Here is a screenshot that follows the guidelines for screenshots.

**Comment by jamesgiroux** [comment]
![Dgepress-desktop](https://github.com/WordPress/Marketing-Team/assets/1839527/5aee854b-5923-421c-9588-d7852c377a5b)
![Dgepress-mobile](https://github.com/WordPress/Marketing-Team/assets/1839527/53fbbb45-517d-4d1d-a31f-7158306bad06)

Here are optimized screenshots for desktop and mobile.

**Comment by jamesgiroux** [comment]
Just following up to see if this can be moved forward. It would be awesome to see another enterprise site with a global brand in the showcase. Let me know if you need more edits to copy or changes to the screenshots.

**Comment by thetinyl** [comment]
Thanks for working in this @jamesgiroux! 

I've made some edits to the copy and beefed it up a bit:

> Disney is an iconic premier brand that is influential in the creative content and entertainment industries. Known worldwide for its films, TV shows, music, and full-scale experiences—from theme parks to cruise ships—it has developed a legacy of delighting audiences for over a century. 
>
> The Disney General Entertainment Press (DGE Press) website focuses on Disney’s television brands and is built to communicate what’s happening across its various creative properties. The site is simple and clean, letting visitors find the content they need quickly and browse through press releases and updates just as easily. 
>
> Disney needed a content platform that could unite multiple network sites into a cohesive editorial workflow with integrated asset management. With WordPress, the DGE Press team was able to streamline content updates for 8,000 press members. The result is an 8X improvement in editorial velocity and improved both asset security and embargoed content distribution. 

This can likely be published at some point today.
