### ISSUE TITLE
[AMPLIFY]: New Sustainability Team Handbook for events

### ISSUE THREAD

**Issue by noraferreiros** [WordPress/Marketing-Team#428]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Sustainability

### What do you want to amplify?

Announcement of the launch of the Sustainability Team’s Handbook for events

### Amplification request details

The Sustainability Team has published a Handbook for helping organizers to make their events more sustainable. It includes suggestions, ideas and examples that can help organizers find ways to do so that suit their resources and possibilities..The main focus is to announce the launch, but we also want the community (organizers but also attendees and sponsors) to review it and give us feedback. All the information is in the link.

### Links

https://make.wordpress.org/sustainability/2024/06/12/the-sustainability-teams-handbook-for-events-is-here/

**Comment by rmartinezduque** [comment]
@noraferreiros, here's some suggested copy to help promote the new handbook on social platforms. Let us know if this looks good to go. 🙂

> 🌱 Every step counts towards a more conscious and responsible future. The Sustainability team has launched a new handbook with information and actionable tips for making #WordPress events more sustainable. Check it out and share your feedback: https://make.wordpress.org/sustainability/2024/06/12/the-sustainability-teams-handbook-for-events-is-here/.

**Comment by rmartinezduque** [comment]
Hi! I recently talked with @Nahuai and he confirmed this looks good to them, so I proceeded to schedule the post for X/Twitter, Facebook, and LinkedIn. It's set to go out on Tuesday, July 2 (pending final review and approval from @bjmcsherry). 🙂

**Comment by noraferreiros** [comment]
Thank you @rmartinezduque!

**Comment by rmartinezduque** [comment]
I'll be closing this issue as the posts are now live. 🎉 cc @noraferreiros 

- [X/Twitter](https://x.com/WordPress/status/1808504736716382330)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid0227pSQdxiD1KD8K6tsLf1VzoZxgapjGxyffGyFaZY8B5LTrm3heuMPNBQbKMTDNpcl)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_the-sustainability-teams-handbook-for-events-activity-7214270431510372353-2kNa/)
