### ISSUE TITLE
Marketing Team meeting notes

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#43]
This card is pulling together the various notes and tasks to update the handbook page https://make.wordpress.org/marketing/handbook/communication/creating-meeting-notes/

From this a revised document will be produced with checklists which are easy to follow and in the order notetakers process items.

- Larissa and Meher updating the instructions for notes from the long period of reviewing items to try and overcome some of the issues faced by notetakers/ reviewers.

- [21 March 2022: Updated from discussion tests with @abhansnuk and @meherbala about how to do this with less steps] Previously individual cards were added for each week's notes. Trying to find a combined solution for all items relating to a weekly meeting. To test: if a card started under GitHub projects, can the discussion take place there rather than in the discussion area and a separate card being needed for the meeting and its notes.. Ideal would be to have one card for each meeting to cover the different aspects of planning agenda, items to include/ cross links, link to script, updates / queries on the notes, and published link, any follow-up which needs to go forward onto a following week's card.

**Comment by eidolonnight** [comment]
https://make.wordpress.org/marketing/handbook/getting-involved/creating-meeting-notes/ has been updated. I think we can close this issue?

**Comment by sereedmedia** [comment]
Closing. This process is from last year and was completed and is now out of date!
