### ISSUE TITLE
[AMPLIFY]: WordPress 6.6 beta 3 available for testing 

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#431]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, WordPress users (existing), Builders/implementers, Developers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

WordPress 6.6 beta 3 is available to test, and to encourage reporting of any potential issues 

### Amplification request details

The post has details of how many fixes etc this beta has which can help you with added detail where there is more more copy space.
https://wordpress.org/news/2024/06/wordpress-6-6-beta-3/

Thanks.

A related question, there is a drop down on this GitHub repo for amplification requests for minor releases. Would this be more useful to you if it was for both major and minor releases? So for beta, RC etc of major releases to use that drop down? Thanks 

@marybaum

### Links

https://wordpress.org/news/2024/06/wordpress-6-6-beta-3/

### Deadline

ASAP please as release live in the last hour.

**Comment by bjmcsherry** [comment]
This has been scheduled and released. I will close the ticket with this comment.
