### ISSUE TITLE
[AMPLIFY]: Beginner WordPress Developer learning pathway

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Marketing-Team#434]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, Developers, Plugin community, Theme community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#LearnWP

### MakeWP Team

Training

### What do you want to amplify?

The Beginner WordPress Developer learning pathway is now complete and live on Learn.WordPress.org

### Amplification request details

I would like to get the word out that this new pathway is available. 

### Links

https://learn.wordpress.org/course/beginner-wordpress-developer/

### Deadline

28 June 2024

### Additional important dates

It would be nice to have this posted on Friday, June 28th.

**Comment by bjmcsherry** [comment]
@jonathanbossenger I have some copy here that we can use for the Friday launch:

> Dreaming of becoming a WordPress developer? 🌟 The Beginner WordPress Developer course is just what you need! From understanding the basics to creating your own projects, this course will guide you every step of the way. https://learn.wordpress.org/course/beginner-wordpress-developer/
> 
> #WordPress #WordPressDevelopment

Let me know if this works for you. Thanks.

**Comment by jonathanbossenger** [comment]
Hey @bjmcsherry, thanks, looks great. 

One thought: could we replace `creating your own projects` with `creating your own WordPress products`? That sounds more accurate in terms of what the course offers. As a developer, when I see 'creating my projects,' I also think of setting up things like version control, which this course doesn't include.

(Pedantic, I know, but us devs can be that way sometimes 😁 )

**Comment by DanSoschin** [comment]
Also, let's use #LearnWP as a hashtag instead of #WordPressDevelopment.

**Comment by bjmcsherry** [comment]
Done. I swapped it out, and this is now scheduled to deploy on Friday, as per the request. I will close this ticket as completed with this comment. :)
