### ISSUE TITLE
[SHOWCASE]: Bugs and Fixes

### ISSUE THREAD

**Issue by marko-srb** [WordPress/Marketing-Team#437]
### Comment

There are issues with a few existing entries.

- seems https://wordpress.org/showcase/zoox/ is no longer on WP
- https://wordpress.org/showcase/ray-charles-video-museum/ seems broken
- https://wordpress.org/showcase/ll-cool-j/ screenshot here isn’t good. Also not sure we had this site before, or if we did, screenshots were better

First to remove. Second to wait a bit if it is a temporary issue, then remove if nothing changes. Third to update screenshot, although I'd remove the site completely as it doesn't feel modern or nicely thought through to be in Showcase.

**Comment by marko-srb** [comment]
Just saw that I have access to edit from before. I removed Zoox (place it to draft), and I left Ray Charles one to be active for a few more days if the technical issue gets fixed.

Regarding https://wordpress.org/showcase/ll-cool-j/:

@thetinyl do you know if we can remove this site, or who I could ask? I don't think it is a good representation of what could be built with WordPress...

Thanks!

**Comment by thetinyl** [comment]
> I don't think it is a good representation of what could be built with WordPress...

@marko-srb I agree. Let's set it to draft. If others feel strongly that it should be included, we can always re-publish it. 

Thanks for looking into this!

**Comment by thetinyl** [comment]
> https://wordpress.org/showcase/ray-charles-video-museum/ seems broken

@marko-srb It looks like the Ray Charles site has been fixed and is back online. So we're all good there. 

I'm going to close this issue as complete.
