### ISSUE TITLE
[AMPLIFY]: WordPress 6.6 RC2 is here and ready for testing

### ISSUE THREAD

**Issue by meherbala** [WordPress/Marketing-Team#439]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, WordPress users (existing), Builders/implementers, Developers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin, Threads

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

WordPress 6.6 RC @ is available to test, and to encourage reporting of any potential issues

### Amplification request details

From the release post:

> Reaching this phase of the release cycle is a worthy achievement. While release candidates are considered ready for release, testing is still vital to make sure everything in WordPress 6.6 is the best it can be.

CC: @marybaum

### Links

https://wordpress.org/news/2024/07/wordpress-6-6-rc2/

### Deadline

ASAP please. Release dropped two hours ago

### Additional important dates

WP 6.6 Release is July 16, 2024

**Comment by bjmcsherry** [comment]
Hello, a campaign has been scheduled and will launch in a few minutes. I will close this ticket with this comment.
