### ISSUE TITLE
[AMPLIFY]: WordPress 6.6 RC 3

### ISSUE THREAD

**Issue by marybaum** [WordPress/Marketing-Team#440]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Threads, WordPress Media

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

WordPress 6.6 RC3 is here! It's the last release candidate before next week's planned general 6.6 release

### Amplification request details

Please download and test! If you maintain a WordPress product, this is your last chance ahead of release to make sure your work is compatible with the new version.

### Links

Release post: https://wordpress.org/news/2024/06/wordpress-6-6-rc3/

### Deadline

ASAP

**Comment by bjmcsherry** [comment]
I have added this campaign, and it will launch shortly. I will close this ticket with this comment.

**Comment by marybaum** [comment]
Thank you very much!
