### ISSUE TITLE
[AMPLIFY]: WordPress Meetup Reactivation 

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/Marketing-Team#441]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary), Solicit feedback, Other

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

We want to reactivate inactive Meetup groups across the world. 

### Amplification request details

Goals: 
1. To reach out to organizers of inactive Meetup groups between April - June to respond to our check-in message that we sent via Meetup.com platform.
2. To encourage Members of Meetup groups to step up as co-organizers for their Meetup groups, especially the inactive ones. 

Benefits:
To build up and maintain local WordPress community, so they can connect and learn together.

Intended audience:
1. Current Meetup organizers, especially inactive groups between April - June (primary)
2. Members of Meetup groups who are interested in stepping up as co-organizers to reactivate the inactive groups

Platform:
We sent our message via Meetup.com to the organizers of 370 inactive groups which will appear in their inbox. However, we only receive around 50 feedback. 
We're happy to receive advice. 

Campaign:
#WordPressMeetups or #WordPressEvents 
We're happy to receive advice. 

Dealine:
We hope to get as much feedback as possible this month but will consider extending the deadline for folks in EU until August. 

### Links

https://make.wordpress.org/community/2024/06/28/reactivating-inactive-meetup-groups/

### Deadline

18 July 2024 is the deadline for the members to respond to our outreach.

**Comment by bjmcsherry** [comment]
Hi @devinmaeztri, is the call to action here to have people open the previously sent meetup.com email? Is there any other way (such as an open form) for organizers to interact with you about questions they might have about reactivating a meetup?

**Comment by devinmaeztri** [comment]
Hellp @bjmcsherry, unfortunately we don't have a form for this project. 

CTAs are: 

1. organizers of inactive groups that don't have an event between April - June 2024 to reach out to WordCamp Central via support@wordcamp.org and let us know their group status.
2. if the organizers are not responding, the members of the inactive groups are invited to step up and apply as co-organizers via https://make.wordpress.org/community/handbook/meetup-organizer/meetup-program-basics/
3. organizers of WP Meetup groups to support each other, such as reaching out to the inactive groups, recruiting volunteers to reactivate the inactive groups. 

Thank you, and please let me or Courtney PK know if you have further questions.

**Comment by bjmcsherry** [comment]
Hi @devinmaeztri, how many people would we be targeting with this campaign? The social reach is 2.2 million followers, but I worry that we are really only targeting a small segment—possibly in the hundreds?

**Comment by DanSoschin** [comment]
I agree that the social accounts (maybe except for LinkedIn) are probably the wrong target audience. It's too broad.

**Comment by devinmaeztri** [comment]
Hi @bjmcsherry and @DanSoschin. Apologies for the delayed response! We still want to reach out to a few hundred thousand co-organizers and members of the inactive groups. We also aim to encourage all community members to support each other and help us reactivate these groups. [Here](https://make.wordpress.org/community/2024/08/06/important-call-to-action-help-us-reactivate-inactive-meetup-groups-by-sept-16/) is a recent post we published for reference. Do you think it is still possible to create a social post about the reactivation?

**Comment by bjmcsherry** [comment]
Hi @devinmaeztri, now that we have a post, I can definitely work on this. I should have something later today for you to review.

**Comment by bjmcsherry** [comment]
Hi @devinmaeztri How does this look:

> 🌍 The heart of WordPress beats with its community! Let's come together and help reactivate our Meetup groups. Your participation can make a huge difference. Learn more:  https://make.wordpress.org/community/2024/08/06/important-call-to-action-help-us-reactivate-inactive-meetup-groups-by-sept-16/

> #WordPress 

Let me know if you are good with this.

**Comment by devinmaeztri** [comment]
Hello, @bjmcsherry. Sounds good! Can we add #WordPressEvents? Or something to indicate events? Thanks so much! May I know where we are going to publish it?

**Comment by bjmcsherry** [comment]
@devinmaeztri what do you think about #WordPressCommunity instead? 

I will publish to TW(X)/FB/LI/THR and perhaps Mastodon as well. I have been thinking about possible campaigns to soft launch with the platform, and this could be good. We wouldn't get a lot of traction, but the OS community may be more receptive there.

**Comment by devinmaeztri** [comment]
Thank you, @bjmcsherry!
