### ISSUE TITLE
[AMPLIFY]: WordCamp US 2024 Ticket Push

### ISSUE THREAD

**Issue by Bretteroo** [WordPress/Marketing-Team#444]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#WordCamp, None/Not sure/Other

### MakeWP Team

Marketing

### What do you want to amplify?

WordCamp US 2024 is just two months away - get your tickets now

### Amplification request details

WordCamp US 2024 is now just two months away, September 17-20.

The organizing team would love some additional help promoting ticket sales and the event overall to help boost attendance in whatever channels/formats the Marketing team feels are appropriate.

There is an About page that explains what WCUS _is_ and spells out takeaways/benefits of attending that may be helpful: https://us.wordcamp.org/2024/about/

The direct links to order tickets is https://us.wordcamp.org/2024/tickets/

Thank you!

### Links

https://us.wordcamp.org/2024/about/ 

### Deadline

Any time!

### Additional important dates

WordCamp US this year is September 17-20.

### Any additional notes or details? If you marked "Other" above, please provide additional details here.

The official event hashtag is simply #WCUS

You can link to any relevant pages on the WordCamp US 2024 site https://us.wordcamp.org/2024/.  The ultimate goal is to boost ticket sales.

**Comment by bjmcsherry** [comment]
Hi @Bretteroo, how does this sound:

> 🎟️ Have you picked up WordCamp US 2024 tickets? Join the community September 17-20 in Portland, Oregon, for an unforgettable event filled with learning, networking, and fun. Tickets are still available: https://us.wordcamp.org/2024/tickets/
> 
> #WCUS #WordPress

Thanks.

**Comment by Bretteroo** [comment]
@bjmcsherry Works for me!   Thank you.

**Comment by bjmcsherry** [comment]
@Bretteroo This has been scheduled and will deploy shortly. I will close this ticket with this comment.
