### ISSUE TITLE
[SHOWCASE]: FCXV Fabienne Chapot site no longer working

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#445]
### Comment

While browsing through the Showcase, I noticed the URL in Fabienne Chapot's entry is no longer working: https://wordpress.org/showcase/fabienne-chapot/.

cc @thetinyl for awareness, in case you can help review it and remove it if necessary.

**Comment by thetinyl** [comment]
Thanks @rmartinezduque. We had a similar issue recently with another site that came back online after a couple of days. 

I'll unpublish for now and check back in a few days to see if there's any change.

**Comment by rmartinezduque** [comment]
Thanks, Lauren!
