### ISSUE TITLE
[SHOWCASE]: Featured sites bug

### ISSUE THREAD

**Issue by marko-srb** [WordPress/Marketing-Team#446]
To replicate the issue:

1. Select any site that is featured on the home page under the second section.
2. Go and edit any text in it. 
3. Publish/Save.
4. Return to live site.*

*Once you return to live site, you'll see that site/post isn't featured anymore. To fix it, you'll need to manually visit this site post and open to edit it — then check 'featured' filter/category, even though you didn't uncheck it. 

—

Can we solve this by disabling automatic 'unchecking' of a 'featured' filter if someone changes text or any edit (that isn't the mentioned check/uncheck)?

Thanks!

**Comment by ryelle** [comment]
@marko-srb Can you report this in [the code repo](https://github.com/WordPress/wporg-showcase-2022)? I think this one is just used for tracking content.

**Comment by marko-srb** [comment]
transfered to 

https://github.com/WordPress/wporg-showcase-2022/issues/272
