### ISSUE TITLE
[AMPLIFY]: WordPress Contributor Mentorship Program Cohort #3 (2024 Q4): Call for Mentees & Mentors

### ISSUE THREAD

**Issue by harishankerr** [WordPress/Marketing-Team#447]
### What is the goal of this amplification request? (select all that apply)

Recruit volunteers

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, WordPress users (existing), WordPress users (new/potential), Builders/implementers, Developers, Designers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin, Threads, Email, WordPress Media

### Campaign

None/Not sure/Other

### MakeWP Team

Community

### What do you want to amplify?

WordPress Contributor Mentorship Program Cohort #3 (2024 Q4): Call for Mentees & Mentors is out and needs to be ap

### Amplification request details

We have just published the WordPress Contributor Mentorship Program Cohort #3 (2024 Q4): Call for Mentees & Mentors, and would like to amplify the call in order to get maximum applications for mentors and mentees.

### Links

https://make.wordpress.org/project/2024/08/16/wordpress-contributor-mentorship-program-cohort-3-2024-q4-call-for-mentees-mentors/

### Deadline

August 20 2024

### Additional important dates

The call ends on August 26th, 2024, so a couple of shares over the week would be greatly appreciated.

**Comment by bjmcsherry** [comment]
Hi @harishankerr, how does this copy look for you?

> Join the next cohort of the Contributor Mentorship Program! Applications are available for Mentor or Mentee. This program is a great way to help new folks start their contributor journey with confidence. Get the details: https://make.wordpress.org/project/2024/08/16/wordpress-contributor-mentorship-program-cohort-3-2024-q4-call-for-mentees-mentors/
> 
> #WordPress

**Comment by harishankerr** [comment]
That looks great to me, @bjmcsherry Please go ahead and share it!

Like I said, it would be amazing if we could share it a couple of times more, perhaps another blast before the August 26th deadline?

**Comment by bjmcsherry** [comment]
@harishankerr We can. I would change up the copy a bit to differentiate it, but I can absolutely get this scheduled with two campaigns before the 26th.

**Comment by harishankerr** [comment]
Sounds like a plan, and yes, a modified copy for the second post sounds excellent. Thank you so much once again, @bjmcsherry

**Comment by bjmcsherry** [comment]
Here is a modified copy for round two:

> Ready to make an impact in the WordPress community? Apply as a Mentor or Mentee with the Contributor Mentorship Program! This is a chance to help be part of growing the community and WordPress contributions. Get the details here: https://make.wordpress.org/project/2024/08/16/wordpress-contributor-mentorship-program-cohort-3-2024-q4-call-for-mentees-mentors/
> 
> #WordPress

Does this work for you?

**Comment by harishankerr** [comment]
That looks perfect, @bjmcsherry - you are a star! 🤩 Let’s fix that!

**Comment by bjmcsherry** [comment]
Great! These have both been scheduled and will be deployed at various times over the week. I will close this ticket with this comment.
