### ISSUE TITLE
[AMPLIFY]: The Wordpress Sustainability Team Roadmap for Q4 2024

### ISSUE THREAD

**Issue by YellowlimeNL** [WordPress/Marketing-Team#448]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Instagram, Linkedin, Threads, Email, WordPress Media

### Campaign

None/Not sure/Other

### MakeWP Team

Sustainability

### What do you want to amplify?

The Roadmap published by the WordPress Sustainability Team

### Amplification request details

The WordPress Sustainability Team has published a roadmap for the last months of 2024. The team focuses on economical, social and environmental sustainability. By amplifying the roadmap we hope to create awareness and attract more contributors to join our forces.

### Links

https://make.wordpress.org/sustainability/2024/09/03/wp-sustainability-team-roadmap-2024/

### Deadline

No, ideally before the end of 2024 😉

**Comment by bjmcsherry** [comment]
@YellowlimeNL, how does this copy look for you?:

> 🌿 Want to make a difference? The WordPress Sustainability Team's 2024 roadmap for the remainder of the year is out, and we're looking for contributors passionate about economic, social, and environmental sustainability. Join us!  
🔗 https://make.wordpress.org/sustainability/2024/09/03/wp-sustainability-team-roadmap-2024/  

> #WordPress #SustainableWordPress

If it looks good for you, I will get this up later this week.

**Comment by YellowlimeNL** [comment]
Excellent @bjmcsherry, thank you for your support.

**Comment by bjmcsherry** [comment]
Happy to help @YellowlimeNL. :) 

I have scheduled the campaign to launch on several platforms this week. I will close this ticket with this comment.
