### ISSUE TITLE
[AMPLIFY RELEASE]: WordPress 6.6.2

### ISSUE THREAD

**Issue by hellofromtonya** [WordPress/Marketing-Team#449]
### Version number

6.6.2

### Release type

Maintenance

### Link to release announcement on WordPress.org News

https://wordpress.org/news/2024/09/wordpress-6-6-2-maintenance-release/

**Comment by bjmcsherry** [comment]
Hi @hellofromtonya, how does this look for you?:

> 🔒 Release announcement: WordPress 6.6.2 is now available. This is a maintenance release, and WordPress recommends updating all environments to this latest version. More information can be found in this post: https://wordpress.org/news/2024/09/wordpress-6-6-2-maintenance-release/

> #WordPress

**Comment by hellofromtonya** [comment]
LGTM 🚢  Thank you @bjmcsherry

**Comment by bjmcsherry** [comment]
Perfect. Thanks @hellofromtonya! 

I have scheduled a campaign to launch soon. I will close this ticket with this comment.
