### ISSUE TITLE
Month in WordPress: March 2022

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#45]
Creating this card for @rmartinezduque

Summary of message shared 30 March 2022:
- Anjana and Reyez are working on the next edition of Month in WordPress newsletter
- Publication date: Tuesday, April 5, 2022
- Actions: If someone has a Make team update that would be valuable and relevant for the post, please feel free to share it on the Make Marketing Slack channel and tag @rmartinezduque (Reyes Martínez) for awareness by Friday, April 1
- Draft will be added to this card and shared in the Marketing channel before publication

**Comment by rmartinezduque** [comment]
Thank you for creating this card, @nalininsbs!

> and tag @reyes Martínez for awareness by Friday, April 1

I think we are tagging the wrong person here. It might help to put my Slack username in code format (single backticks) to avoid any confusion and tag another person by mistake, i.e. `@Reyes Martínez`.

**Comment by meherbala** [comment]
Changed the tag @rmartinezduque

**Comment by rmartinezduque** [comment]
Hi! Here's the [draft of March's Month in WordPress post](https://docs.google.com/document/d/1beIeh2hcY4gT_yU2ioNEvY4y2FTNXx_t-I5z-jJlRV0/edit#). I'm hoping to publish tomorrow (April 5) by 13:00 UTC if possible so that I can include a last-minute reminder about the WordPress 6.0 product walkthrough. Feel free to share any comments by then, thanks!

**Comment by rmartinezduque** [comment]
The post is now published: https://wordpress.org/news/2022/04/the-month-in-wordpress-march-2022/. Thank you!

**Comment by abhansnuk** [comment]
@nalininsbs I have resolved your query on not being able to find the March card. It was labelled April (as it is actioned in April, but it is the March card). I have changed this in the subject. The published link has been added, so I will mark this as closed. 

I will create a replacement April card for you.

**Comment by abhansnuk** [comment]
@rmartinezduque card set up for you for the April 2022 edition of Month in WordPress. 

@nalininsbs let me know if you have still have problems cross-linking to it from the meeting card for the end of the month. It should work now.
