### ISSUE TITLE
[AMPLIFY]: WordPress Dashboards

### ISSUE THREAD

**Issue by harishankerr** [WordPress/Marketing-Team#455]
### What is the goal of this amplification request? (select all that apply)

Solicit feedback

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community, MakeWP community, Builders/implementers, Developers, Plugin community, Theme community, Agencies/Enterprise

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Twitter/X, Facebook, Linkedin, Threads

### Campaign

None/Not sure/Other

### MakeWP Team

Core, Training

### What do you want to amplify?

We would like to get feedback on the usefulness of the newly-launched WordPress Contribution Dashboards.

### Amplification request details

WordPress Contribution Dashboards were launched recently as an experiment. We would like to get feedback from WordPress contributors whether these dashboards are useful and on what would help contributors and contributor teams. We would also love support from contributors to help build and maintain these workshops going forward. We are specifically looking for feedback as comments on this blog post: https://make.wordpress.org/project/2024/09/12/wordpress-contribution-health-dashboards-an-experiment/

Dashboard link:
Core: https://make.wordpress.org/project/core-team-dashboard/
Community: https://make.wordpress.org/project/community-team-dashboard/
Training: https://make.wordpress.org/project/training-team-dashboard/
6.6 Stats: https://make.wordpress.org/project/wordpress-6-6-statistics/

It would also be nice to amplify these dashboards individually, as well. 

### Links

https://make.wordpress.org/project/2024/09/12/wordpress-contribution-health-dashboards-an-experiment/

### Deadline

20 Sept 2024

### Additional important dates

It would be great if we have a tweet that goes out on the WCUS Contributor day (September 16th) with additional amplification request (not more than 1-2) over the week.

**Comment by bjmcsherry** [comment]
Hi @harishankerr, Here is the copy for the campaign. It will launch today in under an hour.

> With Contributor Day upon us at #WCUS, We need your input on a set of WordPress Contribution Health Dashboards to better visualize the incredible work being done in our community. Take a moment to explore and provide your feedback. Let’s continue making WordPress stronger together. Review here: https://make.wordpress.org/project/2024/09/12/wordpress-contribution-health-dashboards-an-experiment/
#WordPress

I will close this ticket with this comment.

**Comment by harishankerr** [comment]
That looks amazing, @bjmcsherry! Thanks for putting this together in such short time!
