### ISSUE TITLE
[AMPLIFY]: WordPress 6.7 Beta 3 News Post

### ISSUE THREAD

**Issue by dream-encode** [WordPress/Marketing-Team#468]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

https://wordpress.org/news/2024/10/wordpress-6-7-beta-3/

### Amplification request details

We'd like the same thing as done for Beta 1 and Beta 2 please :)  https://wordpress.org/news/2024/10/wordpress-6-7-beta-3/

### Links

https://wordpress.org/news/2024/10/wordpress-6-7-beta-3/

**Comment by bjmcsherry** [comment]
Hi @dream-encode, what do you think of this copy?:

> WordPress 6.7 Beta 3 is here! Check out the latest developments and how you can help with testing: https://wordpress.org/news/2024/10/wordpress-6-7-beta-3/
>
>#WordPress

If you are okay with this, I will get this scheduled.

**Comment by dream-encode** [comment]
@bjmcsherry Looks great!  Thank you so much!
