### ISSUE TITLE
March 2022 Make Marketing Handbook Review

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#47]
Our team documentation is important to Make team members old and new. The [WordPress Marketing Handbook](https://make.wordpress.org/marketing/handbook/) is constantly evolving to meet contributor needs. In order to continue improving, we need feedback and comments from readers.

Please read the content within the [WordPress Marketing Handbook](https://make.wordpress.org/marketing/handbook/) and provide feedback in the comments of this issue.

Consider some of the following questions while reading?
- What information is missing?
- What pieces are unclear?
- What content seems outdated?
- Is anything thin the handbook inaccurate?

**Comment by nalininsbs** [comment]
Thank you @nimeshpatel-multidots @dave-kushal and @ronakganatra-multidots. Thank you for looking at this during your contributor event.

@eidolonnight do you want an entry for this each month or could we remove the date in the title? Could we adapt this for WordCamp Europe's Contributor Day? Thank you.

**Comment by nalininsbs** [comment]
Link to update/ summary of the update on this sprint to be added and this card can then  be closed. Over to @eidolonnight . Thank you

**Comment by sereedmedia** [comment]
Handbook updates focusing specifically on the Get Involved and Guidelines for Meeting Notes sections are being considered in GitHub issues:

- https://github.com/WordPress/Marketing-Team/issues/169 (Get Involved)
- https://github.com/WordPress/Marketing-Team/issues/103 (Guidelines for Meeting Notes)

Additional feedback and updates can be handled with those and other more specific issues so I am closing this card.
