### ISSUE TITLE
[AMPLIFY]: Announcing the next Learn WordPress Course Cohort

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Marketing-Team#470]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

General WordPress community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#LearnWP

### MakeWP Team

Training

### What do you want to amplify?

Sign ups for the next Learn WordPress course cohort

### Amplification request details

The cohort was announced last week. We'd like to make the announcement post available to more WordPress community folks.

There is a deadline for sign-ups (Friday, 25 October), so if this can't be amplified before then, please delete this request.

### Links

https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/

### Deadline

25 October 2024

**Comment by bjmcsherry** [comment]
Hi @jonathanbossenger, I have a couple of versions of copy for you to look at. 

FB/LI/TH:

 > Join the Upcoming Learn WordPress Course Cohort—Introduction to Developing Plugins! You'll get hands-on training and dive deep into best practices. 
>
>⏰ Register by: 25 October
>🔗 https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/
>
>#WordPress

X:

> Join the Upcoming Learn WordPress Course Cohort—Introduction to Developing Plugins! You'll get hands-on training and dive deep into best practices. 
>
>#WordPress

X reply:
>⏰ Register by: 25 October
>🔗 https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/

We are moving away from adding in the CTA in the post for X, so you will see that the CTA is in the reply for better impression volume. Let me know if this works for you.

**Comment by bjmcsherry** [comment]
This campaign has launched. I will close this ticket with this comment.
