### ISSUE TITLE
[AMPLIFY RELEASE]: WordPress 6.7.1

### ISSUE THREAD

**Issue by desrosj** [WordPress/Marketing-Team#474]
### Version number

WordPress 6.7.1

### Release type

Maintenance

### Link to release announcement on WordPress.org News

https://wordpress.org/news/2024/11/wordpress-6-7-1-maintenance-release/

### Optional notes and details

WordPress 6.7.1 is a fast-follow release with a strict focus on bugs introduced in WordPress 6.7. 

In total, 16 bug fixes are included for issues throughout Core and the Block Editor.

**Comment by jeffpaul** [comment]
What's the expected response time on something like this?  Had this been a security release we'd want to ensure the social shares go out much more quickly.

**Comment by bjmcsherry** [comment]
> What's the expected response time on something like this? Had this been a security release, we'd want to ensure the social shares go out much more quickly.

Usually within a couple of hours, depending on various factors. We already had this release marked in content calendars, which helps speed things up.

**Comment by desrosj** [comment]
How about this:

> 🔒 Release announcement: WordPress 6.7.1 is now available! This is a maintenance release featuring 16 bug fixes in total. It's recommended to always run the latest version of WordPress, so update today! More information can be found in this post: https://wordpress.org/news/2024/11/wordpress-6-7-1-maintenance-release/
> 
> #WordPress

Also, do we need the `Release announcement:` at the beginning? Seems better to just get to the point.

**Comment by bjmcsherry** [comment]
@desrosj It is part of the template for these types of posts. In terms of attention, it does work to get clicks. 

Thanks. I will get something scheduled now.

**Comment by bjmcsherry** [comment]
This campaign has now launched. I will close this ticket with this comment. Thanks, everyone!!

**Comment by jeffpaul** [comment]
Have we checked with the Accessibility team on including emoji's as lead-in on these sorts of posts?  It would seem that those probably get read out by screen readers and that's not really helpful to those folks so if that's the case then I'd advocate for removing emojis from social share templates.

**Comment by bjmcsherry** [comment]
We can definitely review this further with the Acessibility team for future use. Thanks for the suggestion @jeffpaul

**Comment by joedolson** [comment]
Here's a link to my feedback on that: https://wordpress.slack.com/archives/C02RP4X03/p1732228207344069

To summarize, yes, emoji are read by screen readers. They have a built in alternative text, and are generally announced as graphics. This means that the occasional emoji is fine; but a large quantity of emoji are going to result in a frustrating reading experience. 

Here's a useful reference: https://www.accessible-social.com/copy-and-formatting/emoji

**Comment by bjmcsherry** [comment]
Thanks @joedolson
