### ISSUE TITLE
[AMPLIFY]: Make WordPress gets a refresh

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#475]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

MakeWP community

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Meta

### What do you want to amplify?

Make WordPress redesign

### Amplification request details

Let's amplify the latest design updates for Make. Something like the following should suffice:

> The online home for everyone making #WordPress has leveled up. With a new block-based homepage, refreshed handbooks, and an improved meeting calendar, the recent redesign brings the latest WordPress.org styles to yet another site section.
>
> Check out the highlights and what’s next: [[Link]](https://make.wordpress.org/meta/2024/12/12/make-wordpress-gets-a-refresh/)

### Links

https://make.wordpress.org/meta/2024/12/12/make-wordpress-gets-a-refresh/

### Deadline

14 Dec 2024

**Comment by bjmcsherry** [comment]
The campaign has been set in Sprout for social platforms and will launch over the next day (Saturday). 

With this comment, I will close the ticket.
