### ISSUE TITLE
Month in WordPress: April 2022 edition

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#49]
Creating this card for @rmartinezduque and @nalininonstopnewsuk

Anjana and Reyes will draft the next edition of Month in WordPress newsletter. 

Publication date: Thursday, May 5, 2022 (date tbc)
Note the edition month name is the previous month to publication.

Actions: If someone has a Make team update that would be valuable and relevant for the post, please feel free to share it on the Make Marketing Slack channel and tag @rmartinezduque (Reyes Martínez) for awareness by Monday, May 2 (date tbc - holding date entered)

The draft will be added to this card and shared in the Marketing channel before publication.

**Comment by rmartinezduque** [comment]
The next edition of Month in WordPress aims to be published next Thursday, May 5, 2022.

If anyone has any Make Team updates they would like to see featured, please feel free to:
- Add them as a comment to this GitHub card, or
- Share them in the Make Marketing Slack channel and ping `Reyes Martinez` for awareness by **Tuesday, May 3, 2022**.

Thank you!

**Comment by nalininsbs** [comment]
@rmartinezduque could you add the link to the published newsletter when it is out to this card and then move it to Done. Thank you.

**Comment by rmartinezduque** [comment]
Thanks, @nalininsbs. Here's the draft for the April 2022 edition of the Month in WordPress: https://docs.google.com/document/d/1pKiIciOaSud74fS7WKktQfDXwS6MhSqhLMPY-iZPMik/edit?usp=sharing. I'm hoping to publish it tomorrow (May 5) by 15:00 UTC. Thank you!

**Comment by rmartinezduque** [comment]
The April 2022 edition of Month in WordPress is now published: https://wordpress.org/news/2022/05/the-month-in-wordpress-april-2022/.

**Comment by rmartinezduque** [comment]
@nalininsbs it looks like I don't have permission to close the card or move it to 'Done'.

**Comment by rmartinezduque** [comment]
Thanks, @abhansnuk. I'm afraid I'm still not able to move the card to 'Done' nor close the issue. I only have the option to copy the card link.

<img width="702" alt="screenshot" src="https://user-images.githubusercontent.com/20700757/168474392-609ea0d7-9050-4bb3-8cdf-c9409e64b721.png">

**Comment by abhansnuk** [comment]
I have asked GitHub to send another email to you @rmartinezduque to see if this fixes it once you have confirmed the join request. Thanks.
