### ISSUE TITLE
Team Update P2 post for March 2022

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#52]
Replacement card - original card and link to document not showing - 2022/4/6. Chris/ Meher/ Abha can you check? Original appears to have been archived accidentally. Thank you

**Comment by sereedmedia** [comment]
this is still in the In Progress column on the main screen. Can someone update?

**Comment by abhansnuk** [comment]
This is for Team Reps @sereedmedia and from looking at the previous card, access to the Update channel was awaited. I have allocated it to the Team Reps label for now.

**Comment by murillol** [comment]
From seeing https://github.com/WordPress/Marketing-Team/issues/152 I suggest we close this one too @nalininsbs?

**Comment by nalininsbs** [comment]
This can be closed from my perspective as no access to the Update site was available to me in the year. I do not know if @murillol and Nicholas gained access and updated it.
