### ISSUE TITLE
Showcase (migrated reference file)

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#55]
REFERENCE MATERIAL

**October 2021**
The meeting notes for the showcase redesign live in .org Marketing Materials / showcase. Direct link: https://docs.google.com/document/d/10k6WNb2wCOU5yJHDqE1KGiJwrpWDu9pfzQ-hnxV2QCk/edit#heading=h.4fyuw1whgefe

**2021**
Previous board in Marcomms-Series repository set up in 2021 when the project kickstarted again. It was waiting for more contributors to marketing to progress it, and highlighted in the contributor ladder discussions.  https://github.com/wpmarketingteam/Marcomms-Series/projects/3

**May 2021 discussion in team meeting**
[Redesign as at 2021/6 - Figma file ](https://www.figma.com/file/09QC8T6qMrQ6gTtXDhSsKL/WP-showcase-v5)

Link to @hedgefield's design documents sharing in [slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1622041284245200)
Link to last known [Figma redesign discussions](https://www.figma.com/file/Yi5tNOjcRjE60xgFWvGOAes0/WP-showcase-v4?node-id=0%3A1)

**2020 WordCamp Europe contributor day efforts on Showcase**
[Link to slack thread in marketing](https://wordpress.slack.com/archives/C0GKJ7TFA/p1591272526075900
)

**2020 redesign**
Link to the 2020 redesign discussion notes https://docs.google.com/document/d/10k6WNb2wCOU5yJHDqE1KGiJwrpWDu9pfzQ-hnxV2QCk/edit#heading=h.4fyuw1whgefe

2020/6/8 - [discussion in marketing slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1578496621044000)

**Redesign meta ticket** - [Slack discussion](https://wordpress.slack.com/archives/C0GKJ7TFA/p1578496621044000)
https://trello.com/c/wQJwSmfT/32-showcase-redesign-meta-ticket

**2019-2020 restructure plans**
Trello card to restructure plans 2019-2020 https://trello.com/c/SdIcVK6q
Macro tracking card
https://trello.com/c/OLmjZuhI/253-showcase-macro-tracking-card

**Nov 2019**
Update from WCUS contributor day via Harry Jackson - [slack link](https://wordpress.slack.com/archives/C0GKJ7TFA/p1573660135477900)

**May 2019 Showcase redesign meeting in [Marketing Slack]**(https://wordpress.slack.com/archives/C0GKJ7TFA/p1558360789172600)

**Question on whether locale sites could have a customized view of showcase**
[Link to polyglots [](slack](https://wordpress.slack.com/archives/C02RP50LK/p1648582354717029))
Summary: a rosetta site can have a showcase page with local sites, the actual link redirect to https://wordpress.org/showcase/
wordpress.orgwordpress.org. If you have sites in the "Gallery" you can have some of them displayed in the bottom of the main page, with the link to "Showcase" link will be to the main showcase gallery, but site thumbnails will be from local gallery

**2019/6/2 Query from Jono on taking forward the updating - [Marketing Slack]**(https://wordpress.slack.com/archives/C0GKJ7TFA/p1561970337334200)
This also has some of the background.

2019/7/1 Update from Harry on the Trello board and next steps, [Marketing Slack](https://wordpress.slack.com/archives/C0GKJ7TFA/p1622639865307700?thread_ts=1622040471.224500&cid=C0GKJ7TFA)

**Comment by abhansnuk** [comment]
2022/3/30 Last check with A8C on whether there was now a sponsored contributor allocated to this area to link in with on migration of previous information. [Slack link](https://wordpress.slack.com/archives/C0GKJ7TFA/p1648655551117109)

**Comment by murillol** [comment]
From #meta on Make WP Slack: https://wordpress.slack.com/archives/C02QB8GMM/p1648640123266429
- Dan may be able to help with the Showcase **maintenance** and needs a couple of bullet points on what that would entail. Ryan Marks also interested. 
- Otto suggests considering setting up some kind of team for it.

**Comment by nalininsbs** [comment]
Hello. Ryan Marks will need to comment on this card and he can be assigned to it.

**Comment by nalininsbs** [comment]
@harryjackson1221 to be added to this card. @abhansnuk asked him last week in the slack thread to comment on the card so it can be assigned. Anyone else volunteered on this?

**Comment by nalininsbs** [comment]
Progress on the showcase refresh has been posted in an article https://make.wordpress.org/meta/2022/12/14/showcase-visual-refresh/

**Comment by eidolonnight** [comment]
Now that the new Showcase design is live ([A New WordPress Showcase](https://wordpress.org/news/2023/10/a-new-wordpress-showcase/)), we can close this migrated reference ticket and discuss the remaining issues like [Showcase Guidelines and Content Moderation #221](https://github.com/WordPress/Marketing-Team/issues/221).
