### ISSUE TITLE
Team Reps access to update WordPress.org calendar

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#56]
https://make.wordpress.org/meetings/

Seek access for this site/calendar from Meta. Courtney can provide support.

**Comment by murillol** [comment]
Looks like this is done!!? And confirmed that Marketing has an entry for our weekly meetings.
[From Slack](https://wordpress.slack.com/archives/C023M4VELMB/p1649358928513979)

**Comment by nalininsbs** [comment]
Meta confirmed the existing entry for marketing. @eidolonnight do you now have working access to edit it? Do Larissa and I need access or can ticket be closed? Thank you

**Comment by sereedmedia** [comment]
This is complete.
