### ISSUE TITLE
WordPress.org content audit & SEO

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#57]
Set up macro card in training for Anjana. 

Information at a macro level will belong on this card. Individual tasks will be added into the other columns, and can be cross-linked to this macro card. Have fun Anjana.

**Comment by Starbuck245** [comment]
Thanks so much for helping me by creating this project on GitHub, @abhansnuk ! Would you be able to assign this to me so I can add more information?

**Comment by eidolonnight** [comment]
We don't seem to have an issue description or any details here, so I'm closing this issue for now.
