### ISSUE TITLE
2022/05/04 Global Marketing Team Meeting

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#60]
All things related to this meeting and any collaboration, including:

-  planning
-  suggestions for items and agenda drafting
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources

Useful inks:

- [Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
- https://github.com/WordPress/Marketing-Team/issues/23

**Comment by murillol** [comment]
@yashwardhanrana will be the note-taker for this meeting

**Comment by nalininsbs** [comment]
Card and call for agenda and updates shared in the [Marketing [](Slack](https://github.com/WordPress/Marketing-Team/issues/60))
Next week's card - [May 11, 2022](https://github.com/WordPress/Marketing-Team/issues/62)

**Comment by abhansnuk** [comment]
Latest call for testing on FSE - request for amplification
https://make.wordpress.org/test/2022/04/28/fse-program-testing-call-14-rallying-recipe-reviewers/

**Comment by yvettesonneveld** [comment]
WCEU contributory day update: I'm not speaking, so I'll be able to help facilitate.

**Comment by murillol** [comment]
From @nalininsbs:
[Agenda preview](https://make.wordpress.org/marketing/?p=9192&preview=1&_ppp=ac39f5367f)
Social question: Share what smell you find the most soothing or relaxing, and why?
 
Nalini I copied over what you shared here: https://github.com/WordPress/Marketing-Team/issues/62#issuecomment-1116740800 becasue that's next week's meeting :)

**Comment by jpantani** [comment]
Two issues that would be good to bring up during the team meeting tomorrow include: 

Contributor Day / Marketing Table: https://github.com/WordPress/Marketing-Team/issues/64
Call for ideas and problems to tackle during contributor day

Grow Your Story: https://github.com/WordPress/Marketing-Team/issues/51
Call for Make Marketing Members to participate

**Comment by nalininsbs** [comment]
Published agenda https://make.wordpress.org/marketing/2022/05/04/agenda-global-marketing-meeting-may-4-2022/

**Comment by yashwardhanrana** [comment]
Thanks @murillol!

The post is now live: https://make.wordpress.org/marketing/2022/05/11/notes-global-marketing-meeting-4-may-2022/

🚀

**Comment by abhansnuk** [comment]
@nalininsbs I have added the meetings-notes label to this card. It does not seem to affect the milestones or search by milestone date. Was there anything else you wanted to test?

**Comment by nalininsbs** [comment]
Thank you for testing that so we can share this in the meeting. @abhansnuk If someone goes to the label meetings-notes, will it still show them if an item relates to this area and has been closed? Will they be able to easily see which cards are open when filtering by meetings-notes? Ideal would be to have the meetings to come to appear at the top. From what I understand of your screenshare, this may need the titles to be listed in a different way?

Props to @eidolonnight for the idea of this new label.

**Comment by abhansnuk** [comment]
Yes this card can be closed. I have moved the query on how to search for it to a note in the wiki section as a  GitHub potential docs to do list. Thanks for the question
