### ISSUE TITLE
Documentation Sprint: Friday 22 April 2022

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#61]
Once a month, I spend a day focused on writing and documentation. For this sprint, I'm looking at the following items:

- Create: Coffee hour facilitator guide
- Update: [resource links for Slack and Github training](https://make.wordpress.org/marketing/handbook/getting-involved/new-contributor-orientation/)
  - May benefit from also linking to contributor training: https://wordpress.org/contributor-training/
  - We may need to start a new outline for training new contributors specific to marketing. This could pick up from the end point of the Learn contributor training and cover only the unique aspects of the Marketing team.
- Create: Amplification/promotion request template
  - Possible github issue template? Would need to include link/mission to help people understand what the marketing team can support.
- Create: Guide for WordCamp teams interacting with Marketing for contributor days or other asks
- Update: [Surveys handbook page](https://make.wordpress.org/marketing/handbook/resources/surveys/)
- https://github.com/WordPress/Marketing-Team/issues/47
- Update: [Style Guide and Brand Book handbook page](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/)
- https://github.com/WordPress/Marketing-Team/issues/39
- https://github.com/WordPress/Marketing-Team/issues/54 ([history](https://wordpress.slack.com/archives/C0GKJ7TFA/p1650634391141929?thread_ts=1650633295.379699&cid=C0GKJ7TFA))
- https://github.com/WordPress/Marketing-Team/issues/35

If you would like to join in, contribute, or share a request, please comment on this issue. Whatever doesn't get done in this sprint will get revisited next month.

**Comment by thetinyl** [comment]
New contributor here! I'd like to help out this doc sprint. 👍

**Comment by eidolonnight** [comment]
Added https://make.wordpress.org/marketing/handbook/getting-involved/coffee-breaks/ to the handbook.

**Comment by eidolonnight** [comment]
This sprint is complete and items have been updated. May's sprint will carry on in https://github.com/WordPress/Marketing-Team/issues/63

**Comment by nalininsbs** [comment]
Confirmed coffee break is scheduled for 40 mins and not one hour. References to coffee break one hour/ coffee hour to be updated, and in handbook.
