### ISSUE TITLE
2022/05/11 Global Marketing Team Meeting & week's planning

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#62]
All things related to this meeting and any collaboration, including:

- planning
- suggestions for items and agenda drafting
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources

**Useful cross-links:**
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)
https://github.com/WordPress/Marketing-Team/issues/23

[Coffee breaks rota](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by murillol** [comment]
We have a similar card already open here: https://github.com/WordPress/Marketing-Team/issues/60 - should we merge? @nalininsbs

**Comment by nalininsbs** [comment]
[Agenda preview](https://make.wordpress.org/marketing/?p=9192&preview=1&_ppp=ac39f5367f) 

Social question: Share what smell do you find the most soothing or relaxing, and why?

**Comment by murillol** [comment]
- Reminder that @eidolonnight will likely be unable to attend this week's meeting live, and we shouldn't expect any of the other Automattic folks next either (i.e. no updates from [@jpantani](https://wordpress.slack.com/team/U02E9BE1J6P), [@Reyes Martínez](https://wordpress.slack.com/team/U4QJBN9BK), [@Brett McSherry](https://wordpress.slack.com/team/U02U9S93BDE), [@Dan Soschin](https://wordpress.slack.com/team/U01UNQ7MMCZ), etc.)

- @eidolonnight added a GitHub link to the main menu of our Make site, titled “Tasks”
- @eidolonnight has unstuck the sticky post box on the P2, because many of the links were quite old, already covered in the Welcome box and/or handbook or weren’t particularly helpful. He thinks that a visitor is much more likely to see the latest post and hopefully engage.

**Comment by murillol** [comment]
**Agenda**

1. Welcome to the team and visitors
2. Getting to know each other
    a. Who is with us today – contributors attending live and asynchronously
    b. Social question of the week
3. Notes from May 4, 2022
    a. Volunteer call for notetakers and for our bi-weekly [coffee break](https://github.com/WordPress/Marketing-Team/issues/23)
4. Projects and Task Updates
    a. GitHub links
    b. Forthcoming WordPress releases and FSE
    c. Newsletters, Campaigns and events updates
    d. Contibutor Events update 
5. Diary/Calendar Dates
    a. Next week’s meeting and planning  
    b. Follow this Google [Calendar with meetings, collaborations, and social activities](https://calendar.google.com/calendar/b/2?cid=NDQyN2g1cnZrN2EwYXA5Y3VpNDI5OGYzY3NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ).
    c. We also list important dates in this [Forthcoming Diary Dates](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) post.
    Open Floor

**Comment by murillol** [comment]
@abhansnuk and @megphillips91 [were working on a photo guide](https://wordpress.slack.com/archives/C0GKJ7TFA/p1651677130553099) for People of WordPress and adding photos for the next editions to GitHub in order to help photo editors get started. Do we have an update on this?

**Comment by abhansnuk** [comment]
The photos have not arrived in as yet, follow-ups have been sent. We will look at the guide again in two weeks. Thanks @murillol

**Comment by murillol** [comment]
I've looked at [the draft notes](https://wordpress.slack.com/archives/C0GKJ7TFA/p1652283407598979) from Brett and have made the following edits:

- Changed Slack IDs to WordPress IDs
- Removed hyperlinks from WordPress IDs
- Updated link to Agenda (it was pointing to the May 4 agenda)
- Updated link to Social Question of the week Slack thread it was pointing to the May 4 question)
- item 4b: I've left it as-is, but I didn't understand what this meant "..everyone who has contributed to the About Page, **and to the type of information this page has from previous releases**. that last bit is unclear
- Added the link to the Slack thread for each item on the Agenda
- Added bullet points to updates that were long

I hope I didn't miss anything, would appreciate another pair of eyes @nalininsbs if you have the time, thanks!

**Comment by nalininsbs** [comment]
Adding published link so we can close this card. https://make.wordpress.org/marketing/2022/05/18/notes-global-marketing-meeting-11-may-2022/ 
Thank you
