### ISSUE TITLE
Documentation Sprint: Wednesday 25 May 2022

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#63]
Once a month, I spend a day focused on writing and documentation. For this sprint, I'm I'll be looking at the following items:

- Update: [resource links for Slack and Github training](https://make.wordpress.org/marketing/handbook/getting-involved/new-contributor-orientation/)
  - May benefit from also linking to contributor training: https://wordpress.org/contributor-training/
  - We may need to start a new outline for training new contributors specific to marketing. This could pick up from the end point of the Learn contributor training and cover only the unique aspects of the Marketing team.
- Create: Amplification/promotion request template
  - Possible github issue template? Would need to include link/mission to help people understand what the marketing team can support.
- Create: Guide for WordCamp teams interacting with Marketing for contributor days or other asks
- Update: [Surveys handbook page](https://make.wordpress.org/marketing/handbook/resources/surveys/)
- https://github.com/WordPress/Marketing-Team/issues/47
- Update: [Style Guide and Brand Book handbook page](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/)
- https://github.com/WordPress/Marketing-Team/issues/39
- https://github.com/WordPress/Marketing-Team/issues/54 ([history](https://wordpress.slack.com/archives/C0GKJ7TFA/p1650634391141929?thread_ts=1650633295.379699&cid=C0GKJ7TFA))
- https://github.com/WordPress/Marketing-Team/issues/35
- https://github.com/WordPress/Marketing-Team/issues/46

If you would like to join in, contribute, or share a request, please comment on this issue. Whatever doesn't get done in this sprint will get revisited next month.

**Comment by santanainniss** [comment]
@eidolonnight Looking at the amplification template line item above, must this be in GitHub? Or would a Google form template work? @yvettesonneveld, Reyes and I are discussing this for the Yoast contributor day as a good issue!

**Comment by yvettesonneveld** [comment]
@eidolonnight We're also looking at starting an outline for training for new marketing contributors
How would you like to get input for this? We're chatting about getting new contributors to follow the current training and getting their remaining questions, for instance. Any other thoughts?

**Comment by eidolonnight** [comment]
> @eidolonnight Looking at the amplification template line item above, must this be in GitHub? Or would a Google form template work? @yvettesonneveld, Reyes and I are discussing this for the Yoast contributor day as a good issue!

If we can pipe the form input to a github issue, that'd be great!

**Comment by eidolonnight** [comment]
> @eidolonnight We're also looking at starting an outline for training for new marketing contributors
How would you like to get input for this? We're chatting about getting new contributors to follow the current training and getting their remaining questions, for instance. Any other thoughts?

@yvettesonneveld I heard that the Training team is working on general contributor training too, so IMO we should sync up with them before creating any of our own training. Our training can then be specific to the Marketing team rather than covering the universal basics of Slack, Make blogs, etc.

If we do that, then I think the first thing to do would be to fire up a dedicated github issue and start outlining the training?

**Comment by rmartinezduque** [comment]
> Create: Amplification/promotion request template
Possible github issue template? Would need to include link/mission to help people understand what the marketing team can support.

@eidolonnight I'm not sure if it will be very complicated to implement, but [an issue form](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) could also work for the amplification/promotion requests. Here's an [example](https://github.com/WordPress/openverse-catalog/issues/new?assignees=&labels=%F0%9F%9A%A6+status%3A+awaiting+triage%2C%F0%9F%A7%B9+status%3A+ticket+work+required%2C%E2%98%81%EF%B8%8F+provider%3A+any&template=new_source_suggestion.yml&title=%3CSource+name+here%3E) of a template that Openverse has for suggesting new sources:
![openverse-example-template](https://user-images.githubusercontent.com/20700757/169120829-e85fa480-63ea-468f-b12a-eaf528c56daa.png).

**Comment by nalininsbs** [comment]
Is there a time for this sprint?

**Comment by abhansnuk** [comment]
I am not available after the meeting today. I have added comments and summary of the work that is going on the glossary (and linked to work between docs and Learn WP during 6.0) and related contributor materials coming together on Learn WordPress https://github.com/WordPress/Marketing-Team/issues/39

**Comment by abhansnuk** [comment]
Hello. It is because the card is not assigned to a board. I will add this for you and add a documentation label. 

@eidolonnight when you add a card in the repo, you also have to allocate it to a board. In this case the 'Marketing Tasks board'. You can do this under 'projects'. This will then appear on the board and you can either move it along the columns for progression or it can auto move, for example, when you mark an item with a different status or you close an issue, it will go into 'done'.

**Comment by abhansnuk** [comment]
I have added updates and reviews to as many cards as I could for now. 

I have created a new column for where items need to be available until they physically migrate to another team's GitHub so that it is clearer. Need to get back to work. Have fun in the rest of the sprint.

@murillol - for awareness on the extra column and the note above about the task board. Hope they help.

**Comment by murillol** [comment]
Thanks @abhansnuk , I was creating cards but not adding them to the task board - I will do that from now on. 
Just saw the extra column, it definitely helps keep track.

**Comment by eidolonnight** [comment]
## Recap

- https://make.wordpress.org/marketing/handbook/getting-involved/new-contributor-orientation/ has been updated to fix links, add intros, and add github training links. Removing from the sprint list. We'll want to revisit after Training team has released more contributor training resources sometime after WCEU.
- https://github.com/orgs/WordPress/teams/marketing/ now has the team description and wapuu.
- Added several regular contributors to the GitHub Marketing team.
- Reviewed Showcase process and documentation.
