### ISSUE TITLE
WordCamp Europe 2022 Marketing Table - Contributor Day 

### ISSUE THREAD

**Issue by jpantani** [WordPress/Marketing-Team#64]
During contributor day in WCEU we will have a table dedicated to solving marketing tickets.

This is an open call for brainstorming ideas that can be used to help generate contributor interest in marketing for WordPress. 

Table lead Jonathan Pantani
Participants: TBA

Ideas for problems to solve: TBD

**Comment by jpantani** [comment]
It would be wonderful to get an idea of who might attend as well.

**Comment by murillol** [comment]
@yvettesonneveld [indicated she'd like to participate](https://github.com/WordPress/Marketing-Team/issues/60#issuecomment-1116269866), so adding here here :)

**Comment by nalininsbs** [comment]
Updated card to include event and year, triaged and added to board. Call to be promoted at Marketing Meeting 4 May 2022. Thank you @jpantani for the update and moving this forward.

**Comment by majadidit** [comment]
If you think it would help, I could give a table in our booth to Marketing team throughout the conference, so if people would like to contribute more, or ask questions on Non-contributor days - that would be ok! :)

**Comment by nalininsbs** [comment]
@jpantani and @yvettesonneveld could you please add an update from WCEU and any links to items to this card, Thank you.

**Comment by nalininsbs** [comment]
Update on this card to be done:
- summary and links to any documents used at the event by marketing
- learnings to note to document for next year
- any other comments from attendees

To note for progress at 20 July 2022 meeting #86

**Comment by jpantani** [comment]
@yvettesonneveld and @jpantani worked to organize the Contributor Day Marketing tables at WCEU 2022 Porto. We were helped also by @santanainniss in facilitating the days events. 
All three tables were completely full which was a great success metric. 
Yvette and Jonathan were able to address the crowd twice and make a pitch for contributors as well as asking all attendees to be mini marketers by liking, following, subscribing, and/or sharing the official WordPress accounts on Social media.
Activities for the day were set up and linked to this [WCEU Contributor Day 2022 document](https://docs.google.com/document/d/1dW599URWAO7BlhWHZnjYtua1uMIkrl0tRRYACChC518/edit#heading=h.6umm4mwj62mf)
Contributors were a wide range of folks from business owners to agency workers and more who are eager to promote the many features they believe helps WordPress make their lives easier and/or more fun. ([Survey results](https://docs.google.com/forms/d/17uKtay1N8sbh8-n6vxh2CoCCJZAM_toP3GYtmwpAaEY/edit?ts=628b5d40#responses))
We gained a few replies to the Grow Your Story Survey as well as a few ideas for the showcase. 
All in all, it was a long but very productive and a great way to kick off the conference.

**Comment by nalininsbs** [comment]
Thank you @jpantani and for adding the document used on the day and your update. 

Can I suggest for any confirmed docs/ activities for WCUS to be shared on its GitHub card before the event too to help contributors who would like to or need to read things in advance?
@yvettesonneveld do you have anything further to add?

Are there any learnings / actions for next time that can be listed and shared so that this can be seen by all the team and may get some additional suggestions?

Do we have a list of contributors who took part in marketing that can be listed in this card? Can you please add them as a reply to this message @jpantani and @yvettesonneveld. 

I have pulled together the list of those who helped with information and support before the event and those who took part in cross-working across teams during the event, and will add those to this card. 

I will then combine all the names of those who took part in various ways as a props list on the card before closing this card. Thank you.

**Comment by jpantani** [comment]
I don't have immediate access to the list of participants from WCEU though I have searched. 
@yvettesonneveld, @santanainniss, and I have performed a follow-up debrief with considerations for future contributor day marketing tables. 
That information can be found [here in this Google doc].(https://docs.google.com/document/d/1t4-Ny1LEVWk4m3Bs2BDVhDUEMQvL406xueoaSiEMwb4/edit?usp=sharing)

**Comment by jpantani** [comment]
The Make Blog pointed to this [page for new contributors](https://make.wordpress.org/marketing/handbook/getting-involved/marketing-team-at-contributor-events/) 
We used this [page](https://docs.google.com/document/d/1dW599URWAO7BlhWHZnjYtua1uMIkrl0tRRYACChC518/edit#) to collect all the tasks and questions in one easy to navigate to place. 

Here were some of the new contributors (WordPress IDs):
Nikolay Karaboychev
Santanainniss
bampova
Brittagrunwald
aslugic
lidiaapostol
dannid23
Hideandgeek404
0livera
meriemc

**Comment by abhansnuk** [comment]
Closing this card for now, but feel free to open it again to add thanks to any other contributors who joined you. Thanks for all the updates and efforts.
