### ISSUE TITLE
List of GitHub how to /screenshots to create

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#68]
Adding these in a card temporarily as the wiki area was not accessible to some contributors.

**Comment by abhansnuk** [comment]
**Task:** Create instructions for the wiki on how to filter and use the meeting-notes label as an example. 


_Request from @nalininsbs copied over from another card 14 days ago:_
New meetings-notes label created (thanks to idea from Nicholas)

@abhansnuk: Tests completed: It does not seem to affect the milestones or search by milestone date. Was there anything else you wanted to test?

@nalininsbs
Thank you for testing that so we can share this in the meeting. @abhansnuk If someone goes to the label meetings-notes, will it still show them if an item relates to this area and has been closed? Will they be able to easily see which cards are open when filtering by meetings-notes? Ideal would be to have the meetings to come to appear at the top. From what I understand of your screenshare, this may need the titles to be listed in a different way?

**To do:** Screenshots and how to information on filtering and using this as an example would be useful.

**Comment by sereedmedia** [comment]
This issue of How-To for GitHub contribution is being discussed on a newer ticket here: https://github.com/WordPress/Marketing-Team/issues/167.  I am closing this ticket in lieu of that one.
