### ISSUE TITLE
Documentation Sprint: Friday 24 June 2022

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#71]
Once a month, I spend a day focused on writing and documentation. For this sprint, I'm I'll be looking at the following items:

- Create: Amplification/promotion request template
  - Possible github issue template? Would need to include link/mission to help people understand what the marketing team can support.
  - Recommendation by @rmartinezduque https://github.com/WordPress/Marketing-Team/issues/63#issuecomment-1130380074
- Create: Guide for WordCamp teams interacting with Marketing for contributor days or other asks
- Update: [Surveys handbook page](https://make.wordpress.org/marketing/handbook/resources/surveys/)
- https://github.com/WordPress/Marketing-Team/issues/47
- Update: [Style Guide and Brand Book handbook page](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/)
- https://github.com/WordPress/Marketing-Team/issues/39
- https://github.com/WordPress/Marketing-Team/issues/54 ([history](https://wordpress.slack.com/archives/C0GKJ7TFA/p1650634391141929?thread_ts=1650633295.379699&cid=C0GKJ7TFA))
- https://github.com/WordPress/Marketing-Team/issues/35
- https://github.com/WordPress/Marketing-Team/issues/46

If you would like to join in, contribute, or share a request, please comment on this issue. Whatever doesn't get done in this sprint will get revisited next month.

**Comment by nalininsbs** [comment]
On #35 this has no work for marketing. It is open and in column for transfer to LearnWP. Once done, ticket will be closed in marketing.

**Comment by nalininsbs** [comment]
On #46 this ticket needs updating if it is still being used for WordPressEvents social and Marketing Team LinkedIn. Assigning this to @murillol . If still usable, can the notes be put on a handbook page Larissa? Thank you

**Comment by nalininsbs** [comment]
I have updated and reviewed a number of cards. New cards created for items requiring from this week. Actions added for a couple of cards.

**Comment by nalininsbs** [comment]
@eidolonnight could you please add your update on items you were looking at to this card and close it when you are ready? Thank you.

**Comment by sereedmedia** [comment]
Hi all! Is this issue complete? @eidolonnight @nalininsbs

**Comment by abhansnuk** [comment]
Hello. Going back into the links on this, it seems to be just waiting for the closing update on what had happened in the sprint.

**Comment by sereedmedia** [comment]
The Social Media Amplification request card was created out of this issue/sprint: https://github.com/WordPress/Marketing-Team/issues/7.

I'm going to close this card, as it indicated all undone items will be done in subsequent months. @eidolonnight if it needs further action, please reopen as you see fit!
