### ISSUE TITLE
Polyglots Team newsletter June 2022 - marketing input

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#78]
Link from @nao shared at Marketing Meeting June 22, 2022 https://docs.google.com/document/d/1h8UYOz0gDjs-kfxtBDz_e55AEIq4px4UObb84B7HdWI/edit#

**Comment by naokomc** [comment]
Thanks for help @abhansnuk @ellatrix !
Published two versions:
P2 https://make.wordpress.org/polyglots/2022/06/27/polyglots-monthly-newsletter-june-2022/
Email https://mailchi.mp/wordcamp/wordpress-60-translated-to-65-locales-13653860
