### ISSUE TITLE
WordPress Photo Directory Social Media Campaign - #WPPhotos 

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#80]
**For those interested in the Photo Directory social campaign.**

Example of an update highlighted at the Marketing meeting on June 23, 2022 (https://wordpress.slack.com/archives/C0337A01LHW/p1655471947189519) in the [#photos](https://wordpress.slack.com/archives/C0337A01LHW) channel.

The WordPress Photo Directory reached the 3,000 photos milestone. Examples of social media relating to it:

- [Twitter](https://twitter.com/WordPress/status/1539330572786585605)
- [Facebook](https://www.facebook.com/WordPress/photos/a.10158758550782911/10159945892772911/)
- [Linkedin](https://www.linkedin.com/posts/wordpress_wordpress-wpphotos-activity-6945096263604314112-ntsv/)
- [Instagram](https://www.instagram.com/p/CfFEXbCsWRr/)
- [Pinterest](https://www.pinterest.com/pin/1023865296508934268/)

Update from @rmartinezduque June 17, 2022:

- For the following weeks, I was thinking of continuing to share some posts similar to the ones already posted (photo stories, posts with numerous photos with calls to contribute, etc). However, this is open to any other content suggestions or ideas. If anyone wants to contribute drafts for social posts or collaborate by sharing a story behind any of their photos, please feel free to reach out. Any help is welcome.
- In April and May, 45 social posts were published as part of the #WPPhotos campaign. These were shared across different WordPress social platforms ([Twitter](https://twitter.com/WordPress/), [Facebook](https://www.facebook.com/WordPress/), [Linkedin](https://www.linkedin.com/company/wordpress/), [Instagram](https://www.instagram.com/wordpress/) and [Pinterest](https://www.pinterest.com/WordPress/photo-directory/)). These are 5 top-performing posts from that period of time:

  - https://linkedin.com/feed/update/urn:li:activity:6930499607588167680
  - https://twitter.com/WordPress/status/1528137061114552321
  - https://twitter.com/WordPress/status/1512759232420102147
  - https://twitter.com/WordPress/status/1517542249650864130
  - https://twitter.com/WordPress/status/1514749101769908225

**Comment by rmartinezduque** [comment]
These are some examples of photo stories shared on social as part of the #WPPhotos campaign:

- https://twitter.com/WordPress/status/1512759232420102147
- https://twitter.com/WordPress/status/1517542249650864130
- https://twitter.com/WordPress/status/1521516443023593472
- https://twitter.com/WordPress/status/1529802289493561346

If anyone is interested in sharing a story behind any of their contributed photos, please feel free to reach out in the [#marketing](https://wordpress.slack.com/archives/C0GKJ7TFA) or the [#photos](https://wordpress.slack.com/archives/C0337A01LHW) channel of the Make WordPress Slack.

**Comment by rmartinezduque** [comment]
### Upcoming Photo Directory Challenge to celebrate World Photography Day (August 19)

Following some conversations in the [#photos](https://wordpress.slack.com/archives/C0337A01LHW) channel about a photo challenge, we will be inviting the WordPress community and photography enthusiasts to contribute to the WordPress Photo Directory on the occasion of World Photography Day (August 19). This can be a great opportunity to celebrate the project and grow the directory's image collection.

We are thinking about a geography-based theme challenge. E.g. photos of the contributors’ city, state, country… that represent the geographic diversity of the WordPress community and make the photographer's home area unique.

We will use the [Make Photos blog](https://make.wordpress.org/photos/) to announce the initiative with more information about the theme, brief instructions/steps to participate, and some ideas/examples, and the [WordPress.org](http://wordpress.org/) social media accounts to help spread the word about the photo challenge. More details can be found on this [proposal document](https://docs.google.com/document/d/17J2n5PnVo3cTbblCjBUmaXoOs2H6SWPZqOc7ehfdvqs/edit#).

All and any help to help spread the word and promote the photo challenge will be welcome. I'll share updates in the [Slack Photos channel](https://wordpress.slack.com/archives/C0337A01LHW) and update this GitHub card accordingly.

**Comment by rmartinezduque** [comment]
## Update on the WordPress World Photography Day Challenge (August 19)

The draft for the Make Photos announcement is currently under review and open to suggestions: https://docs.google.com/document/d/1eQ8Q00dV_QoxO8se4kndxLsZkwRWsDlxrn6LEXuM4DA/edit#.

**Please note**: we are looking for feedback especially to improve/proofread the copy and/or regarding any relevant information that is important to include and that we may have missed.

**Deadline**: we're hoping to gather feedback by August 16 so that we can publish it on Thursday (August 18).**

**Comment by abhansnuk** [comment]
Thanks @rmartinezduque . I have shared some feedback and suggestions on the document. Such a good initiative. Really looking forward to the results.

**Comment by rmartinezduque** [comment]
Thank you @abhansnuk and @thetinyl for your valuable feedback on the draft of the Make Photos post.

**Update**: Feedback has been incorporated into the draft, which is now under final review prior to publication. It aims to be posted tomorrow, August 18, on the Make Photos blog.

I'll share some suggestions for social media posts soon as well for review and feedback.

**Comment by rmartinezduque** [comment]
**Update**: I drafted some social posts for the #WorldPhotographyDay challenge in [this document](https://docs.google.com/document/d/1CnJnfKP3VWdnD939XX1ib3wQFEA2JgHSM4SJkkDDnII/edit#). I passed them along to the Photos team for review.

I'll share links to the blog post and social media posts when they are published so we can help spread the word.

**Comment by rmartinezduque** [comment]
**Update**: **[The WordPress World Photography Day Challenge is officially live](https://make.wordpress.org/photos/2022/08/18/wordpress-world-photography-day-challenge-2022/)**! 🎉 

Please help us spread the word amongst other Make teams, WordPress contributors, and friends!

**Comment by rmartinezduque** [comment]
**Update**: Some social posts about the WP Photo Directory post are out. Others will follow shortly:

- [Twitter](https://twitter.com/WordPress/status/1560652578882408448)
- [Instagram](https://www.instagram.com/p/ChcoN8UuxY-/)

We'd love to get some help amplifying them! Thank you!

**Comment by rmartinezduque** [comment]
**Update** - Another round of social posts about the photo challenge is out:

- [Twitter](https://twitter.com/WordPress/status/1562104923227136000)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid027t4C2h7a3CAyFHhDFnNWC3QCTt9aYfz4TEdD3ZqYGPK9tNq1PpNtY1Lkdfxey88jl)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_worldphotographyday-wordpress-wpphotos-activity-6967885951922561024-QGnz/)
- [Instagram](https://www.instagram.com/p/Chm5imWlniP/)
- [Pinterest](https://www.pinterest.com/pin/1023865296509975342/)

**Comment by amitpatel0702** [comment]
Hi @rmartinezduque,

I must say all these social posts deserve even more reach. Amazing photos i must say :)

**Comment by nalininsbs** [comment]
These have been very good social posts. Well done @rmartinezduque and everyone involved. We will continue to promote! Is there a stop point for this deadline? They are wonderful photos @amitpatel0702. Welcome to the Marketing Team GitHub too.

**Comment by rmartinezduque** [comment]
Thanks, @amitpatel0702, @nalininsbs. These are indeed wonderful photos! People can join the photo challenge up to and including Sunday, August 28, 2022. So until then, it's okay to keep promoting it! Tomorrow there will be another social post as a friendly reminder. Let me know if you have any other questions. Thank you for all your help!

**Comment by rmartinezduque** [comment]
**Update**: a few social posts were shared to announce that the challenge is now closed. However, everyone is encouraged to keep contributing to the Photo Directory. 🙂

- [Twitter](https://twitter.com/WordPress/status/1564591280881025025)
- [Facebook](https://www.facebook.com/WordPress/photos/a.10158758550782911/10160064766982911/)
- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6970360743883931648/)
- [Instagram](https://www.instagram.com/p/Ch462YZMCMb/)
- [Pinterest](https://www.pinterest.com/pin/1023865296510082700/)

Photos from the contest will also continue to be featured on WordPress.org's social platforms.

A high number of photos have been submitted and there are still quite a few in the moderation queue. The World Photography Day collection will grow as they are approved. In the meantime, you can enjoy the challenge submissions that have already been approved at https://wordpress.org/photos/t/worldphotographyday22/. Thanks!

**Comment by rmartinezduque** [comment]
**Update**:

I was able to recently collect some data about the World Photography Day challenge:

- The Photos team approved **100 submissions from 47 contributors**, of which 29 were first-timers.
- **25 countries** were represented in the photo contributions.

Thanks to all of you who participated and helped make this initiative possible. ❤️

In addition, I would like to try a new format (probably a short questionnaire) to help gather photo stories from contributors. I'll share more information in this GitHub issue (or a new one) soon.

**Comment by sereedmedia** [comment]
Following as I'd like to help with copy for prompts to encourage folks to add context. I think it makes for great social content, and great human content in the archive. Love it.

**Comment by rmartinezduque** [comment]
I took some inspiration from the @thetinyl's [TT3 "Behind the Scenes" Questionnaire](https://github.com/WordPress/Marketing-Team/issues/128) (thanks, Lauren!) and drafted [this brief questionnaire](https://docs.google.com/forms/d/e/1FAIpQLScM_Pm3atx-PNSVOrf9ko0-_lKmEjzJ3eR0hcNUCH6wO2Tt9Q/viewform?usp=sf_link) to help gather some photo stories. Before circulating it, I'd love to get some feedback. @sereedmedia let me know if you'd like to review it. Thanks!

**Comment by rmartinezduque** [comment]
**Update**:

Some social posts were posted to celebrate the 5,000 photo milestone of the Photo Directory, which performed very well:

- [Twitter](https://twitter.com/WordPress/status/1594378823138541568)
- [Facebook](https://www.facebook.com/WordPress/photos/a.10158758550782911/10160294050227911/)
- [Linkedin](https://www.linkedin.com/posts/wordpress_wordpress-wpphotos-activity-7000112782603907072-CU2E/)
- [Instagram](https://www.instagram.com/p/ClL80ivuHTr/)
- [Pinterest](https://www.pinterest.com/pin/1023865296511549664/)

Today (November 30) and the next week, we will be posting some more social posts to encourage people to contribute photos of their holidays, festivities, and traditions. I'll update this comment when the posts go out. :)

- Twitter
- Facebook
- Linkedin
- [Instagram](https://www.instagram.com/p/CllsWIptzjX/)
- [Pinterest](https://www.pinterest.com/pin/1023865296511730246/)

**Comment by rmartinezduque** [comment]
Hello @mumtahinafaguni! That's great to hear. 🙂 I'm currently working on some documentation/steps to help contribute content and gather photo stories for this campaign. I'll connect with you soon!

**Comment by rmartinezduque** [comment]
I'm closing this card in favor of https://github.com/WordPress/Marketing-Team/issues/178.
