### ISSUE TITLE
Discussion: Social media promotion of WordCamps on WordPress.org social accounts

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#81]
Perhaps for reference only and link to post for comments.
https://make.wordpress.org/marketing/2022/06/17/discussion-promoting-wordcamps-with-the-official-wordpress-social-accounts/

Before ticket closed, add:
- link to decision or follow up post
- any handbook reference on WordPress logos of relevance
- links to WordCamp schedules

**Comment by nalininsbs** [comment]
@eidolonnight is there an outcome of this discussion please? Thank you.

Added to check in list for [August 17, 2022 meeting](https://github.com/WordPress/Marketing-Team/issues/97)

**Comment by eidolonnight** [comment]
This campaign is underway with @Brett McSherry acting as point-of-contact. This is listed in https://github.com/WordPress/Marketing-Team/issues/7

> Any handbook reference on WordPress logos of relevance?

No. No need. WordCamp content will be re-shared and therefore include links to their primary accounts (which will include branding).

> Links to WordCamp schedules?

Scheduled camps are always available on https://central.wordcamp.org/.
