### ISSUE TITLE
The Month in WordPress: July 2022 Edition

### ISSUE THREAD

**Issue by rmartinezduque** [WordPress/Marketing-Team#84]
The expected publication date for the July 2022 edition of The Month in WordPress is **Friday, August 5, 2022**.

### How can you help?

If you have any news or Make team updates that would be valuable and relevant to the post, please feel free to **add them as a comment to this GitHub card**, or share them on the Make Marketing Slack channel and tag `Reyes Martínez` for awareness by Tuesday - August 2, 2022, if possible.

The draft will be added to this card and shared in the Marketing channel prior to publication for review. Your input will be appreciated, too.

### Additional background

The Month in WordPress is a monthly roundup of all the major WordPress news and Make team updates that is usually published by the 5th of each month at WordPress.org/News. It features news from the previous month to publication. To see what's typically featured, please check out any of the [latest editions](https://wordpress.org/news/category/month-in-wordpress/).

**Comment by chaion07** [comment]
Would love to contribute to the July 2022 edition. Thank you for creating this.

**Comment by rmartinezduque** [comment]
@chaion07 Thank you! I'll make sure to keep you in the loop when the draft is ready for input and review. In the meantime, if you think there is a Make team update, testing/feedback calls, etc that would be good to include, please feel free to add them to this GitHub card!

**Comment by rmartinezduque** [comment]
Here are some initial updates that might be worth highlighting in the next edition:

- [WordPress 6.0.1 is now available for download](https://wordpress.org/news/2022/07/wordpress-6-0-1-maintenance-release/)
- [Homepage and Download Page Redesign Project](https://make.wordpress.org/design/2022/07/08/project-kickoff-wordpress-org-homepage-and-download-page-redesign/)
- The Community Team is [looking for supporters](https://make.wordpress.org/community/2022/07/08/call-for-supporters-reactivating-wordpress-meetups-around-the-world/) to help reactivate WordPress meetups around the world
- [What’s new on LearnWP in July 2022](https://make.wordpress.org/updates/2022/07/15/whats-new-on-learnwp-in-july-2022/)

**Comment by rmartinezduque** [comment]
👋 Hello! The draft for the July 2022 edition of The Month in WordPress is ready for review: https://docs.google.com/document/d/18Z80FORqCi-ncTyXg8xOKbNE41xWYggQkyuEyiSYK4A/edit#.

I'm hoping to publish it on **Friday, August 5, 2022,** around 12:00 PM UTC. If there are any other major updates that you would like to see featured, please let me know by then. Thank you!

**Comment by chaion07** [comment]
I have added a few comments as well as made some adjustments to the working document. Thank you @rmartinezduque 🚀

**Comment by rmartinezduque** [comment]
The draft is now ready to publish. Thank you [@chaion07](https://profiles.wordpress.org/chaion07/), [@laurlittle](https://profiles.wordpress.org/laurlittle/), [@mysweetcate](https://profiles.wordpress.org/mysweetcate/), [@sereedmedia](https://profiles.wordpress.org/sereedmedia/), and [@dansoschin](https://profiles.wordpress.org/dansoschin/) for helping to review it and provide suggestions.

**Comment by chaion07** [comment]
Excellent work by @rmartinezduque 
It has been super easy collaborating with you as well as others for the July edition of Month in WordPress. I would love to continue to contribute to the future editions if possible. Thank you much for everything that you do 🚀👏👏

**Comment by rmartinezduque** [comment]
That's great to hear, @chaion07. Your help is much appreciated! I'll open a new GitHub card for the next edition so that you can follow it.

**Comment by rmartinezduque** [comment]
The **July 2022 edition of The Month in WordPress** is now live: https://wordpress.org/news/2022/08/the-month-in-wordpress-july-2022/! 🚀 

If you'd like to collaborate on the next edition, please feel free to follow and subscribe to this GitHub card: https://github.com/WordPress/Marketing-Team/issues/102.
