### ISSUE TITLE
Call for contributions or nominations: Word Wide Web Celebration on WP Briefing Podcast

### ISSUE THREAD

**Issue by santanainniss** [WordPress/Marketing-Team#85]
World Wide Web Day is August 1, 2022. It is a global celebration dedicated to web browsing and the inventor behind it, Tim Berners-Lee. The world wide web revolutionized connection and information sharing, making the world smaller and larger simultaneously. The WordPress mission and community also make the world smaller and larger at the same time! We seek to observe WWW Day 2022 with a dedicated WP Briefing podcast episode featuring voices from contributors around the world sharing their experiences with the WordPress community.

This is an open call for contribution or nomination.

The WP Briefing podcast is looking for 6-8 contributors of diverse backgrounds, experiences w/ WordPress, and geographies to participate in a brief interview via Zoom, Squdcast or similar web-based platform on their experiences with WordPress. The interviews will us audio only (not video) and will be featured on the podcast.

Interview theme: Celebrating World Wide Web Day-- WordPress Around the World. What impact has WordPress had in _your_ world?

The interviews will take place between July 21-26 (excluding weekend days) and will last 15-30 minutes. 

**Please reply to this card or via Slack DM if you'd like to participate or nominate a contributor for participation.** 

The call for contributions will CLOSE on July 15, 2022 by end of day UTC+1. Selections will be made July 18-19.

**Comment by MGParisi** [comment]
I'll contribute can you provide a reference to my website and/or a backlink?

**Comment by amitpatel0702** [comment]
I am ready to contribute as well.

**Comment by chaion07** [comment]
Happy to be a part of the global effort. Please let me know how I can help by contributing. Thank you for everything you do towards the WordPress ecosystem.

**Comment by marybaum** [comment]
Happy to represent the over-60 crowd, if that counts! I'm also based in the Midwestern US, usually known as The Great Flyover.

**Comment by ChrisEdwardsCE** [comment]
Happy to contribute to this.

**Comment by awarner20** [comment]
Would love to contribute.

**Comment by alisorru** [comment]
Hi! I'd be happy to contribute :)

**Comment by getsource** [comment]
I would be happy to contribute if it's helpful!

**Comment by jillb** [comment]
I was privately nominated and I'd be happy to have my name on the potential nominations list

**Comment by santanainniss** [comment]
Thank you again to everyone that submitted their interest in participating in the World Wide Web Day WordPress Briefing podcast episode! We received over 20 responses from contributors in 13 countries! WOOHOO!

While I would love to feature each and every contributors that expressed interest, we only have space for 6-8 as noted above. We are in the process of reviewing the names to select a diverse and inclusive group across geographies to help celebrate the World part of World Wide Web :) 

I will reach out to those selected via Make Slack DM no later that end of day 19 July (EOD UTC) 

Thank you again!!!!!! 


I am now closing this GH Issue.
