### ISSUE TITLE
Big Picture Goals 2022 - Marketing Team input

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#91]
Putting on GitHub request for this. This has previously done in Google docs linked from the old Trello board and GitHub repos, and shared in meetings.

Request from @Bringmannn to the team reps, 18 July 2022
- to put together bullet points for Josepha and Chloe who are reviewing the [big picture goals ](https://make.wordpress.org/project/2022/01/21/big-picture-goals-2022/)shared in January 2022, gauging the progress made and where additional help may be needed.
- to consider: Are there wins from the Marketing team that you would like to share? Any blockers or areas that need additional support?

Deadline for submission: Friday 22 July 2022

**Comment by murillol** [comment]
@eidolonnight submitted the following: 
 
In the first half of 2022, the Marketing team has worked to improve and expedite our processes, including migrating our tasks to [GitHub](https://github.com/orgs/WordPress/projects/21), making a plethora of updates to [our handbook](https://make.wordpress.org/marketing/handbook/), and aiding other teams with marketing efforts. During this time, we’ve also grown our social media audience by over 23,000 followers with over 700 posts collaboratively written with several other Make teams. That includes campaigns focusing on the all new [Photo directory](https://wordpress.org/photos/), [Openverse](https://wordpress.org/openverse/), and [Learn](https://learn.wordpress.org/) tutorials.

**Comment by nalininsbs** [comment]
Has this been published already? If not, can we include a reference to People of WordPress and supporting other teams newsletters.

I also would recommend we add the word 'continue' in the Marketing team has continued to work to,,,' as a lot of this work started before 2022.

**Comment by murillol** [comment]
It has been already submitted, but the final post was more of an overview: https://make.wordpress.org/updates/2022/07/25/a-mid-year-year-look-at-2022-goals/

**Comment by sereedmedia** [comment]
This issue is completed.
