### ISSUE TITLE
Polyglots Team newsletter July 2022 - marketing input

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#95]
Input and review requested by Naoko 20 July 2022. [Slack link](https://wordpress.slack.com/archives/C0GKJ7TFA/p1658329992122449)

**Comment by nalininsbs** [comment]
Published links, thank you Naoko: [P2 post](https://make.wordpress.org/polyglots/2022/07/22/polyglots-monthly-newsletter-july-2022/) / [newsletter](https://mailchi.mp/wordcamp/july-2022)

**Comment by murillol** [comment]
Naoko's GitHub ID is @naokomc
