### ISSUE TITLE
2022 - Meetup Organizers Annual Surveys promotion

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#96]
July 26, 2022: Link to the discussion in the Marketing Slack https://wordpress.slack.com/archives/C0GKJ7TFA/p1658843841370289

Information shared by Julia Golomb, Community Team organizer: 

"Hello Marketing Team! The Annual Meetup survey will be ready to distribute within the next week. I would love to coordinate with Make Marketing to spread the word, in order to encourage as many meetup organizers and participants as possible to respond to the survey. Excitingly, this year the survey will be available in 14 different languages!

"There will be two different surveys, each available in 14 different languages:
Annual Meetup Program Survey (for all WP meetup participants)
Annual Meetup Organizer Survey (for all meetup organizers)"

Actions in marketing: 
- highlight for promotions in various newsletters and social media on WordPress.org, team LinkedIn etc
- add survey links to this card for promotion via anyone viewing it through the repo or GitHub search
- add deadline for surveys 
- promote in Marketing Team meetings for people to share social media posts and link to this card
- card to be marked as closed when deadlines for surveys
- useful if the results from the survey can later be added as a link to this card to help for future promotion ideas

**Comment by murillol** [comment]
Post is up: https://make.wordpress.org/community/2022/08/02/announcing-the-2021-2022-annual-meetup-survey/

**Comment by murillol** [comment]
Survey is now closed!
