### ISSUE TITLE
2022/8/17 Global Marketing Team meeting and planning

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#97]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)

[Coffee break rota](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by abhansnuk** [comment]
Thanks for the query in the marketing Slack @nalininsbs. I have added this card to the repo column you need.

**Comment by nalininsbs** [comment]
Check update on 4a list highlighted in 10 August card. https://github.com/WordPress/Marketing-Team/issues/98#issuecomment-1208623888

**Comment by nalininsbs** [comment]
Agenda [draft]( https://make.wordpress.org/marketing/?p=9704&preview=1&_ppp=dd81b6fbbc) on the P2 for August 17, 2022.
@abhansnuk and @marybaum thank you for your help in how to set these up ready in advance so they ca be updated in the relevant week.

**Comment by nalininsbs** [comment]
Agenda published for tomorrow's meeting https://make.wordpress.org/marketing/2022/08/09/agenda-global-marketing-team-meeting-august-10-2022/

**Comment by nalininsbs** [comment]
Posted in the [Slack channel](https://wordpress.slack.com/archives/C0GKJ7TFA/p1660633129949709) as a reminder for the meeting and check for any other agenda items. Copying in GitHub to make it quicker to share similar update weekly in Slack.

**Marketing Team meeting this week**
If you are new to the channel, we meet on Wednesdays at 15:00 UTC. All are welcome. 

This week after the meeting, there will be a collaboration on Slack about what the marketing table could do at WordCamp US's contributor day. You can recap last week's meeting by reading the notes on the team blog (ADD LINK).

This is the draft agenda (ADD LINK) which will be published in a few hours time to help contributors participate in the team. If anyone has any other items for it, please add to the GitHub card 97 (ADD LINK AND REVISE NUMBER) for this week's planning.

**Comment by nalininsbs** [comment]
Adding a list of GitHub cards I will bring to the meeting this week.

[WordPress Planet update request](https://github.com/WordPress/Marcomms-Rolling-tasks/issues/24) - check where this is and whether it needs to go back to another team.

**Comment by dugyen** [comment]
Could you please assign me for this task as notetaker @murillol

**Comment by nalininsbs** [comment]
@dugyen I can do this for you. I think there is a previous meeting card open with some follow-ups to change Slack IDs in one of the notes, would you be able to look at this please? Do you also have an update on your local translation card? Thank you Ugyen.

**Comment by abhansnuk** [comment]
Adding link to the published agenda for Nalini and Larissa https://make.wordpress.org/marketing/2022/08/16/agenda-global-marketing-team-meeting-august-17-2022/

**Comment by nalininsbs** [comment]
[Script document to help flow of the meeting](https://docs.google.com/document/d/1g3k_0R__WqSQQgQ7T-VEdgsvZRJmONXACApi0bXS0lk/edit?usp=sharing) thanks to @murillol

**Comment by rmartinezduque** [comment]
Hi @nalininsbs, @eidolonnight, @murillo, I just wanted to give you heads up that I won't be able to attend the meeting in a synchronous way today because it conflicts with another meeting. Sorry for the short notice (I just realized this morning). I will share the [photo challenge updates](https://github.com/WordPress/Marketing-Team/issues/80#issuecomment-1217920854) later today. Thanks!

**Comment by dugyen** [comment]
@murillol @nalininsbs Could you please review our draft note - https://make.wordpress.org/marketing/wp-admin/post.php?post=9749&action=edit

**Comment by nalininsbs** [comment]
@dugyen thank you for your draft. 

Can you please help us review your draft by checking some items before you submit it to GitHub. This will be of great assistance. Thank you Ugyen.
- check in preview once you have finished adding the notes to the blog to see if there are any Slack user IDs to be replaced with WordPress.org. I have changed the ones in this draft. It is a good way to check before sending the notes for review. You can also check some of the links by hovering on the link in the P2 draft itself.

- check where the links go including the Slack links. The links to the start of the meeting and agendas went to old meetings, and the social question. So it may not have saved the changes you had added. I have edited these. It can be difficult in Slack. We can all miss these. The preview can really help.

For information and future notes: We are no longer duplicating the link to the meeting at the beginning of the post and under the welcome. You now only need the one in Welcome. 

Main other changes:
- link to social question and question were from an older meeting. Updated both to last week's.
- meeting facilitators: amended
- moved WordPress design section out of releases (it had the wrong section in the meeting, correcting it for the notes)
For GitHub references, would you be able to check the H is capitalized in people's text you are copying. This helps screen readers to read it as a separate word and to match GH itself. 
- amended the reference to Reyes to Laura for the meeting team description discussion and added Slack link
- removed the reference to notes from a different meeting
- updated some links and added Photo blog post 

**Update for notetakers in general:**
To make it easier with lots of GitHub card links and to copy the style in other teams, we are adding a GitHub ticket number in the notes. Could you please start adding these as #GitHub ticket [add number], and link it to the card. We are checking with a core contributor on ways of displaying these cards most effectively. Then the handbook for notes will be updated.

- Tags to add to all notes posts: Marketing Team, Meeting notes

**Comment by nalininsbs** [comment]
Edit done. To be able to include this in the agenda for tomorrow, I have published the notes. https://make.wordpress.org/marketing/2022/08/23/notes-global-marketing-team-meeting-august-17-2022/
