### ISSUE TITLE
2022/8/10 Global Marketing Team meeting and week planning

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#98]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
- any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful** links:
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)

[Coffee break rota](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by rmartinezduque** [comment]
I'll be happy to take notes for this meeting (Aug 10)!

**Comment by nalininsbs** [comment]
For 4a agenda items on WordPress.org social accounts. 

Can we 
For item 4a on WordPress.org social accounts

Can we please add a sentence about the context of the people mentioned to help people coming new to the team and whether we are asking people to contact them or do anything. I have also standardized the references to teams in the list and amended those which are groups. Could we review this and then use this list in future? Thank you @eidolonnight and @murillol . Do we need to include them in the notes each week or these now static and could be in the handbook?

- WordPress Features/Release (#WordPress) - [@Lauren](https://wordpress.slack.com/team/U034VFXCXHB) and [@Dan Soschin](https://wordpress.slack.com/team/U01UNQ7MMCZ) working with those working on the [Release](https://make.wordpress.org/core/6-0/) 
- Ad hoc updates from [WordPress.org/news](http://wordpress.org/news) - [@Brett McSherry](https://wordpress.slack.com/team/U02U9S93BDE)
- Learn WordPress (#LearnWP) - [@Dan Soschin](https://wordpress.slack.com/team/U01UNQ7MMCZ) along with the Training team
- WP Diversity (#WPDiversity) - [@Santana.Inniss](https://wordpress.slack.com/team/U02TM887GQL) along with [@jillbinder](https://wordpress.slack.com/team/U02S5FUKN) and the WP Diversity working group in the Community Team
- Openverse (#Openverse) - [@Reyes Martínez](https://wordpress.slack.com/team/U4QJBN9BK) along with the Openverse team
- Photo Directory (#WPPhotos) - [@Reyes Martínez](https://wordpress.slack.com/team/U4QJBN9BK) along with the Photo team
- Grow Your Story (#GrowYourStoryWP) - [@jpantani](https://wordpress.slack.com/team/U02E9BE1J6P) along with the Design team
- WP Briefing podcast (#WPBriefing) - [@Santana.Inniss](https://wordpress.slack.com/team/U02TM887GQL)  (((Is this with anyone/ any team?)))
- WordCamp (#WordCamp) - [@Brett McSherry](https://wordpress.slack.com/team/U02U9S93BDE) (((Is this with the Community team?)))

**Comment by nalininsbs** [comment]
Agenda drafted. Public preview https://make.wordpress.org/marketing/?p=9699&preview=1&_ppp=c313fa71d9
Once the notes are published from last week, can someone add the link to the agenda and add Lauren's name to the thank you on the notes. Then the agenda can be published. Thank you.
@eidolonnight and @murillol

**Comment by nalininsbs** [comment]
Agenda published for tomorrow's meeting, 10 August 2022 https://make.wordpress.org/marketing/2022/08/09/agenda-global-marketing-team-meeting-august-10-2022/

**Comment by rmartinezduque** [comment]
Hello! I edited Nalini's previous comment (https://github.com/WordPress/Marketing-Team/issues/98#issuecomment-1208623888) to update the Openverse hashtag. It's #WPOpenverse instead of #Openverse. I updated [this GitHub card ](https://github.com/WordPress/Marketing-Team/issues/7) accordingly. Thank you!

**Comment by rmartinezduque** [comment]
Oh, I see. That's good to know. If that script could be also updated to reflect the accurate hashtag (#WPOpenverse) as you said that would be really great. Thank you, @abhansnuk.

**Comment by thetinyl** [comment]
Hoping to add an Open floor item: 

I've drafted some copy to be considered for the [Marketing description in the Welcome Box/Handbook/etc (card #87)](https://github.com/WordPress/Marketing-Team/issues/87#issuecomment-1209819649). 

Thought it'd be worth letting people know in the meeting to continue previous discussions.

**Comment by rmartinezduque** [comment]
Hi! The meeting notes for August 10 are ready for review. You can find them in [this Make Marketing post draft](https://make.wordpress.org/marketing/wp-admin/post.php?post=9716&action=edit). Please let me know when any of you have a chance to review them so that I can post them. Thank you!

**Comment by murillol** [comment]
Hi @rmartinezduque they look great to me, the only thing I added was an **Excerpt** to the post. If noone has any other observations until today end of day, please feel free to post. Thanks!

**Comment by nalininsbs** [comment]
Thank you @rmartinezduque for very helpful notes. I have made some edits including.

Replaced 'view participants' to 'Meeting attendees: participants list is in this Slack Thread' - to be updated in the handbook

Changing 'Take a look' to 'Recap last week's meeting with' - as part of reducing words like 'see' and 'look' where there are alternatives as we have contributors who listen to the meeting notes.

Added GitHub card numbers - this needs to be added to the handbook

Added a card for August 24

Made clearer that the social channels update relates to WordPress.org channels.

Clarified that the collaboration meeting this week is open to everyone.

Added link for the bug scrubs. 

Shortened excerpt and added in global as some languages have mini marketing teams or efforts. Eg  Meeting notes for the global Make WordPress Marketing team on 10 August 2022..

**Comment by nalininsbs** [comment]
Published link: https://make.wordpress.org/marketing/2022/08/16/notes-global-marketing-team-meeting-august-10-2022/

@thetinyl could you add your thoughts if we add a slot at this week's meeting to discuss the welcome text? Thank you.

**Comment by rmartinezduque** [comment]
Thanks for making those edits and for publishing the notes, @nalininsbs. And thank you @murillol for reviewing them as well. I always forgot to add the excerpt. 🤦🏻‍♀️ I'm taking note of your suggestions for next time!

**Comment by nalininsbs** [comment]
Your notes are always a pleasure to go through @rmartinezduque , and together we find ways to help make them easier to follow for everyone.

**Comment by nalininsbs** [comment]
@eidolonnight would you be able to look at my question above please https://github.com/WordPress/Marketing-Team/issues/98#issuecomment-1208623888 Thank you.

**Comment by dugyen** [comment]
@murillol @nalininsbs Could you please review our draft note - https://make.wordpress.org/marketing/wp-admin/post.php?post=9749&action=edit

**Comment by murillol** [comment]
@eidolonnight I think you missed Nalini's mention above!

**Comment by sereedmedia** [comment]
Can we close this issue? Any issues that need their own card or discussion? thanks! @eidolonnight @nalininsbs

**Comment by sereedmedia** [comment]
I'm going to go ahead with closing this card. If there are any issues that need revisiting, we can reopen. Thanks!
