### ISSUE TITLE
Polyglots Team August 2022 newsletter - marketing input

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#99]

**Comment by naokomc** [comment]
Here's the draft of August Polyglots newsletter: https://docs.google.com/document/d/1tLLbk3YI-hWmfhehPqrSe2OMMx8HPLApBczpF8yfVTI/edit#

**Comment by naokomc** [comment]
Published the newsletter and P2 version:

- https://mailchi.mp/wordcamp/polyglots-august-2022
- https://make.wordpress.org/polyglots/2022/08/22/polyglots-monthly-newsletter-august-2022/

Thanks for your editing help, @abhansnuk  @murillol !
